'use strict';
const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');

const originalCreateServer=http.createServer.bind(http);
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const BETA_SECRET=String(process.env.BETA_TOKEN_SECRET||'');
const ALLOWED_ORIGIN=process.env.ALLOWED_ORIGIN||'https://anttivanttinen-max.github.io';
const USERS_FILE=path.join(DATA_DIR,'users','registry.json');
const FEEDBACK_FILE=path.join(DATA_DIR,'users','feedback.json');
const ISSUES_FILE=path.join(DATA_DIR,'community','issues.json');

function unb64(v){return Buffer.from(v,'base64url').toString('utf8')}
function verify(token){if(!BETA_SECRET||!token)return null;const [body,sig]=String(token).split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',BETA_SECRET).update(body).digest('base64url');const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;try{const p=JSON.parse(unb64(body));if(p.exp&&Date.now()>p.exp)return null;return p}catch{return null}}
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}}
function atomic(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(tmp,data);fs.renameSync(tmp,file)}
function send(res,status,obj,origin=''){const body=Buffer.from(JSON.stringify(obj));const h={'Content-Type':'application/json; charset=utf-8','Content-Length':body.length,'Cache-Control':'no-store'};if(origin===ALLOWED_ORIGIN){h['Access-Control-Allow-Origin']=origin;h['Vary']='Origin'}res.writeHead(status,h);res.end(body)}
function readBody(req,max=262144){return new Promise((resolve,reject)=>{let size=0,a=[];req.on('data',c=>{size+=c.length;if(size>max){reject(Object.assign(new Error('Payload too large'),{status:413}));req.destroy();return}a.push(c)});req.on('end',()=>resolve(Buffer.concat(a)));req.on('error',reject)})}
function identity(req){const p=verify(String(req.headers['x-motolab-beta-token']||''));if(!p||!p.deviceId)return null;const db=readJson(USERS_FILE,{users:[]});const u=(p.userId?db.users.find(x=>x.userId===p.userId):null)||db.users.find(x=>(x.devices||[]).some(d=>d.deviceId===p.deviceId));if(!u)return null;const d=(u.devices||[]).find(x=>x.deviceId===p.deviceId);if(!d)return null;return {payload:p,user:u,device:d}}
function cleanText(v,n){return String(v||'').replace(/[<>]/g,'').trim().slice(0,n)}
function id(prefix){return prefix+'_'+crypto.randomBytes(10).toString('hex')}
function readFeedback(){const db=readJson(FEEDBACK_FILE,{schema:'motolab_feedback_v2',items:[]});db.schema='motolab_feedback_v2';db.items=Array.isArray(db.items)?db.items:[];for(const item of db.items){if(!Array.isArray(item.messages)){item.messages=[];if(item.message)item.messages.push({messageId:id('msg'),authorRole:'user',authorUserId:item.userId||'',text:item.message,createdAt:item.createdAt||new Date().toISOString()})}if(!item.status||item.status==='reviewing')item.status=item.status==='reviewing'?'working':'new';if(item.status==='done'||item.status==='archived')item.status='resolved'}return db}
function writeFeedback(x){x.updatedAt=new Date().toISOString();atomic(FEEDBACK_FILE,JSON.stringify(x,null,2))}
function publicMessage(m){return {messageId:m.messageId,authorRole:m.authorRole==='admin'?'admin':'user',text:m.text,createdAt:m.createdAt}}
function userItem(i){return {feedbackId:i.feedbackId,category:i.category,status:i.status,createdAt:i.createdAt,updatedAt:i.updatedAt||i.createdAt,appVersion:i.appVersion||'',messages:(i.messages||[]).map(publicMessage),publishedIssueId:i.publishedIssueId||null}}
function adminItem(i){return {...userItem(i),userId:i.userId,nickname:i.nickname||'',deviceId:i.deviceId||'',page:i.page||''}}
function addMessage(item,role,userId,text){const m={messageId:id('msg'),authorRole:role,authorUserId:userId,text,createdAt:new Date().toISOString()};item.messages=item.messages||[];item.messages.push(m);item.updatedAt=m.createdAt;return m}
async function jsonData(req){return JSON.parse((await readBody(req)).toString('utf8'))}
async function submit(req,res,origin){const x=identity(req);if(!x||x.user.status!=='active')return send(res,401,{ok:false,error:'Active user required'},origin);let data;try{data=await jsonData(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const message=cleanText(data.message,5000),category=['problem','update','development','other'].includes(data.category)?data.category:'other';if(!message)return send(res,400,{ok:false,error:'Comment required'},origin);const db=readFeedback(),now=new Date().toISOString(),item={feedbackId:id('fb'),userId:x.user.userId,nickname:x.user.nickname||'',deviceId:x.device.deviceId,category,appVersion:cleanText(data.appVersion,80),page:cleanText(data.page,200),createdAt:now,updatedAt:now,status:'waiting_admin',messages:[],publishedIssueId:null};addMessage(item,'user',x.user.userId,message);db.items.push(item);writeFeedback(db);return send(res,201,{ok:true,item:userItem(item)},origin)}
function mine(req,res,origin){const x=identity(req);if(!x||x.user.status!=='active')return send(res,401,{ok:false,error:'Active user required'},origin);const db=readFeedback(),items=db.items.filter(i=>i.userId===x.user.userId).map(userItem).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));return send(res,200,{ok:true,items},origin)}
async function userReply(req,res,origin){const x=identity(req);if(!x||x.user.status!=='active')return send(res,401,{ok:false,error:'Active user required'},origin);let data;try{data=await jsonData(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const text=cleanText(data.message,5000),db=readFeedback(),item=db.items.find(i=>i.feedbackId===String(data.feedbackId||'')&&i.userId===x.user.userId);if(!item)return send(res,404,{ok:false,error:'Feedback not found'},origin);if(!text)return send(res,400,{ok:false,error:'Message required'},origin);addMessage(item,'user',x.user.userId,text);if(item.status!=='resolved')item.status='waiting_admin';writeFeedback(db);return send(res,201,{ok:true,item:userItem(item)},origin)}
function list(req,res,origin){const x=identity(req);if(!x||x.user.role!=='admin')return send(res,403,{ok:false,error:'Admin required'},origin);const db=readFeedback(),items=db.items.map(adminItem).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));return send(res,200,{ok:true,items},origin)}
async function adminReply(req,res,origin){const x=identity(req);if(!x||x.user.role!=='admin')return send(res,403,{ok:false,error:'Admin required'},origin);let data;try{data=await jsonData(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const text=cleanText(data.message,5000),db=readFeedback(),item=db.items.find(i=>i.feedbackId===String(data.feedbackId||''));if(!item)return send(res,404,{ok:false,error:'Feedback not found'},origin);if(!text)return send(res,400,{ok:false,error:'Message required'},origin);addMessage(item,'admin',x.user.userId,text);if(item.status!=='resolved')item.status='waiting_user';writeFeedback(db);return send(res,201,{ok:true,item:adminItem(item)},origin)}
async function update(req,res,origin){const x=identity(req);if(!x||x.user.role!=='admin')return send(res,403,{ok:false,error:'Admin required'},origin);let data;try{data=await jsonData(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const db=readFeedback(),item=db.items.find(i=>i.feedbackId===String(data.feedbackId||''));if(!item)return send(res,404,{ok:false,error:'Feedback not found'},origin);if(['new','waiting_admin','waiting_user','working','resolved'].includes(data.status))item.status=data.status;item.updatedAt=new Date().toISOString();item.updatedBy=x.user.userId;writeFeedback(db);return send(res,200,{ok:true,item:adminItem(item)},origin)}
async function publishAnonymous(req,res,origin){const x=identity(req);if(!x||x.user.role!=='admin')return send(res,403,{ok:false,error:'Admin required'},origin);let data;try{data=await jsonData(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const fdb=readFeedback(),item=fdb.items.find(i=>i.feedbackId===String(data.feedbackId||''));if(!item)return send(res,404,{ok:false,error:'Feedback not found'},origin);if(item.publishedIssueId)return send(res,409,{ok:false,error:'Feedback already published',issueId:item.publishedIssueId},origin);const first=(item.messages||[]).find(m=>m.authorRole==='user');const title=cleanText(data.title||'Beta-käyttäjän ilmoittama ongelma',120),description=cleanText(data.description||first?.text||'',5000),category=cleanText(data.category||'Ongelma',40);if(!description)return send(res,400,{ok:false,error:'Description required'},origin);const cdb=readJson(ISSUES_FILE,{schema:'motolab_beta_community_v1',issues:[]});cdb.issues=Array.isArray(cdb.issues)?cdb.issues:[];const now=new Date().toISOString(),issue={issueId:id('issue'),title,description,category,status:'open',anonymous:true,userId:null,nickname:'',createdAt:now,updatedAt:now,sameUsers:[],comments:[],source:'private_feedback',sourceFeedbackId:item.feedbackId};cdb.issues.push(issue);cdb.updatedAt=now;atomic(ISSUES_FILE,JSON.stringify(cdb,null,2));item.publishedIssueId=issue.issueId;item.publishedAt=now;item.publishedBy=x.user.userId;item.updatedAt=now;writeFeedback(fdb);return send(res,201,{ok:true,issueId:issue.issueId,anonymous:true},origin)}

http.createServer=function(listener){return originalCreateServer(async(req,res)=>{const origin=String(req.headers.origin||'');let u;try{u=new URL(req.url,'http://localhost')}catch{return listener(req,res)}
 const p=u.pathname,feedback=p.startsWith('/api/feedback/')||p.startsWith('/api/admin/v1/feedback');
 if(req.method==='OPTIONS'&&origin===ALLOWED_ORIGIN&&feedback){res.writeHead(204,{'Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-MotoLab-Beta-Token','Access-Control-Max-Age':'86400'});return res.end()}
 if(req.method==='POST'&&p==='/api/feedback/v1/comment')return submit(req,res,origin);
 if(req.method==='GET'&&p==='/api/feedback/v1/mine')return mine(req,res,origin);
 if(req.method==='POST'&&p==='/api/feedback/v1/reply')return userReply(req,res,origin);
 if(req.method==='GET'&&p==='/api/admin/v1/feedback')return list(req,res,origin);
 if(req.method==='POST'&&p==='/api/admin/v1/feedback-reply')return adminReply(req,res,origin);
 if(req.method==='POST'&&p==='/api/admin/v1/feedback-status')return update(req,res,origin);
 if(req.method==='POST'&&p==='/api/admin/v1/feedback-publish-anonymous')return publishAnonymous(req,res,origin);
 return listener(req,res)});};
console.log('MotoLab private feedback conversations enabled');
