'use strict';
const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const originalCreateServer=http.createServer.bind(http);
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const SECRET=String(process.env.BETA_TOKEN_SECRET||'');
const ORIGIN=process.env.ALLOWED_ORIGIN||'https://anttivanttinen-max.github.io';
const USERS_FILE=path.join(DATA_DIR,'users','registry.json');
const MERIT_FILE=path.join(DATA_DIR,'users','tester_merit.json');
const FEEDBACK_FILE=path.join(DATA_DIR,'users','feedback.json');
const ISSUES_FILE=path.join(DATA_DIR,'community','issues.json');
const CATEGORIES=['data','reports','activity','community','reliability','ideas'];
function readJson(f,d){try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return d}}
function atomic(f,x){fs.mkdirSync(path.dirname(f),{recursive:true});const t=f+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,f)}
function unb64(v){return Buffer.from(v,'base64url').toString('utf8')}
function verify(t){if(!SECRET||!t)return null;const [b,s]=String(t).split('.');if(!b||!s)return null;const e=crypto.createHmac('sha256',SECRET).update(b).digest('base64url'),a=Buffer.from(s),c=Buffer.from(e);if(a.length!==c.length||!crypto.timingSafeEqual(a,c))return null;try{const p=JSON.parse(unb64(b));if(p.exp&&Date.now()>p.exp)return null;return p}catch{return null}}
function users(){return readJson(USERS_FILE,{users:[]}).users||[]}
function auth(req){const p=verify(req.headers['x-motolab-beta-token']);if(!p)return null;const u=users().find(x=>x.userId===p.userId||(x.devices||[]).some(d=>d.deviceId===p.deviceId));return u?{payload:p,user:u}:null}
function send(res,status,obj,origin=''){const b=Buffer.from(JSON.stringify(obj));const h={'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'};if(origin===ORIGIN){h['Access-Control-Allow-Origin']=origin;h.Vary='Origin'}res.writeHead(status,h);res.end(b)}
function body(req,max=131072){return new Promise((resolve,reject)=>{let n=0,a=[];req.on('data',c=>{n+=c.length;if(n>max){reject(Error('Payload too large'));req.destroy();return}a.push(c)});req.on('end',()=>resolve(Buffer.concat(a)));req.on('error',reject)})}
async function jsonBody(req){return JSON.parse((await body(req)).toString('utf8'))}
function clean(v,n=500){return String(v||'').replace(/[<>\r\n]/g,' ').trim().slice(0,n)}
function db(){return readJson(MERIT_FILE,{schema:'motolab_tester_merit_v1',users:{},reviews:{}})}
function save(x){x.updatedAt=new Date().toISOString();atomic(MERIT_FILE,x)}
function level(score){if(score>=85)return 'core';if(score>=65)return 'advanced';if(score>=40)return 'active';return 'beta'}
function levelName(x){return ({beta:'Beta Tester',active:'Active Tester',advanced:'Advanced Tester',core:'Core Tester'})[x]||'Beta Tester'}
function scoreUser(userId,m){const u=m.users?.[userId]||{events:[]};const events=Array.isArray(u.events)?u.events:[];const categories=Object.fromEntries(CATEGORIES.map(k=>[k,0]));let score=0;for(const e of events){const p=Number(e.points)||0;score+=p;if(categories[e.category]!==undefined)categories[e.category]+=p}score=Math.max(0,Math.min(100,score));const l=level(score);return {score,level:l,levelName:levelName(l),categories,events:events.slice().sort((a,b)=>Date.parse(b.at)-Date.parse(a.at))}}
function publicMerit(userId,m){const s=scoreUser(userId,m);return {level:s.level,levelName:s.levelName,message:'Hyödyllinen osallistuminen ja laadukas testaus voivat avata uusia testiominaisuuksia.'}}
function requireActive(req,res,origin){const x=auth(req);if(!x||x.user.status!=='active'){send(res,401,{ok:false,error:'Active user required'},origin);return null}return x}
function requireAdmin(req,res,origin){const x=requireActive(req,res,origin);if(!x)return null;if(x.user.role!=='admin'){send(res,403,{ok:false,error:'Admin required'},origin);return null}return x}
function candidates(m){const out=[];const feedback=readJson(FEEDBACK_FILE,{items:[]}).items||[];for(const f of feedback){const sourceId='feedback:'+f.feedbackId;if(m.reviews?.[sourceId])continue;const messages=Array.isArray(f.messages)?f.messages:[];const text=messages.find(x=>x.senderRole!=='admin')?.text||f.message||'';out.push({sourceId,userId:f.userId,nickname:f.nickname||'',type:'feedback',category:f.category||'other',title:clean(text,100),createdAt:f.createdAt||'',suggestedCategory:f.category==='development'?'ideas':'reports'})}
 const issues=readJson(ISSUES_FILE,{issues:[]}).issues||[];for(const i of issues){const sourceId='issue:'+i.issueId;if(!m.reviews?.[sourceId]&&i.userId)out.push({sourceId,userId:i.userId,nickname:i.nickname||'',type:'issue',category:i.category||'',title:clean(i.title,100),createdAt:i.createdAt||'',suggestedCategory:/idea/i.test(i.category||'')?'ideas':'reports'});for(const c of (i.comments||[])){const sid='comment:'+c.commentId;if(m.reviews?.[sid]||!c.userId)continue;out.push({sourceId:sid,userId:c.userId,nickname:c.nickname||'',type:'community_comment',category:i.category||'',title:clean(c.text,100),createdAt:c.createdAt||'',suggestedCategory:c.isSolution?'community':'community',isSolution:!!c.isSolution})}}
 return out.sort((a,b)=>Date.parse(b.createdAt||0)-Date.parse(a.createdAt||0)).slice(0,300)}
http.createServer=function(listener){return originalCreateServer(async(req,res)=>{const origin=String(req.headers.origin||'');let u;try{u=new URL(req.url,'http://localhost')}catch{return listener(req,res)};const p=u.pathname,match=p.startsWith('/api/merit/')||p.startsWith('/api/admin/v1/merit/');if(req.method==='OPTIONS'&&match&&origin===ORIGIN){res.writeHead(204,{'Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-MotoLab-Beta-Token','Access-Control-Max-Age':'86400'});return res.end()}
 if(req.method==='GET'&&p==='/api/merit/v1/me'){const x=requireActive(req,res,origin);if(!x)return;return send(res,200,{ok:true,merit:publicMerit(x.user.userId,db())},origin)}
 if(req.method==='GET'&&p==='/api/admin/v1/merit/users'){const x=requireAdmin(req,res,origin);if(!x)return;const m=db();return send(res,200,{ok:true,users:users().filter(z=>z.role!=='admin').map(z=>({userId:z.userId,nickname:z.nickname||'MotoLab user',status:z.status,merit:scoreUser(z.userId,m)})).sort((a,b)=>b.merit.score-a.merit.score)},origin)}
 if(req.method==='GET'&&p==='/api/admin/v1/merit/candidates'){const x=requireAdmin(req,res,origin);if(!x)return;const m=db();return send(res,200,{ok:true,items:candidates(m)},origin)}
 if(req.method==='POST'&&p==='/api/admin/v1/merit/review'){const x=requireAdmin(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const sourceId=clean(d.sourceId,160),userId=clean(d.userId,100),category=CATEGORIES.includes(d.category)?d.category:'reports',points=Math.max(0,Math.min(10,Math.round(Number(d.points)||0))),reason=clean(d.reason,500),cause=['user','device','app','sensor','unknown','none'].includes(d.cause)?d.cause:'none';if(!sourceId||!userId)return send(res,400,{ok:false,error:'sourceId/userId required'},origin);const target=users().find(z=>z.userId===userId);if(!target)return send(res,404,{ok:false,error:'User not found'},origin);const m=db();m.users=m.users||{};m.reviews=m.reviews||{};if(m.reviews[sourceId])return send(res,409,{ok:false,error:'Source already reviewed'},origin);m.users[userId]=m.users[userId]||{events:[]};const at=new Date().toISOString();if(points>0)m.users[userId].events.push({eventId:'mer_'+crypto.randomBytes(8).toString('hex'),sourceId,category,points,reason,cause,at,awardedBy:x.user.userId});m.reviews[sourceId]={userId,points,category,reason,cause,at,reviewedBy:x.user.userId};save(m);return send(res,200,{ok:true,merit:scoreUser(userId,m)},origin)}
 if(req.method==='POST'&&p==='/api/admin/v1/merit/bonus'){const x=requireAdmin(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const userId=clean(d.userId,100),category=CATEGORIES.includes(d.category)?d.category:'ideas',points=Math.max(1,Math.min(15,Math.round(Number(d.points)||0))),reason=clean(d.reason,500);const target=users().find(z=>z.userId===userId);if(!target)return send(res,404,{ok:false,error:'User not found'},origin);const m=db();m.users=m.users||{};m.users[userId]=m.users[userId]||{events:[]};m.users[userId].events.push({eventId:'mer_'+crypto.randomBytes(8).toString('hex'),sourceId:null,category,points,reason,cause:'none',at:new Date().toISOString(),awardedBy:x.user.userId,bonus:true});save(m);return send(res,200,{ok:true,merit:scoreUser(userId,m)},origin)}
 return listener(req,res)});};
console.log('MotoLab Tester Merit server: enabled');
