'use strict';
const {spawn}=require('child_process');const fs=require('fs');const os=require('os');const path=require('path');
const assert=(v,m)=>{if(!v)throw Error(m)};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function json(url,opt={}){const r=await fetch(url,opt);let j={};try{j=await r.json()}catch{}return {r,j}}
async function main(){
 const port=39000+Math.floor(Math.random()*1500),dir=fs.mkdtempSync(path.join(os.tmpdir(),'motolab-id-')),base=`http://127.0.0.1:${port}`;
 const env={...process.env,PORT:String(port),DATA_DIR:dir,BETA_TOKEN_SECRET:'test-secret-32-bytes-minimum',BETA_INVITE_CODES:'OWNER-TEST',MOTOLAB_ADMIN_DEVICE_IDS:'owner-device',MOTOLAB_OWNER_NICKNAME:'VäNä',INGEST_KEY:'ingest-test',READ_KEY:'read-test',ALLOWED_ORIGIN:'https://anttivanttinen-max.github.io'};
 const child=spawn(process.execPath,['-r','./beta_auth_server.js','-r','./user_features_server.js','-r','./community_server.js','-r','./merit_server.js','-r','./owner_device_session_server.js','server.js'],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});let logs='';child.stdout.on('data',x=>logs+=x);child.stderr.on('data',x=>logs+=x);
 try{
  let up=false;for(let i=0;i<60;i++){try{const r=await fetch(base+'/health');if(r.ok){up=true;break}}catch{}await sleep(100)}assert(up,'server failed to start\n'+logs);
  const cors=await fetch(base+'/api/users/v1/state',{method:'OPTIONS',headers:{Origin:env.ALLOWED_ORIGIN,'Access-Control-Request-Method':'PUT','Access-Control-Request-Headers':'content-type,x-motolab-beta-token'}});assert(cors.status===204,'user OPTIONS failed');assert((cors.headers.get('access-control-allow-methods')||'').includes('PUT'),'PUT missing from CORS');
  let x=await json(base+'/api/beta/v1/activate',{method:'POST',headers:{'Content-Type':'application/json',Origin:env.ALLOWED_ORIGIN},body:JSON.stringify({code:'OWNER-TEST',deviceId:'owner-device',nickname:'VäNä'})});assert(x.r.ok&&x.j.token,'owner activation failed '+JSON.stringify(x.j));assert(x.j.user?.role==='admin'&&x.j.user?.status==='active','owner role/status wrong');assert(x.j.token.split('.')[0],'token missing');const ownerToken=x.j.token;
  x=await json(base+'/api/users/v1/me',{headers:{'X-MotoLab-Beta-Token':ownerToken,Origin:env.ALLOWED_ORIGIN}});assert(x.r.ok&&x.j.user?.role==='admin','owner /me failed');
  x=await json(base+'/api/users/v1/invite',{method:'POST',headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':ownerToken,Origin:env.ALLOWED_ORIGIN},body:'{}'});assert(x.r.status===201&&x.j.invite,'dynamic invite creation failed');const invite=x.j.invite;
  x=await json(base+'/api/beta/v1/activate',{method:'POST',headers:{'Content-Type':'application/json',Origin:env.ALLOWED_ORIGIN},body:JSON.stringify({code:invite,deviceId:'tester-device',nickname:'Tester'})});assert(x.r.ok&&x.j.token,'dynamic invite activation failed '+JSON.stringify(x.j));assert(x.j.user?.status==='pending','new tester should be pending');const testerToken=x.j.token,testerId=x.j.user.userId;
  x=await json(base+'/api/admin/v1/user-status',{method:'POST',headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':ownerToken,Origin:env.ALLOWED_ORIGIN},body:JSON.stringify({userId:testerId,status:'active'})});assert(x.r.ok&&x.j.user?.status==='active','tester approval failed');
  const state={motolab_language:'en',example:'ok'};x=await json(base+'/api/users/v1/state',{method:'PUT',headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':testerToken,Origin:env.ALLOWED_ORIGIN},body:JSON.stringify({state})});assert(x.r.ok,'state PUT failed '+JSON.stringify(x.j));x=await json(base+'/api/users/v1/state',{headers:{'X-MotoLab-Beta-Token':testerToken,Origin:env.ALLOWED_ORIGIN}});assert(x.r.ok&&x.j.item?.state?.motolab_language==='en','state GET failed');
  x=await json(base+'/api/users/v1/owner-device-session',{method:'POST',headers:{'Content-Type':'application/json',Origin:env.ALLOWED_ORIGIN},body:JSON.stringify({deviceId:'owner-device',deviceLabel:'same iPhone'})});assert(x.r.ok&&x.j.token&&x.j.user?.role==='admin','same-device owner restore failed '+JSON.stringify(x.j));const restored=x.j.token;
  x=await json(base+'/api/users/v1/me',{headers:{'X-MotoLab-Beta-Token':restored,Origin:env.ALLOWED_ORIGIN}});assert(x.r.ok&&x.j.user?.nickname==='VäNä','restored owner /me failed');
  x=await json(base+'/api/users/v1/owner-device-session',{method:'POST',headers:{'Content-Type':'application/json',Origin:env.ALLOWED_ORIGIN},body:JSON.stringify({deviceId:'unknown-device'})});assert(x.r.status===404,'unknown owner device must not recover');
  console.log('IDENTITY_FLOW_OK',JSON.stringify({owner:'active/admin',dynamicInvite:'pending->active',state:'put/get',ownerRestore:'same-device-only',port}));
 }finally{child.kill('SIGTERM');await sleep(80);fs.rmSync(dir,{recursive:true,force:true})}
}
main().catch(e=>{console.error(e.stack||e);process.exit(1)});
