'use strict';
const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const originalCreateServer=http.createServer.bind(http);
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const SECRET=String(process.env.BETA_TOKEN_SECRET||'');
const ORIGIN=process.env.ALLOWED_ORIGIN||'https://anttivanttinen-max.github.io';
const USERS_FILE=path.join(DATA_DIR,'users','registry.json');
const FEATURES_FILE=path.join(DATA_DIR,'users','features.json');
const META_FILE=path.join(DATA_DIR,'users','client_meta.json');
const SHARES_FILE=path.join(DATA_DIR,'users','run_shares.json');
const DEFAULT_USER={gps:true,phone_mic:true,dyno_runs:true,run_sharing:true,bt_contact_mic:false,raw_data:false,live_data:false,rpm_experimental:false,knock_vibration:false,beta_features:false};
const ALL_KEYS=Object.keys(DEFAULT_USER);
function readJson(f,d){try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return d}}
function atomic(f,x){fs.mkdirSync(path.dirname(f),{recursive:true});const t=f+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,f)}
function unb64(v){return Buffer.from(v,'base64url').toString('utf8')}
function verify(t){if(!SECRET||!t)return null;const [b,s]=String(t).split('.');if(!b||!s)return null;const e=crypto.createHmac('sha256',SECRET).update(b).digest('base64url'),a=Buffer.from(s),c=Buffer.from(e);if(a.length!==c.length||!crypto.timingSafeEqual(a,c))return null;try{const p=JSON.parse(unb64(b));if(p.exp&&Date.now()>p.exp)return null;return p}catch{return null}}
function users(){return readJson(USERS_FILE,{users:[]}).users||[]}
function auth(req){const p=verify(req.headers['x-motolab-beta-token']);if(!p)return null;const list=users(),u=list.find(x=>x.userId===p.userId||(x.devices||[]).some(d=>d.deviceId===p.deviceId));if(!u)return null;return {payload:p,user:u}}
function perms(user){if(user.role==='admin')return Object.fromEntries(ALL_KEYS.map(k=>[k,true]));const db=readJson(FEATURES_FILE,{schema:'motolab_features_v1',users:{}});return {...DEFAULT_USER,...(db.users?.[user.userId]||{})}}
function send(res,status,obj,origin=''){const b=Buffer.from(JSON.stringify(obj));const h={'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'};if(origin===ORIGIN){h['Access-Control-Allow-Origin']=origin;h.Vary='Origin'}res.writeHead(status,h);res.end(b)}
function body(req,max=512000){return new Promise((resolve,reject)=>{let n=0,a=[];req.on('data',c=>{n+=c.length;if(n>max){reject(Error('Payload too large'));req.destroy();return}a.push(c)});req.on('end',()=>resolve(Buffer.concat(a)));req.on('error',reject)})}
async function jsonBody(req){return JSON.parse((await body(req)).toString('utf8'))}
function cleanText(v,n=80){return String(v||'').replace(/[<>\r\n]/g,'').trim().slice(0,n)}
function publicTarget(u){return {userId:u.userId,nickname:u.nickname||'MotoLab user'}}
function requireActive(req,res,origin){const x=auth(req);if(!x)return send(res,401,{ok:false,error:'Invalid device session'},origin),null;if(x.user.status!=='active')return send(res,403,{ok:false,error:'User not approved'},origin),null;return x}
function requireAdmin(req,res,origin){const x=requireActive(req,res,origin);if(!x)return null;if(x.user.role!=='admin')return send(res,403,{ok:false,error:'Admin required'},origin),null;return x}
function normalizeCurve(run){const src=Array.isArray(run?.curve)?run.curve:Array.isArray(run?.data)?run.data:[];const pts=src.filter(x=>Number.isFinite(+x.rpm)&&+x.rpm>0).map(x=>({rpm:Math.round(+x.rpm),hp:Number.isFinite(+x.hp)?+x.hp:0,nm:Number.isFinite(+x.nm)?+x.nm:0}));const step=Math.max(1,Math.ceil(pts.length/220));return pts.filter((_,i)=>i%step===0).slice(0,220)}
function sharePublic(s){return {shareId:s.shareId,status:s.status,senderUserId:s.senderUserId,senderNickname:s.senderNickname,receiverUserId:s.receiverUserId,createdAt:s.createdAt,respondedAt:s.respondedAt||null,run:s.run}}
http.createServer=function(listener){return originalCreateServer(async(req,res)=>{const origin=String(req.headers.origin||'');let u;try{u=new URL(req.url,'http://localhost')}catch{return listener(req,res)};const featurePath=u.pathname.startsWith('/api/features/')||u.pathname.startsWith('/api/shares/')||u.pathname==='/api/users/v1/share-targets'||u.pathname.startsWith('/api/admin/v1/features/');
 if(req.method==='OPTIONS'&&featurePath&&origin===ORIGIN){res.writeHead(204,{'Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-MotoLab-Beta-Token','Access-Control-Max-Age':'86400'});return res.end()}
 if(req.method==='GET'&&u.pathname==='/api/features/v1/me'){const x=requireActive(req,res,origin);if(!x)return;return send(res,200,{ok:true,permissions:perms(x.user)},origin)}
 if(req.method==='POST'&&u.pathname==='/api/features/v1/heartbeat'){const x=requireActive(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const db=readJson(META_FILE,{schema:'motolab_client_meta_v1',users:{}});db.users[x.user.userId]={appVersion:cleanText(d.appVersion,32),build:cleanText(d.build,64),platform:cleanText(d.platform,80),deviceModel:cleanText(d.deviceModel,80),lastSeenAt:new Date().toISOString()};atomic(META_FILE,db);return send(res,200,{ok:true},origin)}
 if(req.method==='GET'&&u.pathname==='/api/users/v1/share-targets'){const x=requireActive(req,res,origin);if(!x)return;if(!perms(x.user).run_sharing)return send(res,403,{ok:false,error:'Run sharing not allowed'},origin);return send(res,200,{ok:true,users:users().filter(z=>z.status==='active'&&z.userId!==x.user.userId).map(publicTarget).sort((a,b)=>a.nickname.localeCompare(b.nickname,'fi'))},origin)}
 if(req.method==='POST'&&u.pathname==='/api/shares/v1/runs'){const x=requireActive(req,res,origin);if(!x)return;if(!perms(x.user).run_sharing)return send(res,403,{ok:false,error:'Run sharing not allowed'},origin);let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const target=users().find(z=>z.userId===d.receiverUserId&&z.status==='active');if(!target||target.userId===x.user.userId)return send(res,404,{ok:false,error:'Receiver not found'},origin);const curve=normalizeCurve(d.run);if(curve.length<2)return send(res,400,{ok:false,error:'Run curve missing'},origin);const db=readJson(SHARES_FILE,{schema:'motolab_run_shares_v1',shares:[]});const item={shareId:'shr_'+crypto.randomBytes(10).toString('hex'),senderUserId:x.user.userId,senderNickname:x.user.nickname||'MotoLab user',receiverUserId:target.userId,status:'pending',createdAt:new Date().toISOString(),run:{sourceRunId:cleanText(d.run?.id,100),profileName:cleanText(d.run?.profileName||'Pyörä',80),date:cleanText(d.run?.date,48),quality:Math.max(0,Math.min(100,Math.round(+d.run?.quality||0))),maxHp:+d.run?.maxHp||0,maxNm:+d.run?.maxNm||0,maxRpm:+d.run?.maxRpm||0,curve}};db.shares.push(item);atomic(SHARES_FILE,db);return send(res,201,{ok:true,share:sharePublic(item)},origin)}
 if(req.method==='GET'&&u.pathname==='/api/shares/v1/inbox'){const x=requireActive(req,res,origin);if(!x)return;const db=readJson(SHARES_FILE,{shares:[]});return send(res,200,{ok:true,shares:(db.shares||[]).filter(s=>s.receiverUserId===x.user.userId&&s.status!=='rejected').map(sharePublic).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt))},origin)}
 if(req.method==='POST'&&u.pathname==='/api/shares/v1/respond'){const x=requireActive(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const db=readJson(SHARES_FILE,{shares:[]}),s=(db.shares||[]).find(z=>z.shareId===d.shareId&&z.receiverUserId===x.user.userId);if(!s)return send(res,404,{ok:false,error:'Share not found'},origin);if(!['accepted','rejected'].includes(d.action))return send(res,400,{ok:false,error:'Invalid action'},origin);s.status=d.action;s.respondedAt=new Date().toISOString();atomic(SHARES_FILE,db);return send(res,200,{ok:true,share:sharePublic(s)},origin)}
 if(req.method==='GET'&&u.pathname==='/api/admin/v1/features/users'){const x=requireAdmin(req,res,origin);if(!x)return;const meta=readJson(META_FILE,{users:{}}).users||{};return send(res,200,{ok:true,users:users().map(z=>({...publicTarget(z),status:z.status,role:z.role||'user',permissions:perms(z),client:meta[z.userId]||null}))},origin)}
 if(req.method==='POST'&&u.pathname==='/api/admin/v1/features/permissions'){const x=requireAdmin(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const target=users().find(z=>z.userId===d.userId);if(!target)return send(res,404,{ok:false,error:'User not found'},origin);if(target.role==='admin')return send(res,400,{ok:false,error:'Admin permissions are always enabled'},origin);const out={};for(const k of ALL_KEYS)if(Object.prototype.hasOwnProperty.call(d.permissions||{},k))out[k]=!!d.permissions[k];const db=readJson(FEATURES_FILE,{schema:'motolab_features_v1',users:{}});db.users=db.users||{};db.users[target.userId]={...(db.users[target.userId]||{}),...out,updatedAt:new Date().toISOString(),updatedBy:x.user.userId};atomic(FEATURES_FILE,db);return send(res,200,{ok:true,permissions:perms(target)},origin)}
 return listener(req,res)});};
console.log('MotoLab user features server: prepared');
