(() => {
'use strict';
const VERSION='motolab-admin-pending-notify-v1';
const TOKEN_KEY='motolab_v32_beta_token';
const SEEN_KEY='motolab_admin_pending_seen_v1';
const PERMISSION_HINT_KEY='motolab_admin_notify_hint_v1';
const POLL_MS=30000;
let timer=0,banner=null,lastPendingSig='';
const api=()=>globalThis.MotoLabUser?.productionServer||'https://v-n-autodyno-production.up.railway.app';
const token=()=>localStorage.getItem(TOKEN_KEY)||'';
const me=()=>globalThis.MotoLabUser?.user||null;
const isAdmin=()=>me()?.role==='admin'&&me()?.status==='active';
function seen(){try{return new Set(JSON.parse(localStorage.getItem(SEEN_KEY)||'[]'))}catch{return new Set()}}
function saveSeen(s){localStorage.setItem(SEEN_KEY,JSON.stringify([...s].slice(-200)))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function users(){if(!token()||!isAdmin())return[];const r=await fetch(api()+'/api/admin/v1/users',{headers:{'X-MotoLab-Beta-Token':token()},cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();return Array.isArray(j.users)?j.users:[]}
function removeBanner(){banner?.remove();banner=null}
function openApprovals(){removeBanner();globalThis.MotoLabUser?.adminUsers?.('Uusi käyttäjä odottaa hyväksyntää.')}
function style(){if(document.getElementById('mlAdminNotifyStyle'))return;const s=document.createElement('style');s.id='mlAdminNotifyStyle';s.textContent=`.ml-admin-pending-banner{position:fixed;left:12px;right:12px;top:calc(12px + env(safe-area-inset-top));z-index:1000500;background:#12080bfa;border:2px solid #ff263f;border-radius:16px;padding:12px 13px;color:#fff;box-shadow:0 12px 40px #000c;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.ml-admin-pending-title{font-size:14px;font-weight:1000}.ml-admin-pending-copy{margin-top:4px;color:#d7d9dd;font-size:10px}.ml-admin-pending-actions{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:9px}.ml-admin-pending-actions button{border-radius:10px;border:1px solid #555;background:#15181d;color:#fff;padding:9px;font-weight:900}.ml-admin-pending-actions button:first-child{background:#b20e22;border-color:#ff263f}`;document.head.appendChild(s)}
function showBanner(pending){style();removeBanner();banner=document.createElement('div');banner.className='ml-admin-pending-banner';const names=pending.map(x=>x.nickname||'Nimetön').join(', ');banner.innerHTML=`<div class="ml-admin-pending-title">UUSI KÄYTTÄJÄ ODOTTAA HYVÄKSYNTÄÄ</div><div class="ml-admin-pending-copy">${esc(names)}${pending.length>1?' • '+pending.length+' käyttäjää':''}</div><div class="ml-admin-pending-actions"><button type="button">AVAA HYVÄKSYNNÄT</button><button type="button">×</button></div>`;document.body.appendChild(banner);const [open,close]=banner.querySelectorAll('button');open.onclick=openApprovals;close.onclick=removeBanner}
async function requestPermission(){if(!('Notification'in window))return'unsupported';try{return await Notification.requestPermission()}catch{return Notification.permission||'denied'}}
async function systemNotify(pending){if(!('Notification'in window)||Notification.permission!=='granted')return;const title='VÄNÄ MotorLab';const names=pending.map(x=>x.nickname||'Nimetön').join(', ');const body=pending.length===1?`${names} odottaa hyväksyntää.`:`${pending.length} käyttäjää odottaa hyväksyntää: ${names}`;try{const reg=await navigator.serviceWorker?.ready;if(reg?.showNotification)await reg.showNotification(title,{body,tag:'motolab-pending-users',renotify:true,icon:'./icon-192.png',badge:'./icon-192.png',data:{url:location.pathname+'?adminUsers=1'}});else new Notification(title,{body,tag:'motolab-pending-users'})}catch{try{new Notification(title,{body,tag:'motolab-pending-users'})}catch{}}}
function permissionHint(){if(!isAdmin()||!('Notification'in window)||Notification.permission!=='default'||localStorage.getItem(PERMISSION_HINT_KEY))return;style();const x=document.createElement('div');x.className='ml-admin-pending-banner';x.innerHTML=`<div class="ml-admin-pending-title">OTA KÄYTTÄJÄILMOITUKSET KÄYTTÖÖN</div><div class="ml-admin-pending-copy">Saat ilmoituksen näytölle, kun uusi käyttäjä odottaa hyväksyntää.</div><div class="ml-admin-pending-actions"><button type="button">SALLI ILMOITUKSET</button><button type="button">MYÖHEMMIN</button></div>`;document.body.appendChild(x);const [yes,no]=x.querySelectorAll('button');yes.onclick=async()=>{localStorage.setItem(PERMISSION_HINT_KEY,'1');await requestPermission();x.remove();check(true)};no.onclick=()=>{localStorage.setItem(PERMISSION_HINT_KEY,'1');x.remove()}}
async function check(force=false){if(!isAdmin())return;let list;try{list=await users()}catch{return}const pending=list.filter(u=>u.status==='pending'&&u.role!=='admin');const sig=pending.map(u=>u.userId).sort().join('|');if(!pending.length){lastPendingSig='';removeBanner();return}const s=seen(),fresh=pending.filter(u=>!s.has(u.userId));if(force||fresh.length||sig!==lastPendingSig){showBanner(pending);if(fresh.length||force)await systemNotify(fresh.length?fresh:pending);for(const u of pending)s.add(u.userId);saveSeen(s)}lastPendingSig=sig}
function handleDeepLink(){const p=new URLSearchParams(location.search);if(!p.has('adminUsers'))return;const clean=()=>{p.delete('adminUsers');history.replaceState(null,'',location.pathname+(p.toString()?'?'+p:'')+location.hash)};let n=0;const t=setInterval(()=>{if(isAdmin()&&globalThis.MotoLabUser?.adminUsers){clearInterval(t);clean();openApprovals()}else if(++n>40){clearInterval(t);clean()}},250)}
function start(){clearInterval(timer);if(!isAdmin())return;permissionHint();check(true);timer=setInterval(()=>check(false),POLL_MS);handleDeepLink()}
document.addEventListener('motorlab-user-ready',()=>setTimeout(start,200));document.addEventListener('visibilitychange',()=>{if(!document.hidden)check(false)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,1200),{once:true});else setTimeout(start,1200);
globalThis.MotoLabAdminPendingNotify={version:VERSION,check,requestPermission,openApprovals};
})();
