(() => {
'use strict';
const VERSION='motolab-app-shell-v34.0';
const $=id=>document.getElementById(id);
let lastSig='',timer=0;
function tr(s){return globalThis.MotoLabI18n?.t?.(s)||s}
function user(){return globalThis.MotoLabUser?.user||null}
function isAdmin(){const u=user();return !!(u&&u.role==='admin'&&u.status==='active')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(text){let e=$('mlShellToast');if(!e){e=document.createElement('div');e.id='mlShellToast';document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function invoke(fn,fallback){try{if(typeof fn!=='function')return toast(tr(fallback||'Toiminto ei ole vielä latautunut.'));const r=fn();if(r?.catch)r.catch(e=>toast(e?.message||String(e)));return r}catch(e){toast(e?.message||String(e))}}
function account(){const p=$('motolabUserPill');if(p)return p.click();const u=user();toast(u?`${u.nickname} • ${u.status}`:tr('Ei aktiivista käyttäjäistuntoa'))}
function approvals(){const p=$('motolabUserPill');if(!p)return toast(tr('Käyttäjäpaneeli ei ole vielä valmis.'));p.click();setTimeout(()=>{const b=$('muiLoadUsers');if(b)b.click();else toast(tr('Hyväksyntänäkymä ei ole vielä latautunut.'))},80)}
async function invite(){try{const x=await globalThis.MotoLabUser?.createInvite?.();if(!x?.url)throw Error(tr('Kutsua ei voitu luoda.'));if(navigator.share)await navigator.share({title:'VÄNÄ MotoLab',text:'MotoLab beta',url:x.url});else if(navigator.clipboard){await navigator.clipboard.writeText(x.url);toast(tr('Kutsulinkki kopioitu.'))}else toast(x.url)}catch(e){if(e?.name!=='AbortError')toast(e?.message||String(e))}}
function styles(){if($('mlShellStyle'))return;const s=document.createElement('style');s.id='mlShellStyle';s.textContent=`
#mlBetaMenuBtn,#motolabUserPill{display:none!important}
#mlUserBetaPanel{border-color:rgba(255,38,63,.55);overflow:visible}
.mlShellHead{padding:12px 11px 5px;display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.mlShellHead h2{margin:0;font-size:15px;font-style:italic}.mlShellIdentity{font-size:8px;color:#aeb4bc;margin-top:4px}.mlShellBadge{padding:4px 7px;border-radius:999px;border:1px solid #3b4049;background:#11151a;font-size:7px;font-weight:1000;color:#cdd2d9;white-space:nowrap}.mlShellBadge.admin{border-color:#ff263f;color:#fff;background:#3b0b12}
.mlShellGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:8px}.mlShellBtn{min-height:62px;border:1px solid #343942;border-radius:12px;background:linear-gradient(#151920,#0b0d11);color:#fff;text-align:left;padding:9px}.mlShellBtn b{display:block;font-size:10px}.mlShellBtn small{display:block;color:#9da5af;font-size:7px;line-height:1.35;margin-top:4px}.mlShellBtn.red{border-color:#ff263f;background:linear-gradient(#431019,#1c080c)}.mlShellBtn.blue{border-color:#2878ff;background:linear-gradient(#102449,#091328)}.mlShellBtn.purple{border-color:#a44cff;background:linear-gradient(#2b1246,#13091f)}
.mlShellSection{padding:8px 10px 2px;color:#b5bbc4;font-size:8px;font-weight:1000;letter-spacing:.08em;text-transform:uppercase}.mlShellLang{margin:8px;padding:10px;border-radius:12px;background:#090b0e;border:1px solid #2c3037;display:grid;grid-template-columns:1fr 1fr;gap:8px;align-items:end}.mlShellLang label{font-size:8px;font-weight:900;color:#afb5be}.mlShellLang select{margin-top:5px}.mlShellLang .note{font-size:7px;color:#8f96a0;line-height:1.4}
#mlShellToast{position:fixed;top:calc(12px + env(safe-area-inset-top));left:50%;transform:translate(-50%,-10px);z-index:350000;border:1px solid #ff263f;background:#101318;color:#fff;padding:9px 13px;border-radius:999px;font:800 9px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;opacity:0;pointer-events:none;transition:.18s}#mlShellToast.show{opacity:1;transform:translate(-50%,0)}
body:not(.dev-mode):not([data-motolab-admin="1"]) #screen-settings>.panel.mlShellDeep{display:none!important}
.bottomNav .nav[data-screen="measure"]{order:1}.bottomNav .nav[data-screen="runs"]{order:2}.bottomNav .nav[data-screen="live"]{order:3}.bottomNav .nav[data-screen="analysis"]{order:4}.bottomNav .nav[data-screen="settings"]{order:5}.bottomNav .nav[data-screen="autotune"]{order:6}
`;document.head.appendChild(s)}
function markDeepPanels(){const screen=$('screen-settings');if(!screen)return;screen.querySelectorAll(':scope > .panel').forEach(p=>{if(p.id==='mlUserBetaPanel')return;const t=(p.querySelector('.ptitle')?.textContent||'').toUpperCase();if(/RAW AUDIO FINGERPRINT|MIC CALIBRATION|JÄRJESTELMÄTESTI/.test(t))p.classList.add('mlShellDeep')})}
function button(act,title,desc,cls=''){return `<button type="button" class="mlShellBtn ${cls}" data-mlact="${act}"><b>${esc(title)}</b><small>${esc(desc)}</small></button>`}
function panelHtml(){const u=user(),admin=isAdmin(),nick=u?.nickname||tr('Ei aktiivista käyttäjäistuntoa'),status=u?.status||'—';const role=admin?'ADMIN':(u?.status==='active'?'BETA':'');return `<div class="mlShellHead"><div><h2>${esc(tr('KÄYTTÄJÄ / BETA'))}</h2><div class="mlShellIdentity">${esc(nick)} • ${esc(status)}</div></div>${role?`<span class="mlShellBadge ${admin?'admin':''}">${esc(role)}</span>`:''}</div><div class="mlShellLang"><label>${esc(tr('KIELI'))}<select data-motolab-language-select id="mlLanguageSelect"><option value="fi">Suomi</option><option value="en">English</option></select></label><div class="note">${esc(globalThis.MotoLabI18n?.language==='en'?'Language changes presentation only. Measurement state is preserved.':'Kielenvaihto muuttaa vain käyttöliittymän tekstit. Mittaustila säilyy.')}</div></div><div class="mlShellSection">${esc(tr('Omat toiminnot'))}</div><div class="mlShellGrid">${button('account',tr('OMA TILI'),tr('Nimimerkki, tila ja käyttäjä'),'red')}${button('feedback',tr('PALAUTE & VIESTIT'),tr('Yksityinen keskustelu ylläpidon kanssa'))}${button('community',tr('BETA-KESKUSTELU'),tr('Ongelmat, ohjeet ja kokemukset'),'blue')}${button('shares',tr('JAETUT VEDOT'),tr('Jaa ja vertaa graafisia vetoja'))}${button('merit',tr('TESTERITASO'),tr('Oma beta-testeritasosi'),'purple')}${button('invite',tr('KUTSU TESTAAJA'),tr('Jaa kutsu sovelluksen jakovalikolla'))}</div>${admin?`<div class="mlShellSection">${esc(tr('Ylläpito'))}</div><div class="mlShellGrid">${button('approvals',tr('KÄYTTÄJIEN HYVÄKSYNNÄT'),tr('Hyväksy, estä ja tarkista käyttäjät'),'red')}${button('adminfeedback',tr('PALAUTTEET'),tr('Yksityiset käyttäjäkeskustelut'))}${button('adminmerit',tr('MERIT-ARVIOINTI'),tr('Pisteet, ideat ja testeriaktiivisuus'),'purple')}${button('permissions',tr('KÄYTTÖOIKEUDET'),tr('Avaa testitoiminnot käyttäjäkohtaisesti'))}${button('community',tr('YHTEISÖ / DIAGNOSTIIKKA'),tr('Ongelmaketjut ja admin-diagnostiikka'),'blue')}</div>`:''}`}
function wire(panel){panel.querySelectorAll('[data-mlact]').forEach(b=>b.onclick=()=>{switch(b.dataset.mlact){case'account':return account();case'feedback':return invoke(globalThis.MotoLabFeedback?.open,'Palaute ei ole vielä latautunut.');case'community':return invoke(globalThis.MotoLabCommunity?.home,'Beta-keskustelu ei ole vielä latautunut.');case'shares':return invoke(globalThis.MotoLabUserFeatures?.sharingHome,'Vetojen jako ei ole vielä latautunut.');case'merit':return invoke(globalThis.MotoLabMerit?.myPanel,'Testeritaso ei ole vielä latautunut.');case'invite':return invite();case'approvals':return approvals();case'adminfeedback':return invoke(globalThis.MotoLabFeedback?.openAdmin,'Palautteet eivät ole vielä latautuneet.');case'adminmerit':return invoke(globalThis.MotoLabMerit?.adminPanel,'Merit ei ole vielä latautunut.');case'permissions':return invoke(globalThis.MotoLabUserFeatures?.adminPanel,'Käyttöoikeudet eivät ole vielä latautuneet.')}});const sel=$('mlLanguageSelect');if(sel){sel.value=globalThis.MotoLabI18n?.language||'fi';sel.onchange=()=>globalThis.MotoLabI18n?.setLanguage?.(sel.value)}}
function ensureHub(force=false){const screen=$('screen-settings');if(!screen)return false;let p=$('mlUserBetaPanel');const u=user(),sig=JSON.stringify([u?.userId,u?.nickname,u?.status,u?.role,globalThis.MotoLabI18n?.language]);document.body.dataset.motolabAdmin=isAdmin()?'1':'0';if(!p){p=document.createElement('div');p.id='mlUserBetaPanel';p.className='panel';screen.insertBefore(p,screen.firstElementChild);force=true}if(force||sig!==lastSig){lastSig=sig;p.innerHTML=panelHtml();wire(p);globalThis.MotoLabI18n?.apply?.()}markDeepPanels();return true}
function normalizeNav(){const nav=document.querySelector('.bottomNav');if(!nav)return false;const wanted=['measure','runs','live','analysis','settings'];wanted.forEach((name,i)=>{const b=nav.querySelector(`[data-screen="${name}"]`);if(b)b.style.order=String(i+1)});return true}
function boot(){styles();ensureHub(true);normalizeNav();window.addEventListener('motolab-language-change',()=>ensureHub(true));new MutationObserver(()=>{ensureHub(false);normalizeNav();markDeepPanels()}).observe(document.documentElement,{childList:true,subtree:true});timer=setInterval(()=>ensureHub(false),1200);try{if(typeof addLearningEvent==='function')addLearningEvent('app_shell_v34_loaded',{version:VERSION})}catch{}}
globalThis.MotoLabAppShell={version:VERSION,refresh:()=>ensureHub(true),isAdmin};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
