(() => {
'use strict';
const VERSION='motolab-beta-menu-v4';const $=id=>document.getElementById(id);let overlay=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function user(){return globalThis.MotoLabUser?.user||null}function close(){overlay?.remove();overlay=null}
function styles(){if($('mlBetaMenuStyle'))return;const s=document.createElement('style');s.id='mlBetaMenuStyle';s.textContent=`
.mlbm-overlay{position:fixed;inset:0;z-index:290000;background:#000e;display:flex;align-items:flex-end;justify-content:center;padding:calc(96px + env(safe-area-inset-top)) 10px calc(10px + env(safe-area-inset-bottom));color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;box-sizing:border-box}
.mlbm-card{width:min(100%,480px);max-height:calc(100dvh - 116px - env(safe-area-inset-top) - env(safe-area-inset-bottom));overflow:auto;background:#090b0e;border:1px solid #ff263f;border-radius:22px;padding:15px;box-sizing:border-box}
.mlbm-head{display:flex;justify-content:space-between;gap:10px}.mlbm-head h2{margin:2px 0 4px}.mlbm-user{font-size:10px;color:#aeb5bf}.mlbm-grid{display:grid;grid-template-columns:1fr;gap:7px;margin:11px 0}.mlbm-btn{min-height:58px;border:1px solid #30343b;border-radius:12px;background:#111318;color:#fff;text-align:left;padding:10px 12px;font-weight:900;display:flex;align-items:center;gap:10px}.mlbm-btn .ico{font-size:19px;width:25px;text-align:center}.mlbm-btn b{display:block;font-size:11px}.mlbm-btn small{display:block;margin-top:3px;color:#9ba3ae;font-size:8px;font-weight:600}.mlbm-btn.primary{border-color:#ff263f;background:#281014}.mlbm-section{margin:13px 0 5px;font-size:9px;font-weight:1000;color:#9097a1;text-transform:uppercase}.mlbm-close{width:100%;padding:10px;border-radius:10px;border:1px solid #444;background:#11151a;color:#fff;font-weight:900}`;document.head.appendChild(s)}
function toast(t){let e=$('mlbmToast');if(!e){e=document.createElement('div');e.id='mlbmToast';e.style.cssText='position:fixed;top:calc(12px + env(safe-area-inset-top));left:50%;transform:translateX(-50%);z-index:310000;background:#111;color:#fff;border:1px solid #ff263f;border-radius:999px;padding:9px 13px;font:800 9px sans-serif';document.body.appendChild(e)}e.textContent=t;clearTimeout(e._t);e._t=setTimeout(()=>e.remove(),2600)}
function invoke(fn,msg){close();try{if(!fn){toast(msg);return}return fn()}catch(e){toast(e.message||String(e))}}
async function invite(){close();try{const x=await globalThis.MotoLabUser?.createInvite?.();if(!x?.url)throw Error('Kutsua ei voitu luoda.');if(navigator.share)await navigator.share({title:'VäNä MotorLab',text:'MotorLab beta-kutsu',url:x.url});else if(navigator.clipboard){await navigator.clipboard.writeText(x.url);toast('Kutsulinkki kopioitu.')}else toast(x.url)}catch(e){toast(e.message||String(e))}}
function live(){close();const b=document.querySelector('.nav[data-screen="live"]');if(b){b.hidden=false;b.click();return}if(globalThis.MotoLabLiveStatus?.open){globalThis.MotoLabLiveStatus.open();return}toast('LIVE ei ole vielä latautunut.')}
function button(act,ico,title,small,primary=false){return `<button class="mlbm-btn${primary?' primary':''}" data-act="${act}"><span class="ico">${ico}</span><span><b>${title}</b><small>${small}</small></span></button>`}
function openMenu(){close();styles();const u=user(),admin=u?.role==='admin';overlay=document.createElement('div');overlay.className='mlbm-overlay';overlay.innerHTML=`<div class="mlbm-card"><div class="mlbm-head"><div><h2>Käyttäjä</h2><div class="mlbm-user">${u?`${esc(u.nickname)} • ${esc(u.status)}${admin?' • OWNER / ADMIN':''}`:'Ei aktivoitua käyttäjää'}</div></div><div style="font-size:9px;color:#8d949e">${esc(globalThis.MOTOLAB_RELEASE?.label||'')}</div></div><div class="mlbm-section">Omat toiminnot</div><div class="mlbm-grid">${button('account','◎','OMA TILI',u?'Käyttäjä, laite ja pilvitila':'Aktivoi tämä laite',true)}${button('rawdata','▣','OMA RAW-DATA','Näe puhelimen data ja lähetä se nyt')}${button('feedback','✉','PALAUTE & VIESTIT','Yksityinen keskustelu ylläpidon kanssa')}${button('shares','⌘','JAETUT VEDOT','Graafiset jaetut vedot ja vertailu')}${button('community','◉','BETA-YHTEISÖ','Keskustelu, ongelmat ja kokemukset')}${button('merit','★','TESTERITASO','Tester Merit ja oma taso')}${button('live','◌','LIVE / ANTURIT','GPS, MIC, IMU ja tekninen tila')}${button('invite','＋','KUTSU TESTAAJA','Luo henkilökohtainen kutsulinkki')}</div>${admin?`<div class="mlbm-section">Ylläpito</div><div class="mlbm-grid">${button('approvals','✓','KÄYTTÄJÄT / HYVÄKSYNNÄT','pending / active / blocked')}${button('adminfeedback','✉','PALAUTTEET','Yksityiset käyttäjäkeskustelut')}${button('adminmerit','★','MERIT-ARVIOINTI','Laadullinen testeriarviointi')}${button('permissions','⚙','KÄYTTÖOIKEUDET','Käyttäjäkohtaiset beta-ominaisuudet')}</div>`:''}<button class="mlbm-close" id="mlbmClose">SULJE</button></div>`;document.body.appendChild(overlay);$('mlbmClose').onclick=close;overlay.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{const a=b.dataset.act;if(a==='account')return invoke(globalThis.MotoLabUser?.openAccount,'Käyttäjätili ei ole latautunut.');if(a==='rawdata')return invoke(globalThis.MotoLabV34RuntimeFixes?.openResearchRawData,'RAW-data-valikko ei ole latautunut.');if(a==='feedback')return invoke(globalThis.MotoLabFeedback?.open,'Palaute ei ole latautunut.');if(a==='community')return invoke(globalThis.MotoLabCommunity?.home,'Beta-yhteisö ei ole latautunut.');if(a==='shares')return invoke(globalThis.MotoLabUserFeatures?.sharingHome,'Jaetut vedot eivät ole latautuneet.');if(a==='merit')return invoke(globalThis.MotoLabMerit?.myPanel,'Testeritaso ei ole latautunut.');if(a==='live')return live();if(a==='invite')return invite();if(a==='approvals')return invoke(globalThis.MotoLabUser?.adminUsers,'Käyttäjähallinta ei ole latautunut.');if(a==='adminfeedback')return invoke(globalThis.MotoLabFeedback?.openAdmin,'Palautteet eivät ole latautuneet.');if(a==='adminmerit')return invoke(globalThis.MotoLabMerit?.adminPanel,'Merit ei ole latautunut.');if(a==='permissions')return invoke(globalThis.MotoLabUserFeatures?.adminPanel,'Käyttöoikeudet eivät ole latautuneet.')})}
function boot(){styles()}
globalThis.MotoLabBetaMenu={version:VERSION,open:openMenu};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
