(() => {
'use strict';
const VERSION='motolab-community-v1';
const SERVER_KEY='motolab_v32_beta_server',TOKEN_KEY='motolab_v32_beta_token';
let overlay=null,history=[];
const $=id=>document.getElementById(id);
function server(){return String(localStorage.getItem(SERVER_KEY)||'').trim().replace(/\/$/,'').replace(/\/api\/raw\/v1\/chunk$/i,'')}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
async function api(path,opt={}){const r=await fetch(server()+path,{cache:'no-store',...opt,headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':token(),...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function val(ids){for(const id of ids){const e=$(id);if(e&&String(e.textContent||e.value||'').trim())return String(e.textContent||e.value||'').trim()}return null}
function sample(){let sensors=null,queues=null;try{sensors=globalThis.MOTOLAB_DIAGNOSTICS?.getSensorSnapshot?.()||null;queues=globalThis.MOTOLAB_DIAGNOSTICS?.getQueueSummary?.()||null}catch{}const s={t:Date.now(),rpm:num(globalThis.currentRPM??globalThis.rpm??globalThis.displayRpm)??val(['rpmVal','rpmValue','rpm']),speed:num(globalThis.speedKmh??globalThis.gpsSpeedKmh??globalThis.currentSpeed)??val(['speedVal','speedValue','speed']),gear:num(globalThis.currentGear??globalThis.gear)??val(['gearVal','gearValue','gear']),rpmSource:globalThis.rpmControlAuthority||globalThis.rpmSource||val(['rpmSource','rpmSourceVal']),rpmConfidence:num(globalThis.rpmConfidence??globalThis.audioRpmConfidence),gpsAccuracy:num(globalThis.gpsAccuracy??globalThis.lastGpsAccuracy),sensors,queues};history.push(s);if(history.length>65)history=history.slice(-65)}
function diagnosticPackage(){let events=[];try{events=globalThis.MOTOLAB_DIAGNOSTICS?.getEvents?.()||[]}catch{}const cut=Date.now()-60000;events=events.filter(e=>Number(e.t||0)>=cut).slice(-200);let profile=null;try{profile=localStorage.getItem('motolab_v26_active_profile')||localStorage.getItem('motolab_active_profile')||null}catch{}return {schema:'motolab_private_issue_diagnostic_v1',capturedAt:new Date().toISOString(),release:globalThis.MOTOLAB_RELEASE||null,platform:navigator.platform||'',userAgent:navigator.userAgent||'',language:navigator.language||'',online:navigator.onLine,profile,history:history.filter(x=>x.t>=cut),events,sensors:globalThis.MOTOLAB_DIAGNOSTICS?.getSensorSnapshot?.()||null,queues:globalThis.MOTOLAB_DIAGNOSTICS?.getQueueSummary?.()||null}}
function clientMeta(){return {release:globalThis.MOTOLAB_RELEASE||null,platform:navigator.platform||'',userAgent:navigator.userAgent||''}}
function style(){if($('mlCommunityStyle'))return;const s=document.createElement('style');s.id='mlCommunityStyle';s.textContent=`#mlCommunityPill{position:fixed;left:10px;bottom:calc(10px + env(safe-area-inset-bottom));z-index:119999;border:1px solid #2878ff;background:#08101ce8;color:#fff;border-radius:999px;padding:7px 11px;font:900 9px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mlc-overlay{position:fixed;inset:0;z-index:270000;background:#000e;display:flex;align-items:flex-end;justify-content:center;padding:10px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mlc-card{width:min(100%,500px);max-height:94vh;overflow:auto;background:#0a0d12;border:1px solid #2878ff;border-radius:20px;padding:14px}.mlc-card h2,.mlc-card h3{margin:5px 0 10px}.mlc-row{border:1px solid #252b34;border-radius:12px;padding:10px;margin:7px 0;background:#0c1118}.mlc-row small{display:block;color:#98a1ae;margin-top:4px}.mlc-btn{width:100%;padding:10px;margin-top:7px;border-radius:10px;border:1px solid #2878ff;background:#1251c9;color:#fff;font-weight:900}.mlc-btn.gray{background:#15191f;border-color:#444}.mlc-btn.green{background:#0b6b2b;border-color:#19a64b}.mlc-input,.mlc-select,.mlc-text{box-sizing:border-box;width:100%;padding:10px;margin:5px 0 9px;border:1px solid #343b46;border-radius:10px;background:#05070a;color:#fff}.mlc-text{min-height:110px}.mlc-comment{border-top:1px solid #252b34;padding:9px 0}.mlc-solution{border:1px solid #19984a;border-radius:10px;padding:9px;background:#07180d}.mlc-private{font-size:9px;color:#8fb6ff}.mlc-code{white-space:pre-wrap;word-break:break-word;font-size:8px;max-height:42vh;overflow:auto;background:#050608;border:1px solid #252a31;border-radius:8px;padding:8px}`;document.head.appendChild(s)}
function close(){overlay?.remove();overlay=null}
function open(html){close();overlay=document.createElement('div');overlay.className='mlc-overlay';overlay.innerHTML=`<div class="mlc-card">${html}<button class="mlc-btn gray" id="mlcClose">SULJE</button></div>`;document.body.appendChild(overlay);$('mlcClose').onclick=close;return overlay}
function statusName(s){return ({open:'AVOIN',working:'TYÖN ALLA',resolved:'RATKAISU LÖYTYI',fixed:'KORJATTU',not_reproduced:'EI TOISTUNUT'})[s]||s}
async function home(){try{const [j,me]=await Promise.all([api('/api/community/v1/issues'),api('/api/users/v1/me')]);open(`<h2>BETA – Keskustelu</h2><p>Ilmoita ongelmasta, kysy neuvoa tai jaa kokemuksia. Tekninen diagnostiikkadata näkyy vain ylläpidolle.</p><button class="mlc-btn" id="mlcNew">+ ILMOITA ONGELMA</button><button class="mlc-btn gray" id="mlcContact">YHTEYSTAPA</button>${me.user?.role==='admin'?'<button class="mlc-btn gray" id="mlcContacts">KÄYTTÄJIEN YHTEYSTIEDOT</button>':''}<h3>Aiheet</h3>${j.issues.length?j.issues.map(i=>`<div class="mlc-row" data-issue="${esc(i.issueId)}"><b>${esc(i.title)}</b><small>${esc(i.category)} • ${statusName(i.status)} • ${i.sameCount} sama ongelma • ${i.comments.length} vastausta</small></div>`).join(''):'<div class="mlc-row">Ei ilmoituksia vielä.</div>'}`);$('mlcNew').onclick=newIssue;$('mlcContact').onclick=contactPanel;if(me.user?.role==='admin')$('mlcContacts').onclick=adminContacts;document.querySelectorAll('[data-issue]').forEach(e=>e.onclick=()=>issue(e.dataset.issue))}catch(e){open(`<h2>Beta-keskustelu</h2><p>${esc(e.message)}</p>`)}}
function newIssue(){open(`<h2>Ilmoita ongelma</h2><label>Otsikko</label><input id="mlcTitle" class="mlc-input" maxlength="120"><label>Kategoria</label><select id="mlcCategory" class="mlc-select"><option>Ongelma</option><option>Kysymys</option><option>Kehitysidea</option><option>Risut</option><option>Ruusut</option></select><label>Kuvaus</label><textarea id="mlcDesc" class="mlc-text" placeholder="Kerro mitä tapahtui ja mitä olit tekemässä."></textarea><div class="mlc-private">Lähetykseen liitetään automaattisesti noin 60 sekunnin tekninen diagnostiikka vain ylläpidon käyttöön. Muut käyttäjät eivät näe sitä.</div><button class="mlc-btn" id="mlcSendIssue">LÄHETÄ</button><div id="mlcStatus"></div>`);$('mlcSendIssue').onclick=async()=>{const title=$('mlcTitle').value.trim(),description=$('mlcDesc').value.trim();if(!title||!description)return $('mlcStatus').textContent='Täytä otsikko ja kuvaus.';try{const j=await api('/api/community/v1/issues',{method:'POST',body:JSON.stringify({title,description,category:$('mlcCategory').value,diagnostic:diagnosticPackage(),client:clientMeta()})});await issue(j.issue.issueId)}catch(e){$('mlcStatus').textContent=e.message}}}
async function issue(id){const [j,me]=await Promise.all([api('/api/community/v1/issue?id='+encodeURIComponent(id)),api('/api/users/v1/me')]);const i=j.issue,admin=me.user?.role==='admin';open(`<h2>${esc(i.title)}</h2><div class="mlc-row"><b>${esc(i.nickname)}</b><small>${esc(i.category)} • ${statusName(i.status)} • ${i.sameCount} käyttäjää</small><div>${esc(i.description)}</div></div><button class="mlc-btn green" id="mlcSame">MINULLA SAMA ONGELMA (${i.sameCount})</button><h3>Vastaukset</h3>${i.comments.map(c=>`<div class="mlc-comment ${c.isSolution?'mlc-solution':''}"><b>${esc(c.nickname)}${c.isSolution?' • TOIMIVA RATKAISU':''}</b><div>${esc(c.text)}</div>${admin&&!c.isSolution?`<button class="mlc-btn gray" data-solution="${esc(c.commentId)}">MERKITSE RATKAISUKSI</button>`:''}</div>`).join('')||'<div class="mlc-row">Ei vastauksia vielä.</div>'}<textarea id="mlcReply" class="mlc-text" placeholder="Kirjoita ohje tai vastaus..."></textarea><button class="mlc-btn" id="mlcReplyBtn">LÄHETÄ VASTAUS</button>${admin?`<h3>Ylläpito</h3><select id="mlcIssueStatus" class="mlc-select"><option value="open">AVOIN</option><option value="working">TYÖN ALLA</option><option value="resolved">RATKAISU LÖYTYI</option><option value="fixed">KORJATTU</option><option value="not_reproduced">EI TOISTUNUT</option></select><button class="mlc-btn gray" id="mlcSetStatus">PÄIVITÄ TILA</button><button class="mlc-btn gray" id="mlcDiag">NÄYTÄ YKSITYINEN DIAGNOSTIIKKA</button>`:''}<div id="mlcStatus"></div>`);$('mlcSame').onclick=async()=>{try{const r=await api('/api/community/v1/same',{method:'POST',body:JSON.stringify({issueId:id,diagnostic:diagnosticPackage(),client:clientMeta()})});$('mlcSame').textContent=`MINULLA SAMA ONGELMA (${r.sameCount})`}catch(e){$('mlcStatus').textContent=e.message}};$('mlcReplyBtn').onclick=async()=>{const text=$('mlcReply').value.trim();if(!text)return;try{await api('/api/community/v1/comments',{method:'POST',body:JSON.stringify({issueId:id,text})});await issue(id)}catch(e){$('mlcStatus').textContent=e.message}};document.querySelectorAll('[data-solution]').forEach(b=>b.onclick=async()=>{await api('/api/admin/v1/community/solution',{method:'POST',body:JSON.stringify({issueId:id,commentId:b.dataset.solution})});await issue(id)});if(admin){$('mlcIssueStatus').value=i.status;$('mlcSetStatus').onclick=async()=>{await api('/api/admin/v1/community/status',{method:'POST',body:JSON.stringify({issueId:id,status:$('mlcIssueStatus').value})});await issue(id)};$('mlcDiag').onclick=()=>adminDiagnostics(id)}}
async function adminDiagnostics(id){try{const j=await api('/api/admin/v1/community/diagnostics?issueId='+encodeURIComponent(id));open(`<h2>Yksityinen diagnostiikka</h2><p class="mlc-private">Vain ylläpidolle. Ei näy muille beta-käyttäjille.</p><div class="mlc-code">${esc(JSON.stringify(j.item,null,2))}</div>`)}catch(e){open(`<h2>Diagnostiikka</h2><p>${esc(e.message)}</p>`)}}
async function contactPanel(){let c=null;try{c=(await api('/api/users/v1/contact')).contact}catch{}open(`<h2>Yhteystapa</h2><p>Tämä tieto näkyy vain ylläpidolle. WhatsApp on kätevä, mutta voit käyttää myös muuta yhteystapaa.</p><select id="mlcContactMethod" class="mlc-select"><option>WhatsApp</option><option>Puhelin</option><option>Sähköposti</option><option>Telegram</option><option>Muu</option><option>Ei yhteystietoa</option></select><input id="mlcContactValue" class="mlc-input" placeholder="Numero, osoite tai tunnus" value="${esc(c?.value||'')}"><button class="mlc-btn" id="mlcSaveContact">TALLENNA</button><div id="mlcStatus"></div>`);if(c?.method)$('mlcContactMethod').value=c.method;$('mlcSaveContact').onclick=async()=>{try{await api('/api/users/v1/contact',{method:'POST',body:JSON.stringify({method:$('mlcContactMethod').value,value:$('mlcContactValue').value.trim()})});$('mlcStatus').textContent='Yhteystapa tallennettu vain ylläpidolle.'}catch(e){$('mlcStatus').textContent=e.message}}}
async function adminContacts(){try{const j=await api('/api/admin/v1/contacts');open(`<h2>Käyttäjien yhteystiedot</h2>${j.users.map(u=>`<div class="mlc-row"><b>${esc(u.nickname)}</b><small>${esc(u.contact?.method||'Ei ilmoitettu')} • ${esc(u.contact?.value||'')}</small></div>`).join('')}`)}catch(e){open(`<h2>Yhteystiedot</h2><p>${esc(e.message)}</p>`)}}
function enhanceAccount(){const p=$('motolabUserPanel');if(!p||p.dataset.communityEnhanced)return;p.dataset.communityEnhanced='1';const card=p.querySelector('.mui-card'),closeBtn=$('muiClose');if(!card||!closeBtn)return;const b=document.createElement('button');b.className='mui-btn secondary';b.textContent='BETA-KESKUSTELU / ONGELMAT';b.onclick=home;card.insertBefore(b,closeBtn);const w=document.createElement('button');w.className='mui-btn secondary';w.textContent='KUTSU WHATSAPPILLA';w.onclick=async()=>{try{const x=await globalThis.MotoLabUser?.createInvite?.();if(!x?.url)return;const text='VÄNÄ MotoLab beta-kutsu: '+x.url;location.href='https://wa.me/?text='+encodeURIComponent(text)}catch{}};card.insertBefore(w,closeBtn)}
function pill(){if($('mlCommunityPill')||!token()||!server())return;const b=document.createElement('button');b.id='mlCommunityPill';b.textContent='BETA';b.onclick=home;document.body.appendChild(b)}
function boot(){style();sample();setInterval(sample,1000);pill();enhanceAccount();new MutationObserver(()=>{pill();enhanceAccount()}).observe(document.documentElement,{childList:true,subtree:true})}
globalThis.MotoLabCommunity={version:VERSION,home,diagnosticPackage,get history(){return history.slice()}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
