(() => {
'use strict';
const VERSION='motolab-feedback-v1';
const TOKEN_KEY='motolab_v32_beta_token';
const SERVER_KEY='motolab_v32_beta_server';
const nativeFetch=window.fetch.bind(window);
const $=id=>document.getElementById(id);
function server(){return String(localStorage.getItem(SERVER_KEY)||'').trim().replace(/\/$/,'').replace(/\/api\/raw\/v1\/chunk$/i,'')}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){const s=server();if(!s)throw Error('MotoLab server missing');const h={'Content-Type':'application/json',...(opt.headers||{})};if(token())h['X-MotoLab-Beta-Token']=token();const r=await nativeFetch(s+path,{cache:'no-store',...opt,headers:h});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
function styles(){if($('motolabFeedbackStyle'))return;const s=document.createElement('style');s.id='motolabFeedbackStyle';s.textContent=`#motolabFeedbackBtn{position:fixed;left:10px;bottom:calc(10px + env(safe-area-inset-bottom));z-index:119999;border:1px solid #555;background:#0b0c0fe8;color:#fff;border-radius:999px;padding:7px 10px;font:800 9px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}#motolabFeedbackOverlay{position:fixed;inset:0;z-index:245000;background:#000d;display:flex;align-items:flex-end;justify-content:center;padding:12px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mfb-card{width:min(100%,460px);background:#0b0c0f;border:1px solid #ff263f;border-radius:22px;padding:18px;box-shadow:0 24px 80px #000}.mfb-card h2{margin:4px 0 10px}.mfb-card select,.mfb-card textarea,.mfb-card input{box-sizing:border-box;width:100%;margin:6px 0;padding:10px;border:1px solid #333;border-radius:10px;background:#050608;color:#fff}.mfb-card textarea{min-height:130px;resize:vertical}.mfb-btn{width:100%;margin-top:8px;padding:11px;border-radius:10px;border:1px solid #ff263f;background:#a80d20;color:#fff;font-weight:900}.mfb-btn.secondary{background:#111;border-color:#444}.mfb-status{font-size:10px;color:#c7cbd0;margin-top:8px}.mfb-list{max-height:45vh;overflow:auto}.mfb-item{border:1px solid #292b31;border-radius:12px;padding:9px;margin:7px 0}.mfb-item small{display:block;color:#999;margin:4px 0}.mfb-item p{white-space:pre-wrap;font-size:11px}`;document.head.appendChild(s)}
function close(){const o=$('motolabFeedbackOverlay');if(o)o.remove()}
async function submit(category,message,status){const release=globalThis.MOTOLAB_RELEASE||{};const j=await api('/api/feedback/v1/comment',{method:'POST',body:JSON.stringify({category,message,appVersion:[release.label,release.build].filter(Boolean).join(' • '),page:location.pathname+location.search})});status.textContent='Palaute lähetetty • '+j.feedbackId;return j}
function openFeedback(){close();const o=document.createElement('div');o.id='motolabFeedbackOverlay';o.innerHTML=`<div class="mfb-card"><h2>Palaute / kommentti</h2><div style="font-size:10px;color:#bbb">Lähetä ongelma, päivitysidea tai kehitysehdotus suoraan MotoLab-ylläpidolle.</div><select id="mfbCategory"><option value="problem">Ongelma / vika</option><option value="update">Päivitys</option><option value="development">Kehitysehdotus</option><option value="other">Muu kommentti</option></select><textarea id="mfbMessage" maxlength="5000" placeholder="Kirjoita kommentti tähän..."></textarea><button class="mfb-btn" id="mfbSend">LÄHETÄ</button><div id="mfbStatus" class="mfb-status"></div><button class="mfb-btn secondary" id="mfbClose">SULJE</button></div>`;document.body.appendChild(o);$('mfbClose').onclick=close;$('mfbSend').onclick=async()=>{const st=$('mfbStatus'),msg=$('mfbMessage').value.trim();if(!msg){st.textContent='Kirjoita kommentti ensin.';return}st.textContent='Lähetetään…';try{await submit($('mfbCategory').value,msg,st);$('mfbMessage').value=''}catch(e){st.textContent='Lähetys epäonnistui • '+e.message}}}
async function openAdminFeedback(){close();const o=document.createElement('div');o.id='motolabFeedbackOverlay';o.innerHTML=`<div class="mfb-card"><h2>Käyttäjäpalautteet</h2><div id="mfbAdminList" class="mfb-list">Haetaan…</div><div id="mfbStatus" class="mfb-status"></div><button class="mfb-btn secondary" id="mfbClose">SULJE</button></div>`;document.body.appendChild(o);$('mfbClose').onclick=close;const box=$('mfbAdminList');try{const j=await api('/api/admin/v1/feedback');if(!j.items.length){box.textContent='Ei palautteita.';return}box.innerHTML=j.items.map(x=>`<div class="mfb-item"><b>${esc(x.nickname||x.userId)} • ${esc(x.category)}</b><small>${esc(x.createdAt)} • ${esc(x.status)} • ${esc(x.deviceId)}</small><p>${esc(x.message)}</p><button data-fb="${esc(x.feedbackId)}" data-status="reviewing">KÄSITTELYYN</button> <button data-fb="${esc(x.feedbackId)}" data-status="done">VALMIS</button></div>`).join('');box.querySelectorAll('button[data-fb]').forEach(b=>b.onclick=async()=>{try{await api('/api/admin/v1/feedback-status',{method:'POST',body:JSON.stringify({feedbackId:b.dataset.fb,status:b.dataset.status})});await openAdminFeedback()}catch(e){$('mfbStatus').textContent=e.message}})}catch(e){box.textContent=e.message}}
function install(){styles();if($('motolabFeedbackBtn'))return;const b=document.createElement('button');b.id='motolabFeedbackBtn';b.textContent='PALAUTE';b.onclick=openFeedback;document.body.appendChild(b);const watch=setInterval(()=>{const u=window.MotoLabUser?.user;if(u?.role==='admin'&&u.status==='active'&&!$('motolabAdminFeedbackBtn')){const a=document.createElement('button');a.id='motolabAdminFeedbackBtn';a.className='mui-user-pill';a.style.bottom='calc(44px + env(safe-area-inset-bottom))';a.textContent='PALAUTTEET';a.onclick=openAdminFeedback;document.body.appendChild(a);clearInterval(watch)}},1200)}
window.MotoLabFeedback={version:VERSION,open:openFeedback,openAdmin:openAdminFeedback};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
