(() => {
'use strict';
const VERSION='motolab-feedback-v2';
const TOKEN_KEY='motolab_v32_beta_token';
const SERVER_KEY='motolab_v32_beta_server';
const nativeFetch=window.fetch.bind(window);
const $=id=>document.getElementById(id);
function server(){return String(localStorage.getItem(SERVER_KEY)||'').trim().replace(/\/$/,'').replace(/\/api\/raw\/v1\/chunk$/i,'')}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){const s=server();if(!s)throw Error('MotoLab server missing');const h={'Content-Type':'application/json',...(opt.headers||{})};if(token())h['X-MotoLab-Beta-Token']=token();const r=await nativeFetch(s+path,{cache:'no-store',...opt,headers:h});let j={};try{j=await r.json()}catch{}if(!r.ok){const e=Error(j.error||('HTTP '+r.status));e.data=j;throw e}return j}
function statusName(s){return ({new:'UUSI',waiting_admin:'ODOTTAA YLLÄPITOA',waiting_user:'ODOTTAA KÄYTTÄJÄÄ',working:'TYÖN ALLA',resolved:'RATKAISTU'})[s]||s}
function styles(){if($('motolabFeedbackStyle'))return;const s=document.createElement('style');s.id='motolabFeedbackStyle';s.textContent=`#motolabFeedbackBtn{position:fixed;left:10px;bottom:calc(44px + env(safe-area-inset-bottom));z-index:119999;border:1px solid #555;background:#0b0c0fe8;color:#fff;border-radius:999px;padding:7px 10px;font:800 9px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}#motolabFeedbackOverlay{position:fixed;inset:0;z-index:275000;background:#000e;display:flex;align-items:flex-end;justify-content:center;padding:12px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mfb-card{width:min(100%,480px);max-height:94vh;overflow:auto;background:#0b0c0f;border:1px solid #ff263f;border-radius:22px;padding:16px;box-shadow:0 24px 80px #000}.mfb-card h2,.mfb-card h3{margin:4px 0 10px}.mfb-card select,.mfb-card textarea,.mfb-card input{box-sizing:border-box;width:100%;margin:6px 0;padding:10px;border:1px solid #333;border-radius:10px;background:#050608;color:#fff}.mfb-card textarea{min-height:100px;resize:vertical}.mfb-btn{width:100%;margin-top:8px;padding:11px;border-radius:10px;border:1px solid #ff263f;background:#a80d20;color:#fff;font-weight:900}.mfb-btn.secondary{background:#111;border-color:#444}.mfb-btn.blue{background:#113a80;border-color:#2878ff}.mfb-status{font-size:10px;color:#c7cbd0;margin-top:8px}.mfb-list{max-height:58vh;overflow:auto}.mfb-item{border:1px solid #292b31;border-radius:12px;padding:9px;margin:7px 0}.mfb-item small{display:block;color:#999;margin:4px 0}.mfb-msg{border-radius:10px;padding:9px;margin:7px 0;font-size:11px;white-space:pre-wrap}.mfb-msg.user{background:#11151a;border:1px solid #30343b}.mfb-msg.admin{background:#241015;border:1px solid #7f2633}.mfb-msg small{font-size:8px;color:#9ca2aa}.mfb-private{font-size:9px;color:#aab2bd}`;document.head.appendChild(s)}
function close(){const o=$('motolabFeedbackOverlay');if(o)o.remove()}
function overlay(html){close();const o=document.createElement('div');o.id='motolabFeedbackOverlay';o.innerHTML=`<div class="mfb-card">${html}<button class="mfb-btn secondary" id="mfbClose">SULJE</button></div>`;document.body.appendChild(o);$('mfbClose').onclick=close;return o}
async function submit(category,message,status){const release=globalThis.MOTOLAB_RELEASE||{};const j=await api('/api/feedback/v1/comment',{method:'POST',body:JSON.stringify({category,message,appVersion:[release.label,release.build].filter(Boolean).join(' • '),page:location.pathname+location.search})});status.textContent='Yksityinen keskustelu avattu.';return j}
function renderMessages(messages){return (messages||[]).map(m=>`<div class="mfb-msg ${m.authorRole==='admin'?'admin':'user'}"><small>${m.authorRole==='admin'?'YLLÄPITO':'SINÄ'} • ${esc(m.createdAt)}</small>${esc(m.text)}</div>`).join('')}
async function openFeedback(){overlay(`<h2>Palaute / yksityisviestit</h2><p class="mfb-private">Tämä alue näkyy vain sinulle ja MotoLab-ylläpidolle.</p><button class="mfb-btn" id="mfbNew">+ UUSI PALAUTE</button><div id="mfbMine" class="mfb-list">Haetaan keskustelut…</div>`);$('mfbNew').onclick=newFeedback;const box=$('mfbMine');try{const j=await api('/api/feedback/v1/mine');box.innerHTML=j.items.length?j.items.map(x=>`<div class="mfb-item" data-thread="${esc(x.feedbackId)}"><b>${esc(x.category)} • ${statusName(x.status)}</b><small>${esc(x.updatedAt)}</small><div>${esc((x.messages?.[x.messages.length-1]?.text||'').slice(0,180))}</div>${x.publishedIssueId?'<small>Asia on julkaistu anonymisoituna Beta-keskusteluun.</small>':''}</div>`).join(''):'Ei palautekeskusteluja vielä.';box.querySelectorAll('[data-thread]').forEach(e=>e.onclick=()=>openThread(e.dataset.thread))}catch(e){box.textContent=e.message}}
function newFeedback(){overlay(`<h2>Uusi yksityinen palaute</h2><select id="mfbCategory"><option value="problem">Ongelma / vika</option><option value="update">Päivitys</option><option value="development">Kehitysehdotus</option><option value="other">Muu kommentti</option></select><textarea id="mfbMessage" maxlength="5000" placeholder="Kirjoita viesti ylläpidolle..."></textarea><button class="mfb-btn" id="mfbSend">LÄHETÄ</button><div id="mfbStatus" class="mfb-status"></div>`);$('mfbSend').onclick=async()=>{const st=$('mfbStatus'),msg=$('mfbMessage').value.trim();if(!msg)return st.textContent='Kirjoita viesti ensin.';st.textContent='Lähetetään…';try{const j=await submit($('mfbCategory').value,msg,st);await openThread(j.item.feedbackId)}catch(e){st.textContent='Lähetys epäonnistui • '+e.message}}}
async function openThread(id){try{const j=await api('/api/feedback/v1/mine'),x=j.items.find(v=>v.feedbackId===id);if(!x)return openFeedback();overlay(`<h2>Yksityinen keskustelu</h2><small>${esc(x.category)} • ${statusName(x.status)}</small>${renderMessages(x.messages)}${x.status!=='resolved'?`<textarea id="mfbReply" maxlength="5000" placeholder="Vastaa ylläpidolle..."></textarea><button class="mfb-btn" id="mfbReplyBtn">LÄHETÄ VASTAUS</button>`:'<div class="mfb-status">Keskustelu on merkitty ratkaistuksi.</div>'}${x.publishedIssueId?'<div class="mfb-status">Ongelma on julkaistu Beta-keskusteluun anonymisoituna. Nimeäsi tai tätä yksityistä keskustelua ei näytetä muille.</div>':''}<button class="mfb-btn secondary" id="mfbBack">TAKAISIN</button><div id="mfbStatus" class="mfb-status"></div>`);$('mfbBack').onclick=openFeedback;if(x.status!=='resolved')$('mfbReplyBtn').onclick=async()=>{const msg=$('mfbReply').value.trim();if(!msg)return;try{await api('/api/feedback/v1/reply',{method:'POST',body:JSON.stringify({feedbackId:id,message:msg})});await openThread(id)}catch(e){$('mfbStatus').textContent=e.message}}}catch(e){overlay(`<h2>Palaute</h2><p>${esc(e.message)}</p>`)}}
async function openAdminFeedback(){overlay(`<h2>Käyttäjäpalautteet</h2><div id="mfbAdminList" class="mfb-list">Haetaan…</div><div id="mfbStatus" class="mfb-status"></div>`);const box=$('mfbAdminList');try{const j=await api('/api/admin/v1/feedback');if(!j.items.length){box.textContent='Ei palautteita.';return}box.innerHTML=j.items.map(x=>`<div class="mfb-item" data-admin-thread="${esc(x.feedbackId)}"><b>${esc(x.nickname||x.userId)} • ${esc(x.category)}</b><small>${statusName(x.status)} • ${esc(x.updatedAt)}${x.publishedIssueId?' • JULKAISTU ANONYYMINÄ':''}</small><div>${esc((x.messages?.[x.messages.length-1]?.text||'').slice(0,180))}</div></div>`).join('');box.querySelectorAll('[data-admin-thread]').forEach(e=>e.onclick=()=>openAdminThread(e.dataset.adminThread))}catch(e){box.textContent=e.message}}
async function openAdminThread(id){try{const j=await api('/api/admin/v1/feedback'),x=j.items.find(v=>v.feedbackId===id);if(!x)return openAdminFeedback();overlay(`<h2>${esc(x.nickname||x.userId)}</h2><small>${esc(x.category)} • ${statusName(x.status)} • ${esc(x.deviceId)}</small>${(x.messages||[]).map(m=>`<div class="mfb-msg ${m.authorRole==='admin'?'admin':'user'}"><small>${m.authorRole==='admin'?'YLLÄPITO':esc(x.nickname||'KÄYTTÄJÄ')} • ${esc(m.createdAt)}</small>${esc(m.text)}</div>`).join('')}<textarea id="mfbAdminReply" maxlength="5000" placeholder="Vastaa käyttäjälle..."></textarea><button class="mfb-btn" id="mfbAdminReplyBtn">LÄHETÄ VASTAUS</button><select id="mfbState"><option value="waiting_admin">ODOTTAA YLLÄPITOA</option><option value="waiting_user">ODOTTAA KÄYTTÄJÄÄ</option><option value="working">TYÖN ALLA</option><option value="resolved">RATKAISTU</option></select><button class="mfb-btn secondary" id="mfbStateBtn">PÄIVITÄ TILA</button>${x.publishedIssueId?`<div class="mfb-status">Julkaistu anonymisoituna: ${esc(x.publishedIssueId)}</div>`:`<button class="mfb-btn blue" id="mfbPublish">JULKAISE ANONYYMINÄ BETA-KESKUSTELUUN</button><div class="mfb-private">Julkaisu ei sisällä nimimerkkiä, käyttäjä-ID:tä, laite-ID:tä, yhteystietoja eikä yksityistä viestihistoriaa.</div>`}<button class="mfb-btn secondary" id="mfbBack">TAKAISIN</button><div id="mfbStatus" class="mfb-status"></div>`);$('mfbBack').onclick=openAdminFeedback;$('mfbState').value=x.status==='new'?'waiting_admin':x.status;$('mfbAdminReplyBtn').onclick=async()=>{const msg=$('mfbAdminReply').value.trim();if(!msg)return;try{await api('/api/admin/v1/feedback-reply',{method:'POST',body:JSON.stringify({feedbackId:id,message:msg})});await openAdminThread(id)}catch(e){$('mfbStatus').textContent=e.message}};$('mfbStateBtn').onclick=async()=>{try{await api('/api/admin/v1/feedback-status',{method:'POST',body:JSON.stringify({feedbackId:id,status:$('mfbState').value})});await openAdminThread(id)}catch(e){$('mfbStatus').textContent=e.message}};if(!x.publishedIssueId)$('mfbPublish').onclick=()=>publishForm(x)}catch(e){overlay(`<h2>Palaute</h2><p>${esc(e.message)}</p>`)}}
function publishForm(x){const first=(x.messages||[]).find(m=>m.authorRole==='user')?.text||'';overlay(`<h2>Julkaise anonymisoituna</h2><p class="mfb-private">Tarkista julkinen teksti. Käyttäjän henkilöllisyyttä tai yksityistä keskustelua ei siirretä.</p><input id="mfbPubTitle" maxlength="120" value="Beta-käyttäjän ilmoittama ongelma"><textarea id="mfbPubDesc" maxlength="5000">${esc(first)}</textarea><button class="mfb-btn blue" id="mfbPubConfirm">JULKAISE ANONYYMINÄ</button><button class="mfb-btn secondary" id="mfbBack">PERUUTA</button><div id="mfbStatus" class="mfb-status"></div>`);$('mfbBack').onclick=()=>openAdminThread(x.feedbackId);$('mfbPubConfirm').onclick=async()=>{try{await api('/api/admin/v1/feedback-publish-anonymous',{method:'POST',body:JSON.stringify({feedbackId:x.feedbackId,title:$('mfbPubTitle').value.trim(),description:$('mfbPubDesc').value.trim(),category:'Ongelma'})});await openAdminThread(x.feedbackId)}catch(e){$('mfbStatus').textContent=e.message}}}
function install(){styles();if($('motolabFeedbackBtn'))return;const b=document.createElement('button');b.id='motolabFeedbackBtn';b.textContent='PALAUTE';b.onclick=openFeedback;document.body.appendChild(b);const watch=setInterval(()=>{const u=window.MotoLabUser?.user;if(u?.role==='admin'&&u.status==='active'&&!$('motolabAdminFeedbackBtn')){const a=document.createElement('button');a.id='motolabAdminFeedbackBtn';a.className='mui-user-pill';a.style.bottom='calc(78px + env(safe-area-inset-bottom))';a.textContent='PALAUTTEET';a.onclick=openAdminFeedback;document.body.appendChild(a);clearInterval(watch)}},1200)}
window.MotoLabFeedback={version:VERSION,open:openFeedback,openAdmin:openAdminFeedback};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
