(() => {
'use strict';
const VERSION='imu-autocal-v1.1-test-fusion',RAW_SCHEMA='imu_raw_v1',MAX_EVENTS=7000,MAX_PAIRS=180;
const state={events:[],pairs:[],latest:null,axis:null,axisConfidence:0,correlation:0,gravity:null,mountState:'INIT',lastStateEvent:'',lastAxisUpdate:0,wrappedCollect:false,wrappedPut:false,wrappedWorker:false,fusionLow:null};
const n=v=>Number.isFinite(+v)?+v:null,clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),vec=(x,y,z)=>[n(x)||0,n(y)||0,n(z)||0],mag=v=>Math.hypot(...v),dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],unit=v=>{const m=mag(v);return m>1e-9?v.map(x=>x/m):null},mix=(a,b,k)=>a.map((x,i)=>x*(1-k)+b[i]*k);
function corr(rows){if(rows.length<8)return 0;const ax=rows.map(x=>x.imu),ay=rows.map(x=>x.gps),mx=ax.reduce((s,x)=>s+x,0)/ax.length,my=ay.reduce((s,x)=>s+x,0)/ay.length;let num=0,dx=0,dy=0;for(let i=0;i<ax.length;i++){const x=ax[i]-mx,y=ay[i]-my;num+=x*y;dx+=x*x;dy+=y*y}return dx>1e-9&&dy>1e-9?num/Math.sqrt(dx*dy):0}
function gravityFromEvent(e,a,ag){if(e.acceleration&&e.accelerationIncludingGravity)return [ag[0]-a[0],ag[1]-a[1],ag[2]-a[2]];return state.gravity||ag}
function snapshot(){return {axis:state.axis?{x:state.axis[0],y:state.axis[1],z:state.axis[2]}:null,gravity:state.gravity?{x:state.gravity[0],y:state.gravity[1],z:state.gravity[2]}:null,confidence:state.axisConfidence,correlation:state.correlation,mountState:state.mountState,pairCount:state.pairs.length,lastEventAt:state.latest?.t||null}}
function onMotion(e){const t=Date.now(),a=vec(e.acceleration?.x,e.acceleration?.y,e.acceleration?.z),ag=vec(e.accelerationIncludingGravity?.x,e.accelerationIncludingGravity?.y,e.accelerationIncludingGravity?.z),r=vec(e.rotationRate?.alpha,e.rotationRate?.beta,e.rotationRate?.gamma),g=gravityFromEvent(e,a,ag);if(mag(g)>4&&mag(g)<15){const gu=unit(g);state.gravity=state.gravity?unit(mix(state.gravity,gu,.035)):gu}const rotMag=mag(r),userMag=mag(a),movingHard=rotMag>85||userMag>7;state.mountState=movingHard?'MOVING':state.axisConfidence>=.55?'CALIBRATED':state.axisConfidence>=.2?'LEARNING':'UNVERIFIED';const longitudinal=state.axis?dot(a,state.axis):null;const rec={t,eventTimeStampMs:n(e.timeStamp),intervalMs:n(e.interval),ax:a[0],ay:a[1],az:a[2],agx:ag[0],agy:ag[1],agz:ag[2],rotAlpha:r[0],rotBeta:r[1],rotGamma:r[2],gx:state.gravity?.[0]??null,gy:state.gravity?.[1]??null,gz:state.gravity?.[2]??null,longitudinalMps2:Number.isFinite(longitudinal)?longitudinal:null,axisX:state.axis?.[0]??null,axisY:state.axis?.[1]??null,axisZ:state.axis?.[2]??null,confidence:state.axisConfidence,correlation:state.correlation,mountState:state.mountState,userAccelMag:userMag,rotationMag:rotMag};state.latest=rec;state.events.push(rec);if(state.events.length>MAX_EVENTS)state.events.splice(0,state.events.length-MAX_EVENTS);globalThis.MOTOLAB_IMU_AUTOCAL={version:VERSION,schema:RAW_SCHEMA,...snapshot()}}
function maybeEvent(){const key=state.mountState+':'+Math.round(state.axisConfidence*10);if(key===state.lastStateEvent)return;state.lastStateEvent=key;try{globalThis.addLearningEvent?.('imu_autocal_state',{module:VERSION,...snapshot()})}catch{}}
function calibrateFromGps(sample){const gpsA=n(sample?.gpsAccelerationMps2??sample?.gpsAccelMps2??sample?.a),rec=state.latest;if(gpsA==null||!rec||Date.now()-rec.t>350)return;const a=[rec.ax||0,rec.ay||0,rec.az||0],am=mag(a);if(Math.abs(gpsA)>.12&&am>.06&&am<8&&rec.rotationMag<90){let candidate=unit(a);if(candidate){if(gpsA<0)candidate=candidate.map(x=>-x);if(state.axis&&dot(candidate,state.axis)<0)candidate=candidate.map(x=>-x);state.axis=state.axis?unit(mix(state.axis,candidate,.1)):candidate;state.lastAxisUpdate=Date.now()}}if(state.axis){const projected=dot(a,state.axis);if(Number.isFinite(projected)&&Math.abs(gpsA)>.05){state.pairs.push({imu:projected,gps:gpsA,t:Date.now()});if(state.pairs.length>MAX_PAIRS)state.pairs.splice(0,state.pairs.length-MAX_PAIRS);const recent=state.pairs.filter(x=>Date.now()-x.t<60000);state.correlation=corr(recent);const countScore=clamp(recent.length/45),corrScore=clamp((state.correlation-.15)/.7),rotPenalty=rec.rotationMag>45?.55:1,freshness=Date.now()-state.lastAxisUpdate<30000?1:.65;state.axisConfidence=clamp(countScore*corrScore*rotPenalty*freshness)}}maybeEvent()}
function nearest(t){if(!state.events.length)return null;let best=null,bestDt=Infinity;for(let i=state.events.length-1;i>=0;i--){const r=state.events[i],d=Math.abs(r.t-t);if(d<bestDt){best=r;bestDt=d}if(r.t<t-500)break}return bestDt<=250?{rec:best,age:bestDt}:null}
function fuseSample(s,lowState=state){if(!s)return s;const gpsA=n(s.gpsAccelerationMps2??s.gpsAccelMps2??s.a),hit=nearest(n(s.t)||Date.now());if(gpsA==null||!hit){s.gpsAccelerationMps2=gpsA;s.fusedAccelerationMps2=gpsA;return s}const r=hit.rec,imu=n(r.longitudinalMps2);if(imu==null){s.gpsAccelerationMps2=gpsA;s.fusedAccelerationMps2=gpsA;return s}lowState.fusionLow=lowState.fusionLow==null?imu:lowState.fusionLow*.92+imu*.08;const fast=imu-lowState.fusionLow,weight=clamp((r.confidence||0)*Math.max(0,r.correlation||0)*.75,0,.65),fused=gpsA+weight*fast;s.gpsAccelerationMps2=gpsA;s.imuLongitudinalMps2=imu;s.imuFusionWeight=weight;s.imuFastResidualMps2=fast;s.fusedAccelerationMps2=fused;s.a=fused;s.g=fused/9.80665;const settings=typeof globalThis.currentSettings==='function'?globalThis.currentSettings():{};const v=(n(s.kmh)||0)/3.6,m=n(settings.mass)||190,rho=n(settings.rho)||1.225,cda=n(settings.cda)||.55,crr=n(settings.crr)||.015,force=m*fused+.5*rho*cda*v*v+crr*m*9.80665,watts=Math.max(0,force*v);s.gpsOnlyHp=Math.max(0,(m*gpsA+.5*rho*cda*v*v+crr*m*9.80665)*v)/735.49875;s.hp=watts/735.49875;s.nm=(n(s.rpm)||0)>200?watts/(s.rpm*2*Math.PI/60):0;return s}
function enrichChunk(chunk){if(!chunk||!Array.isArray(chunk.samples))return chunk;for(const row of chunk.samples){const hit=nearest(n(row.t)||Date.now());if(!hit)continue;const r=hit.rec;Object.assign(row,{imuRawSchema:RAW_SCHEMA,imuCalibrationVersion:VERSION,imuEventAgeMs:hit.age,imuReceiveTimeMs:r.t,imuEventTimeStampMs:r.eventTimeStampMs,imuIntervalMs:r.intervalMs,imuAccelX:r.ax,imuAccelY:r.ay,imuAccelZ:r.az,imuAccelIncludingGravityX:r.agx,imuAccelIncludingGravityY:r.agy,imuAccelIncludingGravityZ:r.agz,imuRotationAlpha:r.rotAlpha,imuRotationBeta:r.rotBeta,imuRotationGamma:r.rotGamma,imuGravityX:r.gx,imuGravityY:r.gy,imuGravityZ:r.gz,imuLongitudinalMps2:r.longitudinalMps2,imuAxisX:r.axisX,imuAxisY:r.axisY,imuAxisZ:r.axisZ,imuCalibrationConfidence:r.confidence,imuGpsCorrelation:r.correlation,imuMountState:r.mountState,imuUserAccelMag:r.userAccelMag,imuRotationMag:r.rotationMag})}chunk.imu={schema:RAW_SCHEMA,calibrationVersion:VERSION,mode:'bounded_test_fusion_plus_full_raw',...snapshot()};return chunk}
function patchCollect(){if(state.wrappedCollect||typeof globalThis.collectLearningSample!=='function')return false;const original=globalThis.collectLearningSample;globalThis.collectLearningSample=function(sample){calibrateFromGps(sample);return original.apply(this,arguments)};state.wrappedCollect=true;return true}
function patchPut(){if(state.wrappedPut||typeof globalThis.putRawChunk!=='function')return false;const original=globalThis.putRawChunk;globalThis.putRawChunk=async function(chunk){return original.call(this,enrichChunk(chunk))};state.wrappedPut=true;return true}
function patchWorker(){if(state.wrappedWorker||!globalThis.measurementWorker||typeof globalThis.measurementWorker.onmessage!=='function')return false;const original=globalThis.measurementWorker.onmessage;globalThis.measurementWorker.onmessage=function(e){try{const m=e?.data;if(m?.type==='ui'&&m.data)fuseSample(m.data);if(m?.type==='runComplete'&&Array.isArray(m.run?.data)){const local={fusionLow:null};for(const s of m.run.data)fuseSample(s,local);m.run.maxHp=Math.max(0,...m.run.data.map(x=>x.hp||0));m.run.maxNm=Math.max(0,...m.run.data.map(x=>x.nm||0));m.run.fusionVersion=VERSION}}catch{}return original.call(this,e)};state.wrappedWorker=true;return true}
window.addEventListener('devicemotion',onMotion,{passive:true});const timer=setInterval(()=>{patchCollect();patchPut();patchWorker();if(state.wrappedCollect&&state.wrappedPut&&state.wrappedWorker)clearInterval(timer)},250);patchCollect();patchPut();patchWorker();globalThis.MotoLabImuAutoCal={version:VERSION,schema:RAW_SCHEMA,snapshot,enrichChunk,fuseSample};try{globalThis.addLearningEvent?.('imu_autocal_loaded',{module:VERSION,schema:RAW_SCHEMA,mode:'bounded_test_fusion_plus_full_raw'})}catch{}
})();
