(() => {
'use strict';
const VERSION='imu-autocal-v2.3-60hz-session',RAW_SCHEMA='imu_raw_v3_60hz',RAW_STREAM_SCHEMA='imu_event_60hz_v1';
const TARGET_HZ=60,MAX_EVENTS=24000,MAX_GPS=220,MAX_PAIRS=240,CAL_HALF_MS=500,SOLVE_EVERY_MS=1500,NEW_RIDE_IDLE_MS=90000;
const LAGS=[];for(let x=-3000;x<=3000;x+=250)LAGS.push(x);
const state={events:[],gps:[],pairs:[],latest:null,axis:null,lateralAxis:null,gravity:null,axisConfidence:0,correlation:0,lateralCorrelation:0,axisStability:0,bestLagMs:0,mountState:'INIT',lastStateEvent:'',wrappedCollect:false,wrappedPut:false,wrappedWorker:false,fusionLow:null,longLow:null,lastGravityStable:null,orientationShiftSince:0,sessionId:null,rideEpoch:0,lastSolveAt:0,lastRawExportT:0,lastEventReceiveT:0,rateDeltas:[],stationarySince:0,lastGpsKmh:0};
const n=v=>Number.isFinite(+v)?+v:null,clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const vec=(x,y,z)=>[n(x)||0,n(y)||0,n(z)||0],mag=v=>Math.hypot(...v),dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const unit=v=>{const m=mag(v);return m>1e-9?v.map(x=>x/m):null};
const mix=(a,b,k)=>a.map((x,i)=>x*(1-k)+b[i]*k),sub=(a,b)=>a.map((x,i)=>x-b[i]),scale=(a,k)=>a.map(x=>x*k);
function horizontal(a,g){const gu=unit(g);return gu?sub(a,scale(gu,dot(a,gu))):a.slice()}
function corrXY(xs,ys){if(xs.length<8)return 0;const mx=xs.reduce((s,x)=>s+x,0)/xs.length,my=ys.reduce((s,x)=>s+x,0)/ys.length;let num=0,dx=0,dy=0;for(let i=0;i<xs.length;i++){const x=xs[i]-mx,y=ys[i]-my;num+=x*y;dx+=x*x;dy+=y*y}return dx>1e-9&&dy>1e-9?num/Math.sqrt(dx*dy):0}
function regressOut(rows,keyX,keyY){const xs=rows.map(z=>z[keyX]),ys=rows.map(z=>z[keyY]),mx=xs.reduce((s,x)=>s+x,0)/xs.length,my=ys.reduce((s,x)=>s+x,0)/ys.length;let cov=0,v=0;for(let i=0;i<xs.length;i++){cov+=(xs[i]-mx)*(ys[i]-my);v+=(ys[i]-my)*(ys[i]-my)}const b=v>1e-9?cov/v:0;return xs.map((x,i)=>x-b*(ys[i]-my))}
function gravityFromEvent(e,a,ag){if(e.acceleration&&e.accelerationIncludingGravity)return [ag[0]-a[0],ag[1]-a[1],ag[2]-a[2]];return state.gravity||ag}
function currentSessionId(){try{return typeof learningSessionId!=='undefined'&&learningSessionId?String(learningSessionId):null}catch{return null}}
function resetCalibration(reason='reset',sessionId=state.sessionId,clearEvents=true){state.axis=null;state.lateralAxis=null;state.axisConfidence=0;state.correlation=0;state.lateralCorrelation=0;state.axisStability=0;state.bestLagMs=0;state.mountState='UNVERIFIED';state.pairs=[];state.gps=[];state.fusionLow=null;state.longLow=null;state.lastSolveAt=0;state.lastRawExportT=0;if(clearEvents)state.events=[];state.sessionId=sessionId;state.rideEpoch++;try{globalThis.addLearningEvent?.('imu_autocal_reset',{module:VERSION,reason,sessionId,rideEpoch:state.rideEpoch})}catch{}}
function maybeResetSession(){const sid=currentSessionId();if(sid&&sid!==state.sessionId)resetCalibration('new_session',sid,true)}
function eventRateHz(){const a=state.rateDeltas.filter(x=>x>2&&x<100);if(!a.length)return 0;const b=a.slice().sort((x,y)=>x-y),m=b[Math.floor(b.length/2)];return m>0?1000/m:0}
function snapshot(){return {axis:state.axis?{x:state.axis[0],y:state.axis[1],z:state.axis[2]}:null,lateralAxis:state.lateralAxis?{x:state.lateralAxis[0],y:state.lateralAxis[1],z:state.lateralAxis[2]}:null,gravity:state.gravity?{x:state.gravity[0],y:state.gravity[1],z:state.gravity[2]}:null,confidence:state.axisConfidence,correlation:state.correlation,lateralCorrelation:state.lateralCorrelation,axisStability:state.axisStability,bestLagMs:state.bestLagMs,mountState:state.mountState,pairCount:state.pairs.length,lastEventAt:state.latest?.t||null,targetHz:TARGET_HZ,eventRateHz:eventRateHz(),rawEventsBuffered:state.events.length,sessionId:state.sessionId,rideEpoch:state.rideEpoch,calWindowMs:CAL_HALF_MS*2}}
function yawRateRad(r,g){const gu=unit(g);if(!gu)return 0;return dot(r,gu)*Math.PI/180}
function onMotion(e){maybeResetSession();const t=Date.now();if(state.lastEventReceiveT){const dt=t-state.lastEventReceiveT;if(dt>0&&dt<250){state.rateDeltas.push(dt);if(state.rateDeltas.length>240)state.rateDeltas.shift()}}state.lastEventReceiveT=t;const a=vec(e.acceleration?.x,e.acceleration?.y,e.acceleration?.z),ag=vec(e.accelerationIncludingGravity?.x,e.accelerationIncludingGravity?.y,e.accelerationIncludingGravity?.z),r=vec(e.rotationRate?.alpha,e.rotationRate?.beta,e.rotationRate?.gamma),g=gravityFromEvent(e,a,ag);if(mag(g)>4&&mag(g)<15){const gu=unit(g);state.gravity=state.gravity?unit(mix(state.gravity,gu,.07)):gu;if(!state.lastGravityStable)state.lastGravityStable=state.gravity.slice()}const h=horizontal(a,state.gravity||g),userMag=mag(a),longitudinal=state.axis?dot(h,state.axis):null,lateral=state.lateralAxis?dot(h,state.lateralAxis):null,yaw=yawRateRad(r,state.gravity||g),rotMag=mag(r);let fastLong=null;if(Number.isFinite(longitudinal)){const dt=state.latest?Math.max(1,t-state.latest.t):17,alpha=1-Math.exp(-dt/800);state.longLow=state.longLow==null?longitudinal:state.longLow+(longitudinal-state.longLow)*alpha;fastLong=longitudinal-state.longLow}state.mountState=state.axisConfidence>=.55&&state.axisStability>=.62&&state.correlation>=.42?'VERIFIED':state.axisConfidence>=.20?'LEARNING':'UNVERIFIED';const rec={t,eventTimeStampMs:n(e.timeStamp),intervalSec:n(e.interval),ax:a[0],ay:a[1],az:a[2],agx:ag[0],agy:ag[1],agz:ag[2],rotAlpha:r[0],rotBeta:r[1],rotGamma:r[2],gx:state.gravity?.[0]??null,gy:state.gravity?.[1]??null,gz:state.gravity?.[2]??null,hx:h[0],hy:h[1],hz:h[2],longitudinalMps2:Number.isFinite(longitudinal)?longitudinal:null,fastLongitudinalMps2:Number.isFinite(fastLong)?fastLong:null,lateralMps2:Number.isFinite(lateral)?lateral:null,yawRateRadS:yaw,axisX:state.axis?.[0]??null,axisY:state.axis?.[1]??null,axisZ:state.axis?.[2]??null,lateralAxisX:state.lateralAxis?.[0]??null,lateralAxisY:state.lateralAxis?.[1]??null,lateralAxisZ:state.lateralAxis?.[2]??null,confidence:state.axisConfidence,correlation:state.correlation,lateralCorrelation:state.lateralCorrelation,axisStability:state.axisStability,bestLagMs:state.bestLagMs,mountState:state.mountState,userAccelMag:userMag,rotationMag:rotMag};state.latest=rec;state.events.push(rec);if(state.events.length>MAX_EVENTS)state.events.splice(0,state.events.length-MAX_EVENTS);globalThis.MOTOLAB_IMU_AUTOCAL={version:VERSION,schema:RAW_SCHEMA,...snapshot()}}
function averagedEvent(t,half=CAL_HALF_MS){let count=0,h0=0,h1=0,h2=0,yaw=0,user=0;for(let i=state.events.length-1;i>=0;i--){const r=state.events[i];if(r.t>t+half)continue;if(r.t<t-half)break;h0+=r.hx||0;h1+=r.hy||0;h2+=r.hz||0;yaw+=r.yawRateRadS||0;user+=r.userAccelMag||0;count++}return count>=8?{count,h0:h0/count,h1:h1/count,h2:h2/count,yaw:yaw/count,user:user/count}:null}
function solveLag(lag){const rows=[];for(const gp of state.gps){const r=averagedEvent(gp.t-lag);if(!r)continue;const hm=Math.hypot(r.h0,r.h1,r.h2);if(hm<.025)continue;const latTarget=(gp.v||0)*(r.yaw||0);if(Math.abs(gp.a)<.08&&Math.abs(latTarget)<.12)continue;rows.push({h0:r.h0,h1:r.h1,h2:r.h2,long:gp.a,lat:latTarget,t:gp.t,count:r.count})}if(rows.length<14)return null;const longRes=regressOut(rows,'long','lat'),hRes=[0,1,2].map(j=>regressOut(rows,'h'+j,'lat'));const ml=longRes.reduce((s,x)=>s+x,0)/longRes.length,means=hRes.map(a=>a.reduce((s,x)=>s+x,0)/a.length),cov=[0,0,0];for(let i=0;i<rows.length;i++)for(let j=0;j<3;j++)cov[j]+=(hRes[j][i]-means[j])*(longRes[i]-ml);let axis=unit(horizontal(cov,state.gravity));if(!axis)return null;let longProj=rows.map(z=>dot([z.h0,z.h1,z.h2],axis)),longY=rows.map(z=>z.long),c=corrXY(longProj,longY);if(c<0){axis=axis.map(x=>-x);longProj=longProj.map(x=>-x);c=-c}let lateralAxis=unit(cross(unit(state.gravity)||[0,0,1],axis));if(!lateralAxis)return null;let latProj=rows.map(z=>dot([z.h0,z.h1,z.h2],lateralAxis)),latY=rows.map(z=>z.lat),lc=corrXY(latProj,latY);if(lc<0){lateralAxis=lateralAxis.map(x=>-x);lc=-lc}return {lag,rows,axis,lateralAxis,corr:c,lateralCorr:lc}}
function solveCalibration(force=false){const now=Date.now();if(!force&&now-state.lastSolveAt<SOLVE_EVERY_MS)return;if(state.gps.length<14||state.events.length<90||!state.gravity)return;state.lastSolveAt=now;let best=null;for(const lag of LAGS){const r=solveLag(lag);if(r&&(!best||(r.corr+.20*r.lateralCorr)>(best.corr+.20*best.lateralCorr)))best=r}if(!best||best.corr<.20)return;const old=state.axis;let next=best.axis;if(old&&dot(old,next)<0)next=next.map(x=>-x);const align=old?dot(old,next):1;if(old&&align<.45&&best.corr>=.45){state.axis=next;state.axisStability=.22;state.axisConfidence=Math.min(state.axisConfidence,.18);state.longLow=null}else{state.axisStability=old?clamp(state.axisStability*.55+Math.abs(align)*.45):.55;const fast=best.corr>=.55&&Math.abs(align)>=.80,medium=best.corr>=.40&&Math.abs(align)>=.62,alpha=old?(fast?.45:medium?.28:.12):1;state.axis=old?unit(mix(old,next,alpha)):next;if(!old||Math.abs(align)<.92)state.longLow=null}state.lateralAxis=unit(cross(unit(state.gravity)||[0,0,1],state.axis));if(state.lateralAxis&&dot(state.lateralAxis,best.lateralAxis)<0)state.lateralAxis=state.lateralAxis.map(x=>-x);state.correlation=best.corr;state.lateralCorrelation=best.lateralCorr;state.bestLagMs=best.lag;state.pairs=best.rows.slice(-MAX_PAIRS).map(z=>({imu:dot([z.h0,z.h1,z.h2],state.axis),gps:z.long,lateralGps:z.lat,lateralImu:state.lateralAxis?dot([z.h0,z.h1,z.h2],state.lateralAxis):null,t:z.t,n:z.count}));const countScore=clamp(best.rows.length/36),corrScore=clamp((best.corr-.16)/.42),stableScore=clamp((state.axisStability-.25)/.60),cornerScore=clamp(.78+.22*Math.max(0,best.lateralCorr));state.axisConfidence=clamp((.45*corrScore+.35*stableScore+.20*countScore)*cornerScore);state.mountState=state.axisConfidence>=.55&&state.axisStability>=.62&&state.correlation>=.42?'VERIFIED':state.axisConfidence>=.20?'LEARNING':'UNVERIFIED';maybeEvent()}
function maybeEvent(){const key=state.mountState+':'+Math.round(state.axisConfidence*10)+':'+state.bestLagMs+':'+state.rideEpoch;if(key===state.lastStateEvent)return;state.lastStateEvent=key;try{globalThis.addLearningEvent?.('imu_autocal_state',{module:VERSION,...snapshot()})}catch{}}
function calibrateFromGps(sample){maybeResetSession();const gpsA=n(sample?.gpsAccelerationMps2??sample?.gpsAccelMps2??sample?.accelerationMps2??sample?.a),t=n(sample?.t)||Date.now(),kmh=n(sample?.kmh??sample?.gpsKmh)??0;if(gpsA==null)return;if(kmh<3){if(!state.stationarySince)state.stationarySince=t}else if(kmh>=8){if(state.stationarySince&&t-state.stationarySince>=NEW_RIDE_IDLE_MS&&state.gps.length>0)resetCalibration('new_ride_after_idle',state.sessionId,true);state.stationarySince=0}state.lastGpsKmh=kmh;state.gps.push({t,a:gpsA,v:Math.max(0,kmh/3.6)});if(state.gps.length>MAX_GPS)state.gps.splice(0,state.gps.length-MAX_GPS);solveCalibration()}
function nearest(t){if(!state.events.length)return null;let best=null,bestDt=Infinity;for(let i=state.events.length-1;i>=0;i--){const r=state.events[i],d=Math.abs(r.t-t);if(d<bestDt){best=r;bestDt=d}if(r.t<t-650)break}return best&&bestDt<=320?{rec:best,age:bestDt}:null}
function fuseSample(s,lowState=state){if(!s)return s;const gpsA=n(s.gpsAccelerationMps2??s.gpsAccelMps2??s.accelerationMps2??s.a),hit=nearest((n(s.t)||Date.now())-state.bestLagMs);if(gpsA==null||!hit){s.gpsAccelerationMps2=gpsA;s.fusedAccelerationMps2=gpsA;return s}const r=hit.rec,imu=n(r.longitudinalMps2),fast=n(r.fastLongitudinalMps2);if(imu==null){s.gpsAccelerationMps2=gpsA;s.fusedAccelerationMps2=gpsA;return s}const v=(n(s.kmh??s.gpsKmh)||0)/3.6,yaw=n(r.yawRateRadS)||0,cornerExpected=v*yaw,cornerMeasured=n(r.lateralMps2),cornerActive=Math.abs(cornerExpected)>.35,cornerAgreement=!cornerActive||cornerMeasured==null?1:clamp(1-Math.abs(Math.abs(cornerMeasured)-Math.abs(cornerExpected))/Math.max(.6,Math.abs(cornerExpected)),0,1),verified=state.mountState==='VERIFIED'&&state.correlation>=.42,cornerPenalty=cornerActive?(.45+.55*cornerAgreement):1,weight=(verified?clamp(state.axisConfidence*state.correlation*1.05,0,.62):0)*cornerPenalty,fastTerm=fast==null?0:fast,fused=gpsA+weight*fastTerm;s.gpsAccelerationMps2=gpsA;s.imuLongitudinalMps2=imu;s.imuFastResidualMps2=fastTerm;s.imuLateralMps2=cornerMeasured;s.imuYawRateRadS=yaw;s.imuCornerExpectedMps2=cornerExpected;s.imuCornerAgreement=cornerAgreement;s.imuCornerActive=cornerActive;s.imuFusionWeight=weight;s.fusedAccelerationMps2=fused;s.a=fused;s.g=fused/9.80665;const settings=typeof globalThis.currentSettings==='function'?globalThis.currentSettings():{},m=n(settings.mass)||190,rho=n(settings.rho)||1.225,cda=n(settings.cda)||.55,crr=n(settings.crr)||.015,force=m*fused+.5*rho*cda*v*v+crr*m*9.80665,watts=Math.max(0,force*v);s.gpsOnlyHp=Math.max(0,(m*gpsA+.5*rho*cda*v*v+crr*m*9.80665)*v)/735.49875;s.hp=watts/735.49875;s.nm=(n(s.rpm)||0)>200?watts/(s.rpm*2*Math.PI/60):0;return s}
const RAW_FIELDS=['t','eventTimeStampMs','intervalSec','ax','ay','az','agx','agy','agz','rotAlpha','rotBeta','rotGamma','gx','gy','gz'];
function rawRowsUntil(tMax){const rows=[];let endT=state.lastRawExportT;for(const r of state.events){if(r.t<=state.lastRawExportT||r.t>tMax)continue;rows.push([r.t,r.eventTimeStampMs,r.intervalSec,r.ax,r.ay,r.az,r.agx,r.agy,r.agz,r.rotAlpha,r.rotBeta,r.rotGamma,r.gx,r.gy,r.gz]);if(r.t>endT)endT=r.t}return {rows,endT}}
function enrichChunk(chunk){if(!chunk||!Array.isArray(chunk.samples))return chunk;let tMax=0;for(const row of chunk.samples){const rt=n(row.t)||0;if(rt>tMax)tMax=rt;const hit=nearest(rt-state.bestLagMs);if(!hit)continue;const r=hit.rec;Object.assign(row,{imuRawSchema:RAW_SCHEMA,imuCalibrationVersion:VERSION,imuEventAgeMs:hit.age,imuReceiveTimeMs:r.t,imuEventTimeStampMs:r.eventTimeStampMs,imuIntervalSec:r.intervalSec,imuIntervalMs:r.intervalSec,imuAccelX:r.ax,imuAccelY:r.ay,imuAccelZ:r.az,imuAccelIncludingGravityX:r.agx,imuAccelIncludingGravityY:r.agy,imuAccelIncludingGravityZ:r.agz,imuRotationAlpha:r.rotAlpha,imuRotationBeta:r.rotBeta,imuRotationGamma:r.rotGamma,imuGravityX:r.gx,imuGravityY:r.gy,imuGravityZ:r.gz,imuLongitudinalMps2:r.longitudinalMps2,imuFastResidualMps2:r.fastLongitudinalMps2,imuLateralMps2:r.lateralMps2,imuYawRateRadS:r.yawRateRadS,imuAxisX:r.axisX,imuAxisY:r.axisY,imuAxisZ:r.axisZ,imuLateralAxisX:r.lateralAxisX,imuLateralAxisY:r.lateralAxisY,imuLateralAxisZ:r.lateralAxisZ,imuCalibrationConfidence:r.confidence,imuGpsCorrelation:r.correlation,imuLateralCorrelation:r.lateralCorrelation,imuAxisStability:r.axisStability,imuBestLagMs:r.bestLagMs,imuMountState:r.mountState,imuUserAccelMag:r.userAccelMag,imuRotationMag:r.rotationMag})}const raw=rawRowsUntil(tMax||Date.now());chunk.imuRaw60Hz={schema:RAW_STREAM_SCHEMA,targetHz:TARGET_HZ,measuredHz:eventRateHz(),fields:RAW_FIELDS,rows:raw.rows,startAfterT:state.lastRawExportT,endT:raw.endT};chunk.imu={schema:RAW_SCHEMA,rawStreamSchema:RAW_STREAM_SCHEMA,calibrationVersion:VERSION,mode:'60hz_raw_session_autocal_gps_anchor_fast_fusion',...snapshot()};return chunk}
function patchCollect(){if(state.wrappedCollect||typeof globalThis.collectLearningSample!=='function')return false;const original=globalThis.collectLearningSample;globalThis.collectLearningSample=function(sample){const out=original.apply(this,arguments);calibrateFromGps(sample);return out};state.wrappedCollect=true;return true}
function patchPut(){if(state.wrappedPut||typeof globalThis.putRawChunk!=='function')return false;const original=globalThis.putRawChunk;globalThis.putRawChunk=async function(chunk){const enriched=enrichChunk(chunk),endT=enriched?.imuRaw60Hz?.endT||state.lastRawExportT;const out=await original.call(this,enriched);if(endT>state.lastRawExportT)state.lastRawExportT=endT;return out};state.wrappedPut=true;return true}
function patchWorker(){if(state.wrappedWorker||!globalThis.measurementWorker||typeof globalThis.measurementWorker.onmessage!=='function')return false;const original=globalThis.measurementWorker.onmessage;globalThis.measurementWorker.onmessage=function(e){try{const m=e?.data;if(m?.type==='ui'&&m.data)fuseSample(m.data);if(m?.type==='runComplete'&&Array.isArray(m.run?.data)){const local={fusionLow:null};for(const s of m.run.data)fuseSample(s,local);m.run.maxHp=Math.max(0,...m.run.data.map(x=>x.hp||0));m.run.maxNm=Math.max(0,...m.run.data.map(x=>x.nm||0));m.run.fusionVersion=VERSION}}catch{}return original.call(this,e)};state.wrappedWorker=true;return true}
window.addEventListener('devicemotion',onMotion,{passive:true});const timer=setInterval(()=>{patchCollect();patchPut();patchWorker();if(state.wrappedCollect&&state.wrappedPut&&state.wrappedWorker)clearInterval(timer)},250);patchCollect();patchPut();patchWorker();globalThis.MotoLabImuAutoCal={version:VERSION,schema:RAW_SCHEMA,snapshot,enrichChunk,fuseSample,solveCalibration,resetCalibration};try{globalThis.addLearningEvent?.('imu_autocal_loaded',{module:VERSION,schema:RAW_SCHEMA,rawStreamSchema:RAW_STREAM_SCHEMA,targetHz:TARGET_HZ,mode:'60hz_raw_session_autocal_gps_anchor_fast_fusion'})}catch{}
})();
