(() => {
'use strict';
const VERSION='imu-autocal-v2.2-3d-corner-aware',RAW_SCHEMA='imu_raw_v2';
const MAX_EVENTS=8000,MAX_GPS=260,MAX_PAIRS=240,LAGS=[-2000,-1500,-1000,-500,0,500,1000,1500,2000];
const state={events:[],gps:[],pairs:[],latest:null,axis:null,lateralAxis:null,gravity:null,axisConfidence:0,correlation:0,lateralCorrelation:0,axisStability:0,bestLagMs:0,mountState:'INIT',lastStateEvent:'',wrappedCollect:false,wrappedPut:false,wrappedWorker:false,fusionLow:null,lastGravityStable:null,orientationShiftSince:0};
const n=v=>Number.isFinite(+v)?+v:null,clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const vec=(x,y,z)=>[n(x)||0,n(y)||0,n(z)||0],mag=v=>Math.hypot(...v),dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const unit=v=>{const m=mag(v);return m>1e-9?v.map(x=>x/m):null};
const mix=(a,b,k)=>a.map((x,i)=>x*(1-k)+b[i]*k),sub=(a,b)=>a.map((x,i)=>x-b[i]),scale=(a,k)=>a.map(x=>x*k);
function horizontal(a,g){const gu=unit(g);return gu?sub(a,scale(gu,dot(a,gu))):a.slice()}
function corrXY(xs,ys){if(xs.length<8)return 0;const mx=xs.reduce((s,x)=>s+x,0)/xs.length,my=ys.reduce((s,x)=>s+x,0)/ys.length;let num=0,dx=0,dy=0;for(let i=0;i<xs.length;i++){const x=xs[i]-mx,y=ys[i]-my;num+=x*y;dx+=x*x;dy+=y*y}return dx>1e-9&&dy>1e-9?num/Math.sqrt(dx*dy):0}
function gravityFromEvent(e,a,ag){if(e.acceleration&&e.accelerationIncludingGravity)return [ag[0]-a[0],ag[1]-a[1],ag[2]-a[2]];return state.gravity||ag}
function nearestEvent(t,maxAge=500){let best=null,dt=Infinity;for(let i=state.events.length-1;i>=0;i--){const r=state.events[i],d=Math.abs(r.t-t);if(d<dt){best=r;dt=d}if(r.t<t-maxAge-2200)break}return best&&dt<=maxAge?best:null}
function yawRateRad(r,g){const gu=unit(g);if(!gu)return 0;return dot(r,gu)*Math.PI/180}
function snapshot(){return {axis:state.axis?{x:state.axis[0],y:state.axis[1],z:state.axis[2]}:null,lateralAxis:state.lateralAxis?{x:state.lateralAxis[0],y:state.lateralAxis[1],z:state.lateralAxis[2]}:null,gravity:state.gravity?{x:state.gravity[0],y:state.gravity[1],z:state.gravity[2]}:null,confidence:state.axisConfidence,correlation:state.correlation,lateralCorrelation:state.lateralCorrelation,axisStability:state.axisStability,bestLagMs:state.bestLagMs,mountState:state.mountState,pairCount:state.pairs.length,lastEventAt:state.latest?.t||null}}
function onMotion(e){const t=Date.now(),a=vec(e.acceleration?.x,e.acceleration?.y,e.acceleration?.z),ag=vec(e.accelerationIncludingGravity?.x,e.accelerationIncludingGravity?.y,e.accelerationIncludingGravity?.z),r=vec(e.rotationRate?.alpha,e.rotationRate?.beta,e.rotationRate?.gamma),g=gravityFromEvent(e,a,ag);if(mag(g)>4&&mag(g)<15){const gu=unit(g);state.gravity=state.gravity?unit(mix(state.gravity,gu,.07)):gu;if(!state.lastGravityStable)state.lastGravityStable=state.gravity.slice();const ga=clamp(dot(state.lastGravityStable,state.gravity),-1,1),deg=Math.acos(ga)*180/Math.PI;if(deg>35){if(!state.orientationShiftSince)state.orientationShiftSince=t;if(t-state.orientationShiftSince>1800){state.lastGravityStable=state.gravity.slice();state.axisConfidence=Math.min(state.axisConfidence,.18);state.axisStability=Math.min(state.axisStability,.30);state.orientationShiftSince=0}}else state.orientationShiftSince=0}const userMag=mag(a),h=horizontal(a,state.gravity||g),longitudinal=state.axis?dot(h,state.axis):null,lateral=state.lateralAxis?dot(h,state.lateralAxis):null,yaw=yawRateRad(r,state.gravity||g),rotMag=mag(r);state.mountState=state.axisConfidence>=.58&&state.axisStability>=.68&&state.correlation>=.50?'VERIFIED':state.axisConfidence>=.20?'LEARNING':'UNVERIFIED';const rec={t,eventTimeStampMs:n(e.timeStamp),intervalMs:n(e.interval),ax:a[0],ay:a[1],az:a[2],agx:ag[0],agy:ag[1],agz:ag[2],rotAlpha:r[0],rotBeta:r[1],rotGamma:r[2],gx:state.gravity?.[0]??null,gy:state.gravity?.[1]??null,gz:state.gravity?.[2]??null,longitudinalMps2:Number.isFinite(longitudinal)?longitudinal:null,lateralMps2:Number.isFinite(lateral)?lateral:null,yawRateRadS:yaw,axisX:state.axis?.[0]??null,axisY:state.axis?.[1]??null,axisZ:state.axis?.[2]??null,lateralAxisX:state.lateralAxis?.[0]??null,lateralAxisY:state.lateralAxis?.[1]??null,lateralAxisZ:state.lateralAxis?.[2]??null,confidence:state.axisConfidence,correlation:state.correlation,lateralCorrelation:state.lateralCorrelation,axisStability:state.axisStability,bestLagMs:state.bestLagMs,mountState:state.mountState,userAccelMag:userMag,rotationMag:rotMag};state.latest=rec;state.events.push(rec);if(state.events.length>MAX_EVENTS)state.events.splice(0,state.events.length-MAX_EVENTS);globalThis.MOTOLAB_IMU_AUTOCAL={version:VERSION,schema:RAW_SCHEMA,...snapshot()}}
function regressOut(rows,keyX,keyY){const xs=rows.map(z=>z[keyX]),ys=rows.map(z=>z[keyY]),mx=xs.reduce((s,x)=>s+x,0)/xs.length,my=ys.reduce((s,x)=>s+x,0)/ys.length;let cov=0,v=0;for(let i=0;i<xs.length;i++){cov+=(xs[i]-mx)*(ys[i]-my);v+=(ys[i]-my)*(ys[i]-my)}const b=v>1e-9?cov/v:0;return xs.map((x,i)=>x-b*(ys[i]-my))}
function solveLag(lag){const rows=[];for(const gp of state.gps){const r=nearestEvent(gp.t-lag,550);if(!r||r.userAccelMag>8)continue;const g=[r.gx||0,r.gy||0,r.gz||0],h=horizontal([r.ax||0,r.ay||0,r.az||0],g);if(mag(h)<.035)continue;const yaw=n(r.yawRateRadS)||0,latTarget=(gp.v||0)*yaw;if(Math.abs(gp.a)<.08&&Math.abs(latTarget)<.12)continue;rows.push({h0:h[0],h1:h[1],h2:h[2],long:gp.a,lat:latTarget,t:gp.t,r})}if(rows.length<14)return null;const longRes=regressOut(rows,'long','lat'),hRes=[0,1,2].map(j=>regressOut(rows,'h'+j,'lat'));const ml=longRes.reduce((s,x)=>s+x,0)/longRes.length,cov=[0,0,0];for(let i=0;i<rows.length;i++)for(let j=0;j<3;j++)cov[j]+=(hRes[j][i]-hRes[j].reduce((s,x)=>s+x,0)/hRes[j].length)*(longRes[i]-ml);let axis=unit(horizontal(cov,state.gravity));if(!axis)return null;let longProj=rows.map(z=>dot([z.h0,z.h1,z.h2],axis)),longY=rows.map(z=>z.long),c=corrXY(longProj,longY);if(c<0){axis=axis.map(x=>-x);longProj=longProj.map(x=>-x);c=-c}let lateralAxis=unit(cross(unit(state.gravity)||[0,0,1],axis));if(!lateralAxis)return null;let latProj=rows.map(z=>dot([z.h0,z.h1,z.h2],lateralAxis)),latY=rows.map(z=>z.lat),lc=corrXY(latProj,latY);if(lc<0){lateralAxis=lateralAxis.map(x=>-x);lc=-lc}return {lag,rows,axis,lateralAxis,corr:c,lateralCorr:lc}}
function solveCalibration(){if(state.gps.length<14||state.events.length<24||!state.gravity)return;let best=null;for(const lag of LAGS){const r=solveLag(lag);if(r&&(!best||(r.corr+.25*r.lateralCorr)>(best.corr+.25*best.lateralCorr)))best=r}if(!best||best.corr<.22)return;const old=state.axis;let next=best.axis;if(old&&dot(old,next)<0)next=next.map(x=>-x);const align=old?dot(old,next):1;if(old&&align<.45&&best.corr>=.50){state.axis=next;state.axisStability=.22;state.axisConfidence=Math.min(state.axisConfidence,.18)}else{state.axisStability=old?clamp(state.axisStability*.55+Math.abs(align)*.45):.55;const cornerGood=best.lateralCorr>=.35||best.rows.every(z=>Math.abs(z.lat)<.35),fast=best.corr>=.62&&Math.abs(align)>=.82&&cornerGood,medium=best.corr>=.48&&Math.abs(align)>=.65,alpha=old?(fast?.55:medium?.32:.12):1;state.axis=old?unit(mix(old,next,alpha)):next}state.lateralAxis=unit(cross(unit(state.gravity)||[0,0,1],state.axis));if(state.lateralAxis&&dot(state.lateralAxis,best.lateralAxis)<0)state.lateralAxis=state.lateralAxis.map(x=>-x);state.correlation=best.corr;state.lateralCorrelation=best.lateralCorr;state.bestLagMs=best.lag;state.pairs=best.rows.slice(-MAX_PAIRS).map(z=>({imu:dot([z.h0,z.h1,z.h2],state.axis),gps:z.long,lateralGps:z.lat,lateralImu:state.lateralAxis?dot([z.h0,z.h1,z.h2],state.lateralAxis):null,t:z.t}));const countScore=clamp(best.rows.length/32),corrScore=clamp((best.corr-.18)/.52),stableScore=clamp((state.axisStability-.30)/.50),cornerScore=clamp(.65+.35*Math.max(0,best.lateralCorr));state.axisConfidence=clamp(countScore*corrScore*(.35+.65*stableScore)*cornerScore);maybeEvent()}
function maybeEvent(){const key=state.mountState+':'+Math.round(state.axisConfidence*10)+':'+state.bestLagMs;if(key===state.lastStateEvent)return;state.lastStateEvent=key;try{globalThis.addLearningEvent?.('imu_autocal_state',{module:VERSION,...snapshot()})}catch{}}
function calibrateFromGps(sample){const gpsA=n(sample?.gpsAccelerationMps2??sample?.gpsAccelMps2??sample?.accelerationMps2??sample?.a),t=n(sample?.t)||Date.now(),kmh=n(sample?.kmh??sample?.gpsKmh)??0;if(gpsA==null)return;state.gps.push({t,a:gpsA,v:Math.max(0,kmh/3.6)});if(state.gps.length>MAX_GPS)state.gps.splice(0,state.gps.length-MAX_GPS);solveCalibration()}
function nearest(t){if(!state.events.length)return null;let best=null,bestDt=Infinity;for(let i=state.events.length-1;i>=0;i--){const r=state.events[i],d=Math.abs(r.t-t);if(d<bestDt){best=r;bestDt=d}if(r.t<t-650)break}return bestDt<=320?{rec:best,age:bestDt}:null}
function fuseSample(s,lowState=state){if(!s)return s;const gpsA=n(s.gpsAccelerationMps2??s.gpsAccelMps2??s.accelerationMps2??s.a),hit=nearest((n(s.t)||Date.now())-state.bestLagMs);if(gpsA==null||!hit){s.gpsAccelerationMps2=gpsA;s.fusedAccelerationMps2=gpsA;return s}const r=hit.rec,imu=n(r.longitudinalMps2);if(imu==null){s.gpsAccelerationMps2=gpsA;s.fusedAccelerationMps2=gpsA;return s}const v=(n(s.kmh??s.gpsKmh)||0)/3.6,yaw=n(r.yawRateRadS)||0,cornerExpected=v*yaw,cornerMeasured=n(r.lateralMps2),cornerActive=Math.abs(cornerExpected)>.35,cornerAgreement=!cornerActive||cornerMeasured==null?1:clamp(1-Math.abs(Math.abs(cornerMeasured)-Math.abs(cornerExpected))/Math.max(.6,Math.abs(cornerExpected)),0,1);lowState.fusionLow=lowState.fusionLow==null?imu:lowState.fusionLow*.88+imu*.12;const fast=imu-lowState.fusionLow,verified=r.mountState==='VERIFIED'&&r.correlation>=.50,cornerPenalty=cornerActive?(.45+.55*cornerAgreement):1,weight=(verified?clamp((r.confidence||0)*(r.correlation||0)*.82,0,.68):clamp((r.confidence||0)*(r.correlation||0)*.14,0,.12))*cornerPenalty,fused=gpsA+weight*fast;s.gpsAccelerationMps2=gpsA;s.imuLongitudinalMps2=imu;s.imuLateralMps2=cornerMeasured;s.imuYawRateRadS=yaw;s.imuCornerExpectedMps2=cornerExpected;s.imuCornerAgreement=cornerAgreement;s.imuCornerActive=cornerActive;s.imuFusionWeight=weight;s.imuFastResidualMps2=fast;s.fusedAccelerationMps2=fused;s.a=fused;s.g=fused/9.80665;const settings=typeof globalThis.currentSettings==='function'?globalThis.currentSettings():{},m=n(settings.mass)||190,rho=n(settings.rho)||1.225,cda=n(settings.cda)||.55,crr=n(settings.crr)||.015,force=m*fused+.5*rho*cda*v*v+crr*m*9.80665,watts=Math.max(0,force*v);s.gpsOnlyHp=Math.max(0,(m*gpsA+.5*rho*cda*v*v+crr*m*9.80665)*v)/735.49875;s.hp=watts/735.49875;s.nm=(n(s.rpm)||0)>200?watts/(s.rpm*2*Math.PI/60):0;return s}
function enrichChunk(chunk){if(!chunk||!Array.isArray(chunk.samples))return chunk;for(const row of chunk.samples){const hit=nearest((n(row.t)||Date.now())-state.bestLagMs);if(!hit)continue;const r=hit.rec;Object.assign(row,{imuRawSchema:RAW_SCHEMA,imuCalibrationVersion:VERSION,imuEventAgeMs:hit.age,imuReceiveTimeMs:r.t,imuEventTimeStampMs:r.eventTimeStampMs,imuIntervalMs:r.intervalMs,imuAccelX:r.ax,imuAccelY:r.ay,imuAccelZ:r.az,imuAccelIncludingGravityX:r.agx,imuAccelIncludingGravityY:r.agy,imuAccelIncludingGravityZ:r.agz,imuRotationAlpha:r.rotAlpha,imuRotationBeta:r.rotBeta,imuRotationGamma:r.rotGamma,imuGravityX:r.gx,imuGravityY:r.gy,imuGravityZ:r.gz,imuLongitudinalMps2:r.longitudinalMps2,imuLateralMps2:r.lateralMps2,imuYawRateRadS:r.yawRateRadS,imuAxisX:r.axisX,imuAxisY:r.axisY,imuAxisZ:r.axisZ,imuLateralAxisX:r.lateralAxisX,imuLateralAxisY:r.lateralAxisY,imuLateralAxisZ:r.lateralAxisZ,imuCalibrationConfidence:r.confidence,imuGpsCorrelation:r.correlation,imuLateralCorrelation:r.lateralCorrelation,imuAxisStability:r.axisStability,imuBestLagMs:r.bestLagMs,imuMountState:r.mountState,imuUserAccelMag:r.userAccelMag,imuRotationMag:r.rotationMag})}chunk.imu={schema:RAW_SCHEMA,calibrationVersion:VERSION,mode:'3d_corner_aware_fast_safe_autocal_fusion',...snapshot()};return chunk}
function patchCollect(){if(state.wrappedCollect||typeof globalThis.collectLearningSample!=='function')return false;const original=globalThis.collectLearningSample;globalThis.collectLearningSample=function(sample){calibrateFromGps(sample);return original.apply(this,arguments)};state.wrappedCollect=true;return true}
function patchPut(){if(state.wrappedPut||typeof globalThis.putRawChunk!=='function')return false;const original=globalThis.putRawChunk;globalThis.putRawChunk=async function(chunk){return original.call(this,enrichChunk(chunk))};state.wrappedPut=true;return true}
function patchWorker(){if(state.wrappedWorker||!globalThis.measurementWorker||typeof globalThis.measurementWorker.onmessage!=='function')return false;const original=globalThis.measurementWorker.onmessage;globalThis.measurementWorker.onmessage=function(e){try{const m=e?.data;if(m?.type==='ui'&&m.data)fuseSample(m.data);if(m?.type==='runComplete'&&Array.isArray(m.run?.data)){const local={fusionLow:null};for(const s of m.run.data)fuseSample(s,local);m.run.maxHp=Math.max(0,...m.run.data.map(x=>x.hp||0));m.run.maxNm=Math.max(0,...m.run.data.map(x=>x.nm||0));m.run.fusionVersion=VERSION}}catch{}return original.call(this,e)};state.wrappedWorker=true;return true}
window.addEventListener('devicemotion',onMotion,{passive:true});const timer=setInterval(()=>{patchCollect();patchPut();patchWorker();if(state.wrappedCollect&&state.wrappedPut&&state.wrappedWorker)clearInterval(timer)},250);patchCollect();patchPut();patchWorker();globalThis.MotoLabImuAutoCal={version:VERSION,schema:RAW_SCHEMA,snapshot,enrichChunk,fuseSample,solveCalibration};try{globalThis.addLearningEvent?.('imu_autocal_loaded',{module:VERSION,schema:RAW_SCHEMA,mode:'3d_corner_aware_fast_safe_autocal_fusion'})}catch{}
})();
