(() => {
'use strict';
const VERSION='motolab-tester-merit-v1';
const SERVER_KEY='motolab_v32_beta_server',TOKEN_KEY='motolab_v32_beta_token';
let merit=null,overlay=null;
const $=id=>document.getElementById(id);
function server(){return String(localStorage.getItem(SERVER_KEY)||'').trim().replace(/\/$/,'').replace(/\/api\/raw\/v1\/chunk$/i,'')}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){const r=await fetch(server()+path,{cache:'no-store',...opt,headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':token(),...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok){const e=Error(j.error||('HTTP '+r.status));e.status=r.status;throw e}return j}
function styles(){if($('motolabMeritStyle'))return;const s=document.createElement('style');s.id='motolabMeritStyle';s.textContent=`.mm-overlay{position:fixed;inset:0;z-index:280000;background:#000e;display:flex;align-items:flex-end;justify-content:center;padding:10px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mm-card{width:min(100%,500px);max-height:94vh;overflow:auto;background:#0b0d11;border:1px solid #a44cff;border-radius:20px;padding:14px}.mm-row{border:1px solid #282d35;border-radius:12px;padding:10px;margin:7px 0}.mm-row small{display:block;color:#9ba3ad;margin-top:4px}.mm-btn{width:100%;padding:9px;margin-top:7px;border:1px solid #a44cff;border-radius:10px;background:#54208f;color:#fff;font-weight:900}.mm-btn.gray{background:#15181d;border-color:#444}.mm-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.mm-grid button{padding:7px 3px}.mm-select,.mm-input{box-sizing:border-box;width:100%;margin:5px 0;padding:9px;border-radius:9px;border:1px solid #343944;background:#06080b;color:#fff}.mm-level{font-size:22px;font-weight:1000}.mm-score{font-size:30px;font-weight:1000;color:#d6b4ff}`;document.head.appendChild(s)}
function close(){overlay?.remove();overlay=null}
function open(html){close();overlay=document.createElement('div');overlay.className='mm-overlay';overlay.innerHTML=`<div class="mm-card">${html}<button class="mm-btn gray" id="mmClose">SULJE</button></div>`;document.body.appendChild(overlay);$('mmClose').onclick=close}
async function refresh(){if(!server()||!token())return;try{merit=(await api('/api/merit/v1/me')).merit;enhanceAccount()}catch{}}
function myPanel(){open(`<h2>Testeritaso</h2><div class="mm-row"><div class="mm-level">${esc(merit?.levelName||'Beta Tester')}</div><small>${esc(merit?.message||'')}</small></div><p style="font-size:10px;color:#aaa">Taso perustuu osallistumisen laatuun, ei viestimäärään. Turhat tai pisteiden vuoksi lähetetyt palautteet eivät nosta tasoa.</p>`)}
async function adminPanel(){const [u,c]=await Promise.all([api('/api/admin/v1/merit/users'),api('/api/admin/v1/merit/candidates')]);open(`<h2>Tester Merit</h2><h3>Testaajat</h3>${u.users.map(x=>`<div class="mm-row"><b>${esc(x.nickname)}</b><div class="mm-score">${x.merit.score}</div><small>${esc(x.merit.levelName)} • reports ${x.merit.categories.reports||0} • community ${x.merit.categories.community||0} • ideas ${x.merit.categories.ideas||0}</small><button class="mm-btn gray" data-bonus="${esc(x.userId)}">BONUSMERIITTI</button></div>`).join('')||'<div class="mm-row">Ei käyttäjiä.</div>'}<h3>Arvioitavat osallistumiset</h3>${c.items.map(x=>`<div class="mm-row"><b>${esc(x.nickname)} • ${esc(x.type)}</b><small>${esc(x.title)}${x.isSolution?' • RATKAISUKSI MERKITTY':''}</small><select class="mm-select" data-cat="${esc(x.sourceId)}"><option value="reports" ${x.suggestedCategory==='reports'?'selected':''}>Raportointi</option><option value="ideas" ${x.suggestedCategory==='ideas'?'selected':''}>Ideat</option><option value="community" ${x.suggestedCategory==='community'?'selected':''}>Yhteisöapu</option><option value="activity">Aktiivisuus</option><option value="data">Data</option><option value="reliability">Luotettavuus</option></select><input class="mm-input" data-reason="${esc(x.sourceId)}" placeholder="Miksi hyödyllinen / miksi 0 p"><select class="mm-select" data-cause="${esc(x.sourceId)}"><option value="none">Ei teknistä epäonnistumista</option><option value="device">Laite rajoitti</option><option value="app">Sovellusvika</option><option value="sensor">Anturivika</option><option value="unknown">Syy tuntematon</option><option value="user">Käyttäjästä johtuva</option></select><div class="mm-grid"><button class="mm-btn gray" data-review="${esc(x.sourceId)}" data-user="${esc(x.userId)}" data-points="0">0 p</button><button class="mm-btn" data-review="${esc(x.sourceId)}" data-user="${esc(x.userId)}" data-points="1">+1</button><button class="mm-btn" data-review="${esc(x.sourceId)}" data-user="${esc(x.userId)}" data-points="3">+3</button><button class="mm-btn" data-review="${esc(x.sourceId)}" data-user="${esc(x.userId)}" data-points="5">+5</button></div></div>`).join('')||'<div class="mm-row">Ei arvioitavaa.</div>'}<div id="mmStatus"></div>`);document.querySelectorAll('[data-review]').forEach(b=>b.onclick=async()=>{const id=b.dataset.review;try{await api('/api/admin/v1/merit/review',{method:'POST',body:JSON.stringify({sourceId:id,userId:b.dataset.user,points:Number(b.dataset.points),category:document.querySelector(`[data-cat="${CSS.escape(id)}"]`)?.value||'reports',reason:document.querySelector(`[data-reason="${CSS.escape(id)}"]`)?.value||'',cause:document.querySelector(`[data-cause="${CSS.escape(id)}"]`)?.value||'none'})});await adminPanel()}catch(e){$('mmStatus').textContent=e.message}});document.querySelectorAll('[data-bonus]').forEach(b=>b.onclick=()=>bonusPanel(b.dataset.bonus,u.users.find(x=>x.userId===b.dataset.bonus)?.nickname||''))}
function bonusPanel(userId,nickname){open(`<h2>Bonusmeriitti</h2><div class="mm-row"><b>${esc(nickname)}</b></div><select id="mmBonusCat" class="mm-select"><option value="ideas">Hyvä idea</option><option value="reports">Raportointi</option><option value="community">Yhteisöapu</option><option value="data">Data</option><option value="reliability">Luotettavuus</option><option value="activity">Aktiivisuus</option></select><input id="mmBonusPoints" class="mm-input" type="number" min="1" max="15" value="5"><input id="mmBonusReason" class="mm-input" placeholder="Perustelu"><button class="mm-btn" id="mmBonusSave">MYÖNNÄ MERIITTI</button><div id="mmStatus"></div>`);$('mmBonusSave').onclick=async()=>{try{await api('/api/admin/v1/merit/bonus',{method:'POST',body:JSON.stringify({userId,category:$('mmBonusCat').value,points:Number($('mmBonusPoints').value),reason:$('mmBonusReason').value})});await adminPanel()}catch(e){$('mmStatus').textContent=e.message}}}
function enhanceAccount(){const p=$('motolabUserPanel');if(!p||p.dataset.meritEnhanced)return;p.dataset.meritEnhanced='1';const card=p.querySelector('.mui-card'),closeBtn=$('muiClose');if(!card||!closeBtn)return;const b=document.createElement('button');b.className='mui-btn secondary';b.textContent='TESTERITASO • '+(merit?.levelName||'Beta Tester');b.onclick=myPanel;card.insertBefore(b,closeBtn);const me=globalThis.MotoLabUser?.user;if(me?.role==='admin'){const a=document.createElement('button');a.className='mui-btn secondary';a.textContent='TESTER MERIT / PISTEYTYS';a.onclick=adminPanel;card.insertBefore(a,closeBtn)}}
function boot(){styles();refresh();new MutationObserver(()=>enhanceAccount()).observe(document.documentElement,{childList:true,subtree:true});setInterval(refresh,60000)}
globalThis.MotoLabMerit={version:VERSION,refresh,myPanel,adminPanel,get merit(){return merit}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
