(() => {
'use strict';
const VERSION='motorlab-i18n-v2';
const KEY='motolab_language';
const FI='fi',EN='en';
const exact={
'MITTAUS':'MEASURE','ETUSIVU':'HOME','VEDOT':'RUNS','ANALYYSI':'ANALYSIS','ASETUKSET':'SETTINGS','KÄYTTÄJÄ':'USER','KÄYTTÄJÄ / BETA':'USER / BETA','LIVE / ANTURIT':'LIVE / SENSORS','LIVE':'LIVE DATA',
'NOPEUS':'SPEED','TEHO':'POWER','VÄÄNTÖ':'TORQUE','VAIHDE':'GEAR','VALMIS':'READY','POIS':'OFF','PÄÄLLÄ':'ON','ANTURIT':'SENSORS','BT KUULOKE':'MIC','ARM AUTO':'ARM AUTO','MANUAALI':'MANUAL','PYSÄYTÄ':'STOP','STOP':'STOP',
'VETO':'RUN','VERTAA':'COMPARE','YHDISTÄ':'MERGE','MYÖS HYLÄTYT':'INCLUDE REJECTED','PÄÄLLEKKÄISVERTAILU':'OVERLAY COMPARISON','AVAA':'OPEN','SULJE':'CLOSE','POISTA VETO':'DELETE RUN','AVAA KÄYRÄ KOKO NÄYTÖLLE':'OPEN FULL-SCREEN CURVE',
'KAASUTTIMEN SÄÄTÖ':'CARBURETOR TUNING','SUUTIN-EHDOTUS':'JETTING SUGGESTION','TALLENNA SÄÄTÖ':'SAVE TUNE','LASKE EHDOTUS':'CALCULATE SUGGESTION',
'PYÖRÄ':'BIKE','MITTAUS & RPM':'MEASUREMENT & RPM','AJONEUVON TIEDOT':'VEHICLE DETAILS','AJONEUVOTIEDON HAKU':'VEHICLE LOOKUP','VÄLITYKSET':'DRIVETRAIN','TEKNISET TIEDOT':'TECHNICAL SPECS','HUOLTO & HISTORIA':'MAINTENANCE & HISTORY','SOVELLUS':'APP','KIELI':'LANGUAGE','SUOMI':'FINNISH','ENGLANTI':'ENGLISH',
'TALLENNA ASETUKSET':'SAVE SETTINGS','UUSI':'NEW','ASENNA / OHJE':'INSTALL / HELP','KOKO NÄYTTÖ':'FULL SCREEN','TALLENNA':'SAVE','PERUUTA':'CANCEL','TYHJENNÄ':'CLEAR','HAE':'SEARCH','KÄYTÄ TÄTÄ':'USE THIS','TALLENNA VÄLITYKSET':'SAVE DRIVETRAIN','TALLENNA TEKNISET TIEDOT':'SAVE TECHNICAL SPECS','MERKITSE TEHDYKSI':'MARK DONE',
'OMA TILI':'MY ACCOUNT','PALAUTE & VIESTIT':'FEEDBACK & MESSAGES','BETA-KESKUSTELU':'BETA COMMUNITY','BETA-YHTEISÖ':'BETA COMMUNITY','JAETUT VEDOT':'SHARED RUNS','TESTERITASO':'TESTER LEVEL','KUTSU TESTAAJA':'INVITE TESTER','KÄYTTÄJIEN HYVÄKSYNNÄT':'USER APPROVALS','PALAUTTEET':'FEEDBACK','MERIT-ARVIOINTI':'MERIT REVIEW','KÄYTTÖOIKEUDET':'FEATURE ACCESS','YHTEISÖ / DIAGNOSTIIKKA':'COMMUNITY / DIAGNOSTICS',
'3. VAIHTEEN TESTI':'3RD GEAR TEST','ALOITA 3. VAIHDE':'START 3RD GEAR TEST','MIKÄ VAIHDE KÄYTÖSSÄ?':'WHICH GEAR IS ENGAGED?','OHITA':'SKIP','VAHVISTA':'CONFIRM','OPETUSDATA':'TRAINING DATA','REFERENSSI':'REFERENCE',
'DIAGNOSTIIKKA':'DIAGNOSTICS','TAPAHTUMALOKI':'EVENT LOG','SYNKRONOINTI':'SYNC','RAAKADATA':'RAW DATA','JÄRJESTELMÄ':'SYSTEM','VIRHE':'ERROR','VAROITUS':'WARNING','LUOTTAMUS':'CONFIDENCE','AUDIOLÄHDE':'AUDIO INPUT','LÄHDE':'SOURCE','JONO':'QUEUE',
'ODOTTAA HYVÄKSYNTÄÄ':'PENDING APPROVAL','AKTIIVINEN':'ACTIVE','ESTETTY':'BLOCKED','ILMOITA ONGELMASTA':'REPORT AN ISSUE','LÄHETÄ':'SEND','VASTAA':'REPLY','MINULLA SAMA ONGELMA':'I HAVE THE SAME ISSUE','RATKAISU':'SOLUTION','TOIMIVA RATKAISU':'WORKING SOLUTION','YKSITYINEN':'PRIVATE','ANONYYMI':'ANONYMOUS'
};
const reverse=Object.fromEntries(Object.entries(exact).map(([a,b])=>[b,a]));
const originals=new WeakMap();
const $=id=>document.getElementById(id);
function lang(){return localStorage.getItem(KEY)==='en'?EN:FI}
function translateText(s,to){const raw=String(s??'');const trimmed=raw.trim();if(!trimmed)return raw;const dict=to===EN?exact:reverse;if(dict[trimmed])return raw.replace(trimmed,dict[trimmed]);let out=raw;for(const [a,b] of Object.entries(dict).sort((x,y)=>y[0].length-x[0].length)){if(out.includes(a))out=out.split(a).join(b)}return out}
function translatable(raw){return translateText(raw,EN)!==raw}
function skipNode(n){const p=n?.parentElement;return !p||['SCRIPT','STYLE','TEXTAREA','INPUT','OPTION','CODE','PRE'].includes(p.tagName)||p.dataset.i18nSkip==='1'||!String(n.nodeValue||'').trim()}
function translateNode(n,to){if(skipNode(n))return;const raw=n.nodeValue;let src=originals.get(n);if(src){const expected=to===EN?translateText(src,EN):src;if(raw!==expected&&raw!==src&&translatable(raw)){src=raw;originals.set(n,raw)}}else if(translatable(raw)){src=raw;originals.set(n,raw)}if(!src)return;const next=to===EN?translateText(src,EN):src;if(raw!==next)n.nodeValue=next}
function translateRoot(root=document.body){if(!root)return;const to=lang();const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(walker.nextNode())translateNode(walker.currentNode,to);document.querySelectorAll('input[placeholder]').forEach(el=>{if(!el.dataset.mlFiPlaceholder)el.dataset.mlFiPlaceholder=el.getAttribute('placeholder')||'';const src=el.dataset.mlFiPlaceholder;const next=to===EN?translateText(src,EN):src;if(el.placeholder!==next)el.placeholder=next});document.querySelectorAll('option').forEach(o=>{if(!o.dataset.mlFiText)o.dataset.mlFiText=o.textContent||'';const src=o.dataset.mlFiText,next=to===EN?translateText(src,EN):src;if(o.textContent!==next)o.textContent=next})}
function setLang(v){const next=v===EN?EN:FI;if(localStorage.getItem(KEY)!==next)localStorage.setItem(KEY,next);document.documentElement.lang=next;apply();document.dispatchEvent(new CustomEvent('motorlab-language-change',{detail:{language:next}}));try{globalThis.MOTOLAB_DIAGNOSTICS?.record?.('language_changed',{language:next,module:VERSION})}catch{}return next}
function selector(){const sec=$('screen-settings');if(!sec||$('motorlabLanguagePanel'))return;const p=document.createElement('div');p.className='panel';p.id='motorlabLanguagePanel';p.dataset.mlOriginalTitle='KIELI';p.innerHTML='<div class="phead"><div class="ptitle"><span class="r">🌐</span> KIELI</div></div><div class="form"><label class="full">Kieli / Language<select id="motorlabLanguage"><option value="fi">Suomi</option><option value="en">English</option></select></label></div><div class="statusbox">Kielen vaihto ei käynnistä antureita tai mittausta uudelleen.</div>';const app=[...sec.querySelectorAll(':scope > .panel')].find(x=>/SOVELLUS/i.test(x.textContent||''));sec.insertBefore(p,app||sec.firstChild);const sel=$('motorlabLanguage');sel.value=lang();sel.onchange=()=>setLang(sel.value);globalThis.MotoLabSimpleUI?.apply?.()}
function apply(){document.documentElement.lang=lang();selector();translateRoot();const sel=$('motorlabLanguage');if(sel&&sel.value!==lang())sel.value=lang()}
function boot(){apply();let pending=false;new MutationObserver(records=>{if(pending)return;if(!records.some(r=>r.addedNodes?.length))return;pending=true;requestAnimationFrame(()=>{pending=false;apply()})}).observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('motorlab-cloud-state-applied',()=>setTimeout(apply,0))}
globalThis.MotorLabI18n={version:VERSION,get language(){return lang()},setLanguage:setLang,apply,t:(s)=>lang()===EN?translateText(s,EN):s};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
