(() => {
'use strict';
const VERSION='motorlab-branding-v4',ASSET='./assets/motorlab_splash_approved.webp';const $=id=>document.getElementById(id);
function style(){if($('motorlabBrandStyle'))return;const s=document.createElement('style');s.id='motorlabBrandStyle';s.textContent=`body.ml-splash-open{overflow:hidden!important}#motorlabSplash{position:fixed;inset:0;z-index:500000;background:#000;display:flex;align-items:center;justify-content:center;opacity:1;pointer-events:auto}#motorlabSplash.ml-hide{opacity:0;transition:opacity .45s ease}#motorlabSplash img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;display:block}#motorlabSplashVersion{position:absolute;left:50%;bottom:calc(15px + env(safe-area-inset-bottom));transform:translateX(-50%);padding:5px 9px;border-radius:999px;border:1px solid rgba(255,38,63,.45);background:rgba(0,0,0,.65);color:#ddd;font:800 9px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;letter-spacing:.08em}.brand{font-size:0!important;display:flex;align-items:baseline;gap:3px}.brand:before{content:'VäNä';font-size:13px;color:#fff;font-weight:1000;font-style:italic}.brand:after{content:'MotorLab';font-size:13px;color:#ff263f;font-weight:1000;font-style:italic}.logo1{font-size:0!important}.logo1:after{content:'VäNä';font-size:48px;line-height:.9;color:#fff;font-weight:1000;font-style:italic;letter-spacing:-3px}.logo2{font-size:0!important}.logo2:after{content:'MotorLab';font-size:35px;line-height:.9;color:#ff263f;font-weight:1000;font-style:italic;letter-spacing:-2px}`;document.head.appendChild(s)}
function visibleBrand(root=document.body){if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(w.nextNode()){const n=w.currentNode,p=n.parentElement;if(!p||['SCRIPT','STYLE','CODE','PRE','TEXTAREA'].includes(p.tagName))continue;const old=n.nodeValue||'';if(!/motolab/i.test(old))continue;const next=old.replace(/VÄNÄ\s+MOTOLAB/gi,'VÄNÄ MOTORLAB').replace(/VäNä\s+MotoLab/g,'VäNä MotorLab').replace(/MotoLab/g,'MotorLab').replace(/MOTOLAB/g,'MOTORLAB');if(next!==old)n.nodeValue=next}}
function relabel(){const title=`VäNä MotorLab ${globalThis.MOTOLAB_RELEASE?.label||''}`.trim();if(document.title!==title)document.title=title;document.querySelectorAll('.brand').forEach(b=>b.setAttribute('aria-label','VäNä MotorLab'));const fv=$('motolabFullVersion'),txt=`VÄNÄ MOTORLAB ${globalThis.MOTOLAB_RELEASE?.label||''} • build ${globalThis.MOTOLAB_RELEASE?.build||''}`;if(fv&&fv.textContent!==txt)fv.textContent=txt;visibleBrand()}
function release(){if(globalThis.MotorLabStartupReady)return;globalThis.MotorLabStartupReady=true;document.dispatchEvent(new CustomEvent('motorlab-startup-ready'))}
async function splash(){if($('motorlabSplash'))return;const el=document.createElement('div');el.id='motorlabSplash';const img=new Image();img.alt='VäNä Motorsport MotorLab';img.decoding='sync';img.fetchPriority='high';img.src=ASSET;el.appendChild(img);const v=document.createElement('div');v.id='motorlabSplashVersion';v.textContent=globalThis.MOTOLAB_RELEASE?.label||'';el.appendChild(v);document.body.classList.add('ml-splash-open');document.body.prepend(el);try{if(img.decode)await img.decode()}catch{}const shown=performance.now();const finish=()=>{const wait=Math.max(0,3000-(performance.now()-shown));setTimeout(()=>{el.classList.add('ml-hide');setTimeout(()=>{el.remove();document.body.classList.remove('ml-splash-open');release()},480)},wait)};if(document.readyState==='complete')finish();else window.addEventListener('load',finish,{once:true});setTimeout(()=>{if(el.isConnected){el.remove();document.body.classList.remove('ml-splash-open');release()}},6500)}
function boot(){style();relabel();splash();let pending=false;new MutationObserver(records=>{if(pending||!records.some(r=>r.addedNodes?.length))return;pending=true;requestAnimationFrame(()=>{pending=false;relabel()})}).observe(document.documentElement,{subtree:true,childList:true})}
globalThis.MotorLabBranding={version:VERSION,apply:relabel,showSplash:splash};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
