(() => {
'use strict';
const VERSION='motolab-password-login-v2-self-register';
const TOKEN_KEY='motolab_v32_beta_token',NICK_KEY='motolab_user_nickname';
const SERVER='https://v-n-autodyno-production.up.railway.app';
const nativeFetch=window.fetch.bind(window);
const MIN_PASSWORD=8;
const $=id=>document.getElementById(id);
function api(){return globalThis.MotoLabUser?.productionServer||SERVER}
function deviceId(){return globalThis.MotoLabUser?.deviceId?.()||localStorage.getItem('motolab_v32_raw_sync_device')||''}
function deviceLabel(){return [navigator.platform||'',navigator.userAgent.includes('iPhone')?'iPhone':''].filter(Boolean).join(' ').slice(0,80)}
function validPassword(p){return String(p||'').length>=MIN_PASSWORD&&String(p||'').length<=128}
async function jsonRequest(path,opt={}){const r=await nativeFetch(api()+path,{cache:'no-store',...opt});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
function saveSession(j,nickname){if(!j?.token)throw Error('Kirjautumistoken puuttuu.');localStorage.setItem(TOKEN_KEY,j.token);localStorage.setItem(NICK_KEY,j.user?.nickname||String(nickname||'').trim())}
async function passwordLogin(nickname,password){nickname=String(nickname||'').trim();password=String(password||'');if(!nickname)throw Error('Nimimerkki puuttuu.');if(!password)throw Error('Salasana puuttuu.');const j=await jsonRequest('/api/users/v1/password-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nickname,password,deviceId:deviceId(),deviceLabel:deviceLabel()})});saveSession(j,nickname);return await globalThis.MotoLabUser?.refresh?.()||j.user||null}
async function register(nickname,password){nickname=String(nickname||'').trim();password=String(password||'');if(nickname.length<2)throw Error('Nimimerkissä pitää olla vähintään 2 merkkiä.');if(!validPassword(password))throw Error(`Valitse vähintään ${MIN_PASSWORD} merkin salasana.`);const j=await jsonRequest('/api/users/v1/password-register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nickname,password,deviceId:deviceId(),deviceLabel:deviceLabel()})});saveSession(j,nickname);sessionStorage.removeItem('motorlab_pending_invite');return await globalThis.MotoLabUser?.refresh?.()||j.user||null}
async function setPassword(password){password=String(password||'');if(!validPassword(password))throw Error(`Salasanassa pitää olla vähintään ${MIN_PASSWORD} merkkiä.`);const token=localStorage.getItem(TOKEN_KEY)||'';if(!token)throw Error('Kirjaudu ensin käyttäjätilille.');return jsonRequest('/api/users/v1/password',{method:'POST',headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':token},body:JSON.stringify({password})})}
async function ownerActivate(code,nickname,password){code=String(code||'').trim();nickname=String(nickname||'').trim();password=String(password||'');if(!code)throw Error('Owner-koodi puuttuu.');if(!nickname)throw Error('Nimimerkki puuttuu.');if(!validPassword(password))throw Error(`Valitse vähintään ${MIN_PASSWORD} merkin salasana.`);const j=await jsonRequest('/api/beta/v1/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,invite:code,deviceId:deviceId(),deviceLabel:deviceLabel(),nickname})});saveSession(j,nickname);await setPassword(password);return await globalThis.MotoLabUser?.refresh?.()||j.user||null}
function makePasswordInput(id,placeholder='Vähintään 8 merkkiä'){const i=document.createElement('input');i.id=id;i.type='password';i.autocomplete='current-password';i.placeholder=placeholder;i.minLength=MIN_PASSWORD;i.maxLength=128;return i}
function addLabel(text,before){const l=document.createElement('label');l.textContent=text;before.parentNode.insertBefore(l,before);return l}
function hideInviteElements(code,activate){if(code){const prev=code.previousElementSibling;if(prev?.tagName==='LABEL')prev.style.display='none';code.style.display='none'}if(activate)activate.style.display='none'}
function addOwnerRecovery(card,nick,pw,msg,before){if(card.querySelector('[data-owner-recovery]'))return;const toggle=document.createElement('button');toggle.type='button';toggle.className=before.className.includes('mui')?'mui-id-btn gray':'mls-ghost';toggle.textContent='OWNER / ADMIN PALAUTUS';toggle.dataset.ownerRecovery='1';const wrap=document.createElement('div');wrap.style.display='none';wrap.innerHTML='<label>Owner-koodi</label><input type="password" autocomplete="off" placeholder="Owner-koodi"><button type="button">PALAUTA OWNER / ADMIN</button>';const ownerInput=wrap.querySelector('input'),ownerBtn=wrap.querySelector('button');ownerBtn.className=before.className.includes('mui')?'mui-id-btn':'mls-secondary';before.parentNode.insertBefore(toggle,before);before.parentNode.insertBefore(wrap,before);toggle.onclick=()=>{wrap.style.display=wrap.style.display==='none'?'block':'none'};ownerBtn.onclick=async()=>{ownerBtn.disabled=true;if(msg)msg.textContent='Palautetaan owner-tiliä…';try{const u=await ownerActivate(ownerInput.value,nick.value,pw.value);if(msg)msg.textContent=u?.status==='active'?'Owner / admin palautettu.':'Owner-palautus odottaa hyväksyntää.';if(u?.status==='active')globalThis.MotoLabSplash?.close?.();else globalThis.MotoLabUser?.openAccount?.()}catch(e){if(msg)msg.textContent='Owner-palautus epäonnistui: '+e.message}finally{ownerBtn.disabled=false}}}
function enhanceSplash(){const card=$('motolabBootLogin');if(!card||card.dataset.passwordEnhanced)return;const code=$('motolabBootCode'),nick=$('motolabBootNick'),activate=$('motolabBootActivate'),refresh=$('motolabBootRefresh');if(!nick||!activate||!refresh)return;card.dataset.passwordEnhanced='1';hideInviteElements(code,activate);const copy=card.querySelector('.mls-login-copy');if(copy)copy.textContent='Kirjaudu nimimerkillä ja salasanalla. Uusi käyttäjä voi rekisteröityä ilman kutsulinkkiä ja odottaa ylläpidon hyväksyntää.';const pw=makePasswordInput('motolabBootPassword');addLabel('Salasana',refresh);refresh.parentNode.insertBefore(pw,refresh);const login=document.createElement('button');login.id='motolabBootPasswordLogin';login.className='mls-secondary';login.textContent='KIRJAUDU';const reg=document.createElement('button');reg.id='motolabBootRegister';reg.className='mls-primary';reg.textContent='REKISTERÖIDY';refresh.parentNode.insertBefore(login,refresh);refresh.parentNode.insertBefore(reg,refresh);const msg=$('motolabBootLoginMsg');login.onclick=async()=>{login.disabled=reg.disabled=true;if(msg)msg.textContent='Kirjaudutaan…';try{const u=await passwordLogin(nick.value,pw.value);if(u?.status==='active'){if(msg)msg.textContent='Kirjautuminen valmis.';globalThis.MotoLabSplash?.close?.()}else if(msg)msg.textContent=u?'Käyttäjä odottaa ylläpidon hyväksyntää.':'Kirjautuminen epäonnistui.'}catch(e){if(msg)msg.textContent='Kirjautuminen epäonnistui: '+e.message}finally{login.disabled=reg.disabled=false}};reg.onclick=async()=>{login.disabled=reg.disabled=true;if(msg)msg.textContent='Luodaan käyttäjätili…';try{const u=await register(nick.value,pw.value);if(msg)msg.textContent=u?.status==='active'?'Tili valmis.':'Rekisteröinti valmis. Odottaa ylläpidon hyväksyntää.';if(u?.status==='active')globalThis.MotoLabSplash?.close?.()}catch(e){if(msg)msg.textContent='Rekisteröinti epäonnistui: '+e.message}finally{login.disabled=reg.disabled=false}};addOwnerRecovery(card,nick,pw,msg,refresh)}
function enhanceAccount(){for(const card of document.querySelectorAll('.mui-id-card')){if(card.dataset.passwordEnhanced)continue;const nick=$('muiNick');if(!nick||!card.contains(nick))continue;card.dataset.passwordEnhanced='1';const active=!!globalThis.MotoLabUser?.user,status=$('muiIdStatus'),refresh=$('muiRefresh');if(!refresh)continue;if(active){const pw=makePasswordInput('muiNewPassword','Uusi salasana, vähintään 8 merkkiä');pw.autocomplete='new-password';addLabel('Salasana',refresh);refresh.parentNode.insertBefore(pw,refresh);const btn=document.createElement('button');btn.className='mui-id-btn';btn.textContent='ASETA / VAIHDA SALASANA';refresh.parentNode.insertBefore(btn,refresh);btn.onclick=async()=>{btn.disabled=true;if(status)status.textContent='Tallennetaan salasanaa…';try{await setPassword(pw.value);pw.value='';if(status)status.textContent='Salasana tallennettu.'}catch(e){if(status)status.textContent=e.message}finally{btn.disabled=false}}}else{const code=$('muiInviteCode'),activate=$('muiActivate');hideInviteElements(code,activate);const pw=makePasswordInput('muiPassword');addLabel('Salasana',refresh);refresh.parentNode.insertBefore(pw,refresh);const login=document.createElement('button');login.className='mui-id-btn gray';login.textContent='KIRJAUDU';const reg=document.createElement('button');reg.className='mui-id-btn';reg.textContent='REKISTERÖIDY';refresh.parentNode.insertBefore(login,refresh);refresh.parentNode.insertBefore(reg,refresh);login.onclick=async()=>{login.disabled=reg.disabled=true;if(status)status.textContent='Kirjaudutaan…';try{await passwordLogin(nick.value,pw.value);globalThis.MotoLabUser?.openAccount?.('Kirjautuminen valmis.')}catch(e){if(status)status.textContent='Kirjautuminen epäonnistui: '+e.message}finally{login.disabled=reg.disabled=false}};reg.onclick=async()=>{login.disabled=reg.disabled=true;if(status)status.textContent='Luodaan käyttäjätili…';try{await register(nick.value,pw.value);globalThis.MotoLabUser?.openAccount?.('Rekisteröinti valmis. Odottaa ylläpidon hyväksyntää.')}catch(e){if(status)status.textContent='Rekisteröinti epäonnistui: '+e.message}finally{login.disabled=reg.disabled=false}};addOwnerRecovery(card,nick,pw,status,refresh)}}}
function enhance(){enhanceSplash();enhanceAccount()}
const observer=new MutationObserver(()=>queueMicrotask(enhance));
function boot(){observer.observe(document.documentElement,{childList:true,subtree:true});enhance();document.addEventListener('motorlab-user-ready',()=>setTimeout(enhance,0))}
globalThis.MotoLabPassword={version:VERSION,login:passwordLogin,register,setPassword,ownerActivate,minLength:MIN_PASSWORD};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
