(() => {
'use strict';
const VERSION='motolab-password-login-v1';
const TOKEN_KEY='motolab_v32_beta_token',NICK_KEY='motolab_user_nickname';
const SERVER='https://v-n-autodyno-production.up.railway.app';
const nativeFetch=window.fetch.bind(window);
const MIN_PASSWORD=8;
const $=id=>document.getElementById(id);
function api(){return globalThis.MotoLabUser?.productionServer||SERVER}
function deviceId(){return globalThis.MotoLabUser?.deviceId?.()||localStorage.getItem('motolab_v32_raw_sync_device')||''}
function deviceLabel(){return [navigator.platform||'',navigator.userAgent.includes('iPhone')?'iPhone':''].filter(Boolean).join(' ').slice(0,80)}
function validPassword(p){return String(p||'').length>=MIN_PASSWORD&&String(p||'').length<=128}
async function jsonRequest(path,opt={}){const r=await nativeFetch(api()+path,{cache:'no-store',...opt});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
async function passwordLogin(nickname,password){nickname=String(nickname||'').trim();password=String(password||'');if(!nickname)throw Error('Nimimerkki puuttuu.');if(!password)throw Error('Salasana puuttuu.');const j=await jsonRequest('/api/users/v1/password-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nickname,password,deviceId:deviceId(),deviceLabel:deviceLabel()})});if(!j.token)throw Error('Kirjautumistoken puuttuu.');localStorage.setItem(TOKEN_KEY,j.token);localStorage.setItem(NICK_KEY,j.user?.nickname||nickname);return await globalThis.MotoLabUser?.refresh?.()||j.user||null}
async function setPassword(password){password=String(password||'');if(!validPassword(password))throw Error(`Salasanassa pitää olla vähintään ${MIN_PASSWORD} merkkiä.`);const token=localStorage.getItem(TOKEN_KEY)||'';if(!token)throw Error('Kirjaudu ensin käyttäjätilille.');const j=await jsonRequest('/api/users/v1/password',{method:'POST',headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':token},body:JSON.stringify({password})});return j}
async function activateWithPassword(code,nickname,password){code=String(code||'').trim();nickname=String(nickname||'').trim();password=String(password||'');if(!code)throw Error('Kutsukoodi puuttuu.');if(!nickname)throw Error('Nimimerkki puuttuu.');if(!validPassword(password))throw Error(`Valitse vähintään ${MIN_PASSWORD} merkin salasana.`);const j=await jsonRequest('/api/beta/v1/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,invite:code,deviceId:deviceId(),deviceLabel:deviceLabel(),nickname})});if(!j.token)throw Error('Aktivointitoken puuttuu.');localStorage.setItem(TOKEN_KEY,j.token);localStorage.setItem(NICK_KEY,j.user?.nickname||nickname);await setPassword(password);sessionStorage.removeItem('motorlab_pending_invite');return await globalThis.MotoLabUser?.refresh?.()||j.user||null}
function makePasswordInput(id,placeholder='Vähintään 8 merkkiä'){const i=document.createElement('input');i.id=id;i.type='password';i.autocomplete='current-password';i.placeholder=placeholder;i.minLength=MIN_PASSWORD;i.maxLength=128;return i}
function addLabel(text,before){const l=document.createElement('label');l.textContent=text;before.parentNode.insertBefore(l,before);return l}
function enhanceSplash(){const card=$('motolabBootLogin');if(!card||card.dataset.passwordEnhanced)return;card.dataset.passwordEnhanced='1';const code=$('motolabBootCode'),nick=$('motolabBootNick'),activate=$('motolabBootActivate');if(!code||!nick||!activate)return;const pw=makePasswordInput('motolabBootPassword');addLabel('Salasana',code);code.parentNode.insertBefore(pw,code);const login=document.createElement('button');login.id='motolabBootPasswordLogin';login.className='mls-secondary';login.textContent='KIRJAUDU SALASANALLA';activate.parentNode.insertBefore(login,activate);const msg=$('motolabBootLoginMsg');login.onclick=async()=>{login.disabled=true;activate.disabled=true;if(msg)msg.textContent='Kirjaudutaan…';try{const u=await passwordLogin(nick.value,pw.value);if(u?.status==='active'){if(msg)msg.textContent='Kirjautuminen valmis.';globalThis.MotoLabSplash?.close?.()}else if(msg)msg.textContent=u?'Käyttäjä odottaa hyväksyntää.':'Kirjautuminen epäonnistui.'}catch(e){if(msg)msg.textContent='Kirjautuminen epäonnistui: '+e.message}finally{login.disabled=false;activate.disabled=false}};activate.onclick=async()=>{activate.disabled=true;login.disabled=true;if(msg)msg.textContent='Aktivoidaan käyttäjä ja tallennetaan salasana…';try{const u=await activateWithPassword(code.value,nick.value,pw.value);if(u?.status==='active'){if(msg)msg.textContent='Aktivointi valmis.';globalThis.MotoLabSplash?.close?.()}else if(msg)msg.textContent='Laite rekisteröity. Odottaa ylläpidon hyväksyntää.'}catch(e){if(msg)msg.textContent='Aktivointi epäonnistui: '+e.message}finally{activate.disabled=false;login.disabled=false}}}
function enhanceAccount(){const cards=[...document.querySelectorAll('.mui-id-card')];for(const card of cards){if(card.dataset.passwordEnhanced)return;const nick=$('muiNick');if(!nick||!card.contains(nick))continue;card.dataset.passwordEnhanced='1';const active=!!globalThis.MotoLabUser?.user;const status=$('muiIdStatus');if(active){const refresh=$('muiRefresh');if(!refresh)continue;const pw=makePasswordInput('muiNewPassword','Uusi salasana, vähintään 8 merkkiä');pw.autocomplete='new-password';addLabel('Salasana',refresh);refresh.parentNode.insertBefore(pw,refresh);const btn=document.createElement('button');btn.className='mui-id-btn';btn.textContent='ASETA / VAIHDA SALASANA';refresh.parentNode.insertBefore(btn,refresh);btn.onclick=async()=>{btn.disabled=true;if(status)status.textContent='Tallennetaan salasanaa…';try{await setPassword(pw.value);pw.value='';if(status)status.textContent='Salasana tallennettu.'}catch(e){if(status)status.textContent=e.message}finally{btn.disabled=false}}}else{const code=$('muiInviteCode'),activate=$('muiActivate');if(!code||!activate)continue;const pw=makePasswordInput('muiPassword');addLabel('Salasana',code);code.parentNode.insertBefore(pw,code);const login=document.createElement('button');login.className='mui-id-btn gray';login.textContent='KIRJAUDU SALASANALLA';activate.parentNode.insertBefore(login,activate);login.onclick=async()=>{login.disabled=true;activate.disabled=true;if(status)status.textContent='Kirjaudutaan…';try{await passwordLogin(nick.value,pw.value);globalThis.MotoLabUser?.openAccount?.('Kirjautuminen valmis.')}catch(e){if(status)status.textContent='Kirjautuminen epäonnistui: '+e.message}finally{login.disabled=false;activate.disabled=false}};activate.onclick=async()=>{activate.disabled=true;login.disabled=true;if(status)status.textContent='Aktivoidaan…';try{await activateWithPassword(code.value,nick.value,pw.value);globalThis.MotoLabUser?.openAccount?.('Aktivointi ja salasana tallennettu.')}catch(e){if(status)status.textContent='Aktivointi epäonnistui: '+e.message}finally{activate.disabled=false;login.disabled=false}}}}
}
function enhance(){enhanceSplash();enhanceAccount()}
const observer=new MutationObserver(()=>queueMicrotask(enhance));
function boot(){observer.observe(document.documentElement,{childList:true,subtree:true});enhance();document.addEventListener('motorlab-user-ready',()=>setTimeout(enhance,0))}
globalThis.MotoLabPassword={version:VERSION,login:passwordLogin,setPassword,activate:activateWithPassword,minLength:MIN_PASSWORD};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
