(() => {
'use strict';
const MODULE_VERSION='v34-user-raw-auto-sync-2-force-flush';
const CFG_KEY='motolab_v32_raw_sync_cfg';
const QUEUE_KEY='motolab_v32_raw_sync_queue';
const DEVICE_KEY='motolab_v32_raw_sync_device';
const TOKEN_KEY='motolab_v32_beta_token';
const SERVER_KEY='motolab_v32_beta_server';
const PRODUCTION_SERVER='https://v-n-autodyno-production.up.railway.app';
const $r=id=>document.getElementById(id);
let syncing=false,syncTimer=null;

function readCfg(){try{return {...{enabled:false,endpoint:'',ingestKey:'',deviceLabel:'iPhone'},...JSON.parse(localStorage.getItem(CFG_KEY)||'{}')}}catch{return {enabled:false,endpoint:'',ingestKey:'',deviceLabel:'iPhone'}}}
function writeCfg(c){localStorage.setItem(CFG_KEY,JSON.stringify(c))}
function readQueue(){try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||'{"pending":[],"sent":0,"lastOk":null,"lastError":null}')}catch{return {pending:[],sent:0,lastOk:null,lastError:null}}}
function writeQueue(q){q.pending=(q.pending||[]).slice(-2500);localStorage.setItem(QUEUE_KEY,JSON.stringify(q));renderState()}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
function loggedIn(){return !!token()&&globalThis.MotoLabUser?.user?.status==='active'}
function server(){return globalThis.MotoLabUser?.productionServer||localStorage.getItem(SERVER_KEY)||PRODUCTION_SERVER}
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=(crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem(DEVICE_KEY,id)}return id}
function normalizeEndpoint(s){s=String(s||'').trim();if(!s)return '';if(!/^https:\/\//i.test(s))throw Error('Vastaanottimen pitää käyttää HTTPS-yhteyttä.');s=s.replace(/\/$/,'');if(!/\/api\/raw\/v1\/chunk$/i.test(s))s+='/api/raw/v1/chunk';return s}
function enqueue(id){if(!id)return;const q=readQueue();if(!q.pending.some(x=>x.id===id))q.pending.push({id,added:Date.now(),tries:0,nextAttempt:0});writeQueue(q);scheduleSync(300)}
async function getChunk(id){
 if(typeof db!=='undefined'&&db&&typeof useFallback!=='undefined'&&!useFallback&&db.objectStoreNames.contains('rawChunks'))return await new Promise((resolve,reject)=>{const tx=db.transaction('rawChunks','readonly'),req=tx.objectStore('rawChunks').get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)});
 try{const a=JSON.parse(localStorage.getItem('motolab_v29_raw_fallback')||'[]');for(const c of a)if(c.id===id)return c}catch{}
 return null
}
function statusText(t){const e=$r('rawSyncStatus');if(e)e.textContent=t}
function renderState(){const c=readCfg(),q=readQueue(),auto=loggedIn();if($r('rawSyncEnabled'))$r('rawSyncEnabled').classList.toggle('on',auto||!!c.enabled);if($r('rawSyncEndpoint')&&document.activeElement!==$r('rawSyncEndpoint'))$r('rawSyncEndpoint').value=c.endpoint||'';if($r('rawSyncKey')&&document.activeElement!==$r('rawSyncKey'))$r('rawSyncKey').value=c.ingestKey||'';if($r('rawSyncLabel')&&document.activeElement!==$r('rawSyncLabel'))$r('rawSyncLabel').value=c.deviceLabel||'';if($r('rawSyncQueue'))$r('rawSyncQueue').textContent=String(q.pending?.length||0);if($r('rawSyncSent'))$r('rawSyncSent').textContent=String(q.sent||0);if($r('rawSyncLast'))$r('rawSyncLast').textContent=q.lastOk?new Date(q.lastOk).toLocaleString('fi-FI'):'–';const note=$r('rawSyncMode');if(note)note.textContent=auto?'Kirjautunut käyttäjä: kaikki RAW-data synkataan automaattisesti käyttäjätilille.':'Vierastila: RAW pysyy paikallisena, ellei manuaalista vastaanotinta oteta käyttöön.'}
function saveFromUi(){const c=readCfg();c.endpoint=($r('rawSyncEndpoint')?.value||'').trim();c.ingestKey=$r('rawSyncKey')?.value||'';c.deviceLabel=($r('rawSyncLabel')?.value||'').trim()||'iPhone';writeCfg(c);renderState();return c}
async function sendAuthenticated(chunk,cfg){const payload={schema:'motolab_user_raw_envelope_v1',moduleVersion:MODULE_VERSION,deviceId:deviceId(),deviceLabel:cfg.deviceLabel||'',uploadedAt:new Date().toISOString(),chunk};const r=await fetch(server()+'/api/users/v1/raw-chunk',{method:'POST',headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':token()},body:JSON.stringify(payload),cache:'no-store'});let body={};try{body=await r.json()}catch{}if(!r.ok)throw Error(body.error||('HTTP '+r.status));return body}
async function sendManual(chunk,cfg){const endpoint=normalizeEndpoint(cfg.endpoint);if(!endpoint||!cfg.ingestKey)throw Error('Aseta vastaanottimen URL ja ingest-avain.');const payload={schema:'motolab_raw_sync_envelope_v1',moduleVersion:MODULE_VERSION,deviceId:deviceId(),deviceLabel:cfg.deviceLabel||'',uploadedAt:new Date().toISOString(),chunk};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-MotoLab-Ingest-Key':cfg.ingestKey},body:JSON.stringify(payload),cache:'no-store'});let body={};try{body=await r.json()}catch{}if(!r.ok)throw Error(body.error||('HTTP '+r.status));return body}
async function sendChunk(chunk,cfg){return loggedIn()?sendAuthenticated(chunk,cfg):sendManual(chunk,cfg)}
async function syncNow(force=false){if(syncing)return;const cfg=readCfg(),auto=loggedIn();if(!auto&&!cfg.enabled&&!force)return;if(!auto&&(!cfg.endpoint||!cfg.ingestKey)){statusText('RAW tallennetaan paikallisesti. Kirjaudu sisään automaattista käyttäjäkohtaista pilvitallennusta varten.');return}syncing=true;clearTimeout(syncTimer);syncTimer=null;try{let q=readQueue(),done=0,skipped=0;for(const item of [...q.pending]){if(!force&&done>=20)break;if(!force&&item.nextAttempt&&Date.now()<item.nextAttempt){skipped++;continue}const chunk=await getChunk(item.id);if(!chunk){const live=q.pending.find(x=>x.id===item.id);if(live){live.tries=(live.tries||0)+1;live.nextAttempt=Date.now()+Math.min(15*60*1000,5000*Math.pow(2,Math.min(7,live.tries-1)))}q.lastError='RAW chunk ei ollut juuri nyt luettavissa paikallisesta tietovarastosta: '+item.id;writeQueue(q);continue}try{await sendChunk(chunk,cfg);q.pending=q.pending.filter(x=>x.id!==item.id);q.sent=(q.sent||0)+1;q.lastOk=Date.now();q.lastError=null;done++;writeQueue(q)}catch(e){const live=q.pending.find(x=>x.id===item.id);if(live){live.tries=(live.tries||0)+1;live.nextAttempt=Date.now()+Math.min(15*60*1000,5000*Math.pow(2,Math.min(7,live.tries-1)))}q.lastError=String(e.message||e);writeQueue(q);statusText('Synkkaus jäi jonoon: '+q.lastError);break}}q=readQueue();if(!q.pending.length)statusText(`${auto?'Käyttäjäkohtainen RAW-synkkaus':'RAW AUTO SYNC'} valmis • lähetetty yhteensä ${q.sent||0}.`);else if(done)statusText(`Lähetetty ${done} • jonossa ${q.pending.length}${skipped?' • osa odottaa uutta yritystä':''}.`)}finally{syncing=false;renderState();if((loggedIn()||readCfg().enabled)&&readQueue().pending.length)scheduleSync(15000)}}
function scheduleSync(ms=1000){if(syncTimer)return;syncTimer=setTimeout(()=>{syncTimer=null;syncNow(false)},ms)}
async function queueAllLocal(){if(typeof getLearningChunks!=='function'){statusText('RAW-tietovarastoa ei löytynyt.');return}statusText('Haetaan paikalliset RAW-jaksot jonoon…');try{const chunks=await getLearningChunks(false);for(const c of chunks)enqueue(c.id);statusText(`Jonotettu ${chunks.length} paikallista RAW-jaksoa.`);scheduleSync(200);return chunks.length}catch(e){statusText('Jonotus epäonnistui: '+e.message);throw e}}
async function forceFlushAll(reason='auto'){if(!loggedIn()&&!readCfg().enabled)return;try{await queueAllLocal();const q=readQueue();for(const item of q.pending||[])item.nextAttempt=0;writeQueue(q);statusText(`Pakotetaan RAW-jono ulos (${reason}) • jonossa ${q.pending?.length||0}.`);await syncNow(true)}catch(e){statusText('RAW-pakotettu synkkaus epäonnistui: '+(e.message||e));scheduleSync(5000)}}
async function exportRawJson(){if(typeof getLearningChunks!=='function'){statusText('RAW-tietovarastoa ei löytynyt.');return}statusText('Kootaan RAW JSON -tiedostoa…');try{const chunks=await getLearningChunks(false);if(!chunks.length){statusText('Paikallista RAW-dataa ei löytynyt vietäväksi.');return}const payload={schema:'motolab_raw_export_v1',exportedAt:new Date().toISOString(),release:globalThis.MOTOLAB_RELEASE||null,deviceId:deviceId(),deviceLabel:readCfg().deviceLabel||'iPhone',chunkCount:chunks.length,chunks};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const stamp=new Date().toISOString().replace(/[:.]/g,'-');const fileName=`MotoLab_RAW_${stamp}.json`;const file=new File([blob],fileName,{type:'application/json'});if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'MotoLab RAW data'});statusText(`RAW JSON valmis • ${chunks.length} chunkia • avattiin iPhonen jakovalikko.`)}else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);statusText(`RAW JSON ladattu • ${chunks.length} chunkia.`)}}catch(e){if(e?.name==='AbortError'){statusText('RAW-vienti peruttiin.');return}statusText('RAW-vienti epäonnistui: '+(e.message||e))}}
async function testReceiver(){const c=saveFromUi();try{const test={id:'connection-test-'+Date.now(),sessionId:'connection-test',created:new Date().toISOString(),schema:'connection_test',samples:[],events:[]};await sendChunk(test,c);statusText(loggedIn()?'Käyttäjäkohtainen palvelintallennus toimii.':'Vastaanotin toimii. Testipaketti hyväksyttiin.')}catch(e){statusText('Vastaanottimen testi epäonnistui: '+e.message)}}
function installUi(){if($r('rawAutoSyncPanel'))return true;const settings=$r('screen-settings');if(!settings)return false;const panels=[...settings.querySelectorAll('.panel')];const anchor=panels.find(p=>/OPPIMIS|RAAKA|RAW/i.test(p.textContent||''))||panels[panels.length-1]||settings;const p=document.createElement('div');p.className='panel';p.id='rawAutoSyncPanel';p.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">☁️</span> DATA / RAW SYNC</div><span class="tiny">${MODULE_VERSION}</span></div><div id="rawSyncMode" class="statusbox"></div><div class="form"><button id="rawExportJson" class="action full" type="button">VIE RAW DATA • JSON</button><label class="full">Laitteen nimi<input id="rawSyncLabel" value="iPhone" placeholder="esim. Antti iPhone"></label><button id="rawSyncAll" class="action gray full" type="button">JONOTA KAIKKI PAIKALLISET RAW-TIEDOT</button><button id="rawSyncNow" class="action full" type="button">PAKOTA KAIKKI RAW ULOS NYT</button><details class="full"><summary>Vanha manuaalinen RAW-vastaanotin</summary><div class="switchrow"><div><b style="font-size:9px">Manuaalinen RAW-synkkaus</b></div><button id="rawSyncEnabled" class="switch" type="button"></button></div><label class="full">Vastaanottimen HTTPS-URL<input id="rawSyncEndpoint" type="url" placeholder="https://...up.railway.app"></label><label class="full">Ingest-avain<input id="rawSyncKey" type="password" autocomplete="off"></label><button id="rawSyncSave" class="action gray full" type="button">TALLENNA VANHAT ASETUKSET</button></details><button id="rawSyncTest" class="action gray full" type="button">TESTAA TALLENNUS</button></div><div class="grid2"><div class="card"><span>Jonossa</span><b id="rawSyncQueue">0</b></div><div class="card"><span>Lähetetty</span><b id="rawSyncSent">0</b></div><div class="card full"><span>Viimeisin onnistuminen</span><b id="rawSyncLast">–</b></div></div><div id="rawSyncStatus" class="statusbox">Kirjautuneen aktiivisen käyttäjän RAW-data tallennetaan automaattisesti käyttäjäkohtaisesti palvelimelle.</div>`;anchor.insertAdjacentElement('afterend',p);$r('rawExportJson').onclick=exportRawJson;$r('rawSyncEnabled').onclick=()=>{const c=saveFromUi();c.enabled=!c.enabled;writeCfg(c);renderState();if(c.enabled)scheduleSync(100)};$r('rawSyncSave').onclick=()=>{saveFromUi();statusText('Manuaalisen RAW-vastaanottimen asetukset tallennettu vain tähän laitteeseen.')};$r('rawSyncTest').onclick=testReceiver;$r('rawSyncAll').onclick=queueAllLocal;$r('rawSyncNow').onclick=()=>forceFlushAll('manual');renderState();return true}
function patchRawStore(){if(typeof putRawChunk!=='function'||putRawChunk.__rawSyncPatched)return false;const original=putRawChunk;const patched=async function(chunk){const out=await original(chunk);enqueue(chunk?.id);return out};patched.__rawSyncPatched=true;putRawChunk=patched;return true}
function boot(){const a=installUi(),b=patchRawStore();if(!a||!b){setTimeout(boot,200);return}window.addEventListener('online',()=>forceFlushAll('online'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')forceFlushAll('resume')});document.addEventListener('motorlab-user-ready',()=>{renderState();forceFlushAll('user-ready')});if(loggedIn())forceFlushAll('boot');else if(readCfg().enabled)forceFlushAll('boot-manual');if(typeof addLearningEvent==='function')addLearningEvent('user_raw_auto_sync_loaded',{module:MODULE_VERSION,deviceId:deviceId()})}
globalThis.MotoLabRawSync={moduleVersion:MODULE_VERSION,readQueue,queueAllLocal,syncNow,forceFlushAll};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
