(() => {
'use strict';
const MODULE_VERSION='v32-research-sync-1';
const CFG_KEY='motolab_research_sync_cfg',STATE_KEY='motolab_research_sync_state',DEVICE_KEY='motolab_research_sync_device';
const DB_NAME='VanaMotoLabResearch',DB_VERSION=1,SESSION_STORE='sessions',AUDIO_STORE='audioChunks',TIMELINE_STORE='timelineChunks';
const $=id=>document.getElementById(id);
let busy=false,timer=null;
function cfg(){let c={enabled:false,endpoint:'',ingestKey:'',driver:'',phone:''};try{Object.assign(c,JSON.parse(localStorage.getItem(CFG_KEY)||'{}'))}catch{}try{const r=JSON.parse(localStorage.getItem('motolab_v32_raw_sync_cfg')||'{}');if(!c.endpoint&&r.endpoint)c.endpoint=String(r.endpoint).replace(/\/api\/raw\/v1\/chunk\/?$/,'');if(!c.ingestKey&&r.ingestKey)c.ingestKey=r.ingestKey;if(!c.phone&&r.deviceLabel)c.phone=r.deviceLabel}catch{}return c}
function saveCfg(c){localStorage.setItem(CFG_KEY,JSON.stringify(c))}
function state(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{return {}}}
function saveState(s){localStorage.setItem(STATE_KEY,JSON.stringify(s))}
function deviceId(){let x=localStorage.getItem(DEVICE_KEY);if(!x){x=crypto.randomUUID?crypto.randomUUID():'phone-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(DEVICE_KEY,x)}return x}
function baseUrl(v){v=String(v||'').trim().replace(/\/$/,'');if(!v)throw Error('Vastaanottimen URL puuttuu.');if(!/^https:\/\//i.test(v))throw Error('Vastaanottimen pitää käyttää HTTPS-yhteyttä.');return v.replace(/\/api\/raw\/v1\/chunk$/,'')}
function status(t){const e=$('researchSyncStatus');if(e)e.textContent=t}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(SESSION_STORE))d.createObjectStore(SESSION_STORE,{keyPath:'id'});if(!d.objectStoreNames.contains(AUDIO_STORE)){const s=d.createObjectStore(AUDIO_STORE,{keyPath:'id'});s.createIndex('sessionId','sessionId',{unique:false})}if(!d.objectStoreNames.contains(TIMELINE_STORE)){const s=d.createObjectStore(TIMELINE_STORE,{keyPath:'id'});s.createIndex('sessionId','sessionId',{unique:false})}}})}
async function getAll(store){const d=await openDb();return await new Promise((resolve,reject)=>{const tx=d.transaction(store,'readonly'),r=tx.objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function bySession(store,id){const d=await openDb();return await new Promise((resolve,reject)=>{const tx=d.transaction(store,'readonly'),s=tx.objectStore(store),r=s.index('sessionId').getAll(id);r.onsuccess=()=>resolve((r.result||[]).sort((a,b)=>(a.index||0)-(b.index||0)));r.onerror=()=>reject(r.error)})}
async function postJson(url,key,obj){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-MotoLab-Ingest-Key':key},body:JSON.stringify(obj),cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
async function postAudio(url,key,meta,blob){const q=new URLSearchParams({deviceId:meta.deviceId,sessionId:meta.sessionId,index:String(meta.index),startMs:String(meta.startMs||0),endMs:String(meta.endMs||0),mime:meta.mime||blob.type||'application/octet-stream',driver:meta.driver||'',phone:meta.phone||''});const r=await fetch(url+'?'+q,{method:'POST',headers:{'Content-Type':blob.type||meta.mime||'application/octet-stream','X-MotoLab-Ingest-Key':key},body:blob,cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
function sessionEnvelope(s,c){return {schema:'motolab_research_session_v1',deviceId:deviceId(),driver:c.driver||'',phone:c.phone||'',uploadedAt:new Date().toISOString(),session:s}}
async function syncSession(s,c,allState){const url=baseUrl(c.endpoint),key=c.ingestKey;if(!key)throw Error('Ingest-avain puuttuu.');const ss=allState[s.id]||{started:false,timeline:-1,audio:-1,finished:false};if(!ss.started){await postJson(url+'/api/research/v1/start',key,sessionEnvelope(s,c));ss.started=true;saveState({...allState,[s.id]:ss})}
 const tls=await bySession(TIMELINE_STORE,s.id);for(const x of tls){if((x.index??-1)<=ss.timeline)continue;await postJson(url+'/api/research/v1/data',key,{schema:'motolab_research_data_v1',deviceId:deviceId(),driver:c.driver||'',phone:c.phone||'',sessionId:s.id,index:x.index,createdAt:x.createdAt,frames:x.frames||[]});ss.timeline=x.index;allState[s.id]=ss;saveState(allState)}
 const aus=await bySession(AUDIO_STORE,s.id);for(const x of aus){if((x.index??-1)<=ss.audio)continue;await postAudio(url+'/api/research/v1/audio',key,{deviceId:deviceId(),sessionId:s.id,index:x.index,startMs:x.startMs,endMs:x.endMs,mime:x.mime,driver:c.driver||'',phone:c.phone||''},x.blob);ss.audio=x.index;allState[s.id]=ss;saveState(allState)}
 const allTimelineDone=!tls.length||ss.timeline>=(tls[tls.length-1].index??-1),allAudioDone=!aus.length||ss.audio>=(aus[aus.length-1].index??-1);if(s.endedAt&&!ss.finished&&allTimelineDone&&allAudioDone){await postJson(url+'/api/research/v1/finish',key,{schema:'motolab_research_finish_v1',deviceId:deviceId(),driver:c.driver||'',phone:c.phone||'',sessionId:s.id,endedAt:s.endedAt,durationMs:s.durationMs||null,audioChunks:s.audioChunks||aus.length,timelineChunks:s.timelineChunks||tls.length,frameCount:s.frameCount||null,candidateFrameCount:s.candidateFrameCount||null});ss.finished=true;allState[s.id]=ss;saveState(allState)}return ss}
async function syncNow(force=false){if(busy)return;const c=cfg();if(!c.enabled&&!force)return;if(!c.endpoint||!c.ingestKey){status('AUTO RESEARCH SYNC odottaa vastaanottimen URL:ia ja ingest-avainta.');return}busy=true;try{const sessions=(await getAll(SESSION_STORE)).sort((a,b)=>(a.startedAtMs||0)-(b.startedAtMs||0)),st=state();let done=0;for(const s of sessions){const before=JSON.stringify(st[s.id]||{});await syncSession(s,c,st);if(JSON.stringify(st[s.id]||{})!==before)done++}const pending=sessions.filter(s=>!st[s.id]?.finished).length;status(`AUTO SYNC OK • sessioita ${sessions.length} • keskeneräisiä ${pending}${done?' • päivitetty '+done:''}`);render()}catch(e){status('AUTO SYNC jonossa: '+(e.message||e))}finally{busy=false}}
function schedule(ms=1000){clearTimeout(timer);timer=setTimeout(()=>syncNow(false),ms)}
function render(){const c=cfg(),st=state();if($('researchSyncEnabled'))$('researchSyncEnabled').classList.toggle('on',!!c.enabled);if($('researchSyncEndpoint')&&document.activeElement!==$('researchSyncEndpoint'))$('researchSyncEndpoint').value=c.endpoint||'';if($('researchSyncKey')&&document.activeElement!==$('researchSyncKey'))$('researchSyncKey').value=c.ingestKey||'';if($('researchSyncDriver')&&document.activeElement!==$('researchSyncDriver'))$('researchSyncDriver').value=c.driver||'';if($('researchSyncPhone')&&document.activeElement!==$('researchSyncPhone'))$('researchSyncPhone').value=c.phone||'';if($('researchSyncDevice'))$('researchSyncDevice').textContent=deviceId().slice(0,12);if($('researchSyncComplete'))$('researchSyncComplete').textContent=String(Object.values(st).filter(x=>x.finished).length)}
function fromUi(){const c=cfg();c.endpoint=$('researchSyncEndpoint')?.value.trim()||'';c.ingestKey=$('researchSyncKey')?.value||'';c.driver=$('researchSyncDriver')?.value.trim()||'';c.phone=$('researchSyncPhone')?.value.trim()||'';saveCfg(c);return c}
async function test(){try{const c=fromUi(),url=baseUrl(c.endpoint);const r=await fetch(url+'/health',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);status('Vastaanotin vastaa. Lähetysasetukset ovat valmiit.')}catch(e){status('Testi epäonnistui: '+(e.message||e))}}
function inject(){if($('researchSyncPanel'))return true;const screen=$('screen-settings');if(!screen)return false;const p=document.createElement('div');p.className='panel';p.id='researchSyncPanel';p.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">☁️</span> AUTO RESEARCH SYNC</div><span class="tiny">${MODULE_VERSION}</span></div><div class="statusbox">Lähettää 3. vaihteen tutkimusajon GPS/candidate-aikajanan ja 5 s BT-audiopalat automaattisesti yhteiseen vastaanottimeen. Yhteyskatkossa data jää puhelimeen ja lähetys jatkuu myöhemmin.</div><div class="form"><div class="switchrow"><div><b style="font-size:9px">Automaattinen lähetys</b><div class="tiny">Toimii myös usealla puhelimella yhtä aikaa.</div></div><button id="researchSyncEnabled" class="switch" type="button"></button></div><label class="full">Vastaanottimen URL<input id="researchSyncEndpoint" type="url" placeholder="https://...up.railway.app"></label><label class="full">Ingest-avain<input id="researchSyncKey" type="password" autocomplete="off"></label><label>Kuski<input id="researchSyncDriver" placeholder="esim. Antti"></label><label>Puhelin<input id="researchSyncPhone" placeholder="esim. iPhone A"></label><button id="researchSyncSave" class="action full">TALLENNA</button><button id="researchSyncTest" class="action gray">TESTAA</button><button id="researchSyncNow" class="action">SYNKKAA NYT</button></div><div class="grid2"><div class="card"><span>Device ID</span><b id="researchSyncDevice">–</b></div><div class="card"><span>Valmiiksi lähetetty</span><b id="researchSyncComplete">0</b></div></div><div id="researchSyncStatus" class="statusbox">AUTO SYNC ei lähetä mitään ennen kuin se on kytketty päälle.</div>`;screen.appendChild(p);$('researchSyncEnabled').onclick=()=>{const c=fromUi();c.enabled=!c.enabled;saveCfg(c);render();status(c.enabled?'AUTO RESEARCH SYNC päällä.':'AUTO RESEARCH SYNC pois päältä.');if(c.enabled)schedule(100)};$('researchSyncSave').onclick=()=>{fromUi();render();status('Asetukset tallennettu tähän puhelimeen.');schedule(100)};$('researchSyncTest').onclick=test;$('researchSyncNow').onclick=()=>syncNow(true);render();return true}
function boot(){if(!inject()){setTimeout(boot,200);return}window.addEventListener('online',()=>schedule(300));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule(500)});setInterval(()=>schedule(50),7000);schedule(1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
