(() => {
'use strict';
const VERSION='motorlab-run-analysis-v34-v1';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=(fi,en)=>globalThis.MotorLabI18n?.language==='en'?en:fi;
const num=(v,d=1)=>Number.isFinite(+v)?(+v).toFixed(d):'–';
function css(){if($('mlRunAnalysisStyle'))return;const s=document.createElement('style');s.id='mlRunAnalysisStyle';s.textContent=`
.ml-ab-form{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:8px}.ml-ab-form label{min-width:0}.ml-ab-form select{width:100%}.ml-ab-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:0 8px 8px}.ml-ab-summary{margin:8px;padding:10px;border:1px solid #302126;border-radius:11px;background:#08090c;font-size:9px;line-height:1.55}.ml-ab-summary b{color:#fff}.ml-ab-summary .gain{color:#65f477;font-weight:900}.ml-ab-summary .loss{color:#ff6b7e;font-weight:900}.ml-ab-summary .warn{color:#ffc62b}.ml-ab-table{width:100%;border-collapse:collapse;margin-top:8px}.ml-ab-table td{padding:5px 4px;border-top:1px solid #26282d;vertical-align:top}.ml-ab-table td:first-child{color:#969da7;width:34%}.ml-meta-form{display:grid;grid-template-columns:1fr 1fr;gap:7px}.ml-meta-form label{font-size:8px;color:#9ba0a8}.ml-meta-form .full{grid-column:1/-1}.ml-meta-note{margin-top:7px;padding:8px;border:1px solid #554314;border-radius:9px;background:#211a06;color:#ffd35d;font-size:8px;line-height:1.45}.ml-active-profile{margin:6px 8px 0;padding:7px 9px;border:1px solid #2d3036;border-radius:9px;background:#0a0b0e;color:#aeb4bd;font-size:8px}.ml-active-profile b{color:#fff}
`;document.head.appendChild(s)}
function label(r){const d=r?.date?new Date(r.date).toLocaleString(globalThis.MotorLabI18n?.language==='en'?'en-GB':'fi-FI'):'–';return `${r?.profileName||tr('Pyörä','Bike')} • ${d} • ${num(r?.maxHp,1)} hv`}
function allRuns(){try{return Array.isArray(runs)?runs:[]}catch{return []}}
function activeProfile(){try{return typeof getCurrentProfile==='function'?getCurrentProfile():null}catch{return null}}
function ensureAnalysisPanel(){const sec=$('screen-analysis');if(!sec||$('mlRunABPanel'))return;const p=document.createElement('div');p.id='mlRunABPanel';p.className='panel';p.innerHTML=`
<div class="phead"><div class="ptitle"><span class="r">⚖️</span> ${tr('VETO A / VETO B – SÄÄTÖVERTAILU','RUN A / RUN B – TUNING COMPARISON')}</div></div>
<div class="ml-ab-form"><label>${tr('Veto A','Run A')}<select id="mlRunA"></select></label><label>${tr('Veto B','Run B')}<select id="mlRunB"></select></label></div>
<div class="ml-ab-actions"><button id="mlCompareAB" class="action">${tr('VERTAA VETOJA','COMPARE RUNS')}</button><button id="mlOpenABFull" class="action gray">${tr('AVAA KÄYRÄ','OPEN CURVE')}</button></div>
<div class="chartwrap"><canvas id="mlABChart" class="chart" width="900" height="520"></canvas></div>
<div id="mlABSummary" class="ml-ab-summary">${tr('Valitse kaksi eri vetoa. Vertailu näyttää sekä mitatun suorituskyvyn että vedoille tallennetut säädöt.','Select two different runs. Comparison shows measured performance and the tuning metadata saved with each run.')}</div>`;
 const first=sec.querySelector('.panel');sec.insertBefore(p,first||sec.firstChild);$('mlCompareAB').onclick=compareAB;$('mlOpenABFull').onclick=()=>{const rr=getAB();if(rr&&typeof openFull==='function')openFull(rr,tr('Veto A / Veto B','Run A / Run B'))};refreshRunOptions()}
function refreshRunOptions(){const a=$('mlRunA'),b=$('mlRunB');if(!a||!b)return;const prevA=a.value,prevB=b.value,p=activeProfile();const list=allRuns().slice().sort((x,y)=>{const xp=x.profileId===p?.id?0:1,yp=y.profileId===p?.id?0:1;return xp-yp||new Date(y.date)-new Date(x.date)});const opts='<option value="">'+tr('Valitse veto…','Select run…')+'</option>'+list.map(r=>`<option value="${esc(r.id)}">${esc(label(r))}</option>`).join('');a.innerHTML=opts;b.innerHTML=opts;if(list.some(r=>r.id===prevA))a.value=prevA;if(list.some(r=>r.id===prevB))b.value=prevB;if(!a.value&&list[0])a.value=list[0].id;if(!b.value&&list[1])b.value=list[1].id;if(a.value===b.value&&list[1])b.value=list.find(r=>r.id!==a.value)?.id||''}
function getAB(){const a=allRuns().find(r=>r.id===$('mlRunA')?.value),b=allRuns().find(r=>r.id===$('mlRunB')?.value);return a&&b&&a.id!==b.id?[a,b]:null}
function hpAt(r,rpm){const pts=(r?.data||[]).filter(x=>Number.isFinite(x.rpm)&&Number.isFinite(x.hp)&&Math.abs(x.rpm-rpm)<=220);return pts.length?pts.reduce((s,x)=>s+x.hp,0)/pts.length:NaN}
function performanceBands(a,b){const all=[...(a.data||[]),...(b.data||[])].filter(x=>Number.isFinite(x.rpm)&&x.rpm>0);if(!all.length)return '';const lo=Math.ceil(Math.max(Math.min(...(a.data||[]).filter(x=>x.rpm>0).map(x=>x.rpm)),Math.min(...(b.data||[]).filter(x=>x.rpm>0).map(x=>x.rpm)))/500)*500;const hi=Math.floor(Math.min(Math.max(...(a.data||[]).map(x=>x.rpm||0)),Math.max(...(b.data||[]).map(x=>x.rpm||0)))/500)*500;const winsA=[],winsB=[];for(let rpm=lo;rpm<=hi;rpm+=500){const x=hpAt(a,rpm),y=hpAt(b,rpm);if(!Number.isFinite(x)||!Number.isFinite(y)||Math.max(x,y)<=0)continue;const d=(y-x)/Math.max(.01,x)*100;if(d>2)winsB.push(rpm);else if(d<-2)winsA.push(rpm)}const fmt=x=>x.length?`${Math.min(...x)}–${Math.max(...x)} rpm`:'–';return `<tr><td>${tr('Parempi tehoalue','Stronger power range')}</td><td>A: ${fmt(winsA)}<br>B: ${fmt(winsB)}</td></tr>`}
const metaFields=[
 ['mainJet','Pääsuutin','Main jet'],['pilotJet','Tyhjäkäyntisuutin','Pilot jet'],['needleType','Neula','Needle'],['needleClip','Neulan klipsi','Needle clip'],['airScrew','Seosruuvi','Air screw'],['slide','Luisti','Slide'],
 ['ignitionMap','Sytytyskartta / versio','Ignition map / version'],['ignitionTiming','Sytytys ° / huomio','Ignition ° / note'],['ypvs','YPVS-asetus','YPVS setting'],['fuel','Polttoaine','Fuel'],['temperatureC','Lämpötila °C','Temperature °C'],['pressureHpa','Ilmanpaine hPa','Air pressure hPa'],['afr','AFR','AFR'],['egt','EGT °C','EGT °C'],['setupTag','Kokoonpanotagi','Setup tag'],['notes','Muistiinpano','Notes']
];
function meta(r){const t=r?.tuning||{},c=r?.carb||{};return {...t,mainJet:t.mainJet??c.mainJet,pilotJet:t.pilotJet??c.pilotJet,needleType:t.needleType??c.needleType,needleClip:t.needleClip??c.needleClip,airScrew:t.airScrew??c.airScrew,slide:t.slide??c.slide,setupTag:t.setupTag??r?.knowledge?.setupTag??''}}
function same(a,b){return String(a??'').trim()===String(b??'').trim()}
function tuningRows(a,b){const ma=meta(a),mb=meta(b);const rows=metaFields.filter(([k])=>!same(ma[k],mb[k])||String(ma[k]??'').trim()||String(mb[k]??'').trim()).map(([k,fi,en])=>`<tr><td>${tr(fi,en)}</td><td>A: <b>${esc(ma[k]??'–')}</b><br>B: <b>${esc(mb[k]??'–')}</b>${same(ma[k],mb[k])?'':' <span class="gain">'+tr('MUUTTUI','CHANGED')+'</span>'}</td></tr>`);return rows.join('')||`<tr><td>${tr('Säädöt','Tuning')}</td><td>${tr('Ei kirjattuja eroja.','No recorded differences.')}</td></tr>`}
function compareAB(){const rr=getAB(),box=$('mlABSummary');if(!rr){if(box)box.textContent=tr('Valitse kaksi eri vetoa.','Select two different runs.');return}const [a,b]=rr;if(typeof drawChart==='function')drawChart($('mlABChart'),rr,true);const dh=(b.maxHp||0)-(a.maxHp||0),dn=(b.maxNm||0)-(a.maxNm||0),hpPct=a.maxHp?dh/a.maxHp*100:0,nmPct=a.maxNm?dn/a.maxNm*100:0;const caveats=[];if(a.profileId!==b.profileId)caveats.push(tr('eri pyöräprofiilit','different bike profiles'));if(a.gear&&b.gear&&a.gear!==b.gear)caveats.push(tr('eri vaihde','different gear'));if(Math.abs((a.quality||0)-(b.quality||0))>15)caveats.push(tr('suuri laatuero','large quality difference'));if(a.setupSignature&&b.setupSignature&&a.setupSignature!==b.setupSignature)caveats.push(tr('kokoonpanosignatuuri muuttui','setup signature changed'));const cls=dh>=0?'gain':'loss';box.innerHTML=`<b>${tr('MITATTU ERO B − A','MEASURED DIFFERENCE B − A')}</b><br><span class="${cls}">${dh>=0?'+':''}${dh.toFixed(1)} hv (${hpPct>=0?'+':''}${hpPct.toFixed(1)} %)</span> • ${dn>=0?'+':''}${dn.toFixed(1)} Nm (${nmPct>=0?'+':''}${nmPct.toFixed(1)} %)<table class="ml-ab-table"><tr><td>${tr('Veto A','Run A')}</td><td>${esc(label(a))} • ${tr('laatu','quality')} ${a.quality??'–'}/100</td></tr><tr><td>${tr('Veto B','Run B')}</td><td>${esc(label(b))} • ${tr('laatu','quality')} ${b.quality??'–'}/100</td></tr>${performanceBands(a,b)}${tuningRows(a,b)}</table>${caveats.length?`<div class="warn">⚠ ${tr('Vertailussa huomioitavaa','Comparison caveats')}: ${esc(caveats.join(', '))}.</div>`:''}<div class="tiny" style="margin-top:7px">${tr('Suorituskyky on mitattua dataa. Säädöt ovat vedolle tallennettua metadataa; sovellus ei väitä muutosta syyksi ilman riittävää vertailukelpoisuutta.','Performance is measured data. Tuning values are run metadata; the app does not claim causation without sufficient comparability.')}</div>`}
async function persistRun(r){if(!r?.id)return false;const arr=allRuns();const i=arr.findIndex(x=>x.id===r.id);if(i>=0)arr[i]=r;if(useFallback||!db){localStorage.setItem(FALLBACK_RUNS,JSON.stringify(arr.slice(0,80)))}else await new Promise((resolve,reject)=>{const tx=db.transaction('runs','readwrite');tx.objectStore('runs').put(r);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});if(typeof renderRuns==='function')renderRuns();if(typeof renderAnalysis==='function')renderAnalysis();refreshRunOptions();return true}
function ensureEditModal(){if($('mlRunEditModal'))return;const d=document.createElement('div');d.id='mlRunEditModal';d.className='modal';d.innerHTML=`<div class="sheet"><h3>${tr('MUOKKAA VEDON TIETOJA','EDIT RUN DETAILS')}</h3><div class="ml-meta-note">${tr('Mittaus- ja RAW-dataa ei muuteta. Nämä kentät ovat vedon metadataa ja jälkikäteen tallennetut arvot merkitään sellaisiksi.','Measurement and RAW data are never changed. These fields are run metadata and post-run edits are marked as such.')}</div><div class="ml-meta-form" style="margin-top:9px">
<label>${tr('Pääsuutin','Main jet')}<input id="mlMetaMain" type="number"></label><label>${tr('Tyhjäkäyntisuutin','Pilot jet')}<input id="mlMetaPilot" type="number"></label>
<label>${tr('Neula','Needle')}<input id="mlMetaNeedle"></label><label>${tr('Klipsi','Clip')}<input id="mlMetaClip"></label>
<label>${tr('Seosruuvi','Air screw')}<input id="mlMetaAir" type="number" step="0.25"></label><label>${tr('Luisti','Slide')}<input id="mlMetaSlide" type="number"></label>
<label>${tr('Sytytyskartta / versio','Ignition map / version')}<input id="mlMetaIgnMap"></label><label>${tr('Sytytys ° / huomio','Ignition ° / note')}<input id="mlMetaIgnTiming"></label>
<label>${tr('YPVS-asetus','YPVS setting')}<input id="mlMetaYpvs"></label><label>${tr('Polttoaine','Fuel')}<input id="mlMetaFuel"></label>
<label>${tr('Lämpötila °C','Temperature °C')}<input id="mlMetaTemp" type="number" step="0.1"></label><label>${tr('Ilmanpaine hPa','Air pressure hPa')}<input id="mlMetaPress" type="number" step="1"></label>
<label>AFR<input id="mlMetaAfr" type="number" step="0.1"></label><label>EGT °C<input id="mlMetaEgt" type="number" step="1"></label>
<label class="full">${tr('Kokoonpanotagi','Setup tag')}<input id="mlMetaTag"></label><label class="full">${tr('Muistiinpano','Notes')}<input id="mlMetaNotes"></label></div>
<button id="mlMetaSave" class="action">${tr('TALLENNA VEDOLLE','SAVE TO RUN')}</button><button id="mlMetaCancel" class="action gray">${tr('PERUUTA','CANCEL')}</button></div>`;document.body.appendChild(d);$('mlMetaCancel').onclick=()=>d.classList.remove('show');$('mlMetaSave').onclick=saveEditor}
function field(id,v){const e=$(id);if(e)e.value=v??''}
function openEditor(id=currentRunModalId){const r=allRuns().find(x=>x.id===id);if(!r)return;ensureEditModal();$('mlRunEditModal').dataset.runId=r.id;const m=meta(r);field('mlMetaMain',m.mainJet);field('mlMetaPilot',m.pilotJet);field('mlMetaNeedle',m.needleType);field('mlMetaClip',m.needleClip);field('mlMetaAir',m.airScrew);field('mlMetaSlide',m.slide);field('mlMetaIgnMap',m.ignitionMap);field('mlMetaIgnTiming',m.ignitionTiming);field('mlMetaYpvs',m.ypvs);field('mlMetaFuel',m.fuel);field('mlMetaTemp',m.temperatureC);field('mlMetaPress',m.pressureHpa);field('mlMetaAfr',m.afr);field('mlMetaEgt',m.egt);field('mlMetaTag',m.setupTag);field('mlMetaNotes',m.notes);$('mlRunEditModal').classList.add('show')}
const val=id=>$(id)?.value?.trim?.()??'';const nval=id=>{const v=val(id);return v===''?null:+v};
async function saveEditor(){const id=$('mlRunEditModal')?.dataset.runId,r=allRuns().find(x=>x.id===id);if(!r)return;const carb={...(r.carb||{}),mainJet:nval('mlMetaMain'),pilotJet:nval('mlMetaPilot'),needleType:val('mlMetaNeedle'),needleClip:val('mlMetaClip'),airScrew:nval('mlMetaAir'),slide:nval('mlMetaSlide')};const tuning={...(r.tuning||{}),...carb,ignitionMap:val('mlMetaIgnMap'),ignitionTiming:val('mlMetaIgnTiming'),ypvs:val('mlMetaYpvs'),fuel:val('mlMetaFuel'),temperatureC:nval('mlMetaTemp'),pressureHpa:nval('mlMetaPress'),afr:nval('mlMetaAfr'),egt:nval('mlMetaEgt'),setupTag:val('mlMetaTag'),notes:val('mlMetaNotes'),metadataEditedAfterRun:true,metadataEditedAt:new Date().toISOString(),metadataOrigin:'post_run_edit'};r.carb=carb;r.tuning=tuning;await persistRun(r);$('mlRunEditModal').classList.remove('show');if(typeof openRun==='function'){try{openRun(r.id)}catch{}}try{globalThis.MOTOLAB_DIAGNOSTICS?.record?.('run_metadata_edited',{runId:r.id,module:VERSION})}catch{}}
function ensureEditButton(){const modal=$('runModal')?.querySelector('.sheet');if(!modal||$('mlEditRunBtn'))return;const b=document.createElement('button');b.id='mlEditRunBtn';b.className='action gray';b.textContent=tr('MUOKKAA SÄÄTÖTIETOJA','EDIT TUNING DATA');const del=$('deleteRunBtn');modal.insertBefore(b,del||$('closeRun'));b.onclick=()=>openEditor()}
function fixProfileSelection(){const s=$('profileSelect');if(!s||s.dataset.mlSelectionFix==='1')return;s.dataset.mlSelectionFix='1';const apply=()=>{const id=s.value;if(!id)return;localStorage.setItem('motolab_v26_profile',id);try{renderProfiles()}catch{}try{pushConfig()}catch{}try{globalThis.MotoLabSimpleUI?.apply?.()}catch{}try{globalThis.MOTOLAB_DIAGNOSTICS?.record?.('profile_selected',{profileId:id,module:VERSION})}catch{}};s.addEventListener('change',apply);s.addEventListener('input',apply);const p=s.closest('.panel');if(p&&!p.querySelector('.ml-active-profile')){const n=document.createElement('div');n.className='ml-active-profile';n.innerHTML=`${tr('Aktiivinen pyörä','Active bike')}: <b id="mlActiveProfileName"></b>`;p.appendChild(n)}updateProfilePill()}
function updateProfilePill(){const e=$('mlActiveProfileName'),p=activeProfile();if(e)e.textContent=p?.name||tr('Ei valittu','Not selected')}
function hookRefresh(){if(globalThis.__mlRunAnalysisHooked)return;globalThis.__mlRunAnalysisHooked=true;document.addEventListener('motorlab-language-change',()=>{const panel=$('mlRunABPanel');panel?.remove();$('mlRunEditModal')?.remove();ensureAnalysisPanel();ensureEditModal();ensureEditButton();refreshRunOptions()});document.addEventListener('motolab:vehicle-applied',()=>setTimeout(()=>{updateProfilePill();refreshRunOptions()},0));}
function apply(){css();ensureAnalysisPanel();ensureEditModal();ensureEditButton();fixProfileSelection();updateProfilePill();refreshRunOptions();hookRefresh()}
function boot(){let n=0;const t=setInterval(()=>{try{apply()}catch(e){console.warn('run_analysis_v34',e)}if(++n>80)clearInterval(t)},350);apply()}
globalThis.MotoLabRunAnalysis={version:VERSION,apply,refresh:refreshRunOptions,compare:compareAB,editRun:openEditor};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
