(() => {
'use strict';
const VERSION='motorlab-simple-user-ui-v35';
const TECH_SETTINGS=/KNOWLEDGE BASE|VAIHDE\s*\/\s*RPM\s*\/\s*GPS|BT RPM|OPPIVA DATA|RAW AUDIO|MIC CALIBRATION|JÄRJESTELMÄTESTI/i;
const USER_VEHICLE=/AJONEUVOTIEDON HAKU|VÄLITYKSET|TEKNISET TIEDOT|HUOLTO\s*&\s*HISTORIA|VEHICLE LOOKUP|DRIVETRAIN|TECHNICAL SPECS|MAINTENANCE/i;
let lastScreen='';const $=id=>document.getElementById(id);const user=()=>globalThis.MotoLabUser?.user||null;const admin=()=>user()?.role==='admin';
function originalTitle(p){return p?.dataset?.mlOriginalTitle||String(p?.querySelector('.ptitle')?.textContent||'').replace(/\s+/g,' ').trim()}
function css(){if($('mlSimpleUiStyle'))return;const s=document.createElement('style');s.id='mlSimpleUiStyle';s.textContent=`
:root{--ml-bottom-nav-h:76px}.app{padding:8px 8px calc(var(--ml-bottom-nav-h) + 34px + env(safe-area-inset-bottom))!important}.bottomNav{position:fixed!important;left:50%;transform:translateX(-50%);bottom:calc(7px + env(safe-area-inset-bottom));width:min(calc(100vw - 16px),424px);z-index:118000;margin:0!important;background:rgba(5,5,7,.91)!important;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);box-shadow:0 14px 40px #000c;border-color:#3a2428!important}.screen{padding-bottom:20px}.screen:after{content:'';display:block;height:12px}
#screen-settings .panel.ml-accordion{overflow:hidden}#screen-settings .panel.ml-accordion>.phead{cursor:pointer;user-select:none;border-bottom:0;min-height:49px}#screen-settings .panel.ml-accordion>.phead:after{content:'›';font-size:22px;color:#ff263f;font-weight:1000;transition:transform .15s ease;transform:rotate(90deg)}#screen-settings .panel.ml-accordion.ml-open>.phead:after{transform:rotate(-90deg)}#screen-settings .panel.ml-accordion:not(.ml-open)>:not(.phead),#screen-settings .panel.ml-hidden-user{display:none!important}
body.ml-basic-user #screen-live,body.ml-basic-user .bottomNav .nav[data-screen="live"],body.ml-basic-user .bottomNav .nav[data-screen="autotune"],body.ml-basic-user #screen-measure>.panel,body.ml-basic-user #sensorBtn,body.ml-basic-user .metrics .metric:nth-child(4),#mlBetaMenuBtn,#motolabUserPill{display:none!important}
body.ml-basic-user .topbar{margin-bottom:5px}body.ml-basic-user .brand{font-size:0!important}body.ml-basic-user .brand:before{font-size:12px!important}body.ml-basic-user .brand:after{font-size:12px!important}body.ml-basic-user .statuses{gap:3px}body.ml-basic-user .spill{padding:5px;font-size:6px}body.ml-basic-user #appVersionBadge{font-size:7px}
body.ml-basic-user .hero{height:min(54vh,420px);min-height:350px;margin-top:3px;border:1px solid rgba(255,38,63,.18);background:radial-gradient(circle at 75% 30%,rgba(255,38,63,.14),transparent 30%),linear-gradient(155deg,#0b0709,#030304 68%);box-shadow:inset 0 0 55px #0008,0 16px 40px #0007}
body.ml-basic-user .logo{left:13px;top:14px}body.ml-basic-user .logo1:after{font-size:39px!important;letter-spacing:-2px!important}body.ml-basic-user .logo2:after{font-size:29px!important;letter-spacing:-1px!important}body.ml-basic-user .tag{font-size:6px;color:#999;letter-spacing:.18em}
body.ml-basic-user .bike{right:-20px;top:54px;width:72%;max-width:300px;opacity:.30;filter:saturate(.72) brightness(.55) contrast(1.15) drop-shadow(0 18px 22px #000)}body.ml-basic-user .heroChartBox{right:9px;top:126px;width:52%;height:150px;opacity:.75;background:rgba(0,0,0,.22);border:1px solid rgba(255,255,255,.05)}body.ml-basic-user .heroChartBox canvas{height:128px}body.ml-basic-user .heroChartTitle{font-size:6px}
body.ml-basic-user .gauge{left:-15px;bottom:-6px;width:250px;height:240px}body.ml-basic-user .gcenter{top:74px;width:136px;height:136px}body.ml-basic-user .gcenter .rpm{font-size:44px}body.ml-basic-user .needle{top:138px;width:80px}body.ml-basic-user .gearBadge{right:14px;bottom:18px;width:78px;height:78px;background:radial-gradient(circle,#17191e,#060609);box-shadow:0 0 24px rgba(255,38,63,.13)}
body.ml-basic-user .metrics{grid-template-columns:repeat(3,1fr);gap:7px;margin-top:8px}body.ml-basic-user .metric{min-height:72px;padding:9px;border-radius:13px;background:linear-gradient(155deg,#131419,#070709);box-shadow:0 9px 20px #0008}body.ml-basic-user .metric b{font-size:23px}
body.ml-basic-user .controls{grid-template-columns:repeat(4,1fr);gap:7px;margin-top:8px}body.ml-basic-user .ctl{min-height:70px;border-radius:13px;background:linear-gradient(155deg,#14151a,#08080a)}body.ml-basic-user #extMicBtn .lbl{font-size:0}body.ml-basic-user #extMicBtn .lbl:after{content:'MIC';font-size:9px}body.ml-basic-user #extMicBtn .ico{font-size:20px}
body.ml-basic-user #screen-settings .tiny{display:none!important}body.ml-basic-user #screen-settings .panel[data-ml-kind="measure"] label:has(#manualGear),body.ml-basic-user #screen-settings .panel[data-ml-kind="measure"] label:has(#autoSensitivity),body.ml-basic-user #screen-settings .panel[data-ml-kind="measure"] label:has(#autoStopDelay),body.ml-basic-user #screen-settings .panel[data-ml-kind="measure"] .switchrow:has(#gearLearnToggle),body.ml-basic-user #screen-settings .panel[data-ml-kind="vehicle"] label:has(#cda),body.ml-basic-user #screen-settings .panel[data-ml-kind="vehicle"] label:has(#crr),body.ml-basic-user #screen-settings .panel[data-ml-kind="vehicle"] label:has(#rho),body.ml-basic-user #screen-settings .panel[data-ml-kind="vehicle"] .switchrow:has(#gridToggle),body.ml-basic-user #screen-settings .panel[data-ml-kind="vehicle"] .switchrow:has(#infoToggle),body.ml-basic-user #screen-settings .panel[data-ml-kind="vehicle"] .switchrow:has(#wakeToggle){display:none!important}.ml-simple-intro{margin:8px 0 2px;padding:11px 12px;border:1px solid #302126;border-radius:13px;background:rgba(8,9,12,.9);color:#b8bec6;font-size:9px;line-height:1.45}.ml-simple-intro b{display:block;color:#fff;font-size:11px;margin-bottom:3px}.bottomNav .ml-user-nav .ico{font-size:18px}
`;document.head.appendChild(s)}
function classify(p){const t=originalTitle(p);if(/SMART BIKE PROFILES/i.test(t))return'profile';if(/MITTAUS\s*&\s*RPM/i.test(t))return'measure';if(/AJONEUVO\s*&\s*DYNO/i.test(t)||USER_VEHICLE.test(t))return'vehicle';if(/SOVELLUS|KIELI|LANGUAGE/i.test(t))return'app';if(TECH_SETTINGS.test(t))return'technical';return'other'}
function closeAll(except=null){document.querySelectorAll('#screen-settings .panel.ml-accordion.ml-open').forEach(p=>{if(p!==except){p.classList.remove('ml-open');p.querySelector(':scope > .phead')?.setAttribute('aria-expanded','false')}})}
function makeAccordion(p){if(p.classList.contains('ml-accordion'))return;p.classList.add('ml-accordion');const h=p.querySelector(':scope > .phead');if(!h)return;h.setAttribute('role','button');h.setAttribute('tabindex','0');h.setAttribute('aria-expanded','false');const toggle=()=>{const open=!p.classList.contains('ml-open');closeAll(p);p.classList.toggle('ml-open',open);h.setAttribute('aria-expanded',String(open))};h.addEventListener('click',e=>{if(!e.target.closest('button,input,select,a'))toggle()});h.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})}
function rename(p,isAdmin){if(isAdmin||p.dataset.mlSimpleRenamed==='1')return;const t=p.querySelector('.ptitle');if(!t)return;const x=originalTitle(p);let html='';if(/SMART BIKE PROFILES/i.test(x))html='<span class="r">🏍️</span> PYÖRÄ';else if(/MITTAUS\s*&\s*RPM/i.test(x))html='<span class="r">🎛️</span> MITTAUS';else if(/AJONEUVO\s*&\s*DYNO/i.test(x))html='<span class="r">⚙️</span> AJONEUVON TIEDOT';else if(/SOVELLUS/i.test(x))html='<span class="r">📱</span> SOVELLUS';if(html)t.innerHTML=html;p.dataset.mlSimpleRenamed='1'}
function settings(isAdmin){const sec=$('screen-settings');if(!sec)return;if(!$('mlSimpleSettingsIntro')){const n=document.createElement('div');n.id='mlSimpleSettingsIntro';n.className='ml-simple-intro';n.innerHTML='<b>ASETUKSET</b>Avaa vain tarvitsemasi kohta. Vain yksi valikko on auki kerrallaan.';sec.insertBefore(n,sec.firstChild)}sec.querySelectorAll(':scope > .panel').forEach(p=>{if(!p.dataset.mlOriginalTitle)p.dataset.mlOriginalTitle=String(p.querySelector('.ptitle')?.textContent||'').replace(/\s+/g,' ').trim();const kind=classify(p);p.dataset.mlKind=kind;makeAccordion(p);p.classList.toggle('ml-hidden-user',!isAdmin&&(kind==='technical'||kind==='other'));rename(p,isAdmin)})}
function setNavLabel(n,screen,text){const e=n.querySelector(`.nav[data-screen="${screen}"] .txt`);if(e&&!e.dataset.mlSimpleLabel){e.textContent=text;e.dataset.mlSimpleLabel='1'}}
function nav(isAdmin){const n=document.querySelector('.bottomNav');if(!n)return;setNavLabel(n,'measure','ETUSIVU');setNavLabel(n,'runs','VEDOT');setNavLabel(n,'analysis','ANALYYSI');setNavLabel(n,'settings','ASETUKSET');let u=n.querySelector('.ml-user-nav');if(!u){u=document.createElement('button');u.className='nav ml-user-nav';u.type='button';u.innerHTML='<div class="ico">👤</div><div class="txt">KÄYTTÄJÄ</div>';u.onclick=()=>globalThis.MotoLabBetaMenu?.open?.();n.appendChild(u)}const live=n.querySelector('.nav[data-screen="live"]');if(live)live.hidden=!isAdmin;const auto=n.querySelector('.nav[data-screen="autotune"]');if(auto)auto.hidden=true}
function home(isAdmin){document.body.classList.toggle('ml-basic-user',!isAdmin);document.body.classList.toggle('ml-admin-user',isAdmin);const live=$('screen-live');if(live)live.hidden=!isAdmin}
function currentScreen(){return document.querySelector('.screen.active')?.id||''}function apply(){css();const a=admin();home(a);settings(a);nav(a);const now=currentScreen();if(now==='screen-settings'&&lastScreen!=='screen-settings'||lastScreen==='screen-settings'&&now!=='screen-settings')closeAll();lastScreen=now}
function boot(){apply();let tries=0;const t=setInterval(()=>{apply();if(++tries>80)clearInterval(t)},400);let pending=false;new MutationObserver(r=>{if(pending||!r.some(x=>x.addedNodes?.length))return;pending=true;requestAnimationFrame(()=>{pending=false;apply()})}).observe(document.documentElement,{childList:true,subtree:true})}globalThis.MotoLabSimpleUI={version:VERSION,apply,closeSettings:closeAll,get role(){return admin()?'admin':'user'}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
