importScripts("./version.js?build=2026-08-17q-startup-gate");
const VERSION=globalThis.MOTOLAB_RELEASE?.version||"34.2";
const VERSION_LABEL=globalThis.MOTOLAB_RELEASE?.label||("v"+VERSION);
const BUILD=globalThis.MOTOLAB_RELEASE?.build||"2026-08-17q-startup-gate";
const V=encodeURIComponent(VERSION),B=encodeURIComponent(BUILD);
const CACHE="vana-motorlab-"+VERSION.replace(/[^a-z0-9]+/gi,"-")+"-"+BUILD.replace(/[^a-z0-9]+/gi,"-");
const CORE=["./manifest.webmanifest","./bike.png","./icon-192.png","./icon-512.png","./assets/motorlab_splash_approved.webp","./diagnostics.js","./vehicle_lookup.js","./vehicle_catalog.json","./maintenance.js","./maintenance_catalog.json","./technical_specs.js","./gps_master_learning.js","./raw_sync.js","./dyno_curve_v2.js","./ui_compact.js","./default_dt.js","./trip_research.js","./research_sync.js","./user_identity.js","./user_features.js","./feedback.js","./community.js","./merit.js","./beta_menu.js","./beta_release.js","./mic_authority.js","./sensor_persistence.js","./sensor_autostart.js","./admin_test_tools.js","./phone_rpm_smart.js","./adaptive_rpm_learning.js","./trip_phone_raw.js","./trip_gear_guard.js","./trip_gear_marker.js","./live_status.js","./live_status_guard.js","./motorlab_branding.js","./simple_user_ui.js","./motorlab_i18n.js","./rpm-learning-model.json","./version.js"].map(u=>/\.(?:js|json|webmanifest)$/.test(u)?u+"?v="+V+"&build="+B:u+"?build="+B);
function injectModules(html){const names=["vehicle_lookup","technical_specs","maintenance","gps_master_learning","raw_sync","dyno_curve_v2","ui_compact","default_dt","trip_research","research_sync","user_identity","user_features","feedback","community","merit","beta_menu","beta_release","mic_authority","sensor_persistence","sensor_autostart","admin_test_tools","phone_rpm_smart","adaptive_rpm_learning","trip_phone_raw","trip_gear_guard","trip_gear_marker","live_status","live_status_guard","motorlab_branding","simple_user_ui","motorlab_i18n"];const scripts=[];for(const n of names)if(!html.includes(n+".js"))scripts.push('<script src="./'+n+'.js?v='+V+'&build='+B+'"></script>');const diag=html.includes('diagnostics.js')?'':'<script src="./diagnostics.js?v='+V+'&build='+B+'"></script>';const banner='<style>#motolabFullVersion{position:sticky;top:0;z-index:99999;text-align:center;padding:7px 9px;background:#110508;border-bottom:1px solid #ff263f;color:#fff;font:800 11px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;letter-spacing:.2px}</style><div id="motolabFullVersion">VÄNÄ MOTORLAB '+VERSION_LABEL+' • build '+BUILD+'</div><script>document.addEventListener("DOMContentLoaded",function(){var b=document.querySelector(".ver");if(b)b.textContent="'+VERSION_LABEL+'";document.title="VäNä MotorLab '+VERSION_LABEL+'"})</script>';html=html.replace(/<link rel="manifest" href="manifest\.webmanifest(?:\?[^\"]*)?">/,'<link rel="manifest" href="manifest.webmanifest?v='+V+'&build='+B+'">');html=html.replace(/navigator\.serviceWorker\.register\("\.\/sw\.js\?[^"]*"(?:,\{[^}]*\})?\)/g,'navigator.serviceWorker.register("./sw.js?build='+BUILD+'",{updateViaCache:"none"})');if(!html.includes('motolabFullVersion'))html=html.replace('<body>','<body>'+diag+banner);else if(diag)html=html.replace('<body>','<body>'+diag);return scripts.length?html.replace("</body>",scripts.join("")+"</body>"):html}
async function cacheInjectedIndex(c){const r=await fetch("./index.html?v="+V+"&build="+B,{cache:"no-store"});if(!r.ok)throw Error("index "+r.status);await c.put("./index.html?v="+V+"&build="+B,new Response(injectModules(await r.text()),{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-cache, no-store, must-revalidate"}}))}
self.addEventListener("message",e=>{if(e.data?.type==="SKIP_WAITING")self.skipWaiting()});self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil((async()=>{const c=await caches.open(CACHE);for(const u of CORE){try{const r=await fetch(new Request(u,{cache:"reload"}));if(r.ok)await c.put(u,r.clone())}catch{}}await cacheInjectedIndex(c)})())});self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith("vana-motolab-")||k.startsWith("vana-motorlab-")).filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=new URL(e.request.url);if(u.origin!==location.origin)return;if(e.request.mode==="navigate"){e.respondWith(fetch(e.request,{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error();const out=new Response(injectModules(await r.text()),{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-cache, no-store, must-revalidate"}});const c=await caches.open(CACHE);await c.put("./index.html?v="+V+"&build="+B,out.clone());return out}).catch(()=>caches.match("./index.html?v="+V+"&build="+B)));return}if(/\.(?:js|json|webmanifest|webp|png)$/.test(u.pathname)){e.respondWith(fetch(new Request(e.request,{cache:"reload"})).then(async r=>{if(r.ok)(await caches.open(CACHE)).put(e.request,r.clone());return r}).catch(()=>caches.match(e.request)));return}e.respondWith(caches.match(e.request).then(x=>x||fetch(e.request))) });
