(() => {
'use strict';
const MODULE='trip-gear-guard-v7-all-gears';
const HOLD_MS=450, TRANSITION_MS=900, MIN_CONF=.55;
const $g=id=>document.getElementById(id);
let stableGear=null,pendingGear=null,pendingAt=0,previousGear=null,transitionUntil=0,lastPaint='';
function ui(){try{return typeof lastUi!=='undefined'&&lastUi?lastUi:{}}catch{return {}}}
function captureActive(){try{return !!learningEnabled||$g('tripResearchState')?.textContent?.trim()==='TALLENTAA'}catch{return $g('tripResearchState')?.textContent?.trim()==='TALLENTAA'}}
function manualConfirmed(){const x=globalThis.MOTOLAB_CONFIRMED_GEAR;return x&&Date.now()-(+x.t||0)<5000?+x.gear||null:null}
function evidence(){const u=ui(),manual=manualConfirmed(),app=+u.gear||0,conf=+u.gearConf||0,gear=manual||(app>0&&conf>=MIN_CONF?app:null);return {gear,appGear:app||null,gearConf:conf||null,manual:!!manual,kmh:+u.kmh||0,rpm:+u.rpm||0,ratio:+u.ratio||0}}
function publish(ev){const now=Date.now(),changing=now<transitionUntil,payload={module:MODULE,state:changing?'changing':(stableGear?'stable':'unknown'),gear:stableGear,previousGear,gearChangeActive:changing,learningAllowed:!!stableGear&&!changing,micDataAllowed:true,t:now,evidence:ev||null};globalThis.MOTOLAB_TRIP_GEAR_GUARD=payload;try{globalThis.dispatchEvent(new CustomEvent('motolab-trip-gear-guard',{detail:payload}))}catch{}}
function commitGear(next,ev){if(!next)return;if(stableGear===next){publish(ev);return}const from=stableGear;previousGear=from;stableGear=next;pendingGear=null;pendingAt=0;transitionUntil=Date.now()+TRANSITION_MS;const detail={module:MODULE,fromGear:from,toGear:next,gear:next,evidence:ev,t:Date.now()};try{if(typeof addLearningEvent==='function')addLearningEvent('gear_change_detected',detail)}catch{}try{globalThis.dispatchEvent(new CustomEvent('motolab-gear-change',{detail}))}catch{}publish(ev);paint(ev)}
function update(){if(!captureActive()){pendingGear=null;pendingAt=0;publish({reason:'capture_inactive'});paint();return}const ev=evidence(),g=ev.gear,now=Date.now();if(!g){publish(ev);paint(ev);return}if(stableGear===g){pendingGear=null;pendingAt=0;publish(ev);paint(ev);return}if(pendingGear!==g){pendingGear=g;pendingAt=now;publish(ev);paint(ev);return}if(now-pendingAt>=HOLD_MS)commitGear(g,ev);else{publish(ev);paint(ev)}}
function confirmGear(gear){gear=+gear;if(!(gear>=1&&gear<=6))return;globalThis.MOTOLAB_CONFIRMED_GEAR={gear,t:Date.now(),origin:'user_confirmed'};commitGear(gear,{gear,manual:true});try{if(typeof addLearningEvent==='function')addLearningEvent('trip_gear_manual_confirm',{module:MODULE,gear})}catch{}}
function ensureUi(){const panel=$g('tripResearchPanel');if(!panel||$g('tripGearGuardBox'))return !!panel;const box=document.createElement('div');box.id='tripGearGuardBox';box.className='statusbox';box.style.marginTop='8px';box.innerHTML='<div style="font-weight:900;margin-bottom:5px">VAIHDEOPPIMINEN</div><div id="tripGearGuardStatus">Odottaa ajoa.</div><div style="margin-top:5px;color:#8f969f;font-size:8px">Kaikki vaihteet ja vaihdot tallennetaan. Vain lyhyt epävakaa vaihtohetki rajataan harmonic-opetuksesta.</div>';const st=$g('tripResearchStatus');if(st)st.insertAdjacentElement('beforebegin',box);else panel.appendChild(box);return true}
function paint(ev){ensureUi();const s=$g('tripGearGuardStatus');if(!s)return;const changing=Date.now()<transitionUntil;let text=!captureActive()?'Vaihdeoppiminen odottaa ajoa.':changing?'Vaihde vaihtuu • vakautetaan':(stableGear?'Vaihde '+stableGear+' • opetus aktiivinen':'Etsitään vaihdetta…');if(ev?.gearConf)text+=' • '+Math.round(ev.gearConf*100)+' %';if(text!==lastPaint){s.textContent=text;lastPaint=text}}
function patchLearning(){try{if(typeof collectLearningSample!=='function'||collectLearningSample.__tripGearGuardPatched)return false;const orig=collectLearningSample,wrapped=function(s){const before=Array.isArray(learningBuffer)?learningBuffer.length:0,out=orig(s);try{if(Array.isArray(learningBuffer)&&learningBuffer.length>before){const row=learningBuffer[learningBuffer.length-1],g=globalThis.MOTOLAB_TRIP_GEAR_GUARD||{};row.tripGearGuardState=g.state||'unknown';row.tripDetectedGear=g.gear||s?.gear||null;row.tripPreviousGear=g.previousGear||null;row.tripGearChangeActive=!!g.gearChangeActive;row.tripGearLearningAllowed=g.learningAllowed!==false;row.tripMicDataAllowed=true;if(g.gearChangeActive)row.micLearningEligible=false}}catch{}return out};wrapped.__tripGearGuardPatched=true;collectLearningSample=wrapped;return true}catch{return false}}
function boot(){ensureUi();patchLearning();setInterval(()=>{patchLearning();update()},200)}
globalThis.MotoLabTripGearGuard={version:MODULE,confirm:confirmGear,state:()=>globalThis.MOTOLAB_TRIP_GEAR_GUARD||null};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
