(() => {
'use strict';
const MODULE_VERSION='v32-trip-research-1';
const DB_NAME='VanaMotoLabResearch',DB_VERSION=1;
const SESSION_STORE='sessions',AUDIO_STORE='audioChunks',TIMELINE_STORE='timelineChunks';
const CANDIDATE_FORMAT=['rpm','observedHz','rawRpm','corr','fingerprint','score','multiplier'];
const $t=id=>document.getElementById(id);
let rdb=null,active=false,session=null,recorder=null,audioIndex=0,audioLastT=0,timeline=[],timelineIndex=0,frameCount=0,candidateFrameCount=0,audioBytes=0,lastCandidateSave=0,gpsTimer=null,uiTimer=null,lastSessionId=null;

function reqP(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'))})}
async function openDb(){if(rdb)return rdb;rdb=await new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(SESSION_STORE))d.createObjectStore(SESSION_STORE,{keyPath:'id'});if(!d.objectStoreNames.contains(AUDIO_STORE)){const s=d.createObjectStore(AUDIO_STORE,{keyPath:'id'});s.createIndex('sessionId','sessionId',{unique:false})}if(!d.objectStoreNames.contains(TIMELINE_STORE)){const s=d.createObjectStore(TIMELINE_STORE,{keyPath:'id'});s.createIndex('sessionId','sessionId',{unique:false})}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return rdb}
async function put(store,value){const d=await openDb(),tx=d.transaction(store,'readwrite');tx.objectStore(store).put(value);await txDone(tx)}
async function allBySession(store,id){const d=await openDb(),tx=d.transaction(store,'readonly'),s=tx.objectStore(store);const req=s.indexNames.contains('sessionId')?s.index('sessionId').getAll(id):s.getAll();const out=await reqP(req);await txDone(tx);return (out||[]).filter(x=>!x.sessionId||x.sessionId===id)}
async function getSession(id){const d=await openDb(),tx=d.transaction(SESSION_STORE,'readonly'),out=await reqP(tx.objectStore(SESSION_STORE).get(id));await txDone(tx);return out||null}
async function latestSession(){const d=await openDb(),tx=d.transaction(SESSION_STORE,'readonly'),a=await reqP(tx.objectStore(SESSION_STORE).getAll());await txDone(tx);return (a||[]).sort((x,y)=>(y.startedAtMs||0)-(x.startedAtMs||0))[0]||null}

function profileSnapshot(){try{return typeof learningProfileSnapshot==='function'?learningProfileSnapshot():{profileId:getCurrentProfile?.()?.id||null,profileName:getCurrentProfile?.()?.name||null}}catch{return {}}}
function uiData(){try{return typeof lastUi!=='undefined'&&lastUi?lastUi:{}}catch{return {}}}
function compactCandidates(a){return Array.isArray(a)?a.map(x=>Array.isArray(x)?x.slice(0,7):[x.rpm||0,x.observedHz||x.f||0,x.rawRpm||0,x.corr||x.q||0,x.fingerprint||x.fp||0,x.score||0,x.multiplier||x.mult||1]):[]}
function pushFrame(kind,audio=null){if(!active||!session)return;const u=uiData(),t=Date.now();const frame={t,kind,gpsKmh:Number.isFinite(u.kmh)?u.kmh:null,gpsRpm:Number.isFinite(u.speedRpm)?u.speedRpm:null,gpsConf:Number.isFinite(u.speedConf)?u.speedConf:null,gpsAccuracyM:Number.isFinite(u.gpsAcc)?u.gpsAcc:null,gear:3,accelMps2:Number.isFinite(u.a)?u.a:null,accelG:Number.isFinite(u.g)?u.g:null};if(audio){frame.audio={rpm:audio.rpm||0,rawRpm:audio.rawRpm||0,conf:audio.conf||0,fp:audio.fpScore||0,f0:audio.observedF0||0,level:audio.level||0,gap:audio.candidateGap||0,runnerRpm:audio.runnerRpm||0,candidates:compactCandidates(audio.candidates)};candidateFrameCount++}timeline.push(frame);frameCount++;if(timeline.length>=100)flushTimeline().catch(showError);renderState()}
async function flushTimeline(){if(!timeline.length||!session)return;const frames=timeline.splice(0,timeline.length),i=timelineIndex++;await put(TIMELINE_STORE,{id:`${session.id}-timeline-${String(i).padStart(6,'0')}`,sessionId:session.id,index:i,createdAt:new Date().toISOString(),frames});session.timelineChunks=timelineIndex;session.frameCount=frameCount;session.candidateFrameCount=candidateFrameCount;session.updatedAt=new Date().toISOString();await put(SESSION_STORE,session)}
function onCandidates(e){if(!active)return;const now=Date.now();if(now-lastCandidateSave<150)return;lastCandidateSave=now;pushFrame('audio',e.detail||null)}

function chooseMime(){if(typeof MediaRecorder==='undefined')return '';const choices=['audio/mp4;codecs=mp4a.40.2','audio/mp4','audio/webm;codecs=opus','audio/webm'];for(const m of choices){try{if(MediaRecorder.isTypeSupported?.(m))return m}catch{}}return ''}
async function storeAudioBlob(blob,startMs,endMs){if(!session||!blob||!blob.size)return;const i=audioIndex++;audioBytes+=blob.size;await put(AUDIO_STORE,{id:`${session.id}-audio-${String(i).padStart(6,'0')}`,sessionId:session.id,index:i,startMs,endMs,mime:blob.type||session.audioMime||'',size:blob.size,blob});session.audioChunks=audioIndex;session.audioBytes=audioBytes;session.updatedAt=new Date().toISOString();await put(SESSION_STORE,session);renderState()}
function startRecorder(stream){const mime=chooseMime(),opts=mime?{mimeType:mime,audioBitsPerSecond:96000}:{audioBitsPerSecond:96000};recorder=new MediaRecorder(stream,opts);session.audioMime=recorder.mimeType||mime||'audio/unknown';audioLastT=Date.now();recorder.ondataavailable=e=>{const end=Date.now(),start=audioLastT;audioLastT=end;storeAudioBlob(e.data,start,end).catch(showError)};recorder.onerror=e=>showError(e.error||e);recorder.start(5000)}

async function prepareSources(){const sel=$t('rpmSourceMode');if(sel&&[...sel.options].some(o=>o.value==='gpslearn'))sel.value='gpslearn';const gear=$t('manualGear');if(gear)gear.value='3';try{if(typeof updateSourceModeUI==='function')updateSourceModeUI();if(typeof pushConfig==='function')pushConfig()}catch{}let gpsOk=false,micOk=false;try{gpsOk=typeof startGPS==='function'?await startGPS():false}catch{}try{micOk=typeof startAudio==='function'?await startAudio():false}catch{}return {gpsOk,micOk}}
async function startResearch(){if(active)return;status('Valmistellaan GPS MASTER + BT MIC tutkimusajoa…');try{await openDb();try{await navigator.storage?.persist?.()}catch{}const {gpsOk,micOk}=await prepareSources();if(!gpsOk||!micOk||!audioSessions?.ext?.stream){status(`EI KÄYNNISTYNYT • GPS ${gpsOk?'OK':'EI'} • BT MIC ${micOk?'OK':'EI'}`);return}const now=Date.now();session={id:`trip-${now}-${Math.random().toString(16).slice(2)}`,schema:'motolab_trip_research_v1',moduleVersion:MODULE_VERSION,appRelease:globalThis.MOTOLAB_RELEASE||null,startedAt:new Date(now).toISOString(),startedAtMs:now,endedAt:null,selectedGear:3,rpmAuthority:'gps',micAuthority:'shadow_only',candidateFormat:CANDIDATE_FORMAT,profile:profileSnapshot(),audioDevice:audioSessions.ext?.track?.label||null,audioSampleRate:audioSessions.ext?.ac?.sampleRate||null,audioMime:'',audioChunks:0,audioBytes:0,timelineChunks:0,frameCount:0,candidateFrameCount:0};await put(SESSION_STORE,session);lastSessionId=session.id;active=true;audioIndex=0;audioBytes=0;timeline=[];timelineIndex=0;frameCount=0;candidateFrameCount=0;lastCandidateSave=0;window.addEventListener('motolab-audio-candidates',onCandidates);gpsTimer=setInterval(()=>pushFrame('gps'),200);uiTimer=setInterval(renderState,1000);startRecorder(audioSessions.ext.stream);try{if(typeof addLearningEvent==='function')addLearningEvent('trip_research_start',{sessionId:session.id,gear:3,module:MODULE_VERSION})}catch{}renderState();status('TUTKIMUSAJO KÄYNNISSÄ • 3. vaihde • GPS MASTER • koko BT-audio + kaikki candidate-haarat tallentuvat.')}catch(e){showError(e)}}
async function stopResearch(){if(!active)return;active=false;window.removeEventListener('motolab-audio-candidates',onCandidates);clearInterval(gpsTimer);clearInterval(uiTimer);gpsTimer=uiTimer=null;if(recorder&&recorder.state!=='inactive'){await new Promise(resolve=>{const old=recorder.onstop;recorder.onstop=e=>{try{old?.(e)}catch{}resolve()};try{recorder.stop()}catch{resolve()}})}recorder=null;await new Promise(r=>setTimeout(r,120));await flushTimeline();if(session){session.endedAt=new Date().toISOString();session.endedAtMs=Date.now();session.durationMs=session.endedAtMs-session.startedAtMs;session.audioChunks=audioIndex;session.audioBytes=audioBytes;session.frameCount=frameCount;session.candidateFrameCount=candidateFrameCount;await put(SESSION_STORE,session);lastSessionId=session.id;try{if(typeof addLearningEvent==='function')addLearningEvent('trip_research_stop',{sessionId:session.id,durationMs:session.durationMs,audioBytes,frameCount,candidateFrameCount})}catch{}}renderState();status(`TUTKIMUSAJO TALLENNETTU • ${formatDuration(session?.durationMs||0)} • ${(audioBytes/1048576).toFixed(1)} MB audioa • ${candidateFrameCount} candidate-kehystä.`)}

function formatDuration(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60),h=Math.floor(m/60);return h?`${h}h ${m%60}m ${s%60}s`:`${m}m ${s%60}s`}
function status(s){const e=$t('tripResearchStatus');if(e)e.textContent=s}
function showError(e){status('VIRHE: '+(e?.message||e));console.error(e)}
function renderState(){if(!$t('tripResearchState'))return;const now=Date.now(),dur=session?(active?now-session.startedAtMs:(session.durationMs||0)):0;$t('tripResearchState').textContent=active?'TALLENTAA':'VALMIS';$t('tripResearchDuration').textContent=formatDuration(dur);$t('tripResearchFrames').textContent=String(frameCount);$t('tripResearchCandidates').textContent=String(candidateFrameCount);$t('tripResearchAudio').textContent=`${audioIndex} • ${(audioBytes/1048576).toFixed(1)} MB`;const s=$t('tripResearchStart');if(s){s.classList.toggle('on',active);s.disabled=active}const x=$t('tripResearchStop');if(x)x.disabled=!active}
async function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
async function exportLast(){if(active){status('Pysäytä tutkimusajo ennen vientiä.');return}try{const meta=lastSessionId?await getSession(lastSessionId):await latestSession();if(!meta){status('Ei tutkimusajoa vietäväksi.');return}const tls=(await allBySession(TIMELINE_STORE,meta.id)).sort((a,b)=>a.index-b.index),aus=(await allBySession(AUDIO_STORE,meta.id)).sort((a,b)=>a.index-b.index);const frames=tls.flatMap(x=>x.frames||[]);const manifest={schema:'motolab_trip_research_export_v1',exportedAt:new Date().toISOString(),session:meta,candidateFormat:CANDIDATE_FORMAT,timeline:frames,audioChunks:aus.map(x=>({index:x.index,startMs:x.startMs,endMs:x.endMs,size:x.size,mime:x.mime}))};const stamp=(meta.startedAt||new Date().toISOString()).replace(/[:.]/g,'-'),jsonFile=new File([JSON.stringify(manifest)],`MotoLab_TRIP_${stamp}.json`,{type:'application/json'}),audioBlob=new Blob(aus.map(x=>x.blob),{type:meta.audioMime||aus[0]?.mime||'audio/mp4'}),ext=(meta.audioMime||'').includes('webm')?'webm':'m4a',audioFile=new File([audioBlob],`MotoLab_AUDIO_${stamp}.${ext}`,{type:audioBlob.type});const files=[jsonFile,audioFile];if(navigator.share&&navigator.canShare?.({files})){await navigator.share({files,title:'MotoLab 3. vaihteen tutkimusajo'});status(`Vienti valmis • ${frames.length} aikajanan kehystä + ${(audioBlob.size/1048576).toFixed(1)} MB audio.`)}else{await downloadBlob(jsonFile,jsonFile.name);setTimeout(()=>downloadBlob(audioFile,audioFile.name),700);status('Vienti ladattu JSON + audio -tiedostoina.')}}catch(e){if(e?.name==='AbortError'){status('Vienti peruttiin.');return}showError(e)}}

function injectUi(){if($t('tripResearchPanel'))return true;const screen=$t('screen-measure');if(!screen)return false;const p=document.createElement('div');p.className='panel';p.id='tripResearchPanel';p.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">🎙️</span> 3. VAIHTEEN GPS + MIC TUTKIMUSAJO</div><span class="tiny">${MODULE_VERSION}</span></div><div class="statusbox">Koko lenkki tallennetaan tutkimusaineistoksi. GPS/nopeus + 3. vaihde on RPM-referenssi. BT MIC on vain shadow-dataa. Audiosta säilytetään 5 s palat sekä koko algoritmin candidate-joukko, jotta oikeaa RPM-haaraa voidaan etsiä jälkikäteen koko ajon yli.</div><div class="grid2"><button id="tripResearchStart" class="action">ALOITA 3. VAIHDE</button><button id="tripResearchStop" class="action gray" disabled>STOP & TALLENNA</button><button id="tripResearchExport" class="action full">VIE VIIMEISIN • JSON + AUDIO</button><div class="card"><span>Tila</span><b id="tripResearchState">VALMIS</b></div><div class="card"><span>Kesto</span><b id="tripResearchDuration">0m 0s</b></div><div class="card"><span>Aikajana</span><b id="tripResearchFrames">0</b></div><div class="card"><span>Candidate-kehykset</span><b id="tripResearchCandidates">0</b></div><div class="card full"><span>Audio</span><b id="tripResearchAudio">0 • 0.0 MB</b></div></div><div id="tripResearchStatus" class="statusbox">Valitse BT MIC tarvittaessa Asetuksista. Aloitus pakottaa tutkimusajon 3. vaihteelle ja GPS MASTER + MIC LEARN -tilaan.</div>`;screen.appendChild(p);$t('tripResearchStart').onclick=startResearch;$t('tripResearchStop').onclick=stopResearch;$t('tripResearchExport').onclick=exportLast;latestSession().then(x=>{if(x){lastSessionId=x.id;session=x;frameCount=x.frameCount||0;candidateFrameCount=x.candidateFrameCount||0;audioIndex=x.audioChunks||0;audioBytes=x.audioBytes||0;renderState()}}).catch(()=>{});return true}
function boot(){openDb().catch(()=>{});if(!injectUi()){setTimeout(boot,200);return}renderState()}
window.addEventListener('beforeunload',()=>{if(active)flushTimeline().catch(()=>{})});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
