(() => {
'use strict';
const MODULE_VERSION='v32-ui-compact-1';
const STATE_KEY='motolab_v32_settings_panel_state';
const $u=id=>document.getElementById(id);
function readState(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{return {}}}
function writeState(state){try{localStorage.setItem(STATE_KEY,JSON.stringify(state))}catch{}}
function panelKey(panel){const title=panel.querySelector(':scope > .phead .ptitle')?.textContent?.replace(/\s+/g,' ').trim()||'panel';return title.toLowerCase().replace(/[^a-z0-9åäö]+/gi,'-').replace(/^-|-$/g,'')}
function defaultOpen(panel){const title=panel.querySelector(':scope > .phead .ptitle')?.textContent||'';return /SMART BIKE PROFILES|MITTAUS\s*&\s*RPM/i.test(title)}
function setCollapsed(panel,collapsed,save=true){const body=panel.querySelector(':scope > .settingsPanelBody'),btn=panel.querySelector(':scope > .phead .settingsCollapseBtn');if(!body)return;panel.classList.toggle('settings-collapsed',collapsed);body.hidden=collapsed;if(btn){btn.textContent=collapsed?'AVAA ▾':'SULJE ▴';btn.setAttribute('aria-expanded',collapsed?'false':'true')}if(save){const state=readState();state[panelKey(panel)]=collapsed;writeState(state)}}
function makeCollapsible(panel){if(!panel||panel.dataset.settingsCollapsible==='1')return;const head=panel.querySelector(':scope > .phead');if(!head)return;panel.dataset.settingsCollapsible='1';const body=document.createElement('div');body.className='settingsPanelBody';while(head.nextSibling)body.appendChild(head.nextSibling);panel.appendChild(body);const btn=document.createElement('button');btn.type='button';btn.className='settingsCollapseBtn';btn.setAttribute('aria-label','Avaa tai sulje asetusryhmä');head.appendChild(btn);const state=readState(),key=panelKey(panel),collapsed=Object.prototype.hasOwnProperty.call(state,key)?!!state[key]:!defaultOpen(panel);setCollapsed(panel,collapsed,false);btn.addEventListener('click',e=>{e.stopPropagation();setCollapsed(panel,!panel.classList.contains('settings-collapsed'))});head.addEventListener('click',e=>{if(e.target.closest('button,input,select,a,label'))return;setCollapsed(panel,!panel.classList.contains('settings-collapsed'))})}
function installSettingsCollapse(){const screen=$u('screen-settings');if(!screen)return false;screen.querySelectorAll(':scope > .panel').forEach(makeCollapsible);if(!screen.__compactObserver){screen.__compactObserver=new MutationObserver(()=>screen.querySelectorAll(':scope > .panel').forEach(makeCollapsible));screen.__compactObserver.observe(screen,{childList:true})}return true}
function installQuickBtMic(){const btn=$u('extMicBtn');if(!btn)return false;const label=btn.querySelector('.lbl');if(label)label.textContent='BT MIC';btn.setAttribute('aria-label','BT MIC päälle tai pois');btn.title='BT MIC päälle / pois suoraan etusivulta';return true}
function installStyles(){if($u('compactUiStyles'))return;const style=document.createElement('style');style.id='compactUiStyles';style.textContent=`#screen-settings>.panel>.phead{cursor:pointer;gap:8px}.settingsCollapseBtn{margin-left:auto;flex:0 0 auto;border:1px solid rgba(255,255,255,.14);background:#15171b;color:#dfe2e6;border-radius:9px;padding:5px 8px;font-size:7px;font-weight:1000;letter-spacing:.03em}.settings-collapsed>.phead{border-bottom-color:transparent}.settings-collapsed{background:linear-gradient(#0d0f13,#090a0d)}#extMicBtn.on{box-shadow:0 0 0 1px rgba(59,240,107,.2),0 0 18px rgba(59,240,107,.10)}`;document.head.appendChild(style)}
function boot(){installStyles();const a=installQuickBtMic(),b=installSettingsCollapse();if(!a||!b){setTimeout(boot,180);return}if(typeof addLearningEvent==='function')addLearningEvent('ui_compact_loaded',{module:MODULE_VERSION})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
