(() => {
'use strict';
const VERSION='motolab-user-features-v2';
const SERVER_KEY='motolab_v32_beta_server',TOKEN_KEY='motolab_v32_beta_token';
let permissions=null,me=null,overlay=null;
const $=id=>document.getElementById(id);
function server(){return String(localStorage.getItem(SERVER_KEY)||'').trim().replace(/\/$/,'').replace(/\/api\/raw\/v1\/chunk$/i,'')}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
async function api(path,opt={}){const r=await fetch(server()+path,{cache:'no-store',...opt,headers:{'Content-Type':'application/json','X-MotoLab-Beta-Token':token(),...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function appMeta(){return {appVersion:String(globalThis.MOTOLAB_RELEASE?.version||''),build:String(globalThis.MOTOLAB_RELEASE?.build||''),platform:navigator.platform||navigator.userAgent||'',deviceModel:navigator.userAgent||''}}
function hideDenied(){
 if(!permissions)return;
 const phoneMicAllowed=permissions.phone_mic!==false,btAllowed=!!permissions.bt_contact_mic;
 // The dashboard MIC control is the normal phone/default microphone control and must
 // not disappear just because advanced BT/contact-source selection is unavailable.
 ['extMicBtn','extChip'].forEach(id=>{const e=$(id);if(!e)return;e.disabled=!phoneMicAllowed;e.closest('.panel,.card,.ctl,.switchrow')?.classList.toggle('muf-denied',!phoneMicAllowed);if(!phoneMicAllowed)e.title='Mikrofoni ei kuulu tämän käyttäjän oikeuksiin';else e.removeAttribute('title')});
 // Only advanced source-selection controls are admin/BT-contact gated.
 ['audioDevice','audioRefreshBtn','btTestBtn'].forEach(id=>{const e=$(id);if(e)e.closest('label,.panel,.card,.switchrow')?.classList.toggle('muf-denied',!btAllowed)});
 document.body.dataset.motolabPhoneMic=phoneMicAllowed?'1':'0';document.body.dataset.motolabBtContact=btAllowed?'1':'0'
}
async function refresh(){if(!server()||!token())return;try{const a=await api('/api/users/v1/me'),b=await api('/api/features/v1/me');me=a.user;permissions=b.permissions||{};hideDenied();await api('/api/features/v1/heartbeat',{method:'POST',body:JSON.stringify(appMeta())});enhanceAccount()}catch{}}
function styles(){if($('motolabUserFeaturesStyle'))return;const s=document.createElement('style');s.id='motolabUserFeaturesStyle';s.textContent=`.muf-denied{display:none!important}.muf-overlay{position:fixed;inset:0;z-index:260000;background:#000e;display:flex;align-items:flex-end;justify-content:center;padding:10px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.muf-card{width:min(100%,480px);max-height:92vh;overflow:auto;background:#0b0c0f;border:1px solid #ff263f;border-radius:20px;padding:14px}.muf-card h2,.muf-card h3{margin:5px 0 10px}.muf-row{border:1px solid #2d3036;border-radius:11px;padding:9px;margin:7px 0}.muf-row small{display:block;color:#9ca2aa;margin:3px 0}.muf-btn{width:100%;padding:10px;margin-top:7px;border-radius:10px;border:1px solid #ff263f;background:#66101c;color:#fff;font-weight:900}.muf-btn.gray{border-color:#444;background:#17191e}.muf-perm{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1px solid #202228}.muf-perm input{width:auto}.muf-canvas{width:100%;height:260px;background:#050608;border:1px solid #292c31;border-radius:10px}`;document.head.appendChild(s)}
function close(){if(overlay){overlay.remove();overlay=null}}
function open(html){close();overlay=document.createElement('div');overlay.className='muf-overlay';overlay.innerHTML=`<div class="muf-card">${html}<button class="muf-btn gray" id="mufClose">SULJE</button></div>`;document.body.appendChild(overlay);$('mufClose').onclick=close;return overlay}
async function allRuns(){return new Promise(resolve=>{try{const req=indexedDB.open('VanaMotoLab',2);req.onerror=()=>resolve(fallbackRuns());req.onsuccess=()=>{const d=req.result;if(!d.objectStoreNames.contains('runs'))return resolve(fallbackRuns());const q=d.transaction('runs','readonly').objectStore('runs').getAll();q.onsuccess=()=>resolve((q.result||[]).sort((a,b)=>Date.parse(b.date||0)-Date.parse(a.date||0)));q.onerror=()=>resolve(fallbackRuns())}}catch{resolve(fallbackRuns())}})}
function fallbackRuns(){try{return JSON.parse(localStorage.getItem('motolab_v26_runs')||'[]')}catch{return []}}
function graphPayload(r){return {id:r.id,profileName:r.profileName,date:r.date,quality:r.quality,maxHp:r.maxHp,maxNm:r.maxNm,maxRpm:r.maxRpm,curve:(r.data||[]).map(x=>({rpm:x.rpm,hp:x.hp,nm:x.nm}))}}
async function sharingHome(){const [targets,inbox,runs]=await Promise.all([api('/api/users/v1/share-targets'),api('/api/shares/v1/inbox'),allRuns()]);const pending=inbox.shares.filter(s=>s.status==='pending'),accepted=inbox.shares.filter(s=>s.status==='accepted');open(`<h2>Vetojen jako</h2>${pending.length?'<h3>Odottaa hyväksyntää</h3>'+pending.map(s=>`<div class="muf-row"><b>${esc(s.senderNickname)}</b><small>${esc(s.run.profileName)} • ${s.run.quality}% • ${Number(s.run.maxHp||0).toFixed(1)} hv</small><button class="muf-btn" data-accept="${s.shareId}">HYVÄKSY</button><button class="muf-btn gray" data-reject="${s.shareId}">HYLKÄÄ</button></div>`).join(''):''}<h3>Jaetut vedot</h3>${accepted.length?accepted.map(s=>`<div class="muf-row"><b>${esc(s.senderNickname)} • ${esc(s.run.profileName)}</b><small>Laatu ${s.run.quality}% • ${Number(s.run.maxHp||0).toFixed(1)} hv</small><button class="muf-btn" data-compare="${s.shareId}">VERTAA OMAAN VETOON</button><button class="muf-btn gray" data-best="${s.shareId}">VERTAA PARHAASEEN OMAAN VETOON</button></div>`).join(''):'<div class="muf-row">Ei hyväksyttyjä jaettuja vetoja.</div>'}<h3>Jaa oma veto</h3><select id="mufRun">${runs.map(r=>`<option value="${esc(r.id)}">${esc(r.profileName||'Pyörä')} • ${r.quality||0}% • ${Number(r.maxHp||0).toFixed(1)} hv</option>`).join('')}</select><select id="mufTarget">${targets.users.map(u=>`<option value="${u.userId}">${esc(u.nickname)}</option>`).join('')}</select><button class="muf-btn" id="mufSend">LÄHETÄ JAKOPYYNTÖ</button><div id="mufStatus"></div>`);document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>respond(b.dataset.accept,'accepted'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>respond(b.dataset.reject,'rejected'));document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>chooseOwn(inbox.shares.find(s=>s.shareId===b.dataset.compare),runs));document.querySelectorAll('[data-best]').forEach(b=>b.onclick=()=>compareBest(inbox.shares.find(s=>s.shareId===b.dataset.best),runs));$('mufSend').onclick=async()=>{const r=runs.find(x=>String(x.id)===String($('mufRun').value));if(!r)return;try{await api('/api/shares/v1/runs',{method:'POST',body:JSON.stringify({receiverUserId:$('mufTarget').value,run:graphPayload(r)})});$('mufStatus').textContent='Jakopyyntö lähetetty.'}catch(e){$('mufStatus').textContent=e.message}}}
async function respond(id,action){await api('/api/shares/v1/respond',{method:'POST',body:JSON.stringify({shareId:id,action})});sharingHome()}
function comparable(shared,runs){const same=runs.filter(r=>(r.profileName||'')===(shared.run.profileName||'')&&Number(r.quality||0)>=60);return same.length?same:runs.filter(r=>Number(r.quality||0)>=60)}
function chooseOwn(shared,runs){const rr=comparable(shared,runs);open(`<h2>Vertaa omaan vetoon</h2><div class="muf-row"><b>${esc(shared.senderNickname)} • ${esc(shared.run.profileName)}</b><small>Jaettu veto • laatu ${shared.run.quality}%</small></div>${rr.map(r=>`<button class="muf-btn gray" data-own="${esc(r.id)}">${esc(r.profileName||'Pyörä')} • ${r.quality||0}% • ${Number(r.maxHp||0).toFixed(1)} hv</button>`).join('')}`);document.querySelectorAll('[data-own]').forEach(b=>b.onclick=()=>drawCompare(shared,runs.find(r=>String(r.id)===String(b.dataset.own))))}
function compareBest(shared,runs){const rr=comparable(shared,runs);if(!rr.length)return chooseOwn(shared,runs);rr.sort((a,b)=>(Number(b.maxHp||0)*(Number(b.quality||0)/100))-(Number(a.maxHp||0)*(Number(a.quality||0)/100)));drawCompare(shared,rr[0])}
function drawCompare(shared,own){open(`<h2>Vetojen vertailu</h2><canvas id="mufCanvas" class="muf-canvas" width="900" height="520"></canvas><div class="muf-row"><b>${esc(shared.senderNickname)}</b><small>${esc(shared.run.profileName)} • ${shared.run.quality}% • ${Number(shared.run.maxHp||0).toFixed(1)} hv</small></div><div class="muf-row"><b>Oma veto</b><small>${esc(own.profileName||'Pyörä')} • ${own.quality||0}% • ${Number(own.maxHp||0).toFixed(1)} hv</small></div>`);const c=$('mufCanvas'),ctx=c.getContext('2d'),a=shared.run.curve||[],b=(own.data||[]).filter(x=>x.rpm>0);const all=[...a,...b];if(!all.length)return;const min=Math.min(...all.map(x=>x.rpm)),max=Math.max(...all.map(x=>x.rpm)),top=Math.max(1,...all.map(x=>x.hp||0));const sx=x=>50+(x-min)/Math.max(1,max-min)*(c.width-80),sy=y=>c.height-45-(y/top)*(c.height-80);ctx.strokeStyle='#333';ctx.lineWidth=1;for(let i=0;i<6;i++){const y=30+i*(c.height-80)/5;ctx.beginPath();ctx.moveTo(45,y);ctx.lineTo(c.width-20,y);ctx.stroke()}function line(arr,color){ctx.strokeStyle=color;ctx.lineWidth=5;ctx.beginPath();arr.forEach((p,i)=>i?ctx.lineTo(sx(p.rpm),sy(p.hp)):ctx.moveTo(sx(p.rpm),sy(p.hp)));ctx.stroke()}line(a,'#ff263f');line(b,'#35a7ff');ctx.fillStyle='#fff';ctx.font='24px sans-serif';ctx.fillText('Jaettu veto',55,30);ctx.fillText('Oma veto',250,30)}
async function adminPanel(){const j=await api('/api/admin/v1/features/users');open(`<h2>Käyttäjien käyttöoikeudet</h2>${j.users.map(u=>`<div class="muf-row"><b>${esc(u.nickname)}</b><small>${esc(u.status)} • ${esc(u.client?.appVersion||'versio ?')} / ${esc(u.client?.build||'build ?')} • ${esc(u.client?.lastSeenAt||'ei yhteyttä')}</small>${u.role==='admin'?'<small>ADMIN • kaikki oikeudet</small>':Object.entries(u.permissions||{}).map(([k,v])=>`<label class="muf-perm">${esc(k)}<input type="checkbox" data-puser="${u.userId}" data-pkey="${k}" ${v?'checked':''}></label>`).join('')}</div>`).join('')}<button class="muf-btn" id="mufSavePerms">TALLENNA OIKEUDET</button><div id="mufStatus"></div>`);$('mufSavePerms').onclick=async()=>{const grouped={};document.querySelectorAll('[data-puser]').forEach(e=>{grouped[e.dataset.puser]=grouped[e.dataset.puser]||{};grouped[e.dataset.puser][e.dataset.pkey]=e.checked});try{for(const [userId,p] of Object.entries(grouped))await api('/api/admin/v1/features/permissions',{method:'POST',body:JSON.stringify({userId,permissions:p})});$('mufStatus').textContent='Oikeudet tallennettu.'}catch(e){$('mufStatus').textContent=e.message}}}
function enhanceAccount(){const p=$('motolabUserPanel');if(!p||p.dataset.featuresEnhanced)return;p.dataset.featuresEnhanced='1';const card=p.querySelector('.mui-card');if(!card)return;const closeBtn=$('muiClose');const share=document.createElement('button');share.className='mui-btn secondary';share.textContent='JAETUT VEDOT / JAA VETO';share.onclick=sharingHome;card.insertBefore(share,closeBtn);if(me?.role==='admin'){const a=document.createElement('button');a.className='mui-btn secondary';a.textContent='KÄYTTÖOIKEUDET / VERSIOT';a.onclick=adminPanel;card.insertBefore(a,closeBtn)}}
function boot(){styles();refresh();new MutationObserver(()=>{hideDenied();enhanceAccount()}).observe(document.documentElement,{childList:true,subtree:true});setInterval(refresh,60000)}
window.MotoLabUserFeatures={version:VERSION,refresh,sharingHome,adminPanel,get permissions(){return permissions}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();