(() => {
'use strict';
const VERSION='motolab-user-identity-v1';
const DEVICE_KEY='motolab_v32_raw_sync_device';
const TOKEN_KEY='motolab_v32_beta_token';
const SERVER_KEY='motolab_v32_beta_server';
const NICK_KEY='motolab_user_nickname';
const STATE_KEYS=['motolab_v26_profiles','motolab_v26_runs','motolab_v29_raw_fallback','motolab_v29_learning_enabled','motolab_v32_raw_sync_cfg','motolab_v32_beta_consent','motolab_v32_dev_unlocked'];
const nativeFetch=window.fetch.bind(window);
let me=null,lastSnapshot='',syncTimer=0,overlay=null;
const $=id=>document.getElementById(id);
function ensureDeviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(DEVICE_KEY,id)}return id}
function server(){return String(localStorage.getItem(SERVER_KEY)||'').trim().replace(/\/$/,'').replace(/\/api\/raw\/v1\/chunk$/i,'')}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
function headers(json=true){const h={};if(json)h['Content-Type']='application/json';if(token())h['X-MotoLab-Beta-Token']=token();return h}
async function api(path,opt={}){const s=server();if(!s)throw Error('MotoLab server missing');const r=await nativeFetch(s+path,{cache:'no-store',...opt,headers:{...headers(opt.json!==false),...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok){const e=Error(j.error||('HTTP '+r.status));e.status=r.status;e.data=j;throw e}return j}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function snapshot(){const out={};for(const k of STATE_KEYS){const v=localStorage.getItem(k);if(v!==null)out[k]=v}return out}
function applyState(state){if(!state||typeof state!=='object')return;for(const k of STATE_KEYS)if(Object.prototype.hasOwnProperty.call(state,k)){const v=state[k];if(v===null)localStorage.removeItem(k);else if(typeof v==='string')localStorage.setItem(k,v)}}
async function uploadState(force=false){if(!me||me.status!=='active')return;const state=snapshot(),sig=JSON.stringify(state);if(!force&&sig===lastSnapshot)return;await api('/api/users/v1/state',{method:'PUT',body:JSON.stringify({state})});lastSnapshot=sig}
async function initialSync(){if(!me||me.status!=='active')return;const j=await api('/api/users/v1/state');const remote=j.item||{};if(remote.updatedAt&&remote.state&&Object.keys(remote.state).length){applyState(remote.state);lastSnapshot=JSON.stringify(snapshot())}else{await uploadState(true)}clearInterval(syncTimer);syncTimer=setInterval(()=>uploadState(false).catch(()=>{}),6000)}
function closeOverlay(){if(overlay){overlay.remove();overlay=null}}
function style(){if($('motolabUserIdentityStyle'))return;const s=document.createElement('style');s.id='motolabUserIdentityStyle';s.textContent=`#motolabUserLock{position:fixed;inset:0;z-index:250000;background:rgba(0,0,0,.96);display:flex;align-items:flex-end;justify-content:center;padding:12px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mui-card{width:min(100%,460px);background:#0b0c0f;border:1px solid #ff263f;border-radius:22px;padding:18px;box-shadow:0 24px 80px #000}.mui-card h2{margin:6px 0 10px;font-size:20px}.mui-card p{font-size:11px;line-height:1.55;color:#c8cbd1}.mui-card input{box-sizing:border-box;width:100%;padding:11px;border-radius:10px;border:1px solid #333;background:#050608;color:#fff}.mui-btn{width:100%;margin-top:9px;padding:11px;border-radius:10px;border:1px solid #ff263f;background:#a80d20;color:#fff;font-weight:900}.mui-btn.secondary{background:#111;border-color:#444}.mui-status{font-size:10px;color:#c7cbd0;margin-top:9px}.mui-user-pill{position:fixed;right:10px;bottom:calc(10px + env(safe-area-inset-bottom));z-index:120000;border:1px solid #ff263f;background:#0b0c0fe8;color:#fff;border-radius:999px;padding:7px 10px;font:800 9px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mui-admin-list{max-height:40vh;overflow:auto;margin-top:10px}.mui-admin-row{border:1px solid #292b31;border-radius:12px;padding:9px;margin:7px 0}.mui-admin-row b{font-size:11px}.mui-admin-row small{display:block;color:#999;margin:3px 0 6px}.mui-admin-row button{margin-right:5px;padding:6px 8px}`;document.head.appendChild(s)}
function lockScreen(user){closeOverlay();overlay=document.createElement('div');overlay.id='motolabUserLock';const pending=user?.status==='pending',blocked=user?.status==='blocked';overlay.innerHTML=`<div class="mui-card"><div style="font-weight:1000;font-style:italic">VÄNÄ <span style="color:#ff263f">MotoLab</span></div><h2>${blocked?'Käyttö estetty':'Odottaa hyväksyntää'}</h2><p>${blocked?'Tämä käyttäjä on poistettu käytöstä.':'Laite on rekisteröity MotoLabiin. Pääylläpitäjä hyväksyy käyttäjän nimimerkin perusteella.'}</p>${pending?`<label style="font-size:9px;color:#aaa">Nimimerkki</label><input id="muiNick" maxlength="32" value="${esc(user.nickname||localStorage.getItem(NICK_KEY)||'')}"><button class="mui-btn" id="muiNickSave">TALLENNA NIMIMERKKI</button>`:''}<div class="mui-status" id="muiStatus">Käyttäjä: ${esc(user?.nickname||'')} • ${esc(user?.status||'')}</div><div class="mui-status">Laite: ${esc(ensureDeviceId().slice(0,18))}…</div></div>`;document.body.appendChild(overlay);if(pending){$('muiNickSave').onclick=async()=>{const n=$('muiNick').value.trim();if(!n)return;try{const j=await api('/api/users/v1/nickname',{method:'POST',body:JSON.stringify({nickname:n})});localStorage.setItem(NICK_KEY,n);me=j.user;$('muiStatus').textContent='Nimimerkki tallennettu • odottaa hyväksyntää'}catch(e){$('muiStatus').textContent=e.message}}}}
async function createInvite(){const j=await api('/api/users/v1/invite',{method:'POST',body:'{}'});const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('betaServer',server());u.searchParams.set('invite',j.invite);return {url:u.toString(),expiresAt:j.expiresAt,inviteId:j.inviteId}}
function accountPanel(){let old=$('motolabUserPanel');if(old){old.remove();return}const p=document.createElement('div');p.id='motolabUserPanel';p.style.cssText='position:fixed;inset:0;z-index:240000;background:#000d;display:flex;align-items:flex-end;justify-content:center;padding:12px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif';p.innerHTML=`<div class="mui-card"><h2>${esc(me.nickname)}</h2><p>${me.role==='admin'?'Pääylläpitäjä':'MotoLab-käyttäjä'} • ${esc(me.status)}</p><button class="mui-btn" id="muiInvite">LUO KUTSULINKKI</button>${me.role==='admin'?'<button class="mui-btn secondary" id="muiLoadUsers">KÄYTTÄJÄT / HYVÄKSYNNÄT</button><div id="muiUsers" class="mui-admin-list"></div>':''}<div id="muiPanelStatus" class="mui-status"></div><button class="mui-btn secondary" id="muiClose">SULJE</button></div>`;document.body.appendChild(p);$('muiClose').onclick=()=>p.remove();$('muiInvite').onclick=async()=>{try{const x=await createInvite();const st=$('muiPanelStatus');st.textContent=x.url;if(navigator.share)await navigator.share({title:'VÄNÄ MotoLab',text:'MotoLab-kutsu',url:x.url});else if(navigator.clipboard){await navigator.clipboard.writeText(x.url);st.textContent='Kutsulinkki kopioitu leikepöydälle.'}}catch(e){$('muiPanelStatus').textContent=e.message}};if(me.role==='admin')$('muiLoadUsers').onclick=loadUsers}
async function loadUsers(){const box=$('muiUsers');box.textContent='Haetaan…';try{const j=await api('/api/admin/v1/users');box.innerHTML=j.users.map(u=>`<div class="mui-admin-row"><b>${esc(u.nickname)}</b><small>${esc(u.status)} • ${esc(u.userId)}${u.invitedBy?' • kutsui '+esc(u.invitedBy):''}</small>${u.status!=='active'?`<button data-user="${esc(u.userId)}" data-status="active">HYVÄKSY</button>`:''}${u.role!=='admin'&&u.status!=='blocked'?`<button data-user="${esc(u.userId)}" data-status="blocked">ESTÄ</button>`:''}</div>`).join('');box.querySelectorAll('button[data-user]').forEach(b=>b.onclick=async()=>{try{await api('/api/admin/v1/user-status',{method:'POST',body:JSON.stringify({userId:b.dataset.user,status:b.dataset.status})});await loadUsers()}catch(e){$('muiPanelStatus').textContent=e.message}})}catch(e){box.textContent=e.message}}
function installPill(){if($('motolabUserPill')||!me||me.status!=='active')return;const b=document.createElement('button');b.id='motolabUserPill';b.className='mui-user-pill';b.textContent=(me.role==='admin'?'ADMIN • ':'')+me.nickname;b.onclick=accountPanel;document.body.appendChild(b)}
async function refresh(){if(!token()||!server())return null;try{const j=await api('/api/users/v1/me',{method:'GET'});me=j.user;localStorage.setItem(NICK_KEY,me.nickname||'');if(me.status==='active'){closeOverlay();installPill();await initialSync()}else lockScreen(me);return me}catch(e){if(e.status===401)localStorage.removeItem(TOKEN_KEY);return null}}
function observePending(){setInterval(async()=>{if(!token()||!server())return;if(me?.status==='active')return;const before=me?.status;await refresh();if(before!=='active'&&me?.status==='active')location.reload()},12000)}
function boot(){style();ensureDeviceId();refresh().catch(()=>{});observePending();const mo=new MutationObserver(()=>{if(token()&&server()&&!me)refresh().catch(()=>{})});mo.observe(document.documentElement,{childList:true,subtree:true})}
window.MotoLabUser={version:VERSION,refresh,createInvite,get user(){return me},deviceId:ensureDeviceId};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
