(() => {
'use strict';
const VERSION='motorlab-user-identity-v4',DEVICE_KEY='motolab_v32_raw_sync_device',TOKEN_KEY='motolab_v32_beta_token',SERVER_KEY='motolab_v32_beta_server',NICK_KEY='motolab_user_nickname';
let me=null,overlay=null;const $=id=>document.getElementById(id);const nativeFetch=window.fetch.bind(window);
function device(){let x=localStorage.getItem(DEVICE_KEY);if(!x){x=crypto.randomUUID?.()||'dev-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(DEVICE_KEY,x)}return x}function server(){return String(localStorage.getItem(SERVER_KEY)||'').trim().replace(/\/$/,'').replace(/\/api\/raw\/v1\/chunk$/i,'')}function token(){return localStorage.getItem(TOKEN_KEY)||''}function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){if(!server())throw Object.assign(Error('MotorLab-palvelinta ei ole vielä yhdistetty.'),{code:'NO_SERVER'});const h={...(opt.headers||{})};if(opt.json!==false)h['Content-Type']='application/json';if(token())h['X-MotoLab-Beta-Token']=token();const r=await nativeFetch(server()+path,{cache:'no-store',...opt,headers:h});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Object.assign(Error(j.error||('HTTP '+r.status)),{status:r.status,data:j});return j}
function close(){overlay?.remove();overlay=null}function style(){if($('muiRecoveryStyle'))return;const s=document.createElement('style');s.id='muiRecoveryStyle';s.textContent=`#motolabUserLock{position:fixed;inset:0;z-index:250000;background:#000f;display:flex;align-items:flex-end;justify-content:center;padding:12px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mui-card{width:min(100%,460px);background:#0b0c0f;border:1px solid #ff263f;border-radius:22px;padding:18px}.mui-card input{box-sizing:border-box;width:100%;padding:11px;margin:6px 0;border-radius:10px;border:1px solid #333;background:#050608;color:#fff}.mui-btn{width:100%;margin-top:9px;padding:11px;border-radius:10px;border:1px solid #ff263f;background:#a80d20;color:#fff;font-weight:900}.mui-btn.secondary{background:#111;border-color:#444}.mui-status{font-size:10px;color:#c7cbd0;margin-top:9px;white-space:pre-wrap}.mui-user-pill{position:fixed;right:10px;bottom:calc(88px + env(safe-area-inset-bottom));z-index:120000;border:1px solid #ff263f;background:#0b0c0fe8;color:#fff;border-radius:999px;padding:7px 10px;font:800 9px sans-serif}`;document.head.appendChild(s)}
function showRecovery(msg=''){close();overlay=document.createElement('div');overlay.id='motolabUserLock';overlay.innerHTML=`<div class="mui-card"><b>VÄNÄ <span style="color:#ff263f">MotorLab</span></b><h2>Yhdistä käyttäjä</h2><p>Kirjautumistietoa ei löytynyt tai vanha istunto on vanhentunut. Mittaustietoja ei poisteta.</p><label>MotorLab-palvelin</label><input id="muiServer" value="${esc(server())}" placeholder="https://…"><label>Kutsukoodi</label><input id="muiInvite" placeholder="Kutsukoodi"><button class="mui-btn" id="muiActivate">AKTIVOI / KIRJAUDU</button><button class="mui-btn secondary" id="muiRetry">YRITÄ UUDELLEEN</button><div id="muiStatus" class="mui-status">${esc(msg)}</div></div>`;document.body.appendChild(overlay);$('muiActivate').onclick=activate;$('muiRetry').onclick=()=>refresh(true)}
async function activate(){const st=$('muiStatus'),s=String($('muiServer').value||'').trim().replace(/\/$/,'');if(!s)return st.textContent='Palvelimen osoite puuttuu.';localStorage.setItem(SERVER_KEY,s);const code=String($('muiInvite').value||'').trim();if(!code)return refresh(true);st.textContent='Aktivoidaan…';try{const r=await nativeFetch(s+'/api/beta/v1/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,deviceId:device()}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok||!j.token)throw Error(j.error||('HTTP '+r.status));localStorage.setItem(TOKEN_KEY,j.token);await refresh(true)}catch(e){st.textContent='Aktivointi epäonnistui: '+e.message}}
function lockUser(u){showRecovery(u?.status==='blocked'?'Käyttö estetty.':'Käyttäjä odottaa ylläpidon hyväksyntää.');if(u?.status==='pending'){$('muiActivate').style.display='none';$('muiRetry').textContent='TARKISTA HYVÄKSYNTÄ'}}
function pill(){if($('motolabUserPill')||!me||me.status!=='active')return;const b=document.createElement('button');b.id='motolabUserPill';b.className='mui-user-pill';b.textContent=(me.role==='admin'?'ADMIN • ':'')+(me.nickname||'KÄYTTÄJÄ');b.onclick=account;document.body.appendChild(b)}
async function account(){close();overlay=document.createElement('div');overlay.id='motolabUserLock';overlay.innerHTML=`<div class="mui-card"><h2>${esc(me?.nickname||'MotorLab')}</h2><p>${esc(me?.role||'user')} • ${esc(me?.status||'')}</p><button class="mui-btn" id="muiCommunity">BETA-KESKUSTELU</button><button class="mui-btn secondary" id="muiInviteCreate">LUO KUTSU</button><button class="mui-btn secondary" id="muiClose">SULJE</button><div id="muiStatus" class="mui-status"></div></div>`;document.body.appendChild(overlay);$('muiClose').onclick=close;$('muiCommunity').onclick=()=>globalThis.MotoLabCommunity?.home?.();$('muiInviteCreate').onclick=async()=>{try{const x=await createInvite();$('muiStatus').textContent=x.url;if(navigator.share)await navigator.share({title:'VäNä MotorLab',url:x.url})}catch(e){$('muiStatus').textContent=e.message}}}
async function createInvite(){const j=await api('/api/users/v1/invite',{method:'POST',body:'{}'}),u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('betaServer',server());u.searchParams.set('invite',j.invite);return{url:u.toString(),expiresAt:j.expiresAt}}
async function refresh(show=true){if(!server()||!token()){if(show)showRecovery(!server()?'Palvelinyhteys puuttuu.':'Kirjautuminen puuttuu.');return null}try{const j=await api('/api/users/v1/me');me=j.user;if(me?.nickname)localStorage.setItem(NICK_KEY,me.nickname);if(me?.status==='active'){close();pill();document.dispatchEvent(new CustomEvent('motorlab-user-ready',{detail:me}))}else lockUser(me);return me}catch(e){if(e.status===401){localStorage.removeItem(TOKEN_KEY);me=null;if(show)showRecovery('Istunto vanheni. Aktivoi kutsu uudelleen.')}else if(show)showRecovery('Palvelinyhteys epäonnistui: '+e.message);return null}}
function capture(){try{const p=new URLSearchParams(location.search),s=p.get('betaServer'),i=p.get('invite');if(s)localStorage.setItem(SERVER_KEY,String(s).replace(/\/$/,''));if(i)sessionStorage.setItem('motorlab_pending_invite',i);if(s||i){p.delete('betaServer');p.delete('invite');history.replaceState(null,'',location.pathname+(p.toString()?'?'+p:'')+location.hash)}}catch{}}
function boot(){style();device();capture();const pending=sessionStorage.getItem('motorlab_pending_invite');if(pending&&server()&&!token()){showRecovery('Kutsu löydetty. Aktivoi laite.');$('muiInvite').value=pending}else refresh(true);setInterval(()=>{if(me?.status!=='active'&&token()&&server())refresh(false)},12000)}
globalThis.MotoLabUser={version:VERSION,refresh,createInvite,get user(){return me},deviceId:device};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
