(() => {
'use strict';
const VERSION='motorlab-v34-dashboard-ui-v1';const $=id=>document.getElementById(id);
function css(){if($('mlV34DashboardStyle'))return;const s=document.createElement('style');s.id='mlV34DashboardStyle';s.textContent=`
:root{--ml-red:#ff263f;--ml-card:#0b0d11;--ml-line:#272a30}.app{background:#030304!important}.topbar{min-height:47px;padding:3px 2px}.brand{font-size:0!important}.brand:before{content:'VäNä ';font-size:14px;font-style:italic;font-weight:1000;color:#fff}.brand:after{content:'MotorLab';font-size:14px;font-style:italic;font-weight:1000;color:var(--ml-red)}.statuses .spill{background:#090a0d!important;border-color:#24262c!important}.ver{background:#0b0b0d!important}
body:not(.ml-admin-user) .hero{height:min(51vh,410px)!important;min-height:342px!important;border-radius:17px!important;border:1px solid #18191d!important;background:radial-gradient(circle at 76% 22%,rgba(255,38,63,.10),transparent 32%),linear-gradient(#060608,#020203)!important}.logo{display:none!important}body:not(.ml-admin-user) .bike{opacity:.20!important;right:-18px!important;top:48px!important;filter:saturate(.55) brightness(.48) contrast(1.12)!important}.heroChartBox{border:0!important;background:transparent!important}.heroChartTitle{opacity:.65}.gaugeRing{filter:none!important}.gcenter{border-color:#23252a!important;background:radial-gradient(circle,#101216,#040405 75%)!important}.gearBadge{border-color:#3b1c22!important}
body:not(.ml-admin-user) .metrics{grid-template-columns:repeat(3,1fr)!important}.metric{border-color:#202228!important;background:#090a0d!important}.metric.red{border-color:#382027!important}.controls{grid-template-columns:repeat(4,1fr)!important}.ctl{background:#0b0d10!important;border-color:#24272d!important;min-height:66px!important}#sensorBtn{grid-column:span 2}#extMicBtn{grid-column:span 2}#armBtn{grid-column:1/-1!important;min-height:56px!important;background:linear-gradient(180deg,#d4142c,#8e0b1d)!important;border-color:#ff263f!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:8px!important}#armBtn .ico{font-size:17px!important}#armBtn .lbl{font-size:0!important;margin:0!important}#armBtn .lbl:after{content:'ARM / ALOITA VETO';font-size:12px;font-weight:1000}#armBtn .state{display:none!important}#manualBtn,#stopBtn{min-height:54px!important}.bottomNav{border-radius:14px!important;border-color:#24262c!important;background:rgba(5,6,8,.95)!important}.bottomNav .nav{min-height:55px!important}.bottomNav .nav.active{background:transparent!important;border-color:transparent!important;color:#ff263f!important}.bottomNav .nav .ico{font-size:17px!important}.bottomNav .nav .txt{font-size:7px!important}
#screen-runs>.panel,#screen-analysis>.panel,#screen-settings>.panel{background:#090a0d!important;border-color:#24262c!important}.runCard{background:#0b0d10!important;border-color:#282b31!important}.action{background:#a80d20!important;border-color:#ff263f!important}.action.gray{background:#111318!important;border-color:#35383f!important}
.ml-analysis-launch{display:grid;gap:7px;margin:8px 0}.ml-analysis-item{width:100%;min-height:58px;border:1px solid #282b31;border-radius:12px;background:#0b0d10;color:#fff;text-align:left;padding:10px 12px;display:flex;align-items:center;justify-content:space-between}.ml-analysis-item span b{display:block;font-size:11px}.ml-analysis-item span small{display:block;margin-top:3px;color:#969da7;font-size:8px}.ml-analysis-item>i{font-style:normal;color:#ff263f;font-size:20px}.ml-analysis-beta{font-size:7px;color:#ff263f;border:1px solid #5c1e29;border-radius:7px;padding:2px 5px;margin-left:6px}.ml-settings-title{margin:9px 2px 2px;color:#fff;font-size:18px;font-weight:1000}
`;document.head.appendChild(s)}
function labelControl(){const ext=$('extMicBtn');if(ext){const l=ext.querySelector('.lbl');if(l)l.textContent='MIC';const i=ext.querySelector('.ico');if(i)i.textContent='🎙'}const sensor=$('sensorBtn');if(sensor){const l=sensor.querySelector('.lbl');if(l)l.textContent='GPS + IMU'}}
function analysisMenu(){const sec=$('screen-analysis');if(!sec||$('mlAnalysisLaunch'))return;const box=document.createElement('div');box.id='mlAnalysisLaunch';box.className='ml-analysis-launch';box.innerHTML=`<button class="ml-analysis-item" data-find="ANALYYSI"><span><b>SUORITUSKYKY</b><small>Teho, vääntö ja kiihtyvyysanalyysi</small></span><i>›</i></button><button class="ml-analysis-item" data-find="KAASUTTIMEN"><span><b>KAASUTTIMEN SÄÄTÖ</b><small>Vertaa suutinkokoja ja tuloksia</small></span><i>›</i></button><button class="ml-analysis-item" data-find="SUUTIN"><span><b>SUUTIN-EHDOTUS</b><small>Suositukset moottorillesi</small></span><i>›</i></button><button class="ml-analysis-item" data-disabled="1"><span><b>SYTYTYS <em class="ml-analysis-beta">BETA</em></b><small>Sytytyskartta ja optimointi • kehityksessä</small></span><i>›</i></button>`;sec.insertBefore(box,sec.firstChild);box.querySelectorAll('[data-find]').forEach(b=>b.onclick=()=>{const q=b.dataset.find,p=[...sec.querySelectorAll('.panel')].find(x=>(x.querySelector('.ptitle')?.textContent||'').includes(q));p?.scrollIntoView({behavior:'smooth',block:'start'})});box.querySelector('[data-disabled]').onclick=()=>{const s=$('analysisText');if(s)s.textContent='Sytytyksen automaattinen optimointi on vielä tarkoituksella pois käytöstä.'}}
function settingsTitle(){const sec=$('screen-settings');if(!sec||$('mlSettingsTitle'))return;const h=document.createElement('div');h.id='mlSettingsTitle';h.className='ml-settings-title';h.textContent='Asetukset';sec.insertBefore(h,sec.firstChild)}
function nav(){const n=document.querySelector('.bottomNav');if(!n)return;n.querySelectorAll('.nav[data-screen="live"],.nav[data-screen="autotune"]').forEach(x=>x.hidden=true);const labels={measure:'Etusivu',runs:'Vedot',analysis:'Analyysi',settings:'Asetukset'};for(const [k,v] of Object.entries(labels)){const e=n.querySelector(`.nav[data-screen="${k}"] .txt`);if(e)e.textContent=v}const u=n.querySelector('.ml-user-nav');if(u){u.hidden=false;const t=u.querySelector('.txt');if(t)t.textContent='Käyttäjä'}}
function apply(){css();labelControl();analysisMenu();settingsTitle();nav()}
function boot(){apply();let n=0;const t=setInterval(()=>{apply();if(++n>60)clearInterval(t)},350);new MutationObserver(()=>requestAnimationFrame(apply)).observe(document.documentElement,{childList:true,subtree:true})}
globalThis.MotoLabV34UI={version:VERSION,apply};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
