(() => {
'use strict';
const MODULE_VERSION='v32-vehicle-lookup-2.2'; let catalog=null,matches=[];
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function kbPanel(){return [...document.querySelectorAll('.panel')].find(p=>/VEHICLE\s*\/\s*ENGINE KNOWLEDGE BASE/i.test(p.textContent||''))||null}
function settingsHost(){return $('screen-settings')||document.querySelector('.screen[data-screen="settings"]')||document.querySelector('.screen:last-of-type')||null}
function injectUi(){if($('vehicleLookupPanel'))return true;const kb=kbPanel(),host=kb?.parentNode||settingsHost();if(!host)return false;const p=document.createElement('div');p.className='panel';p.id='vehicleLookupPanel';p.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">🔎</span> AJONEUVOTIEDON HAKU</div><span class="tiny">${MODULE_VERSION}</span></div><div class="form"><label class="full">Hae merkki / malli / versio<input id="vehicleLookupInput" value="Derbi Senda 50" placeholder="esim. Derbi Senda 50 tai Yamaha DT125R"></label><button id="vehicleLookupBtn" class="action full" type="button">HAE AJONEUVOTIEDOT</button></div><div id="vehicleLookupStatus" class="statusbox">Valitse tehdaslähtökohta. Profiili muuttuu vasta hyväksynnän jälkeen.</div><div id="vehicleLookupResults" class="runlist"></div>`;if(kb)host.insertBefore(p,kb);else host.appendChild(p);const g=document.createElement('div');g.className='panel';g.id='drivetrainEditor';g.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">⚙️</span> VÄLITYKSET</div><span class="tiny">muokattava</span></div><div class="form"><label>Primääri<input id="dtPrimary" type="number" step="0.001"></label><label>Eturatas<input id="dtFront" type="number" step="1"></label><label>Takaratas<input id="dtRear" type="number" step="1"></label><label>1. vaihde<input id="dtG1" type="number" step="0.001"></label><label>2. vaihde<input id="dtG2" type="number" step="0.001"></label><label>3. vaihde<input id="dtG3" type="number" step="0.001"></label><label>4. vaihde<input id="dtG4" type="number" step="0.001"></label><label>5. vaihde<input id="dtG5" type="number" step="0.001"></label><label>6. vaihde<input id="dtG6" type="number" step="0.001"></label><button id="dtSave" class="action full" type="button">TALLENNA VÄLITYKSET</button></div><div id="dtStatus" class="statusbox">Välitykset ovat profiilikohtaisia. Rataskoot voi vaihtaa koska tahansa.</div>`;if(kb)host.insertBefore(g,kb);else host.appendChild(g);$('vehicleLookupBtn').onclick=search;$('vehicleLookupInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search()}};$('dtSave').onclick=saveDrivetrain;loadDrivetrain();return true}
async function loadCatalog(){if(catalog)return catalog;const r=await fetch('./vehicle_catalog.json?v=32.3',{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);catalog=await r.json();return catalog}
function score(e,q){const hay=[e.make,e.model,e.variant,e.engineCode,...(e.aliases||[])].filter(Boolean).join(' ').toLowerCase();const ps=q.toLowerCase().trim().split(/\s+/).filter(Boolean);return ps.length?ps.filter(p=>hay.includes(p)).length/ps.length:0}
async function search(){const q=($('vehicleLookupInput')?.value||'').trim();if(!q)return; $('vehicleLookupStatus').textContent='Haetaan ajoneuvotietoja…';try{const db=await loadCatalog();matches=db.entries.map(e=>({e,s:score(e,q)})).filter(x=>x.s>=.5).sort((a,b)=>b.s-a.s).slice(0,10).map(x=>x.e);render(q)}catch(e){$('vehicleLookupStatus').textContent='Ajoneuvotietokannan lataus epäonnistui: '+e.message}}
function render(q){const box=$('vehicleLookupResults');if(!matches.length){box.innerHTML='';$('vehicleLookupStatus').textContent=`Ei osumaa haulle “${q}”.`;return}$('vehicleLookupStatus').textContent=`Löytyi ${matches.length} ehdotusta. Valitse oikea tehdaslähtökohta.`;box.innerHTML=matches.map(e=>{const en=e.engine||{},d=e.drivetrain||{},yr=e.yearFrom?(e.yearTo&&e.yearTo!==e.yearFrom?`${e.yearFrom}–${e.yearTo}`:`${e.yearFrom}`):'vuosimalli tarkistettava';const gears=(d.gearRatios||[]).map((x,i)=>`${i+1}:${x}`).join(' • ');return `<div class="runCard good"><h4>${esc(e.make)} ${esc(e.model)} ${esc(e.variant||'')}</h4><p>${esc(yr)} • ${esc(e.engineType||'–')} • ${en.displacementCc??'–'} cc • ${en.boreMm??'–'} × ${en.strokeMm??'–'} mm</p><p>${esc(e.engineCode||'')} ${en.carburetor?`• ${esc(en.carburetor)}`:''}</p><p>Primääri ${d.primaryRatio??'–'} • rattaat ${d.frontSprocket??'–'}/${d.rearSprocket??'–'} ${gears?'• '+gears:''}</p><button class="action" data-vehicle-id="${esc(e.id)}" style="margin-top:7px;width:100%">KÄYTÄ EHDOTUSTA</button></div>`}).join('');box.querySelectorAll('[data-vehicle-id]').forEach(b=>b.onclick=()=>apply(b.dataset.vehicleId))}
function apply(id){const e=matches.find(x=>x.id===id);if(!e||typeof getCurrentProfile!=='function'||typeof saveCurrentProfile!=='function')return;const cur=getCurrentProfile(),kb=JSON.parse(JSON.stringify(cur.knowledge||{}));kb.engine={...(kb.engine||{}),...(e.engine||{})};kb.drivetrain={...(kb.drivetrain||{}),...(e.drivetrain||{})};kb.vehicle={make:e.make,model:e.model,variant:e.variant||'',yearFrom:e.yearFrom||null,yearTo:e.yearTo||null,engineCode:e.engineCode||''};kb.reference={catalogVersion:catalog?.version||'',vehicleId:e.id,source:e.source||{}};if(e.chassis)kb.chassis={...(kb.chassis||{}),...e.chassis};if(e.fluids)kb.fluids={...(kb.fluids||{}),...e.fluids};const note=`Ajoneuvohaku: ${[e.make,e.model,e.variant].filter(Boolean).join(' ')} | ${e.notes||''}`;if(!String(kb.notes||'').includes(`Ajoneuvohaku: ${e.make} ${e.model}`))kb.notes=[kb.notes,note].filter(Boolean).join(' | ');saveCurrentProfile({name:[e.make,e.model,e.variant].filter(Boolean).join(' '),engineType:e.engineType||cur.engineType,knowledge:kb});if(typeof renderProfiles==='function')renderProfiles();loadDrivetrain();$('vehicleLookupStatus').textContent='Tehdaslähtökohta tallennettu. Tekniset tiedot päivitettiin. Muokkaa todelliset rattaat ja muut muutokset profiiliin.';window.dispatchEvent(new CustomEvent('motolab:vehicle-applied',{detail:{vehicleId:e.id,catalogVersion:catalog?.version||''}}));if(typeof addLearningEvent==='function')addLearningEvent('vehicle_lookup_applied',{vehicleId:e.id,catalogVersion:catalog?.version})}
function loadDrivetrain(){if(typeof getCurrentProfile!=='function')return;const d=getCurrentProfile()?.knowledge?.drivetrain||{};$('dtPrimary')&&($('dtPrimary').value=d.primaryRatio??'');$('dtFront')&&($('dtFront').value=d.frontSprocket??'');$('dtRear')&&($('dtRear').value=d.rearSprocket??'');const gs=d.gearRatios||[];for(let i=1;i<=6;i++)if($('dtG'+i))$('dtG'+i).value=gs[i-1]??''}
function saveDrivetrain(){if(typeof getCurrentProfile!=='function'||typeof saveCurrentProfile!=='function')return;const cur=getCurrentProfile(),kb=JSON.parse(JSON.stringify(cur.knowledge||{})),d={...(kb.drivetrain||{})};const n=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:null};d.primaryRatio=n('dtPrimary');d.frontSprocket=n('dtFront');d.rearSprocket=n('dtRear');d.finalRatio=d.frontSprocket&&d.rearSprocket?d.rearSprocket/d.frontSprocket:null;d.gearRatios=[1,2,3,4,5,6].map(i=>n('dtG'+i));kb.drivetrain=d;saveCurrentProfile({knowledge:kb});$('dtStatus').textContent=`Tallennettu: ${d.frontSprocket||'–'}/${d.rearSprocket||'–'} • loppuvälitys ${d.finalRatio?d.finalRatio.toFixed(3):'–'}`;if(typeof addLearningEvent==='function')addLearningEvent('drivetrain_changed',{primaryRatio:d.primaryRatio,front:d.frontSprocket,rear:d.rearSprocket,gearRatios:d.gearRatios})}
function boot(){if(injectUi())return;let tries=0;const timer=setInterval(()=>{tries++;if(injectUi()||tries>=20)clearInterval(timer)},250)} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
