(() => {
'use strict';
const MANIFEST='./vehicle_catalog_finland_v2_ready_manifest.json';
const cache=new Map();
async function json(url){if(cache.has(url))return cache.get(url);const p=fetch(url,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()});cache.set(url,p);return p}
function mergeDefined(target,source){for(const [k,v] of Object.entries(source||{})){if(v===undefined)continue;if(v&&typeof v==='object'&&!Array.isArray(v)&&target[k]&&typeof target[k]==='object'&&!Array.isArray(target[k]))mergeDefined(target[k],v);else target[k]=structuredClone(v)}return target}
function confOf(v,f){return String(v.gearboxOverrideConfidence||v.gearRatioConfidence||v.gearboxConfidence||f?.confidence||v.status||'pending')}
function policy(conf,ratios){const c=String(conf).toLowerCase();if(/probable|candidate|reference-only|partial/.test(c))return'weak-prior-only';if(/verified/.test(c)&&Array.isArray(ratios)&&ratios.length)return'strong-seed-yields-to-learned-data';return'no-ratio-seed'}
async function load(){
 const m=await json(MANIFEST);const b=structuredClone(await json('./'+m.base.replace(/^\.\//,'')));b.gearboxFamilies={...(b.gearboxFamilies||{})};b.vehicles=Array.isArray(b.vehicles)?b.vehicles:[];const byId=new Map(b.vehicles.map(v=>[v.id,v]));
 for(const file of m.overlayOrder){const d=await json('./'+file.replace(/^\.\//,''));for(const [key,def] of Object.entries(d.gearboxes||d.gearboxFamilies||{}))b.gearboxFamilies[key]=mergeDefined(b.gearboxFamilies[key]||{},def);for(const o of d.vehicleOverlays||[]){const v=byId.get(o.targetId);if(!v)continue;const p=structuredClone(o);delete p.targetId;mergeDefined(v,p)}}
 const entries=b.vehicles.map(v=>{const f=v.gearbox?b.gearboxFamilies[v.gearbox]:null;const ratios=Array.isArray(v.gearRatios)?v.gearRatios:(Array.isArray(f?.ratios)?f.ratios:[]);const primary=v.primaryRatio??f?.primaryRatio??null;const speeds=v.speeds??f?.speeds??ratios.length||null;const confidence=confOf(v,f);const engine={...(v.engine||{})};if(!engine.displacementCc){const m=String(v.class||'').match(/(50|125)/);if(m)engine.displacementCc=Number(m[1])}return {id:'fi-v2-'+v.id,make:v.make,model:v.model,variant:v.generation||'',aliases:[...(v.variants||[]),v.generation,v.class].filter(Boolean),yearFrom:v.yearFrom??null,yearTo:v.yearTo??null,engineType:engine.cycle||v.engineType||'',engineCode:engine.engineFamily||v.engineFamily||'',engine,drivetrain:{primaryRatio:primary,primaryTeeth:f?.primaryTeeth||v.primaryTeeth||null,gearRatios:ratios,gearRatioConfidence:confidence,gearboxSpeeds:speeds,overallTransmissionRatios:v.overallTransmissionRatios||null,finalRatio:v.finalRatio??null},confidence,verificationStatus:confidence,gearLearnPolicy:policy(confidence,ratios),source:{verified:/verified/i.test(confidence),type:'motolab_finland_catalog_v2',title:'MotoLab Finland vehicle catalog v2 staging'},notes:v.notes||(/probable|candidate|partial/i.test(confidence)?'Epävarma välitys on vain Gear Learn -ehdokas. GPS/RPM-opittu tieto on ensisijainen.':!ratios.length?'Sisäiset vaihdevälitykset tarkistuksessa.':'Sukupolvi-/mallikohtainen vaihteistoreferenssi.')}});
 return {schema:'motolab_vehicle_catalog_lookup_v2',version:'2026-08-16.fi-v2-staging',production:false,entries,gearboxFamilies:b.gearboxFamilies,policy:m.mergePolicy};
}
window.MotoLabFinlandVehicleCatalogV2={load};
})();
