globalThis.MOTOLAB_RELEASE={version:"34.9",label:"v34.9 BETA",build:"2026-09-05-0538-phone-bridge-v1"};
(() => {
 if(typeof document==='undefined')return;
 const BUILD=globalThis.MOTOLAB_RELEASE.build;
 const LABEL=globalThis.MOTOLAB_RELEASE.label;
 const VERSION=globalThis.MOTOLAB_RELEASE.version;
 document.documentElement.classList.add('ml-early-boot');
 const s=document.createElement('style');s.id='mlEarlyBootStyle';s.textContent=`html.ml-early-boot body>*{visibility:hidden}html.ml-early-boot #motolabBootSplash{visibility:visible!important}#motolabBootSplash{position:fixed;inset:0;z-index:1000000;background:#000;color:#fff;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;opacity:1;transition:opacity .45s ease}#motolabBootSplash.mls-out{opacity:0;pointer-events:none}#motolabBootImage{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;object-position:50% 50%;filter:none;background:#000;image-rendering:auto}.mls-version{position:absolute;top:calc(16px + env(safe-area-inset-top));right:14px;z-index:5;padding:7px 10px;border-radius:10px;border:1px solid #ff263f;background:rgba(3,3,4,.94);color:#fff;font-size:11px;font-weight:1000;letter-spacing:.02em;box-shadow:0 4px 18px #000}.mls-version b{color:#ff263f}#motolabBootStatus{position:absolute;left:50%;bottom:calc(14px + env(safe-area-inset-bottom));transform:translateX(-50%);z-index:5;max-width:88vw;padding:7px 11px;border-radius:9px;background:rgba(0,0,0,.74);font-size:9px;font-weight:900;letter-spacing:.12em;text-align:center;white-space:nowrap}.mls-boot-bottom{display:none}#motolabBootPanel{position:absolute;inset:calc(88px + env(safe-area-inset-top)) 12px calc(84px + env(safe-area-inset-bottom));z-index:6;display:flex;align-items:center;justify-content:center;pointer-events:none}#motolabBootPanel.mls-panel-on{pointer-events:auto}.mls-login{box-sizing:border-box;width:min(88vw,390px);max-height:66vh;overflow:auto;background:rgba(7,8,11,.94);border:1px solid #ff263f;border-radius:20px;padding:14px;box-shadow:0 24px 70px #000d;text-align:left}.mls-login-title{font-size:18px;font-weight:1000;font-style:italic}.mls-login-copy{margin:6px 0 9px;color:#c2c6cc;font-size:9px;line-height:1.38}.mls-login label{display:block;margin-top:6px;color:#aeb4bc;font-size:8px}.mls-login input{box-sizing:border-box;width:100%;margin-top:4px;padding:10px 11px;border-radius:10px;border:1px solid #42464d;background:#050609;color:#fff;font-size:15px}.mls-login button{width:100%;min-height:44px;margin-top:7px;border-radius:11px;color:#fff;font-weight:1000;font-size:14px}.mls-primary{border:1px solid #ff263f;background:#a80d20}.mls-secondary,.mls-ghost{border:1px solid #555;background:#15181d}.mls-msg{min-height:15px;margin-top:7px;font-size:8px;line-height:1.35;text-align:center}@media(max-height:720px){#motolabBootPanel{inset:calc(68px + env(safe-area-inset-top)) 10px calc(60px + env(safe-area-inset-bottom))}.mls-login{max-height:72vh;padding:12px}.mls-login-copy{display:none}.mls-login button{min-height:40px;margin-top:6px}.mls-login input{padding:9px 10px}}`;document.head.appendChild(s);
 function loadScript(src,key,done){if(document.querySelector(`script[data-${key}]`)){done?.();return}const x=document.createElement('script');x.src=src;x.dataset[key]='1';x.onload=()=>done?.();document.body.appendChild(x)}
 function ensureBootLogic(){
  const loadSplash=()=>{if(!globalThis.MotoLabSplash&&!document.querySelector('script[data-ml-splash-early]'))loadScript('./splash_boot.js?build='+encodeURIComponent(BUILD),'mlSplashEarly')};
  const loadPassword=()=>{if(!globalThis.MotoLabPassword&&!document.querySelector('script[data-ml-password-early]'))loadScript('./password_login.js?build='+encodeURIComponent(BUILD),'mlPasswordEarly',loadSplash);else loadSplash()};
  const loadGuard=()=>{if(!globalThis.MotoLabAuthSessionGuard&&!document.querySelector('script[data-ml-auth-guard-early]'))loadScript('./auth_session_guard.js?build='+encodeURIComponent(BUILD),'mlAuthGuardEarly',loadPassword);else loadPassword()};
  if(!globalThis.MotoLabUser&&!document.querySelector('script[data-ml-identity-early]'))loadScript('./user_identity.js?build='+encodeURIComponent(BUILD),'mlIdentityEarly',loadGuard);else loadGuard();
 }
 function applyReleaseLabels(){const badge=document.getElementById('appVersionBadge');if(badge)badge.textContent=LABEL;const full=document.getElementById('motolabFullVersion');if(full)full.textContent=`VÄNÄ MotorLab ${LABEL} • ${BUILD}`;document.title=`VÄNÄ MOTOLAB ${LABEL}`}
 function mount(){if(!document.getElementById('motolabBootSplash')){const d=document.createElement('div');d.id='motolabBootSplash';d.innerHTML=`<img id="motolabBootImage" src="./assets/motolab-start-v34.png?build=${encodeURIComponent(BUILD)}" alt="VäNä Motorsport MotorLab"><div class="mls-version"><b>${LABEL}</b></div><div id="motolabBootPanel"></div><div id="motolabBootStatus">LADATAAN MOTORLABIA…</div>`;document.body.prepend(d)}document.documentElement.classList.remove('ml-early-boot');applyReleaseLabels();ensureBootLogic();setTimeout(applyReleaseLabels,250);setTimeout(applyReleaseLabels,1500)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
