globalThis.MOTOLAB_RELEASE={version:"34.8",label:"v34.8 BETA",build:"2026-08-18c-final-ui-gear-auth"};
(() => {
 if(typeof document==='undefined')return;
 const BUILD=globalThis.MOTOLAB_RELEASE.build;
 document.documentElement.classList.add('ml-early-boot');
 const s=document.createElement('style');s.id='mlEarlyBootStyle';s.textContent=`html.ml-early-boot body>*{visibility:hidden}html.ml-early-boot #motolabBootSplash{visibility:visible!important}#motolabBootSplash{position:fixed;inset:0;z-index:1000000;background:#030304;color:#fff;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;opacity:1;transition:opacity .45s ease}#motolabBootSplash.mls-out{opacity:0;pointer-events:none}#motolabBootImage{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:50% 48%;filter:none}#motolabBootSplash:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 0%,rgba(0,0,0,.04) 50%,rgba(0,0,0,.58) 100%);z-index:1;pointer-events:none}.mls-boot-bottom{position:absolute;left:50%;bottom:calc(22px + env(safe-area-inset-bottom));transform:translateX(-50%);z-index:3;width:min(90vw,430px);text-align:center}.mls-boot-brand{font-size:12px;font-weight:1000;font-style:italic;text-shadow:0 2px 10px #000}.mls-boot-brand b{color:#ff263f}#motolabBootStatus{margin-top:7px;font-size:9px;font-weight:900;letter-spacing:.15em}.mls-loader{width:96px;height:3px;margin:11px auto 0;border-radius:99px;overflow:hidden;background:#ffffff22}.mls-loader:after{content:"";display:block;width:42%;height:100%;background:#ff263f;animation:mlEarlyLoad 1.05s ease-in-out infinite alternate}@keyframes mlEarlyLoad{from{transform:translateX(-10%)}to{transform:translateX(150%)}}#motolabBootPanel{position:absolute;inset:calc(72px + env(safe-area-inset-top)) 12px calc(72px + env(safe-area-inset-bottom));z-index:4;display:flex;align-items:center;justify-content:center;pointer-events:none}#motolabBootPanel.mls-panel-on{pointer-events:auto}.mls-login{width:min(90vw,430px);max-height:72vh;overflow:auto;background:rgba(7,8,11,.92);backdrop-filter:blur(17px);-webkit-backdrop-filter:blur(17px);border:1px solid #ff263f;border-radius:22px;padding:16px;box-shadow:0 24px 70px #000d;text-align:left}.mls-login-title{font-size:20px;font-weight:1000;font-style:italic}.mls-login-copy{margin:7px 0 11px;color:#c2c6cc;font-size:10px;line-height:1.45}.mls-login label{display:block;margin-top:8px;color:#aeb4bc;font-size:9px}.mls-login input{box-sizing:border-box;width:100%;margin-top:5px;padding:12px;border-radius:11px;border:1px solid #42464d;background:#050609;color:#fff;font-size:16px}.mls-login button{width:100%;min-height:52px;margin-top:9px;border-radius:12px;color:#fff;font-weight:1000}.mls-primary{border:1px solid #ff263f;background:#a80d20}.mls-secondary,.mls-ghost{border:1px solid #555;background:#15181d}.mls-msg{min-height:18px;margin-top:9px;font-size:9px;text-align:center}`;document.head.appendChild(s);
 function loadScript(src,key,done){if(document.querySelector(`script[data-${key}]`)){done?.();return}const x=document.createElement('script');x.src=src;x.dataset[key]='1';x.onload=()=>done?.();document.body.appendChild(x)}
 function ensureBootLogic(){const loadSplash=()=>{if(!globalThis.MotoLabSplash&&!document.querySelector('script[data-ml-splash-early]'))loadScript('./splash_boot.js?build='+encodeURIComponent(BUILD),'mlSplashEarly')};if(!navigator.serviceWorker?.controller&&!globalThis.MotoLabUser&&!document.querySelector('script[data-ml-identity-early]'))loadScript('./user_identity.js?build='+encodeURIComponent(BUILD),'mlIdentityEarly',loadSplash);else loadSplash()}
 function mount(){
  if(!document.getElementById('motolabBootSplash')){const d=document.createElement('div');d.id='motolabBootSplash';d.innerHTML=`<img id="motolabBootImage" src="./assets/motorlab_splash_approved.webp?build=${encodeURIComponent(BUILD)}" alt="VäNä Motorsport MotorLab"><div id="motolabBootPanel"></div><div class="mls-boot-bottom"><div class="mls-boot-brand">VÄNÄ <b>MotorLab</b></div><div id="motolabBootStatus">LADATAAN MOTORLABIA…</div><div class="mls-loader"></div></div>`;document.body.prepend(d)}
  document.documentElement.classList.remove('ml-early-boot');ensureBootLogic();
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
