const UUID={service:'f7b10001-6a4d-4b2a-9c41-7a3b84d2e001',measurement:'f7b10002-6a4d-4b2a-9c41-7a3b84d2e001',status:'f7b10003-6a4d-4b2a-9c41-7a3b84d2e001',config:'f7b10004-6a4d-4b2a-9c41-7a3b84d2e001'};
const $=id=>document.getElementById(id),dec=new TextDecoder();let values={rpm:0,confidence:0,hz:0,status:'disconnected',diag:{}},rows=[],recording=false,device;
function text(e){return dec.decode(e.target.value)}
function render(){const ref=+$('reference').value,err=ref&&values.rpm?100*(values.rpm-ref)/ref:null;$('rpm').textContent=values.rpm?values.rpm.toFixed(0):'–';$('confidence').textContent=values.confidence+'%';$('hz').textContent=values.hz.toFixed(2)+' Hz';$('error').textContent=err===null?'–':`${err.toFixed(2)}%`;$('state').textContent=values.status;$('state').className=values.status==='valid'?'ok':'bad';$('diag').textContent=JSON.stringify(values.diag,null,2);if(recording)rows.push({host_iso:new Date().toISOString(),host_ms:performance.timeOrigin+performance.now(),rpm:values.rpm,confidence:values.confidence,pulse_hz:values.hz,status:values.status,reference_rpm:ref||null,error_pct:err,...values.diag})}
function measurement(e){const d=e.target.value;if(d.byteLength!==24)throw Error(`measurement ${d.byteLength} bytes`);const flags=d.getUint16(2,true);values.rpm=d.getUint16(12,true);values.confidence=d.getUint8(14);values.hz=d.getFloat32(16,true);values.status=(flags&1)?'valid':(flags&8)?'dropout':'rejected';values.diag={version:d.getUint8(0),source:d.getUint8(1),flags,seq:d.getUint32(4,true),device_ms:d.getUint32(8,true),signal:d.getUint8(15),raw_candidate_rpm:d.getUint16(20,true),rejections:d.getUint16(22,true),learning_eligible:!!(flags&2)};render()}
async function subscribe(service,uuid,handler){const c=await service.getCharacteristic(uuid);await c.startNotifications();c.addEventListener('characteristicvaluechanged',handler)}
$('connect').onclick=async()=>{try{device=await navigator.bluetooth.requestDevice({filters:[{services:[UUID.service]}]});device.addEventListener('gattserverdisconnected',()=>{values.status='disconnected';render()});const g=await device.gatt.connect(),s=await g.getPrimaryService(UUID.service);await subscribe(s,UUID.measurement,measurement);await subscribe(s,UUID.status,e=>{try{values.diag.device_status=JSON.parse(text(e))}catch{}});$('record').disabled=false;$('state').textContent='Yhdistetty.'}catch(e){$('state').textContent='Yhdistäminen epäonnistui: '+e.message}}
$('record').onclick=()=>{recording=!recording;$('record').textContent=recording?'Lopeta tallennus':'Aloita tallennus';$('download').disabled=recording||!rows.length};
function save(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('download').onclick=()=>{const stamp=new Date().toISOString().replace(/[:.]/g,'-'),keys=[...new Set(rows.flatMap(Object.keys))],q=v=>`"${String(v??'').replaceAll('"','""')}"`;save(`rpm-bt-${stamp}.csv`,'text/csv',keys.join(',')+'\n'+rows.map(r=>keys.map(k=>q(r[k])).join(',')).join('\n'));save(`rpm-bt-${stamp}.jsonl`,'application/jsonl',rows.map(JSON.stringify).join('\n'))};
