'use strict';
const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');

const originalCreateServer=http.createServer.bind(http);
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const SECRET=String(process.env.BETA_TOKEN_SECRET||'');
const ORIGIN=process.env.ALLOWED_ORIGIN||'https://anttivanttinen-max.github.io';
const USERS_FILE=path.join(DATA_DIR,'users','registry.json');
const ISSUES_FILE=path.join(DATA_DIR,'community','issues.json');
const CONTACT_FILE=path.join(DATA_DIR,'community','contacts.json');
const PRIVATE_DIR=path.join(DATA_DIR,'community','private');
const MAX_BODY=Math.max(256000,Number(process.env.MOTOLAB_COMMUNITY_MAX_BODY_BYTES||2*1024*1024));

function readJson(f,d){try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return d}}
function atomic(f,x){fs.mkdirSync(path.dirname(f),{recursive:true});const t=f+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,f)}
function unb64(v){return Buffer.from(v,'base64url').toString('utf8')}
function verify(t){if(!SECRET||!t)return null;const [b,s]=String(t).split('.');if(!b||!s)return null;const e=crypto.createHmac('sha256',SECRET).update(b).digest('base64url'),a=Buffer.from(s),c=Buffer.from(e);if(a.length!==c.length||!crypto.timingSafeEqual(a,c))return null;try{const p=JSON.parse(unb64(b));if(p.exp&&Date.now()>p.exp)return null;return p}catch{return null}}
function users(){return readJson(USERS_FILE,{users:[]}).users||[]}
function auth(req){const p=verify(req.headers['x-motolab-beta-token']);if(!p)return null;const u=users().find(x=>x.userId===p.userId||(x.devices||[]).some(d=>d.deviceId===p.deviceId));if(!u)return null;return {payload:p,user:u}}
function requireActive(req,res,origin){const x=auth(req);if(!x){send(res,401,{ok:false,error:'Invalid device session'},origin);return null}if(x.user.status!=='active'){send(res,403,{ok:false,error:'User not approved'},origin);return null}return x}
function requireAdmin(req,res,origin){const x=requireActive(req,res,origin);if(!x)return null;if(x.user.role!=='admin'){send(res,403,{ok:false,error:'Admin required'},origin);return null}return x}
function send(res,status,obj,origin=''){const b=Buffer.from(JSON.stringify(obj));const h={'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'};if(origin===ORIGIN){h['Access-Control-Allow-Origin']=origin;h.Vary='Origin'}res.writeHead(status,h);res.end(b)}
function body(req,max=MAX_BODY){return new Promise((resolve,reject)=>{let n=0,a=[];req.on('data',c=>{n+=c.length;if(n>max){reject(Object.assign(new Error('Payload too large'),{status:413}));req.destroy();return}a.push(c)});req.on('end',()=>resolve(Buffer.concat(a)));req.on('error',reject)})}
async function jsonBody(req){return JSON.parse((await body(req)).toString('utf8'))}
function clean(v,n=4000){return String(v||'').replace(/[<>]/g,'').trim().slice(0,n)}
function id(p){return p+'_'+crypto.randomBytes(10).toString('hex')}
function db(){return readJson(ISSUES_FILE,{schema:'motolab_beta_community_v1',issues:[]})}
function save(x){x.updatedAt=new Date().toISOString();atomic(ISSUES_FILE,x)}
function publicComment(c){return {commentId:c.commentId,nickname:c.nickname,text:c.text,createdAt:c.createdAt,isSolution:!!c.isSolution}}
function publicIssue(i){return {issueId:i.issueId,title:i.title,description:i.description,category:i.category,status:i.status||'open',nickname:i.nickname,createdAt:i.createdAt,updatedAt:i.updatedAt||i.createdAt,sameCount:(i.sameUsers||[]).length,comments:(i.comments||[]).map(publicComment),solutionCommentId:i.solutionCommentId||null}}
function privateFile(issueId){return path.join(PRIVATE_DIR,clean(issueId,120)+'.json')}
function addPrivate(issueId,entry){const f=privateFile(issueId),x=readJson(f,{schema:'motolab_issue_private_diagnostics_v1',issueId,reports:[]});x.reports.push(entry);x.updatedAt=new Date().toISOString();atomic(f,x)}
function privateEntry(x,data,kind){return {reportId:id('diag'),kind,userId:x.user.userId,nickname:x.user.nickname||'MotoLab user',deviceId:x.payload.deviceId||'',createdAt:new Date().toISOString(),diagnostic:data?.diagnostic||null,client:data?.client||null}}

http.createServer=function(listener){return originalCreateServer(async(req,res)=>{const origin=String(req.headers.origin||'');let u;try{u=new URL(req.url,'http://localhost')}catch{return listener(req,res)};const p=u.pathname,community=p.startsWith('/api/community/')||p.startsWith('/api/admin/v1/community/')||p.startsWith('/api/users/v1/contact')||p.startsWith('/api/admin/v1/contacts');
 if(req.method==='OPTIONS'&&community&&origin===ORIGIN){res.writeHead(204,{'Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-MotoLab-Beta-Token','Access-Control-Max-Age':'86400'});return res.end()}
 if(req.method==='GET'&&p==='/api/community/v1/issues'){const x=requireActive(req,res,origin);if(!x)return;const items=(db().issues||[]).map(publicIssue).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));return send(res,200,{ok:true,issues:items},origin)}
 if(req.method==='GET'&&p==='/api/community/v1/issue'){const x=requireActive(req,res,origin);if(!x)return;const i=(db().issues||[]).find(z=>z.issueId===u.searchParams.get('id'));if(!i)return send(res,404,{ok:false,error:'Issue not found'},origin);return send(res,200,{ok:true,issue:publicIssue(i)},origin)}
 if(req.method==='POST'&&p==='/api/community/v1/issues'){const x=requireActive(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch(e){return send(res,e.status||400,{ok:false,error:'Invalid JSON'},origin)}const title=clean(d.title,120),description=clean(d.description,5000),category=clean(d.category||'Ongelma',40);if(!title||!description)return send(res,400,{ok:false,error:'Title and description required'},origin);const z=db(),now=new Date().toISOString(),i={issueId:id('issue'),title,description,category,status:'open',userId:x.user.userId,nickname:x.user.nickname||'MotoLab user',createdAt:now,updatedAt:now,sameUsers:[x.user.userId],comments:[]};z.issues.push(i);save(z);addPrivate(i.issueId,privateEntry(x,d,'created'));return send(res,201,{ok:true,issue:publicIssue(i)},origin)}
 if(req.method==='POST'&&p==='/api/community/v1/comments'){const x=requireActive(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const z=db(),i=z.issues.find(q=>q.issueId===d.issueId),text=clean(d.text,4000);if(!i)return send(res,404,{ok:false,error:'Issue not found'},origin);if(!text)return send(res,400,{ok:false,error:'Comment required'},origin);const c={commentId:id('com'),userId:x.user.userId,nickname:x.user.nickname||'MotoLab user',text,createdAt:new Date().toISOString(),isSolution:false};i.comments.push(c);i.updatedAt=c.createdAt;save(z);return send(res,201,{ok:true,comment:publicComment(c)},origin)}
 if(req.method==='POST'&&p==='/api/community/v1/same'){const x=requireActive(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch(e){return send(res,e.status||400,{ok:false,error:'Invalid JSON'},origin)}const z=db(),i=z.issues.find(q=>q.issueId===d.issueId);if(!i)return send(res,404,{ok:false,error:'Issue not found'},origin);i.sameUsers=i.sameUsers||[];if(!i.sameUsers.includes(x.user.userId))i.sameUsers.push(x.user.userId);i.updatedAt=new Date().toISOString();save(z);addPrivate(i.issueId,privateEntry(x,d,'same_problem'));return send(res,200,{ok:true,sameCount:i.sameUsers.length},origin)}
 if(req.method==='POST'&&p==='/api/admin/v1/community/status'){const x=requireAdmin(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const allowed=['open','working','resolved','fixed','not_reproduced'],z=db(),i=z.issues.find(q=>q.issueId===d.issueId);if(!i)return send(res,404,{ok:false,error:'Issue not found'},origin);if(!allowed.includes(d.status))return send(res,400,{ok:false,error:'Invalid status'},origin);i.status=d.status;i.updatedAt=new Date().toISOString();save(z);return send(res,200,{ok:true,issue:publicIssue(i)},origin)}
 if(req.method==='POST'&&p==='/api/admin/v1/community/solution'){const x=requireAdmin(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const z=db(),i=z.issues.find(q=>q.issueId===d.issueId);if(!i)return send(res,404,{ok:false,error:'Issue not found'},origin);const c=(i.comments||[]).find(q=>q.commentId===d.commentId);if(!c)return send(res,404,{ok:false,error:'Comment not found'},origin);for(const q of i.comments)q.isSolution=false;c.isSolution=true;i.solutionCommentId=c.commentId;i.status='resolved';i.updatedAt=new Date().toISOString();save(z);return send(res,200,{ok:true,issue:publicIssue(i)},origin)}
 if(req.method==='GET'&&p==='/api/admin/v1/community/diagnostics'){const x=requireAdmin(req,res,origin);if(!x)return;const issueId=clean(u.searchParams.get('issueId'),120);if(!issueId)return send(res,400,{ok:false,error:'issueId required'},origin);return send(res,200,{ok:true,item:readJson(privateFile(issueId),{schema:'motolab_issue_private_diagnostics_v1',issueId,reports:[]})},origin)}
 if(req.method==='GET'&&p==='/api/users/v1/contact'){const x=requireActive(req,res,origin);if(!x)return;const c=readJson(CONTACT_FILE,{schema:'motolab_private_contacts_v1',users:{}});return send(res,200,{ok:true,contact:c.users?.[x.user.userId]||null},origin)}
 if(req.method==='POST'&&p==='/api/users/v1/contact'){const x=requireActive(req,res,origin);if(!x)return;let d;try{d=await jsonBody(req)}catch{return send(res,400,{ok:false,error:'Invalid JSON'},origin)}const method=clean(d.method,30),value=clean(d.value,180),c=readJson(CONTACT_FILE,{schema:'motolab_private_contacts_v1',users:{}});c.users=c.users||{};c.users[x.user.userId]={method,value,updatedAt:new Date().toISOString()};atomic(CONTACT_FILE,c);return send(res,200,{ok:true},origin)}
 if(req.method==='GET'&&p==='/api/admin/v1/contacts'){const x=requireAdmin(req,res,origin);if(!x)return;const c=readJson(CONTACT_FILE,{users:{}}).users||{},list=users().map(v=>({userId:v.userId,nickname:v.nickname||'MotoLab user',contact:c[v.userId]||null}));return send(res,200,{ok:true,users:list},origin)}
 return listener(req,res)});};
console.log('MotoLab beta community server: enabled');
