param([string]$BaseDir="$env:USERPROFILE\Documents\MotoLab\ZeelCapture",[string]$SessionA='',[string]$SessionB='',[string]$Search='',[int]$TopNgrams=50)
$ErrorActionPreference='Stop'
function Dirs{Get-ChildItem$BaseDir -Directory -ErrorAction SilentlyContinue|Sort-Object Name}
function ResolveS([string]$s){if(-not$s){return$null};if(Test-Path$s){return(Resolve-Path$s).Path};$p=Join-Path$BaseDir$s;if(Test-Path$p){return(Resolve-Path$p).Path};$null}
function Raw([string]$d,[string]$n){$p=Join-Path$d$n;if(Test-Path$p){[IO.File]::ReadAllBytes($p)}else{[byte[]]@()}}
function Ngrams([byte[]]$b,[int]$n){$h=@{};if($b.Length-lt$n){return$h};for($i=0;$i-le$b.Length-$n;$i++){$k=([BitConverter]::ToString($b,$i,$n)).Replace('-',' ');if($h.ContainsKey($k)){$h[$k]++}else{$h[$k]=1}};$h}
function Diff([byte[]]$a,[byte[]]$b){$r=@();$m=[Math]::Max($a.Length,$b.Length);for($i=0;$i-lt$m;$i++){$x=if($i-lt$a.Length){$a[$i]}else{$null};$y=if($i-lt$b.Length){$b[$i]}else{$null};if($x-ne$y){$r+=[pscustomobject]@{Offset=$i;A=if($null-ne$x){'{0:X2}'-f$x}else{'--'};B=if($null-ne$y){'{0:X2}'-f$y}else{'--'}}}};$r}
New-Item -ItemType Directory -Force$BaseDir|Out-Null
if($Search){$q=$Search.ToUpperInvariant();foreach($d in Dirs){$f=Join-Path$d.FullName'events.jsonl';if(-not(Test-Path$f)){continue};$n=0;foreach($l in Get-Content$f){$n++;if($l.ToUpperInvariant().Contains($q)){[pscustomobject]@{Session=$d.Name;Line=$n;Text=$l}}}}|Format-Table -Wrap -AutoSize;exit}
$a=ResolveS$SessionA;$b=ResolveS$SessionB;if($a-and$b){$o=Join-Path$BaseDir("diff_"+(Split-Path$a -Leaf)+"__"+(Split-Path$b -Leaf));New-Item -ItemType Directory -Force$o|Out-Null;foreach($n in'zeel_to_pc.raw','pc_to_zeel.raw'){$ra=Raw$a$n;$rb=Raw$b$n;$df=Diff$ra$rb;$df|Export-Csv -NoTypeInformation -Encoding UTF8(Join-Path$o($n+'.diff.csv'));[ordered]@{file=$n;a_bytes=$ra.Length;b_bytes=$rb.Length;changed_offsets=$df.Count;first_changes=@($df|Select-Object -First200)}|ConvertTo-Json -Depth6|Set-Content -Encoding UTF8(Join-Path$o($n+'.summary.json'))};Write-Host"Diff valmis: $o";exit}
$idx=@();foreach($d in Dirs){try{$m=Get-Content(Join-Path$d.FullName'session.json')-Raw|ConvertFrom-Json;$sp=Join-Path$d.FullName'summary.json';$s=if(Test-Path$sp){Get-Content$sp -Raw|ConvertFrom-Json}else{$null};$idx+=[pscustomobject]@{Session=$d.Name;Created=$m.created_utc;Mode=$m.mode;Hardware=$m.hardware_port;Virtual=$m.virtual_port;Baud=$m.baud;RX=$s.bytes_zeel_to_pc;TX=$s.bytes_pc_to_zeel}}catch{}}
$idx|Export-Csv -NoTypeInformation -Encoding UTF8(Join-Path$BaseDir'capture_index.csv')
foreach($d in Dirs){$ad=Join-Path$d.FullName'analysis';New-Item -ItemType Directory -Force$ad|Out-Null;foreach($n in'zeel_to_pc.raw','pc_to_zeel.raw'){$r=Raw$d.FullName$n;$st=[ordered]@{file=$n;bytes=$r.Length;unique_bytes=@($r|Sort-Object -Unique).Count;histogram=@{};ngrams=@{}};foreach($x in$r){$k='{0:X2}'-f$x;if($st.histogram.Contains($k)){$st.histogram[$k]++}else{$st.histogram[$k]=1}};foreach($z in2..8){$h=Ngrams$r$z;$st.ngrams["n$z"]=@($h.GetEnumerator()|Sort-Object Value -Descending|Select-Object -First$TopNgrams|%{[ordered]@{hex=$_.Key;count=$_.Value}})};$st|ConvertTo-Json -Depth8|Set-Content -Encoding UTF8(Join-Path$ad($n+'.analysis.json'))}}
Write-Host"Indeksi, tavuhistogrammit ja n-gram-analyysit päivitetty: $BaseDir"