param([string]$BaseDir="$env:USERPROFILE\Documents\MotoLab\ZeelCapture")
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$ErrorActionPreference='Stop'
$script:Version='1.0.0-readonly-first';$script:Capture=$null;$script:SessionDir=$null;$script:EventsWriter=$null;$script:CsvWriter=$null;$script:RawRx=$null;$script:RawTx=$null;$script:BytesRx=0L;$script:BytesTx=0L;$script:PacketsRx=0L;$script:PacketsTx=0L;$script:StartUtc=$null
New-Item -ItemType Directory -Force -Path $BaseDir|Out-Null
function NowUs{return [int64]([DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()*1000)}
function PortInventory{$r=@();try{$p=Get-PnpDevice -Class Ports -PresentOnly;foreach($d in$p){$n=[string]$d.FriendlyName;if($n-match'\((COM\d+)\)'){$c=$Matches[1]}else{continue};$i=[string]$d.InstanceId;$k='other';if($i-match'VID_0403&PID_6001'){$k='zeel-ftdi'}elseif($n-match'CH343|Enhanced-SERIAL'){$k='esp32-debug'}elseif($n-match'Virtual|com0com|CNCA|CNCB'){$k='virtual'};$r+=[pscustomobject]@{Port=$c;Name=$n;Id=$i;Kind=$k}}}catch{foreach($c in[IO.Ports.SerialPort]::GetPortNames()){$r+=[pscustomobject]@{Port=$c;Name=$c;Id='';Kind='unknown'}}};$r|Sort-Object{[int]($_.Port-replace'\D','')}}
function Log([string]$s){if($script:LogBox){$script:LogBox.AppendText("[$((Get-Date).ToString('HH:mm:ss.fff'))] $s`r`n");$script:LogBox.SelectionStart=$script:LogBox.TextLength;$script:LogBox.ScrollToCaret()}}
function Event([string]$dir,[byte[]]$data,[string]$note=''){if(-not$script:EventsWriter){return};$o=[ordered]@{ts_us=NowUs;utc=[DateTimeOffset]::UtcNow.ToString('o');direction=$dir;length=if($data){$data.Length}else{0};hex=if($data){([BitConverter]::ToString($data)).Replace('-',' ')}else{''};ascii=if($data){-join($data|%{if($_-ge32-and$_-le126){[char]$_}else{'.'}})}else{''};note=$note};$script:EventsWriter.WriteLine(($o|ConvertTo-Json -Compress));$script:EventsWriter.Flush();$script:CsvWriter.WriteLine(('"{0}","{1}","{2}",{3},"{4}","{5}","{6}"'-f$o.ts_us,$o.utc,$o.direction,$o.length,($o.hex-replace'"','""'),($o.ascii-replace'"','""'),($o.note-replace'"','""')));$script:CsvWriter.Flush()}
function NewSession([string]$mode,[string]$hw,[int]$baud,[string]$virt=''){$script:SessionDir=Join-Path$BaseDir(Get-Date -Format'yyyy-MM-dd_HH-mm-ss');New-Item -ItemType Directory -Force$script:SessionDir|Out-Null;$script:StartUtc=[DateTimeOffset]::UtcNow;$script:BytesRx=0;$script:BytesTx=0;$script:PacketsRx=0;$script:PacketsTx=0;$m=[ordered]@{schema='motolab_zeel_capture_v1';app_version=$script:Version;created_utc=$script:StartUtc.ToString('o');mode=$mode;hardware_port=$hw;virtual_port=$virt;baud=$baud;device=[ordered]@{vendor='FTDI';vid='0403';pid='6001';expected='Zeeltronic PC-USB'};safety=[ordered]@{generated_writes=$false;raw_preserved=$true}};$m|ConvertTo-Json -Depth6|Set-Content -Encoding UTF8(Join-Path$script:SessionDir'session.json');$script:EventsWriter=[IO.StreamWriter]::new((Join-Path$script:SessionDir'events.jsonl'),$false,[Text.UTF8Encoding]::new($false));$script:CsvWriter=[IO.StreamWriter]::new((Join-Path$script:SessionDir'timeline.csv'),$false,[Text.UTF8Encoding]::new($false));$script:CsvWriter.WriteLine('ts_us,utc,direction,length,hex,ascii,note');$script:RawRx=[IO.File]::Open((Join-Path$script:SessionDir'zeel_to_pc.raw'),[IO.FileMode]::Create,[IO.FileAccess]::Write,[IO.FileShare]::Read);$script:RawTx=[IO.File]::Open((Join-Path$script:SessionDir'pc_to_zeel.raw'),[IO.FileMode]::Create,[IO.FileAccess]::Write,[IO.FileShare]::Read);Event'META'([byte[]]@())"start $mode hw=$hw virt=$virt baud=$baud";Log"Sessio: $script:SessionDir"}
function CloseSession{try{if($script:Capture){$script:Capture.Dispose();$script:Capture=$null}}catch{};foreach($n in'RawRx','RawTx','EventsWriter','CsvWriter'){try{$v=Get-Variable -Name$n -Scope Script -ValueOnly -ErrorAction SilentlyContinue;if($v){$v.Flush();$v.Dispose();Set-Variable -Name$n -Scope Script -Value$null}}catch{}};if($script:SessionDir){[ordered]@{ended_utc=[DateTimeOffset]::UtcNow.ToString('o');duration_s=([DateTimeOffset]::UtcNow-$script:StartUtc).TotalSeconds;bytes_zeel_to_pc=$script:BytesRx;bytes_pc_to_zeel=$script:BytesTx;packets_zeel_to_pc=$script:PacketsRx;packets_pc_to_zeel=$script:PacketsTx}|ConvertTo-Json|Set-Content -Encoding UTF8(Join-Path$script:SessionDir'summary.json');$script:SessionDir=$null}}
class EP:System.IDisposable{[IO.Ports.SerialPort]$P;EP([string]$n,[int]$b){$this.P=[IO.Ports.SerialPort]::new($n,$b,[IO.Ports.Parity]::None,8,[IO.Ports.StopBits]::One);$this.P.ReadTimeout=50;$this.P.WriteTimeout=1000;$this.P.DtrEnable=$false;$this.P.RtsEnable=$false;$this.P.Open()}[byte[]]R(){$n=$this.P.BytesToRead;if($n-le0){return[byte[]]@()};$b=New-Object byte[]$n;$r=$this.P.Read($b,0,$n);if($r-le0){return[byte[]]@()};if($r-eq$n){return$b};return[byte[]]$b[0..($r-1)]}[void]W([byte[]]$b){if($b-and$b.Length){$this.P.Write($b,0,$b.Length)}}[void]Dispose(){try{if($this.P.IsOpen){$this.P.Close()}}catch{};try{$this.P.Dispose()}catch{}}}
class Pair:System.IDisposable{[EP]$H;[EP]$V;[bool]$Proxy;Pair([string]$h,[int]$b,[string]$v){$this.H=[EP]::new($h,$b);if($v){$this.V=[EP]::new($v,$b);$this.Proxy=$true}}[void]Dispose(){if($this.H){$this.H.Dispose()};if($this.V){$this.V.Dispose()}}}
function Poll{if(-not$script:Capture){return};try{$r=$script:Capture.H.R();if($r.Length){$script:RawRx.Write($r,0,$r.Length);$script:RawRx.Flush();Event'ZEEL->PC'$r;$script:BytesRx+=$r.Length;$script:PacketsRx++;if($script:Capture.Proxy){$script:Capture.V.W($r)}};if($script:Capture.Proxy){$t=$script:Capture.V.R();if($t.Length){$script:RawTx.Write($t,0,$t.Length);$script:RawTx.Flush();Event'PC->ZEEL'$t'ZeelProg passthrough';$script:BytesTx+=$t.Length;$script:PacketsTx++;$script:Capture.H.W($t)}};$script:Status.Text="RX $script:BytesRx B / $script:PacketsRx pkt   TX $script:BytesTx B / $script:PacketsTx pkt"}catch{Log"ERROR $($_.Exception.Message)";Event'ERROR'([byte[]]@())$_.Exception.Message}}
function Selected($c){if($c.SelectedItem-and([string]$c.SelectedItem)-match'^(COM\d+)'){return$Matches[1]};''}
function RefreshPorts{$i=@(PortInventory);$script:HW.Items.Clear();$script:VV.Items.Clear();foreach($p in$i){[void]$script:HW.Items.Add("$($p.Port) | $($p.Kind) | $($p.Name)");if($p.Kind-eq'virtual'){[void]$script:VV.Items.Add("$($p.Port) | $($p.Name)")}};$z=$i|? Kind-eq'zeel-ftdi'|select -First1;if($z){for($x=0;$x-lt$script:HW.Items.Count;$x++){if([string]$script:HW.Items[$x]-like"$($z.Port) *"){$script:HW.SelectedIndex=$x;break}};Log"Zeeltronic: $($z.Port), FTDI 0403:6001"}else{Log'Zeeltronic FTDI ei löytynyt'};$e=$i|? Kind-eq'esp32-debug'|select -First1;if($e){Log"ESP32 Single Serial: $($e.Port)"};if(-not$script:VV.Items.Count){[void]$script:VV.Items.Add('(ei virtuaali-COM-paria)')};if($script:HW.Items.Count-and$script:HW.SelectedIndex-lt0){$script:HW.SelectedIndex=0};$script:VV.SelectedIndex=0}
function StartDirect{if($script:Capture){return};$h=Selected$script:HW;if(-not$h){return};$b=[int]$script:Baud.SelectedItem;try{NewSession'direct-read-only'$h$b;$script:Capture=[Pair]::new($h,$b,'');Log"READ-ONLY $h @ $b"}catch{Log$_.Exception.Message;CloseSession}}
function StartProxy{if($script:Capture){return};$h=Selected$script:HW;$v=Selected$script:VV;if(-not$h-or-not$v){[Windows.Forms.MessageBox]::Show('Proxy vaatii valmiin virtuaali-COM-parin.');return};$b=[int]$script:Baud.SelectedItem;if([Windows.Forms.MessageBox]::Show('Proxy välittää ZeelProgin aidot komennot CDI:lle ja tallentaa molemmat suunnat. Sovellus ei generoi omia komentoja. Jatketaanko?','MotoLab',[Windows.Forms.MessageBoxButtons]::YesNo)-ne[Windows.Forms.DialogResult]::Yes){return};try{NewSession'transparent-proxy'$h$b$v;$script:Capture=[Pair]::new($h,$b,$v);Log"PROXY Capture=$v Hardware=$h. ZeelProg käyttää virtuaaliparin TOISTA päätä."}catch{Log$_.Exception.Message;CloseSession}}
function SearchAll([string]$q){$script:SearchOut.Clear();if([string]::IsNullOrWhiteSpace($q)){return};$q=$q.ToUpperInvariant();foreach($d in Get-ChildItem$BaseDir -Directory -ErrorAction SilentlyContinue){$f=Join-Path$d.FullName'events.jsonl';if(-not(Test-Path$f)){continue};$n=0;foreach($l in Get-Content$f){$n++;if($l.ToUpperInvariant().Contains($q)){$script:SearchOut.AppendText("$($d.Name):$n`r`n$l`r`n`r`n")}}}}
function Index{& powershell.exe -NoProfile -ExecutionPolicy Bypass -File(Join-Path$PSScriptRoot'Analyze-ZeelCapture.ps1')-BaseDir$BaseDir;Log'Analyysi ja indeksi päivitetty'}
$f=New-Object Windows.Forms.Form;$f.Text="MotoLab Zeel Capture $script:Version";$f.Size=New-Object Drawing.Size(1040,720);$f.StartPosition='CenterScreen';$f.BackColor=[Drawing.Color]::FromArgb(18,18,20);$f.ForeColor=[Drawing.Color]::White
$p=New-Object Windows.Forms.Panel;$p.Dock='Top';$p.Height=145;$f.Controls.Add($p);$l=New-Object Windows.Forms.Label;$l.Text='VäNä MotoLab • ZEEL CAPTURE';$l.Font=New-Object Drawing.Font('Segoe UI',16,[Drawing.FontStyle]::Bold);$l.AutoSize=$true;$l.Location=New-Object Drawing.Point(15,12);$p.Controls.Add($l)
$script:HW=New-Object Windows.Forms.ComboBox;$script:HW.Location=New-Object Drawing.Point(15,52);$script:HW.Width=430;$script:HW.DropDownStyle='DropDownList';$p.Controls.Add($script:HW);$script:VV=New-Object Windows.Forms.ComboBox;$script:VV.Location=New-Object Drawing.Point(455,52);$script:VV.Width=320;$script:VV.DropDownStyle='DropDownList';$p.Controls.Add($script:VV);$script:Baud=New-Object Windows.Forms.ComboBox;$script:Baud.Location=New-Object Drawing.Point(785,52);$script:Baud.Width=105;$script:Baud.DropDownStyle='DropDownList';foreach($b in9600,19200,38400,57600,115200,230400,460800,921600){[void]$script:Baud.Items.Add($b)};$script:Baud.SelectedItem=115200;$p.Controls.Add($script:Baud)
$buttons=@(@('TUNNISTA',15,120,{RefreshPorts}),@('READ-ONLY',145,120,{StartDirect}),@('ZEELPROG PROXY',275,150,{StartProxy}),@('STOP',435,80,{CloseSession;$script:Status.Text='Pysäytetty'}),@('AVAA DATA',525,100,{Start-Process explorer.exe$BaseDir}),@('ANALYSOI',635,100,{Index}));foreach($q in$buttons){$b=New-Object Windows.Forms.Button;$b.Text=$q[0];$b.Location=New-Object Drawing.Point($q[1],88);$b.Width=$q[2];$b.Add_Click($q[3]);$p.Controls.Add($b)}
$t=New-Object Windows.Forms.TabControl;$t.Dock='Fill';$f.Controls.Add($t);$a=New-Object Windows.Forms.TabPage;$a.Text='LIVE';$t.TabPages.Add($a);$script:LogBox=New-Object Windows.Forms.TextBox;$script:LogBox.Multiline=$true;$script:LogBox.ReadOnly=$true;$script:LogBox.Dock='Fill';$script:LogBox.ScrollBars='Vertical';$script:LogBox.BackColor=[Drawing.Color]::Black;$script:LogBox.ForeColor=[Drawing.Color]::LightGreen;$script:LogBox.Font=New-Object Drawing.Font('Consolas',10);$a.Controls.Add($script:LogBox);$script:Status=New-Object Windows.Forms.Label;$script:Status.Dock='Bottom';$script:Status.Height=26;$script:Status.Text='Valmis';$a.Controls.Add($script:Status)
$s=New-Object Windows.Forms.TabPage;$s.Text='HAKU';$t.TabPages.Add($s);$sp=New-Object Windows.Forms.Panel;$sp.Dock='Top';$sp.Height=45;$s.Controls.Add($sp);$si=New-Object Windows.Forms.TextBox;$si.Location=New-Object Drawing.Point(10,10);$si.Width=700;$sp.Controls.Add($si);$sb=New-Object Windows.Forms.Button;$sb.Text='HAE HEX / ASCII / META';$sb.Location=New-Object Drawing.Point(720,8);$sb.Width=170;$sb.Add_Click({SearchAll$si.Text});$sp.Controls.Add($sb);$script:SearchOut=New-Object Windows.Forms.TextBox;$script:SearchOut.Multiline=$true;$script:SearchOut.ReadOnly=$true;$script:SearchOut.Dock='Fill';$script:SearchOut.ScrollBars='Both';$script:SearchOut.Font=New-Object Drawing.Font('Consolas',9);$s.Controls.Add($script:SearchOut);$script:SearchOut.BringToFront()
$i=New-Object Windows.Forms.TabPage;$i.Text='TURVA / OHJE';$t.TabPages.Add($i);$ib=New-Object Windows.Forms.TextBox;$ib.Multiline=$true;$ib.ReadOnly=$true;$ib.Dock='Fill';$ib.Text="READ-ONLY ei generoi CDI-kirjoituksia.`r`nPROXY välittää vain ZeelProgin aidon liikenteen.`r`nRAW säilytetään muuttamattomana.`r`nTunnettu adapteri: FTDI VID 0403 PID 6001.`r`n`r`nProxy vaatii erillisen virtuaali-COM kernel-ajurin. Sitä ei asenneta huomaamatta.";$i.Controls.Add($ib)
$tm=New-Object Windows.Forms.Timer;$tm.Interval=20;$tm.Add_Tick({Poll});$tm.Start();$f.Add_FormClosing({$tm.Stop();CloseSession});RefreshPorts;Log"MotoLab Zeel Capture $script:Version";[void]$f.ShowDialog()