(() => {
'use strict';
const VERSION='motorlab-beta-release-v4-nonblocking',CONSENT_KEY='motolab_v32_beta_consent',DEV_KEY='motolab_v32_dev_unlocked',LEARNING_KEY='motolab_v29_learning_enabled',RAW_CFG_KEY='motolab_v32_raw_sync_cfg',TOKEN_KEY='motolab_v32_beta_token';
const SERVER='https://v-n-autodyno-production.up.railway.app';const $=id=>document.getElementById(id);const nativeFetch=window.fetch.bind(window);
function token(){return localStorage.getItem(TOKEN_KEY)||''}function consent(){try{return JSON.parse(localStorage.getItem(CONSENT_KEY)||'null')}catch{return null}}function forceLearningOn(){localStorage.setItem(LEARNING_KEY,'1');try{if(typeof learningEnabled!=='undefined')learningEnabled=true}catch{}}
function patchFetch(){if(window.fetch.__motolabBetaPatched)return;const wrapped=async(input,init={})=>{try{const u=new URL(typeof input==='string'?input:input.url,location.href),t=token();if(t&&u.href.startsWith(SERVER+'/')){const h=new Headers(init.headers||(typeof input!=='string'?input.headers:undefined)||{});h.set('X-MotoLab-Beta-Token',t);init={...init,headers:h}}}catch{}return nativeFetch(input,init)};wrapped.__motolabBetaPatched=true;window.fetch=wrapped}
function configureRaw(){if(!token()||!consent()?.accepted)return;try{const old=JSON.parse(localStorage.getItem(RAW_CFG_KEY)||'{}');localStorage.setItem(RAW_CFG_KEY,JSON.stringify({...old,enabled:true,endpoint:SERVER,ingestKey:old.ingestKey||'BETA_TOKEN_AUTH'}))}catch{}}
function applyMode(){const dev=localStorage.getItem(DEV_KEY)==='1';document.body.classList.toggle('dev-mode',dev);document.body.classList.toggle('beta-user-mode',!dev);forceLearningOn();configureRaw()}
function styles(){if($('mlBetaConsentStyle'))return;const s=document.createElement('style');s.id='mlBetaConsentStyle';s.textContent=`.mlbc-overlay{position:fixed;inset:0;z-index:294000;background:#000e;display:flex;align-items:flex-end;justify-content:center;padding:10px;color:#fff}.mlbc-card{width:min(100%,470px);background:#0a0c0f;border:1px solid #ff263f;border-radius:22px;padding:16px;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mlbc-card h2{margin:5px 0}.mlbc-card p{font-size:10px;line-height:1.5;color:#b9bec6}.mlbc-card button{width:100%;margin-top:8px;padding:11px;border-radius:11px;border:1px solid #ff263f;background:#a80d20;color:#fff;font-weight:900}.mlbc-card button.gray{background:#111318;border-color:#42464e}`;document.head.appendChild(s)}
function openConsent(){styles();document.querySelector('.mlbc-overlay')?.remove();const o=document.createElement('div');o.className='mlbc-overlay';o.innerHTML=`<div class="mlbc-card"><b>VäNä <span style="color:#ff263f">MotorLab BETA</span></b><h2>Testikäytön luvat</h2><p>GPS:ää käytetään nopeuteen, dynolaskentaan ja Gear Learniin. Mikrofonia käytetään moottorin taajuuksien ja harmonisten oppimiseen. GPS MASTER säilyy RPM:n ohjaavana lähteenä.</p><p>Tekninen RAW- ja oppimisdata voidaan synkronoida kehityspalvelimelle käyttäjätilin yhteydessä. Mikrofonia ei käynnistetä tästä ikkunasta; iOS-lupa pyydetään vasta kun painat MIC-painiketta.</p><button id="mlbcAccept">HYVÄKSY</button><button class="gray" id="mlbcClose">SULJE</button></div>`;document.body.appendChild(o);$('mlbcClose').onclick=()=>o.remove();$('mlbcAccept').onclick=()=>{localStorage.setItem(CONSENT_KEY,JSON.stringify({accepted:true,at:new Date().toISOString(),version:VERSION,learning:true,rawTechnicalData:true,microphoneFeatures:true}));forceLearningOn();configureRaw();o.remove();document.dispatchEvent(new CustomEvent('motolab-beta-consent-ready'))}}
function boot(){patchFetch();styles();forceLearningOn();applyMode();document.addEventListener('motorlab-user-ready',()=>{patchFetch();configureRaw()});setInterval(()=>{forceLearningOn();configureRaw()},10000)}
globalThis.MotoLabBeta={version:VERSION,openConsent,forceLearningOn,get accepted(){return !!consent()?.accepted},get devOn(){return localStorage.getItem(DEV_KEY)==='1'}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
