(() => {
'use strict';
const MODULE='motolab-live-status-v1';
const $l=id=>document.getElementById(id);
let timer=null;

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n.toFixed(d):'–'}
function pct(v){const n=Number(v);return Number.isFinite(n)?Math.round(n*100)+'%':'–'}
function boolState(ok,onText='OK',offText='OFF'){return `<span class="liveState ${ok?'ok':'bad'}">${ok?onText:offText}</span>`}
function row(k,v){return `<div class="liveRow"><span>${esc(k)}</span><b>${v==null?'–':v}</b></div>`}
function safeJson(key,fallback=null){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function diag(){return globalThis.MOTOLAB_DIAGNOSTICS||null}
function queues(){try{return diag()?.getQueueSummary?.()||{}}catch{return {}}}
function sensors(){try{return diag()?.getSensorSnapshot?.()||{}}catch{return {}}}
function ui(){try{return typeof lastUi!=='undefined'&&lastUi?lastUi:{}}catch{return {}}}
function audio(){try{const s=typeof audioSessions!=='undefined'?audioSessions?.ext:null;const t=s?.track||s?.stream?.getAudioTracks?.()[0]||null;return {session:s,track:t,live:!!(t&&t.readyState==='live'&&t.enabled!==false&&(!s?.stream||s.stream.active!==false))}}catch{return {session:null,track:null,live:false}}}
function gpsActive(){try{return typeof gpsOn!=='undefined'&&!!gpsOn}catch{return !!sensors()?.active?.gps}}
function imuActive(){try{return typeof imuOn!=='undefined'&&!!imuOn}catch{return !!sensors()?.active?.imu}}
function micWanted(){const p=safeJson('motolab_v32_sensor_prefs',{});return !!p?.mic}
function rawQueue(){return safeJson('motolab_v32_raw_sync_queue',{pending:[],sent:0,lastOk:null,lastError:null})||{pending:[],sent:0,lastOk:null,lastError:null}}
function fmtTime(t){if(!t)return '–';try{return new Date(t).toLocaleTimeString('fi-FI')}catch{return '–'}}
function eventRows(){let ev=[];try{ev=diag()?.getEvents?.()||[]}catch{}return ev.slice(-30).reverse().map(e=>`<div class="liveEvent ${e.severity==='error'?'err':e.severity==='warn'?'warn':''}"><b>${esc(e.type)}</b><span>${fmtTime(e.t)} • ${esc(e.severity||'info')}</span></div>`).join('')||'<div class="liveEmpty">Ei diagnostiikkatapahtumia.</div>'}
function queueRows(){const q=queues(),keys=Object.keys(q);if(!keys.length)return '<div class="liveEmpty">Ei tunnettuja tapahtumajonoja.</div>';return keys.map(k=>{const x=q[k]||{};const count=x.pending??x.length??0;return `<div class="liveQueue"><b>${esc(k)}</b><span>jonossa ${esc(count)}${x.lastError?' • virhe: '+esc(x.lastError):''}</span></div>`}).join('')}
function setHtml(id,html){const e=$l(id);if(e)e.innerHTML=html}
function setText(id,text){const e=$l(id);if(e)e.textContent=text}
function statusDot(id,ok,warn=false){const e=$l(id);if(!e)return;e.classList.toggle('ok',!!ok&&!warn);e.classList.toggle('warn',!!warn);e.classList.toggle('bad',!ok&&!warn)}

function render(){
 if(!$l('screen-live')||!$l('screen-live').classList.contains('active'))return;
 const d=ui(),a=audio(),rq=rawQueue(),q=queues(),ss=sensors();
 const gps=gpsActive(),imu=imuActive(),mic=a.live;
 const rawPending=Array.isArray(rq.pending)?rq.pending.length:0;
 const syncWarn=!!rq.lastError;
 statusDot('liveSumGps',gps);statusDot('liveSumMic',mic,micWanted()&&!mic);statusDot('liveSumImu',imu);statusDot('liveSumRaw',true,rawPending>0);statusDot('liveSumSync',!syncWarn,syncWarn);
 setText('liveSumGpsTxt',gps?'OK':'OFF');setText('liveSumMicTxt',mic?'OK':(micWanted()?'WAIT':'OFF'));setText('liveSumImuTxt',imu?'OK':'OFF');setText('liveSumRawTxt',rawPending?`${rawPending} QUEUED`:'OK');setText('liveSumSyncTxt',syncWarn?'ERROR':'OK');

 setHtml('liveGpsBody',row('Status',boolState(gps,'ACTIVE','OFF'))+row('Speed',`${num(d.kmh,1)} km/h`)+row('GPS RPM',d.speedRpm?`${Math.round(d.speedRpm)} rpm`:'–')+row('RPM authority',esc(globalThis.MOTOLAB_RPM_CONTROL_AUTHORITY||'GPS MASTER / current mode'))+row('Online',boolState(navigator.onLine,'YES','NO')));
 setHtml('liveMicBody',row('Wanted',boolState(micWanted(),'ON','OFF'))+row('Track',a.track?esc(a.track.readyState):'none')+row('Enabled',a.track?boolState(a.track.enabled!==false,'YES','NO'):'–')+row('Muted',a.track?boolState(!a.track.muted,'NO','YES'):'–')+row('Device',esc(a.track?.label||a.session?.chosen?.label||'–'))+row('Audio RPM',d.audioRpm?`${Math.round(d.audioRpm)} rpm`:'–')+row('Raw RPM',d.audioRawRpm?`${Math.round(d.audioRawRpm)} rpm`:'–')+row('Confidence',pct(d.audioConf))+row('f0',d.audioObservedF0?`${num(d.audioObservedF0,1)} Hz`:'–')+row('Candidate gap',pct(d.audioCandidateGap))+row('Runner-up',d.audioRunnerRpm?`${Math.round(d.audioRunnerRpm)} rpm`:'–'));
 setHtml('liveImuBody',row('Status',boolState(imu,'ACTIVE','OFF'))+row('Acceleration',d.g!=null?`${num(d.g,3)} g`:'–')+row('Diagnostic active',boolState(!!ss?.active?.imu,'YES','NO')));
 setHtml('liveGearBody',row('Detected gear',d.gear??'–')+row('Gear confidence',pct(d.gearConf))+row('Speed RPM',d.speedRpm?`${Math.round(d.speedRpm)} rpm`:'–')+row('Fusion mode',esc(d.fusionMode||'–'))+row('Slip',boolState(!d.slip,'NO','YES'))+row('Agreement',d.agreement!=null?pct(1-Number(d.agreement)):'–'));
 setHtml('liveDynoBody',row('Displayed RPM',d.rpm?`${Math.round(d.rpm)} rpm`:'–')+row('Power',d.hp!=null?`${num(d.hp,2)} hp`:'–')+row('Torque',d.nm!=null?`${num(d.nm,2)} Nm`:'–')+row('Quality',d.quality!=null?`${Math.round(d.quality)}/100`:'–')+row('Source',esc(d.source||'–'))+row('ARM state',esc($l('armState')?.textContent||'–'))+row('Manual state',esc($l('manualState')?.textContent||'–'))+row('Measure status',esc($l('measureStatus')?.textContent||'–')));
 let learnSamples='–',learnChunks='–',learnOn='–';try{learnSamples=typeof learningSampleCount!=='undefined'?learningSampleCount:'–';learnChunks=typeof learningChunkCount!=='undefined'?learningChunkCount:'–';learnOn=typeof learningEnabled!=='undefined'?learningEnabled:false}catch{}
 setHtml('liveRawBody',row('Learning data',boolState(!!learnOn,'ON','OFF'))+row('Session samples',esc(learnSamples))+row('Stored chunks',esc(learnChunks))+row('RAW sync queued',String(rawPending))+row('RAW sync sent',String(rq.sent||0))+row('Last sync',rq.lastOk?fmtTime(rq.lastOk):'–')+row('Last sync error',esc(rq.lastError||'–'))+`<div class="liveSubTitle">EVENT QUEUES</div><div id="liveQueueList">${queueRows()}</div>`);
 let ev=[];try{ev=diag()?.getEvents?.()||[]}catch{}const errs=ev.filter(x=>x.severity==='error').length,warns=ev.filter(x=>x.severity==='warn').length;
 setHtml('liveDiagBody',row('Diagnostics',boolState(!!diag(),'ACTIVE','NOT READY'))+row('Session',esc(diag()?.sessionId||'–'))+row('Stored events',String(ev.length))+row('Errors',String(errs))+row('Warnings',String(warns))+row('Last event',ev.length?`${esc(ev[ev.length-1].type)} • ${fmtTime(ev[ev.length-1].t)}`:'–')+`<div class="liveSubTitle">LATEST EVENTS</div><div id="liveEventList">${eventRows()}</div>`);
 const r=globalThis.MOTOLAB_RELEASE||{};
 setHtml('liveSystemBody',row('Version',esc(r.label||r.version||'–'))+row('Build',esc(r.build||'–'))+row('Visibility',esc(document.visibilityState))+row('Online',boolState(navigator.onLine,'YES','NO'))+row('Secure context',boolState(window.isSecureContext,'YES','NO'))+row('Service Worker',boolState(!!navigator.serviceWorker?.controller,'ACTIVE','NO CONTROLLER'))+row('User agent',esc(navigator.userAgent)));
}

function installStyle(){if($l('motolabLiveStyle'))return;const s=document.createElement('style');s.id='motolabLiveStyle';s.textContent=`
#screen-live{padding-bottom:4px}.liveTitle{font-size:18px;font-weight:1000;font-style:italic;margin:12px 4px 5px}.liveLead{font-size:9px;color:#aeb4bc;margin:0 4px 10px;line-height:1.45}.liveSummary{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin:7px 0 9px}.livePill{min-width:0;padding:8px 3px;border-radius:11px;background:#0b0d11;border:1px solid #2e3138;text-align:center}.livePill i{display:block;width:8px;height:8px;border-radius:50%;margin:0 auto 5px;background:#555}.livePill i.ok{background:#3bf06b;box-shadow:0 0 9px rgba(59,240,107,.5)}.livePill i.warn{background:#ffc62b;box-shadow:0 0 9px rgba(255,198,43,.45)}.livePill i.bad{background:#ff263f;box-shadow:0 0 9px rgba(255,38,63,.45)}.livePill b{display:block;font-size:7px}.livePill span{display:block;margin-top:3px;font-size:6px;color:#aeb4bc;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.liveDetails{margin:7px 0;border-radius:14px;background:linear-gradient(#0e1015,#08090c);border:1px solid rgba(255,255,255,.09);overflow:hidden}.liveDetails[open]{border-color:#4a282e}.liveDetails summary{list-style:none;cursor:pointer;padding:12px 11px;font-size:11px;font-weight:1000;display:flex;justify-content:space-between;align-items:center}.liveDetails summary::-webkit-details-marker{display:none}.liveDetails summary:after{content:'›';font-size:18px;color:#ff263f;transform:rotate(90deg)}.liveDetails[open] summary:after{transform:rotate(-90deg)}.liveBody{padding:0 10px 10px}.liveRow{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.35fr);gap:8px;padding:7px 2px;border-top:1px solid rgba(255,255,255,.055);font-size:8px}.liveRow span{color:#969da7}.liveRow b{text-align:right;font-size:8px;overflow-wrap:anywhere}.liveState{font-size:7px;font-weight:1000}.liveState.ok{color:#3bf06b}.liveState.bad{color:#ff596c}.liveSubTitle{margin:10px 0 5px;color:#ff596c;font-size:7px;font-weight:1000;letter-spacing:.12em}.liveQueue,.liveEvent{padding:7px 2px;border-top:1px solid rgba(255,255,255,.05);display:grid;gap:2px}.liveQueue b,.liveEvent b{font-size:8px;overflow-wrap:anywhere}.liveQueue span,.liveEvent span{font-size:7px;color:#8f96a0;overflow-wrap:anywhere}.liveEvent.err b{color:#ff596c}.liveEvent.warn b{color:#ffc62b}.liveEmpty{padding:8px 2px;color:#777;font-size:8px}`;document.head.appendChild(s)}
function installScreen(){if($l('screen-live'))return;const nav=document.querySelector('.bottomNav');if(!nav)return;const screen=document.createElement('section');screen.id='screen-live';screen.className='screen';screen.innerHTML=`<div class="liveTitle">📡 LIVE DATA</div><div class="liveLead">MotoLabin tekninen tarkastusnäkymä. Näyttää mitä anturit, mittaus, RAW, synkkaus ja diagnostiikka tekevät juuri nyt ilman että LIVE-näkymä ohjaa mittausta.</div><div class="liveSummary"><div class="livePill"><i id="liveSumGps"></i><b>GPS</b><span id="liveSumGpsTxt">–</span></div><div class="livePill"><i id="liveSumMic"></i><b>MIC</b><span id="liveSumMicTxt">–</span></div><div class="livePill"><i id="liveSumImu"></i><b>IMU</b><span id="liveSumImuTxt">–</span></div><div class="livePill"><i id="liveSumRaw"></i><b>RAW</b><span id="liveSumRawTxt">–</span></div><div class="livePill"><i id="liveSumSync"></i><b>SYNC</b><span id="liveSumSyncTxt">–</span></div></div><details class="liveDetails" open><summary>📍 GPS</summary><div id="liveGpsBody" class="liveBody"></div></details><details class="liveDetails" open><summary>🎙️ MIC / RPM</summary><div id="liveMicBody" class="liveBody"></div></details><details class="liveDetails"><summary>📐 IMU</summary><div id="liveImuBody" class="liveBody"></div></details><details class="liveDetails"><summary>⚙️ GEAR</summary><div id="liveGearBody" class="liveBody"></div></details><details class="liveDetails"><summary>🏁 DYNO / RUN</summary><div id="liveDynoBody" class="liveBody"></div></details><details class="liveDetails"><summary>💾 RAW / SYNC / QUEUES</summary><div id="liveRawBody" class="liveBody"></div></details><details class="liveDetails"><summary>🧪 DIAGNOSTICS / EVENT LOG</summary><div id="liveDiagBody" class="liveBody"></div></details><details class="liveDetails"><summary>📱 SYSTEM</summary><div id="liveSystemBody" class="liveBody"></div></details>`;nav.parentNode.insertBefore(screen,nav);
 const b=document.createElement('button');b.className='nav';b.dataset.screen='live';b.innerHTML='<div class="ico">📡</div><div class="txt">LIVE</div>';const analysis=nav.querySelector('[data-screen="analysis"]');nav.insertBefore(b,analysis||nav.lastElementChild);b.onclick=()=>{try{if(typeof switchScreen==='function')switchScreen('live');else{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));screen.classList.add('active');b.classList.add('active')}}catch{}render()};
}
function boot(){installStyle();installScreen();render();if(timer)clearInterval(timer);timer=setInterval(render,750);try{globalThis.MOTOLAB_DIAGNOSTICS?.record?.('live_status_loaded',{module:MODULE})}catch{}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
