(() => {
'use strict';
const V='v32-maintenance-1';let db=null,tpl=null;
const $=id=>document.getElementById(id),num=v=>Number.isFinite(+v)?+v:0,today=()=>new Date().toISOString().slice(0,10),clone=v=>JSON.parse(JSON.stringify(v||{}));
function p(){return typeof getCurrentProfile==='function'?getCurrentProfile():null}
async function loadDb(){if(db)return db;const r=await fetch('./maintenance_catalog.json?v=32',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);db=await r.json();return db}
function choose(){const x=p(),hay=[x?.name,x?.knowledge?.notes,x?.knowledge?.vehicle?.model].filter(Boolean).join(' ').toLowerCase();return (db?.profiles||[]).map(t=>({t,n:(t.match||[]).filter(s=>hay.includes(String(s).toLowerCase())).length})).sort((a,b)=>b.n-a.n)[0]?.n?(db.profiles||[]).map(t=>({t,n:(t.match||[]).filter(s=>hay.includes(String(s).toLowerCase())).length})).sort((a,b)=>b.n-a.n)[0].t:null}
function data(){const x=p(),kb=clone(x?.knowledge||{});kb.maintenance=kb.maintenance||{odometerKm:0,tasks:{},history:[]};const m=kb.maintenance;m.tasks=m.tasks||{};m.history=Array.isArray(m.history)?m.history:[];for(const q of tpl?.tasks||[])m.tasks[q.id]=m.tasks[q.id]||{...q,lastKm:null,lastDate:null,notes:''};return{x,kb,m}}
function kbPanel(){return [...document.querySelectorAll('.panel')].find(e=>/VEHICLE\s*\/\s*ENGINE KNOWLEDGE BASE/i.test(e.textContent||''))}
function inject(){if($('maintenancePanel'))return;const k=kbPanel();if(!k)return;const e=document.createElement('div');e.className='panel';e.id='maintenancePanel';e.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">🛠</span> HUOLTO & HISTORIA</div><span class="tiny">${V}</span></div><div class="form"><label>Mittarilukema km<input id="mOdo" type="number" min="0" step="1"></label><button id="mOdoSave" class="action" type="button">TALLENNA KM</button><button id="mAdd" class="action gray full" type="button">+ OMA HUOLTOKOHDE</button></div><div id="mStatus" class="statusbox"></div><div id="mTasks" class="runlist"></div><div class="phead"><div class="ptitle">VIIMEISIMMÄT HUOLLOT</div></div><div id="mHist" class="runlist"></div>`;k.parentNode.insertBefore(e,k);$('mOdoSave').onclick=()=>save(m=>m.odometerKm=Math.max(0,Math.round(num($('mOdo').value))));$('mAdd').onclick=add}
function save(fn){if(typeof saveCurrentProfile!=='function')return;const {kb,m}=data();fn(m);saveCurrentProfile({knowledge:kb});if(typeof addLearningEvent==='function')addLearningEvent('maintenance_changed',{});render()}
function add(){const name=prompt('Huoltokohteen nimi');if(!name)return;const km=Math.max(0,Math.round(num(prompt('Huoltoväli km (0 = ei km-muistutusta)','0')))),mo=Math.max(0,Math.round(num(prompt('Huoltoväli kuukausina','0'))));save(m=>{const id='custom-'+Date.now();m.tasks[id]={id,name,category:'OMA',intervalKm:km,intervalMonths:mo,lastKm:null,lastDate:null,notes:''}})}
function done(id){const odo=Math.max(0,Math.round(num($('mOdo').value))),note=prompt('Huoltomerkintä / osa / öljy / huomio','')||'';save(m=>{const t=m.tasks[id];if(!t)return;t.lastKm=odo;t.lastDate=today();t.notes=note;m.odometerKm=odo;m.history.unshift({id:'h'+Date.now(),taskId:id,name:t.name,date:t.lastDate,km:odo,note});m.history=m.history.slice(0,150)})}
function interval(id){const km=Math.max(0,Math.round(num(document.querySelector(`[data-km="${CSS.escape(id)}"]`)?.value))),mo=Math.max(0,Math.round(num(document.querySelector(`[data-mo="${CSS.escape(id)}"]`)?.value)));save(m=>{if(m.tasks[id]){m.tasks[id].intervalKm=km;m.tasks[id].intervalMonths=mo}})}
function render(){const {m}=data(),odo=num(m.odometerKm);$('mOdo').value=Math.round(odo);$('mStatus').textContent=tpl?`${tpl.title} • huoltovälit ovat profiilikohtaisesti muokattavia.`:'Ajoneuvokohtaista tehdaspohjaa ei tunnistettu. Voit silti lisätä omat huollot.';const tasks=Object.values(m.tasks);$('mTasks').innerHTML=tasks.map(t=>{const used=t.lastKm==null?null:odo-num(t.lastKm),left=t.intervalKm>0&&used!=null?t.intervalKm-used:null,cls=left!=null&&left<=0?'bad':left!=null&&left<=Math.max(100,t.intervalKm*.15)?'warn':'good';return `<div class="runCard ${cls}"><h4>${t.category||'HUOLTO'} • ${t.name}</h4><p>Viimeksi ${t.lastDate||'–'} • ${t.lastKm??'–'} km ${left!=null?`• ${left<=0?'YLI '+Math.abs(Math.round(left))+' km':Math.round(left)+' km jäljellä'}`:''}</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:6px"><label>km<input data-km="${t.id}" type="number" value="${num(t.intervalKm)}"></label><label>kk<input data-mo="${t.id}" type="number" value="${num(t.intervalMonths)}"></label></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:6px"><button class="action gray" data-int="${t.id}">TALLENNA VÄLI</button><button class="action" data-done="${t.id}">MERKITSE TEHDYKSI</button></div></div>`}).join('')||'<div class="statusbox">Ei huoltokohteita.</div>';$('mTasks').querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>done(b.dataset.done));$('mTasks').querySelectorAll('[data-int]').forEach(b=>b.onclick=()=>interval(b.dataset.int));$('mHist').innerHTML=(m.history||[]).slice(0,12).map(h=>`<div class="runCard"><h4>${h.name}</h4><p>${h.date} • ${h.km} km${h.note?' • '+h.note:''}</p></div>`).join('')||'<div class="statusbox">Ei vielä huoltohistoriaa.</div>'}
async function boot(){inject();try{await loadDb();tpl=choose();render()}catch(e){$('mStatus')&&($('mStatus').textContent='Huoltotietokannan lataus epäonnistui: '+e.message)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();