(() => {
'use strict';
const V='v32-tech-specs-1.3',$=id=>document.getElementById(id),clone=v=>JSON.parse(JSON.stringify(v||{}));
const BUILD='2026-08-16d';
let catalogPromise=null;
function profile(){return typeof getCurrentProfile==='function'?getCurrentProfile():null}
function kbPanel(){return [...document.querySelectorAll('.panel')].find(e=>/VEHICLE\s*\/\s*ENGINE KNOWLEDGE BASE/i.test(e.textContent||''))}
const fields=[
 ['techSparkPlug','Sytytystulppa','engine','sparkPlug'],['techPlugGap','Tulpan kärkiväli mm','engine','sparkPlugGapMm'],['techCarb','Kaasutin','engine','carburetor'],['techCarbMm','Kaasuttimen koko mm','engine','carburetorMm'],['techIgn','Sytytys','engine','ignition'],['techTiming','Sytytysennakko / perusasetus','engine','ignitionTiming'],['techOilType','Vaihteistoöljy','fluids','transmissionOil'],['techOilQty','Vaihteistoöljyn kokonaismäärä L','fluids','transmissionOilTotalL'],['techOilChange','Vaihteistoöljy vaihdossa L','fluids','transmissionOilChangeL'],['techCoolant','Jäähdytysneste määrä L','fluids','coolantL'],['tech2TOil','2T-öljy / suositus','fluids','twoStrokeOil'],['tech2TTank','2T-öljysäiliö L','fluids','twoStrokeOilTankL'],['techBrakeFluid','Jarruneste','fluids','brakeFluid'],['techForkOil','Haarukkaöljy','fluids','forkOil'],['techFrontPressure','Eturengas paine','chassis','frontTyrePressure'],['techRearPressure','Takarengas paine','chassis','rearTyrePressure'],['techBattery','Akku','electrical','battery'],['techCharging','Latausjärjestelmä','electrical','charging'],['techNotes','Tekniset lisätiedot','technical','notes']
];
function inject(){if($('technicalSpecsPanel'))return;const k=kbPanel();if(!k)return;const e=document.createElement('div');e.className='panel';e.id='technicalSpecsPanel';e.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">🔧</span> TEKNISET TIEDOT</div><span class="tiny">${V}</span></div><div class="form">${fields.map(([id,label])=>`<label class="${id==='techNotes'?'full':''}">${label}<input id="${id}"></label>`).join('')}<button id="techSave" class="action full" type="button">TALLENNA TEKNISET TIEDOT</button></div><div id="techStatus" class="statusbox">Ajoneuvohaun tehdasarvot näkyvät täällä. Kaikki arvot voi muuttaa pyörän todellisen kokoonpanon mukaan.</div>`;k.parentNode.insertBefore(e,k);$('techSave').onclick=save;load()}
async function catalog(){if(!catalogPromise)catalogPromise=fetch(`./vehicle_catalog.json?v=32.3&build=${BUILD}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).catch(()=>null);return catalogPromise}
async function catalogEntry(kb){const db=await catalog();if(!db?.entries?.length)return null;const id=kb?.reference?.vehicleId;if(id){const hit=db.entries.find(e=>e.id===id);if(hit)return hit}const v=kb?.vehicle||{};if(!v.make||!v.model)return null;const norm=s=>String(s||'').trim().toLowerCase();return db.entries.find(e=>norm(e.make)===norm(v.make)&&norm(e.model)===norm(v.model)&&(!v.variant||norm(e.variant)===norm(v.variant)))||db.entries.find(e=>norm(e.make)===norm(v.make)&&norm(e.model)===norm(v.model))||null}
function read(obj,group,key){let v=obj?.[group]?.[key];if((v===undefined||v===null||v==='')&&group==='fluids'&&key==='transmissionOilTotalL')v=obj?.fluids?.transmissionOilL;if((v===undefined||v===null||v==='')&&group==='fluids'&&key==='transmissionOilL')v=obj?.fluids?.transmissionOilTotalL;return v??''}
function isDt(kb,p){const text=[p?.name,kb?.vehicle?.make,kb?.vehicle?.model,kb?.vehicle?.variant,kb?.reference?.vehicleId].filter(Boolean).join(' ').toLowerCase();return /yamaha/.test(text)&&/(dt125|dt 125|dtr|athena 170|dt170)/.test(text)}
function dtFallback(group,key){if(group!=='fluids')return'';return ({transmissionOilTotalL:0.8,transmissionOilL:0.8,transmissionOilChangeL:0.75,coolantL:0.92,twoStrokeOilTankL:1.2})[key]??''}
async function load(){const p=profile(),kb=p?.knowledge||{},base=await catalogEntry(kb),dt=isDt(kb,p);let fallbackCount=0;for(const [id,,g,k] of fields){if(!$(id))continue;let v=read(kb,g,k);if((v===''||v===null)&&base){v=read(base,g,k);if(v!==''&&v!==null)fallbackCount++}if((v===''||v===null)&&dt){v=dtFallback(g,k);if(v!==''&&v!==null)fallbackCount++}$(id).value=v??''}if($('techStatus'))$('techStatus').textContent=fallbackCount?`Tekniset tiedot päivitetty. ${fallbackCount} puuttuvaa arvoa täydennettiin DT-referenssistä.`:'Tekniset tiedot päivitetty aktiivisesta profiilista.'}
function parse(v){const s=String(v??'').trim();if(!s)return'';const n=Number(s.replace(',','.'));return Number.isFinite(n)&&/^[-+]?\d+(?:[.,]\d+)?$/.test(s)?n:s}
function save(){if(typeof saveCurrentProfile!=='function')return;const p=profile(),kb=clone(p?.knowledge||{});for(const [id,,g,k] of fields){kb[g]=kb[g]||{};kb[g][k]=parse($(id)?.value)}saveCurrentProfile({knowledge:kb});$('techStatus').textContent='Tekniset tiedot tallennettu profiiliin.';if(typeof addLearningEvent==='function')addLearningEvent('technical_specs_changed',{})}
function boot(){inject();window.addEventListener('motolab:vehicle-applied',()=>setTimeout(load,0));window.addEventListener('motolab:profile-updated',()=>setTimeout(load,0));document.addEventListener('change',e=>{if(e.target&&e.target.id==='profileSelect')setTimeout(load,0)})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();