(() => {
'use strict';
const VERSION='motorlab-user-identity-v9';
const PRODUCTION_SERVER='https://v-n-autodyno-production.up.railway.app';
const DEVICE_KEY='motolab_v32_raw_sync_device',TOKEN_KEY='motolab_v32_beta_token',SERVER_KEY='motolab_v32_beta_server',NICK_KEY='motolab_user_nickname';
const STATE_KEYS=['motolab_v26_profiles','motolab_v26_runs','motolab_v29_raw_fallback','motolab_v29_learning_enabled','motolab_v32_raw_sync_cfg','motolab_v32_beta_consent','motolab_v32_dev_unlocked','motolab_language'];
const nativeFetch=window.fetch.bind(window);let me=null,overlay=null,lastSnapshot='',syncTimer=0,ownerRestoreTried=false;
const $=id=>document.getElementById(id);
function server(){localStorage.setItem(SERVER_KEY,PRODUCTION_SERVER);return PRODUCTION_SERVER}
function device(){let x=localStorage.getItem(DEVICE_KEY);if(!x){x=crypto.randomUUID?.()||'dev-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(DEVICE_KEY,x)}return x}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function deviceLabel(){return [navigator.platform||'',navigator.userAgent.includes('iPhone')?'iPhone':''].filter(Boolean).join(' ').slice(0,80)}
async function request(path,opt={}){const h={...(opt.headers||{})};if(opt.json!==false)h['Content-Type']='application/json';if(token())h['X-MotoLab-Beta-Token']=token();const r=await nativeFetch(server()+path,{cache:'no-store',...opt,headers:h});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Object.assign(Error(j.error||('HTTP '+r.status)),{status:r.status,data:j});return j}
function snapshot(){const out={};for(const k of STATE_KEYS){const v=localStorage.getItem(k);if(v!==null)out[k]=v}return out}
function applyState(state){if(!state||typeof state!=='object')return;for(const k of STATE_KEYS)if(Object.prototype.hasOwnProperty.call(state,k)){const v=state[k];if(v===null)localStorage.removeItem(k);else if(typeof v==='string')localStorage.setItem(k,v)}}
async function uploadState(force=false){if(!me||me.status!=='active')return;const state=snapshot(),sig=JSON.stringify(state);if(!force&&sig===lastSnapshot)return;await request('/api/users/v1/state',{method:'PUT',body:JSON.stringify({state})});lastSnapshot=sig}
async function syncState(){if(!me||me.status!=='active')return;try{const j=await request('/api/users/v1/state'),remote=j.item||{};if(remote.updatedAt&&remote.state&&Object.keys(remote.state).length){applyState(remote.state);lastSnapshot=JSON.stringify(snapshot())}else await uploadState(true);clearInterval(syncTimer);syncTimer=setInterval(()=>uploadState(false).catch(()=>{}),12000)}catch{}}
function dispatch(){document.body?.classList.toggle('ml-admin-user',me?.role==='admin');document.dispatchEvent(new CustomEvent('motorlab-user-ready',{detail:me}));globalThis.MotoLabSimpleUI?.apply?.();globalThis.MotoLabV34UI?.apply?.()}
async function restoreOwnerDevice(){if(ownerRestoreTried)return null;ownerRestoreTried=true;try{const r=await nativeFetch(server()+'/api/users/v1/owner-device-session',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({deviceId:device(),deviceLabel:deviceLabel()})}),j=await r.json().catch(()=>({}));if(!r.ok||!j.token)return null;localStorage.setItem(TOKEN_KEY,j.token);me=j.user||null;if(me?.nickname)localStorage.setItem(NICK_KEY,me.nickname);if(me){dispatch();syncState()}return me}catch{return null}}
async function refresh(){if(!token())return restoreOwnerDevice();try{const j=await request('/api/users/v1/me');me=j.user||null;if(me?.nickname)localStorage.setItem(NICK_KEY,me.nickname);if(me){dispatch();syncState()}return me}catch(e){if(e.status===401){localStorage.removeItem(TOKEN_KEY);me=null;document.body?.classList.remove('ml-admin-user');return restoreOwnerDevice()}return null}}
async function activate(code,nickname=''){code=String(code||'').trim();if(!code)throw Error('Kutsukoodi puuttuu.');const r=await nativeFetch(server()+'/api/beta/v1/activate',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({code,invite:code,deviceId:device(),deviceLabel:deviceLabel(),nickname:nickname||localStorage.getItem(NICK_KEY)||'MotoLab user'})}),j=await r.json().catch(()=>({}));if(!r.ok||!j.token)throw Error(j.error||('HTTP '+r.status));localStorage.setItem(TOKEN_KEY,j.token);me=j.user||null;if(nickname)localStorage.setItem(NICK_KEY,nickname);sessionStorage.removeItem('motorlab_pending_invite');if(me){dispatch();syncState()}return me}
async function saveNickname(n){n=String(n||'').trim();if(!n)throw Error('Nimimerkki puuttuu.');const j=await request('/api/users/v1/nickname',{method:'POST',body:JSON.stringify({nickname:n})});me=j.user;localStorage.setItem(NICK_KEY,n);dispatch();return me}
async function createInvite(){if(!token()||me?.status!=='active')throw Error('Aktiivinen käyttäjä tarvitaan kutsun luontiin.');const j=await request('/api/users/v1/invite',{method:'POST',body:'{}'}),u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('invite',j.invite);return{url:u.toString(),expiresAt:j.expiresAt,inviteId:j.inviteId}}
function styles(){if($('muiIdentityStyle'))return;const s=document.createElement('style');s.id='muiIdentityStyle';s.textContent=`.mui-id-overlay{position:fixed;inset:0;z-index:295000;background:#000e;display:flex;align-items:flex-end;justify-content:center;padding:10px;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.mui-id-card{width:min(100%,480px);max-height:92vh;overflow:auto;background:#0b0d11;border:1px solid #ff263f;border-radius:22px;padding:16px}.mui-id-card h2{margin:5px 0 7px}.mui-id-card p{color:#aeb4bc;font-size:10px;line-height:1.45}.mui-id-card input{width:100%;padding:11px;margin:5px 0 9px;border-radius:11px;border:1px solid #363a42;background:#050609;color:#fff}.mui-id-btn{width:100%;padding:11px;margin-top:7px;border-radius:11px;border:1px solid #ff263f;background:#a80d20;color:#fff;font-weight:900}.mui-id-btn.gray{background:#14171c;border-color:#42464e}.mui-id-status{margin-top:9px;padding:9px;border-radius:10px;background:#07080b;border:1px solid #292d34;color:#aeb5bf;font-size:9px}.mui-user-row{border:1px solid #292d34;border-radius:12px;padding:10px;margin:8px 0;background:#080a0d}.mui-user-row b{display:block;font-size:11px}.mui-user-row small{display:block;color:#929aa5;font-size:8px;margin:4px 0 7px}.mui-user-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.mui-user-actions button{padding:8px;border-radius:9px;border:1px solid #42464e;background:#13161b;color:#fff;font-size:8px;font-weight:900}.mui-user-actions button.ok{border-color:#237e3e}.mui-user-actions button.bad{border-color:#8d2635}`;document.head.appendChild(s)}
function closeAccount(){overlay?.remove();overlay=null}
function renderAccount(msg=''){styles();closeAccount();const pending=sessionStorage.getItem('motorlab_pending_invite')||'';overlay=document.createElement('div');overlay.className='mui-id-overlay';const active=!!me,admin=me?.role==='admin';overlay.innerHTML=`<div class="mui-id-card"><div style="font-weight:1000;font-style:italic">VäNä <span style="color:#ff263f">MotorLab</span></div><h2>${active?'Oma tili':'Aktivoi käyttäjä'}</h2>${active?`<p>${esc(me.nickname)} • ${esc(me.status)}${admin?' • OWNER / ADMIN':''}<br>Laite ${esc(device().slice(0,20))}…</p><label>Nimimerkki</label><input id="muiNick" maxlength="32" value="${esc(me.nickname||'')}"><button class="mui-id-btn" id="muiSaveNick">TALLENNA NIMIMERKKI</button>${me.status==='active'?'<button class="mui-id-btn gray" id="muiInviteCreate">LUO KUTSULINKKI</button>':''}${admin?'<button class="mui-id-btn gray" id="muiAdminUsers">KÄYTTÄJÄT / HYVÄKSYNNÄT</button>':''}`:`<p>Mittaus toimii ilman käyttäjätiliä. Käyttäjätili tarvitaan pilvitallennukseen, Beta-yhteisöön, palautteisiin ja jaettuihin vetoihin.</p><label>Nimimerkki</label><input id="muiNick" maxlength="32" value="${esc(localStorage.getItem(NICK_KEY)||'')}"><label>Kutsukoodi</label><input id="muiInviteCode" value="${esc(pending)}" placeholder="Kutsukoodi"><button class="mui-id-btn" id="muiActivate">AKTIVOI TÄMÄ LAITE</button>`}<button class="mui-id-btn gray" id="muiRefresh">PÄIVITÄ TILA</button><button class="mui-id-btn gray" id="muiClose">SULJE</button><div id="muiIdStatus" class="mui-id-status">${esc(msg||('Palvelin: '+server()))}</div></div>`;document.body.appendChild(overlay);$('muiClose').onclick=closeAccount;$('muiRefresh').onclick=async()=>{const st=$('muiIdStatus');st.textContent='Tarkistetaan…';await refresh();renderAccount(me?'Yhteys OK.':'Ei aktiivista käyttäjäistuntoa.')};if($('muiActivate'))$('muiActivate').onclick=async()=>{const st=$('muiIdStatus');st.textContent='Aktivoidaan…';try{await activate($('muiInviteCode').value,$('muiNick').value);renderAccount(me?.status==='pending'?'Laite rekisteröity. Odottaa ylläpidon hyväksyntää.':'Kirjautuminen valmis.')}catch(e){st.textContent='Aktivointi epäonnistui: '+e.message}};if($('muiSaveNick'))$('muiSaveNick').onclick=async()=>{try{await saveNickname($('muiNick').value);renderAccount('Nimimerkki tallennettu.')}catch(e){$('muiIdStatus').textContent=e.message}};if($('muiInviteCreate'))$('muiInviteCreate').onclick=async()=>{try{const x=await createInvite();if(navigator.share)await navigator.share({title:'VäNä MotorLab',text:'MotorLab beta-kutsu',url:x.url});else if(navigator.clipboard){await navigator.clipboard.writeText(x.url);$('muiIdStatus').textContent='Kutsulinkki kopioitu.'}else $('muiIdStatus').textContent=x.url}catch(e){$('muiIdStatus').textContent=e.message}};if($('muiAdminUsers'))$('muiAdminUsers').onclick=adminUsers}
async function setUserStatus(userId,status){await request('/api/admin/v1/user-status',{method:'POST',body:JSON.stringify({userId,status})});return adminUsers('Käyttäjätila päivitetty.')}
async function adminUsers(msg=''){styles();if(me?.role!=='admin')return renderAccount('Admin-oikeus vaaditaan.');let j;try{j=await request('/api/admin/v1/users')}catch(e){return renderAccount('Käyttäjien haku epäonnistui: '+e.message)}closeAccount();overlay=document.createElement('div');overlay.className='mui-id-overlay';const users=(j.users||[]).slice().sort((a,b)=>({pending:0,active:1,blocked:2}[a.status]??9)-({pending:0,active:1,blocked:2}[b.status]??9)||String(a.nickname||'').localeCompare(String(b.nickname||''),'fi'));overlay.innerHTML=`<div class="mui-id-card"><h2>Käyttäjät / hyväksynnät</h2><p>Sinä hyväksyt kaikki uudet käyttäjät nimimerkin perusteella. Kutsuja voi tehdä aktiivinen käyttäjä, mutta käyttö avautuu vasta pääylläpitäjän hyväksynnällä.</p>${users.map(u=>`<div class="mui-user-row"><b>${esc(u.nickname||'Nimetön')} ${u.role==='admin'?'• ADMIN':''}</b><small>${esc(u.status)} • ${esc(u.userId)} • ${(u.devices||[]).length} laitetta${u.invitedBy?' • kutsui '+esc(u.invitedBy):''}</small>${u.role==='admin'?'<small>Admin-tiliä ei muuteta tästä.</small>':`<div class="mui-user-actions">${u.status!=='active'?`<button class="ok" data-user-status="active" data-user-id="${esc(u.userId)}">HYVÄKSY</button>`:'<button disabled>AKTIIVINEN</button>'}${u.status!=='blocked'?`<button class="bad" data-user-status="blocked" data-user-id="${esc(u.userId)}">ESTÄ</button>`:`<button data-user-status="active" data-user-id="${esc(u.userId)}">PALAUTA</button>`}</div>`}</div>`).join('')||'<div class="mui-id-status">Ei käyttäjiä.</div>'}<button class="mui-id-btn gray" id="muiAdminBack">TAKAISIN OMAAN TILIIN</button><button class="mui-id-btn gray" id="muiAdminClose">SULJE</button><div class="mui-id-status">${esc(msg||'Päivitetty '+new Date().toLocaleTimeString('fi-FI'))}</div></div>`;document.body.appendChild(overlay);$('muiAdminBack').onclick=()=>renderAccount();$('muiAdminClose').onclick=closeAccount;overlay.querySelectorAll('[data-user-status]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await setUserStatus(b.dataset.userId,b.dataset.userStatus)}catch(e){adminUsers('Muutos epäonnistui: '+e.message)}})}
function capture(){const p=new URLSearchParams(location.search),i=p.get('invite');server();if(i)sessionStorage.setItem('motorlab_pending_invite',i);if(p.has('betaServer'))p.delete('betaServer');if(p.has('invite'))p.delete('invite');history.replaceState(null,'',location.pathname+(p.toString()?'?'+p:'')+location.hash)}
async function boot(){server();device();capture();await refresh();if(sessionStorage.getItem('motorlab_pending_invite')&&!me)renderAccount('Kutsu löydetty. Valitse nimimerkki ja aktivoi laite.')}
globalThis.MotoLabUser={version:VERSION,refresh,activate,saveNickname,createInvite,openAccount:renderAccount,adminUsers,productionServer:PRODUCTION_SERVER,get user(){return me},deviceId:device};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
