(() => {
'use strict';
const MODULE_VERSION='v32-vehicle-lookup-2.5-fi-v2'; let catalog=null,matches=[];
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function kbPanel(){return [...document.querySelectorAll('.panel')].find(p=>/VEHICLE\s*\/\s*ENGINE KNOWLEDGE BASE/i.test(p.textContent||''))||null}
function settingsHost(){return $('screen-settings')||document.querySelector('.screen[data-screen="settings"]')||document.querySelector('.screen:last-of-type')||null}
function injectUi(){if($('vehicleLookupPanel'))return true;const kb=kbPanel(),host=kb?.parentNode||settingsHost();if(!host)return false;const p=document.createElement('div');p.className='panel';p.id='vehicleLookupPanel';p.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">🔎</span> AJONEUVOTIEDON HAKU</div><span class="tiny">${MODULE_VERSION}</span></div><div class="form"><label class="full">Hae merkki / malli / versio<input id="vehicleLookupInput" value="Derbi Senda 50" placeholder="esim. Rieju MRT 50 tai Yamaha YZF-R125"></label><button id="vehicleLookupBtn" class="action full" type="button">HAE</button></div><div id="vehicleLookupStatus" class="statusbox">Haku tehdään MotoLabin tietokannasta. Jos mallia ei löydy, pyyntö tallennetaan tarkistettavaksi.</div><div id="vehicleLookupResults" class="runlist"></div>`;if(kb)host.insertBefore(p,kb);else host.appendChild(p);const g=document.createElement('div');g.className='panel';g.id='drivetrainEditor';g.innerHTML=`<div class="phead"><div class="ptitle"><span class="r">⚙️</span> VÄLITYKSET</div><span class="tiny">muokattava</span></div><div class="form"><label>Primääri<input id="dtPrimary" type="number" step="0.001"></label><label>Eturatas<input id="dtFront" type="number" step="1"></label><label>Takaratas<input id="dtRear" type="number" step="1"></label><label>1. vaihde<input id="dtG1" type="number" step="0.001"></label><label>2. vaihde<input id="dtG2" type="number" step="0.001"></label><label>3. vaihde<input id="dtG3" type="number" step="0.001"></label><label>4. vaihde<input id="dtG4" type="number" step="0.001"></label><label>5. vaihde<input id="dtG5" type="number" step="0.001"></label><label>6. vaihde<input id="dtG6" type="number" step="0.001"></label><button id="dtSave" class="action full" type="button">TALLENNA VÄLITYKSET</button></div><div id="dtStatus" class="statusbox">Välitykset ovat profiilikohtaisia. Rataskoot voi vaihtaa koska tahansa.</div>`;if(kb)host.insertBefore(g,kb);else host.appendChild(g);$('vehicleLookupBtn').onclick=search;$('vehicleLookupInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search()}};$('dtSave').onclick=saveDrivetrain;loadDrivetrain();return true}
function ensureFiV2Loader(){if(window.MotoLabFinlandVehicleCatalogV2?.load)return Promise.resolve();if(window.__motolabFiV2Loader)return window.__motolabFiV2Loader;window.__motolabFiV2Loader=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='./vehicle_catalog_finland_v2_loader.js?v=2026-08-16.2';s.async=true;s.onload=()=>window.MotoLabFinlandVehicleCatalogV2?.load?resolve():reject(Error('FI v2 loader ei rekisteröitynyt'));s.onerror=()=>reject(Error('FI v2 loader ei latautunut'));document.head.appendChild(s)});return window.__motolabFiV2Loader}
async function loadCatalog(){if(catalog)return catalog;const baseR=await fetch('./vehicle_catalog.json?v=32.4',{cache:'no-store'});if(!baseR.ok)throw Error(`HTTP ${baseR.status}`);const base=await baseR.json();let extra=[];try{await ensureFiV2Loader();const fi=await window.MotoLabFinlandVehicleCatalogV2.load();extra=fi.entries||[]}catch(e){console.warn('FI v2 vehicle catalog ignored',e)}const seen=new Set((base.entries||[]).map(e=>e.id));catalog={...base,version:String(base.version||'')+'+fi-v2',entries:[...(base.entries||[]),...extra.filter(e=>!seen.has(e.id))]};return catalog}
function score(e,q){const hay=[e.make,e.model,e.variant,e.engineCode,...(e.aliases||[])].filter(Boolean).join(' ').toLowerCase();const ps=q.toLowerCase().trim().split(/\s+/).filter(Boolean);return ps.length?ps.filter(p=>hay.includes(p)).length/ps.length:0}
async function search(){const q=($('vehicleLookupInput')?.value||'').trim();if(!q)return;$('vehicleLookupStatus').textContent='HAETAAN…';try{const db=await loadCatalog();matches=db.entries.map(e=>({e,s:score(e,q)})).filter(x=>x.s>=.5).sort((a,b)=>b.s-a.s).slice(0,10).map(x=>x.e);render(q)}catch(e){$('vehicleLookupStatus').textContent='Haku epäonnistui: '+e.message}}
function trust(e){const v=String(e?.confidence||e?.verificationStatus||e?.drivetrain?.gearRatioConfidence||'').toLowerCase();if(/verified|vahvist/.test(v))return 'VAHVISTETTU';if(/probable|likely|todenn|researched/.test(v))return 'TODENNÄKÖINEN';if(/pending|uncertain|tarkist|partial/.test(v))return 'TARKISTUS KESKEN';return 'TIETOKANTA'}
function render(q){const box=$('vehicleLookupResults');if(!matches.length){box.innerHTML='';const sent=window.MotoLabBeta?.reportVehicleMissing?.(q);$('vehicleLookupStatus').textContent=sent?`EI LÖYTYNYT • “${q}” • TARKISTUS KESKEN. Hakupyyntö tallennettiin oppimisdataan ja lähtee palvelimelle RAW-synkan mukana.`:`EI LÖYTYNYT • “${q}” • TARKISTUS KESKEN.`;return}$('vehicleLookupStatus').textContent=`LÖYTYI ${matches.length} ehdotusta. Valitse oikea tehdaslähtökohta.`;box.innerHTML=matches.map(e=>{const en=e.engine||{},d=e.drivetrain||{},yr=e.yearFrom?(e.yearTo&&e.yearTo!==e.yearFrom?`${e.yearFrom}–${e.yearTo}`:`${e.yearFrom}`):(e.variant||'vuosimalli tarkistettava');const gears=(d.gearRatios||[]).map((x,i)=>`${i+1}:${x}`).join(' • ');const dims=[en.boreMm,en.strokeMm].every(Number.isFinite)?` • ${en.boreMm} × ${en.strokeMm} mm`:'';return `<div class="runCard good"><h4>${esc(e.make)} ${esc(e.model)} ${esc(e.variant||'')} <span class="badge">${trust(e)}</span></h4><p>${esc(yr)} • ${esc(e.engineType||'–')} • ${en.displacementCc??'–'} cc${dims}</p><p>${esc(e.engineCode||'')}</p><p>Primääri ${d.primaryRatio??'–'} ${gears?'• '+gears:'• välitykset tarkistuksessa'}</p><button class="action" data-vehicle-id="${esc(e.id)}" style="margin-top:7px;width:100%">KÄYTÄ TÄTÄ</button></div>`}).join('');box.querySelectorAll('[data-vehicle-id]').forEach(b=>b.onclick=()=>apply(b.dataset.vehicleId))}
function apply(id){const e=matches.find(x=>x.id===id);if(!e||typeof getCurrentProfile!=='function'||typeof saveCurrentProfile!=='function')return;const cur=getCurrentProfile(),kb=JSON.parse(JSON.stringify(cur.knowledge||{}));kb.engine={...(kb.engine||{}),...(e.engine||{})};kb.drivetrain={...(kb.drivetrain||{}),...(e.drivetrain||{})};kb.vehicle={make:e.make,model:e.model,variant:e.variant||'',yearFrom:e.yearFrom||null,yearTo:e.yearTo||null,engineCode:e.engineCode||''};kb.reference={catalogVersion:catalog?.version||'',vehicleId:e.id,source:e.source||{},confidence:e.confidence||e.verificationStatus||'catalog',gearLearnPolicy:e.gearLearnPolicy||null};if(e.chassis)kb.chassis={...(kb.chassis||{}),...e.chassis};if(e.fluids)kb.fluids={...(kb.fluids||{}),...e.fluids};const note=`Ajoneuvohaku: ${[e.make,e.model,e.variant].filter(Boolean).join(' ')} | ${e.notes||''}`;if(!String(kb.notes||'').includes(`Ajoneuvohaku: ${e.make} ${e.model}`))kb.notes=[kb.notes,note].filter(Boolean).join(' | ');saveCurrentProfile({name:[e.make,e.model,e.variant].filter(Boolean).join(' '),engineType:e.engineType||cur.engineType,knowledge:kb});if(typeof renderProfiles==='function')renderProfiles();loadDrivetrain();$('vehicleLookupStatus').textContent=`LÖYTYI • ${trust(e)} • Tehdaslähtökohta tallennettu.`;window.dispatchEvent(new CustomEvent('motolab:vehicle-applied',{detail:{vehicleId:e.id,catalogVersion:catalog?.version||'',gearLearnPolicy:e.gearLearnPolicy||null}}));if(typeof addLearningEvent==='function')addLearningEvent('vehicle_lookup_applied',{vehicleId:e.id,catalogVersion:catalog?.version,trust:trust(e),gearLearnPolicy:e.gearLearnPolicy||null})}
function loadDrivetrain(){if(typeof getCurrentProfile!=='function')return;const d=getCurrentProfile()?.knowledge?.drivetrain||{};$('dtPrimary')&&($('dtPrimary').value=d.primaryRatio??'');$('dtFront')&&($('dtFront').value=d.frontSprocket??'');$('dtRear')&&($('dtRear').value=d.rearSprocket??'');const gs=d.gearRatios||[];for(let i=1;i<=6;i++)if($('dtG'+i))$('dtG'+i).value=gs[i-1]??''}
function saveDrivetrain(){if(typeof getCurrentProfile!=='function'||typeof saveCurrentProfile!=='function')return;const cur=getCurrentProfile(),kb=JSON.parse(JSON.stringify(cur.knowledge||{})),d={...(kb.drivetrain||{})};const n=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:null};d.primaryRatio=n('dtPrimary');d.frontSprocket=n('dtFront');d.rearSprocket=n('dtRear');d.finalRatio=d.frontSprocket&&d.rearSprocket?d.rearSprocket/d.frontSprocket:null;d.gearRatios=[1,2,3,4,5,6].map(i=>n('dtG'+i));kb.drivetrain=d;saveCurrentProfile({knowledge:kb});$('dtStatus').textContent=`Tallennettu: ${d.frontSprocket||'–'}/${d.rearSprocket||'–'} • loppuvälitys ${d.finalRatio?d.finalRatio.toFixed(3):'–'}`;if(typeof addLearningEvent==='function')addLearningEvent('drivetrain_changed',{primaryRatio:d.primaryRatio,front:d.frontSprocket,rear:d.rearSprocket,gearRatios:d.gearRatios})}
function boot(){if(injectUi())return;let tries=0;const timer=setInterval(()=>{tries++;if(injectUi()||tries>=20)clearInterval(timer)},250)} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
