'use strict';
const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('dyno_only_v351.js','utf8');
const css=fs.readFileSync('dyno_only_v351.css','utf8');
const version=fs.readFileSync('version.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
function need(ok,msg){if(!ok)throw new Error(msg)}
need(/version:"35\.1"/.test(version),'v35.1 release missing');
need(/2026-09-26-dyno-only-v7/.test(version),'v35.1 build missing');
need(html.includes('dyno_only_v351.css'),'dyno css not linked');
need(html.includes('dyno_only_v351.js'),'dyno js not linked');
need(ui.includes('["measure","runs","settings"]'),'three-screen allowlist missing');
need(ui.includes('ALOITA DYNO'),'dyno start label missing');
need(ui.includes('await startGPS()'),'GPS autostart missing');
need(ui.includes('await startIMU()'),'IMU autostart missing');
need(ui.includes('await startAudio()'),'audio autostart missing');
need(ui.includes('switchScreen("runs")')&&ui.includes('openRun(r.id)'),'automatic result opening missing');
need(ui.includes('learningEnabled=true'),'raw learning capture force-on missing');
need(ui.includes('keepScreenAwake()'),'dyno screen-awake enforcement missing');
need(ui.includes('wake.dataset.dynoWakeLocked="1"'),'dyno wake toggle lock missing');
need(html.includes('wakeLock.addEventListener?.("release"'),'wake-lock release reacquire missing');
need(ui.includes('mnav&&mnav.textContent!=="DYNO"')&&ui.includes('rnav&&rnav.textContent!=="VEDOT"')&&ui.includes('snav&&snav.textContent!=="ASETUKSET"'),'nav MutationObserver writes are not idempotent');
const legacyDash=fs.readFileSync('v34_dashboard_ui.js','utf8');
need(legacyDash.includes("if(document.body.classList.contains('dyno-only-v351'))return"),'legacy v34 dashboard observer is not disabled in dyno-only mode');
need(css.includes('#manualBtn')&&css.includes('#sensorBtn')&&css.includes('#extMicBtn'),'legacy controls not hidden');
need(!css.includes('body.dyno-only-v351 #imuChip{display:none!important}'),'IMU control is hidden in dyno-only mode');
need(html.includes('id="imuChip"')&&html.includes('$("imuChip").onclick=async e=>{e.preventDefault();e.stopPropagation();await toggleIMU()}'),'dedicated IMU direct-gesture wiring missing');
need(html.includes('DeviceMotionEvent.requestPermission()'),'iOS motion permission request missing');
need(html.includes('imu_start_failed'),'IMU start failure telemetry missing');
const sensorPersistence=fs.readFileSync('sensor_persistence.js','utf8');
need(sensorPersistence.includes("iosNeedsGesture")&&sensorPersistence.includes("imu_restore_waiting_for_user_gesture"),'iOS IMU auto-restore gesture guard missing');
const sensorAutostart=fs.readFileSync('sensor_autostart.js','utf8');
need(sensorAutostart.includes("iosNeedsGesture")&&sensorAutostart.includes("imu_autostart_waiting_for_user_gesture"),'iOS IMU sensor-autostart gesture guard missing');
need(ui.indexOf('await startIMU()')<ui.indexOf('await startGPS()'),'IMU permission is not requested before GPS async start');
need(sw.includes("'dyno_only_v351'"),'dyno UI module not cached');
need(sw.includes("'dyno_only_v351.css'"),'dyno UI css not cached');
need(html.includes('audioSpectrum:{startHz:20,endHz:1000,stepHz:5,frames:spectra}'),'run wide-spectrum payload missing');
const phoneBridge=fs.readFileSync('phone_bridge.js','utf8');
need(phoneBridge.includes('calc(var(--ml-bottom-nav-h,76px) + 18px + env(safe-area-inset-bottom))'),'Phone Bridge bottom-nav clearance missing');
need(phoneBridge.includes('max-height:calc(100dvh - var(--ml-bottom-nav-h,76px) - 42px - env(safe-area-inset-bottom))'),'Phone Bridge viewport max-height missing');
console.log('V351_DYNO_STATIC_OK');
