'use strict';
const fs=require('fs');
const runtime=fs.readFileSync('v34_runtime_fixes.js','utf8');
const sync=fs.readFileSync('raw_sync.js','utf8');
const light=fs.readFileSync('raw_data_ui_light.js','utf8');
const version=fs.readFileSync('version.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const fail=m=>{throw new Error(m)};
const block=(src,start,end)=>{const a=src.indexOf(start),b=src.indexOf(end,a+start.length);if(a<0||b<0)fail('missing block '+start);return src.slice(a,b)};
const summary=block(runtime,'async function researchRawSummary()','function rawRecoveryText');
const open=block(runtime,'function openResearchRawData()','async function sendResearchRow');
const researchSync=block(runtime,'async function syncResearchRaw()','function scheduleResearchSync');
const queue=block(sync,'async function localLearningIds','function sleep');
if(summary.includes('readResearchStore')||summary.includes('.getAll('))fail('summary loads full research store');
if(open.includes('readResearchStore')||open.includes('.getAll('))fail('RAW view loads full research store');
if(researchSync.includes('readResearchStore')||researchSync.includes('.getAll('))fail('research sync loads full research store');
if(!runtime.includes('openKeyCursor')||!runtime.includes('recentResearchKeys(db,name,limit=8)'))fail('bounded research key cursor missing');
if(!researchSync.includes('researchKeys')||!researchSync.includes('researchRow'))fail('research payloads are not streamed one at a time');
if(queue.includes('getLearningChunks(false)'))fail('learning queue preloads all payloads');
if(!queue.includes('openKeyCursor')||!queue.includes('localLearningIds(capacity,exclude)'))fail('learning queue is not ID-only');
if(!sync.includes("const MODULE_VERSION='v40-reserve-safe-id-queue'"))fail('raw sync module version not bumped');
if(!light.includes('countStore')||!light.includes('recentKeys'))fail('light RAW UI lost nonblocking implementation');
if(runtime.includes("objectStore('rawChunks').delete")||sync.includes("objectStore('rawChunks').delete"))fail('RAW deletion introduced');
const build=(version.match(/build:\"([^\"]+)\"/)||[])[1];
if(build!=='2026-09-07-mic-primary-v1')fail('unexpected build '+build);
if(!sw.includes(build))fail('service worker build mismatch');
console.log('RAW_RESERVE_SAFE_OK',JSON.stringify({build,researchSummary:'count-only',researchView:'8-keys-only',researchSync:'key-list+single-row',learningQueue:'id-only',rawDelete:false}));
